### ISSUE TITLE
fieldType constraint in the XML schema

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#10]
@igarashitm commented on [Fri Oct 27 2017](https://github.com/atlasmap/atlasmap-runtime/issues/247)

https://github.com/atlasmap/atlasmap-runtime/blob/master/atlas-model/src/main/resources/atlas-model-v2.xsd#L152

Right now JsonField and JsonComplexType doesn't have any constraint for the fieldType in the schema, but JsonComplexType should only be used for 'Complex' and JsonField for others. See if possible to reflect that constraint in the XML schema. XML model as well.

**Comment by sunilmeddr** [comment]
We can't override the XML attribute in child Schema. So we have the following options. @igarashitm please share your thoughts.

Option 1: Make no changes

Option 2: Make a static 'factory' method the create the complex fields and sets the FieldType.COMPLEX 
   ie.   AtlasJavaModelUtil.createJavaDocument(..)

Option 3: Refactor all the references to use a non-enum solution (864 places to change)

Option 4: Use a Maven build solution, where we copy a modified version on top of the generated class that implements a constant return value of FieldType.COMPLEX

**Comment by mattrpav** [comment]
@igarashitm I recommend we look to Option 2. We'd need to maintain the convention throughout the code, but it would be a straight-forward search for anything that does "new JavaDocument()" and replace it with the static factory method.

**Comment by igarashitm** [comment]
I'm OK with doing Option 2, but better to file another issue and go with it. The initial motivation of this issue is to add a constraint at schema level, so I'd want to keep this open and revisit when we have chance to make a major refactor on the schema.

**Comment by sunilmeddr** [comment]
Created the issue 227 to create the XMLComplexType and JsonComplexType using the factory method
