### ISSUE TITLE
Allow multiple mappings for source elements

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1003]

**Comment by pleacu** [comment]
Clearing out everything seems to work but the 'Select mapping' dropdown appears so the user can distinguish which mapping they want:

![sc1](https://user-images.githubusercontent.com/2981421/59462434-bb44e500-8df1-11e9-8639-27c64015f20e.png)

![Screenshot from 2019-06-13 15-32-35](https://user-images.githubusercontent.com/2981421/59462471-ce57b500-8df1-11e9-8085-84e5ab0f0608.png)

**Comment by igarashitm** [comment]
Yep, until we address #635 it's a bit annoying, but from functionality this is better I would say.
