### ISSUE TITLE
[Regression]Indexing in combine/separate from "add new mapping" panel

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1018]
I noticed that indexing of fields has changed. Creating combine mapping from "add new mapping" dialog"  had order of actual adding order. Currently it's order is reversed so new field added into combine has always index 1. 

Let say we are adding: field1 , field2, field3 -> target. Actual indexes would be 1:field3 2:field2 3:field1 -> target in current version

@igarashitm @pleacu is it a bug or intentional change?  wdyt?

**Comment by pleacu** [comment]
definitely a bug - looking now
