### ISSUE TITLE
[regression][combine] Gaps are ignored 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1020]
In combine are gaps ignored in both in mappings preview and actual mapping. On image below I've changed index of "sourceString" from 3 to 5 so expected result is `200.547--1000---Some String`
![screenshot_20190619_122207](https://user-images.githubusercontent.com/6814482/59758101-75729b80-928d-11e9-8e2f-a62e2c610f0f.png)

**Comment by mmelko** [comment]
first gap is still ignored

**Comment by igarashitm** [comment]
merged #1183
