### ISSUE TITLE
[regression]Remove of mapping is not refreshing UI immediately for the blue link

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#1028]
versions standalone 1.40.0 on Chrome and Firefox

- create two mapping
![image](https://user-images.githubusercontent.com/1105127/59924482-1d2acd80-9436-11e9-8948-56ff56b05fb7.png)
- click on the top right icon of the third column to delete the mapping
- Click remove in the popup
![image](https://user-images.githubusercontent.com/1105127/59924553-43506d80-9436-11e9-90a9-ed72b105c937.png)

--> there is still a blue link connection

![image](https://user-images.githubusercontent.com/1105127/59924565-4b101200-9436-11e9-9344-802671e7a132.png)

when clicking in another place the blue link is removed

**Comment by pleacu** [comment]
This is fixed by https://github.com/atlasmap/atlasmap/commit/5c1da4539a258c712afd4c86671df8f6db4465e5
