### ISSUE TITLE
Validation errors doesn't show up after 2nd visit

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1045]
Validation errors shows up when mapping is established, but it doesn't after deactivate and activate again.
![warn](https://user-images.githubusercontent.com/265462/60203411-93567800-981a-11e9-9a13-c18c1b616b62.gif)

**Comment by pleacu** [comment]
This was fixed with this commit:
https://github.com/atlasmap/atlasmap/commit/badbbca2bc773c4dfbb812f7bfd0939de2138e1b
