### ISSUE TITLE
Optimize vertical usage in Mapping Details panel

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1083]
If we collapse the document id into just an icon (where tooltip will reveal the doc name), then add the field name, index number (if applicable) and trash can onto a single line then we can more effectively show more info in the mappings detail panel.

ref - old format:
![sc1](https://user-images.githubusercontent.com/2981421/60816927-b52ff300-a168-11e9-9e5f-c0fa9fdd415c.png)

current format:
![sc2](https://user-images.githubusercontent.com/2981421/60816950-c11bb500-a168-11e9-9d07-361e8e233cbf.png)

**Comment by pleacu** [comment]
Orig:
![sc1](https://user-images.githubusercontent.com/2981421/61974574-d9872e80-afb4-11e9-99be-07b87ae6820e.png)

New:

![sc2](https://user-images.githubusercontent.com/2981421/61974588-e1df6980-afb4-11e9-9835-3be8db290008.png)


wdyt???  @igarashitm

**Comment by igarashitm** [comment]
:+1: saved lot of pixels :-D
