### ISSUE TITLE
Group search result by Document

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1086]
Field search from Mapping Detail pane only shows field path ATM, would be better to group them by Document. Document name could be shown as an unselectable separator in the list.

![search](https://user-images.githubusercontent.com/265462/60828694-1368d000-a181-11e9-8a7c-600ced5c030e.png)

In this case last two are coming from different Document, but it's not clear from search result.
Same for expression field search starting by `@`.

**Comment by pleacu** [comment]
Here's what I've got for the mapping details and expression search boxes:
![sc1](https://user-images.githubusercontent.com/2981421/66317410-733d5700-e8e7-11e9-93fc-30e5fd4d3889.png)

![sc2](https://user-images.githubusercontent.com/2981421/66317418-78020b00-e8e7-11e9-8807-8bb87100a7de.png)

**Comment by igarashitm** [comment]
Looks great! so the document name is not selectable?

**Comment by pleacu** [comment]
correct - here's the target mapping details search:
![sc3](https://user-images.githubusercontent.com/2981421/66317612-d4652a80-e8e7-11e9-8549-97f53495001f.png)
