### ISSUE TITLE
xml: Migrate XmlPathCoordinate to use AtlasPath

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#11]
@mattrpav commented on [Thu Jul 27 2017](https://github.com/atlasmap/atlasmap-runtime/issues/111)

The Xml module uses XmlPathCoordinate and should be migrated to the common AtlasPath handler, or an extension of the AtlasPath class that supports namespaces

**Comment by mattrpav** [comment]
@igarashitm please review and approve the suggested requirements. I've ramped up Sunil this morning on AtlasMap and this task specifically. He'll be ready to start working it shortly.

1. XmlPath class extends from AtlasPath
2. Adds support for an optional namespace modifier on a path segment (no other formats have a concept of a segment modifier at this time)
3. Refactor Xml Module / Service(s) to use XmlPath class

**Comment by igarashitm** [comment]
@mattrpav sounds good! do you think is it worth aligning JSON module as well from future maintenance cost point of view?

**Comment by mattrpav** [comment]
@igarashitm good deal, I'll work on transitioning this task to Sunil w/ the requirements as described. 

Regarding JSON module-- yes, a quick look it appears it is using the legacy PathUtil class instead of AtlasPath. I'll create another ticket and assign it to Sunil to do after this one.

Thanks!
