### ISSUE TITLE
Caught exception while attempting to serialize mapping, skipping

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1105]
It's here
https://github.com/atlasmap/atlasmap/blob/e72a18808e0bc7e8943f2c08ebf5fa5f836a75ae/ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts#L40

This sometimes happens when reload, seems one of field is not filled with required properties, but it IS in the `parsedData`. We can call `MappingDefinition#updateMappedFieldsFromDucments()` right before serialization, but it's just putting a lid on a rotten pot. We have to find how that `parsedData => properties` update is missed. I tried to add that update in `deserializeMappingServiceJSON()` but it didn't help.

**Comment by pleacu** [comment]
I've caught a few async issues recently and haven't seen this pop up for a while - It may be fixed.

**Comment by igarashitm** [comment]
I don't see either, let's close now
