### ISSUE TITLE
[regression]Empty transformation are added when importing an .adm file

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#1121]
tested with standalone 1.41.1 version

- create a data transformation without transformation, for instance something like
![image](https://user-images.githubusercontent.com/1105127/61361439-ca033980-a880-11e9-8b4a-5888ce4bb58e.png)
- export the current mappings
- click settings -> reset all
- import the previously exported AtlasMap mapping
--> empty transformation are added to all mappings
![image](https://user-images.githubusercontent.com/1105127/61361388-b8219680-a880-11e9-96c2-4ab763687d06.png)

**Comment by pleacu** [comment]
Hey @apupier - I'm not quite seeing the issue here.  You have three separate mappings with no transformations.  You export then reset then import the exported ADM file.  Looking at the generated mappings JSON file - I see no empty transformations.  In your example there is no selected active mapping.  Can you expand on the issue that you're having?

**Comment by apupier** [comment]
in the second screenshot we can notice that there is a little thunder icon added close to each transformation. If I click on the mapping, there is an empty transformation field.

but... I cannot reproduce today

**Comment by apupier** [comment]
tried again this morning. I still cannot reproduce.
So either I had a corrupted work folder or it is something that it is not happening often.
Removing the regression flag as we cannot know then.
Closing as I guess that without more information we can't do nothing, we can still reopen if we hit the same issue and try to provide more context/information.
(by the way @pleacu is there something specific to check if it happens again? Maybe to backup the workfolder?)
