### ISSUE TITLE
Last provided name for exporting adm files is not respected

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1123]
Couldn't get it to move to our issue queue - ref:
https://github.com/jboss-fuse/vscode-atlasmap/issues/133

create a data transformation
click on export
specify a name, for instance "demo.adm"
click ok
a native window is opening with demo.adm by default
click finish
click again on export
the field is pre-filled with "demo.adm"
click ok
the native window is prefilled with "atlasmap-mapping.adm" instead of "demo.adm"

**Comment by apupier** [comment]
ah cool, I thought it was something specific to our extension. Thanks for noticing it in the other tracker and fixing it!
