### ISSUE TITLE
Implement OOTB TypeConverters for NUMBER fieldType

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#114]
Support NUMBER <=> {primitives, DATE/TIME related field types} OOTB.

**Comment by igarashitm** [comment]
Support NUMBER <=> {primitives, DATE/TIME related field types} OOTB.

**Comment by mmelko** [comment]
Without this any number-related field action can be used.

**Comment by rohanmars** [comment]
@mmelko @igarashitm could you describe/confirm exactly what you need fixed by this issue? If you are able to provide samples that would be very helpful.

**Comment by igarashitm** [comment]
@rohanmars most critical one is #233, so the type converter detection doesn't recognize `INTEGER` as a kind of `NUMBER`.

Basically type converter shouldn't throw any exception until the mapping user defines is wrong, and if it's wrong, that should be warned at design time.
