### ISSUE TITLE
[backport] cfg.mappings could be null when many-to-one mapping is involved

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1142]
Below is thrown when reopen a data mapper step which contains many-to-one mapping in Syndesis.
```
atlasmap-main.js:96 TypeError: Cannot read property 'updateMappedFieldsFromDocuments' of null
    at Function.e.deserializeFieldMapping (VM164 atlasmap-vendor.js:4321)
    at Function.e.deserializeMappings (VM164 atlasmap-vendor.js:4235)
    at Function.e.deserializeMappingServiceJSON (VM164 atlasmap-vendor.js:4098)
    at e.reset (VM165 atlasmap-main.js:94)
    at e.ngOnInit (VM165 atlasmap-main.js:73)
    at VM164 atlasmap-vendor.js:14735
    at VM164 atlasmap-vendor.js:14736
    at Fl (VM164 atlasmap-vendor.js:14814)
    at ro (VM164 atlasmap-vendor.js:15169)
    at Object.updateDirectives (VM165 atlasmap-main.js:150)
```
I don't see this on current upstream, seems to have been fixed. We have to identify the fix and backport to 1.40.x so that potential Syndesis patch release can consume it.

**Comment by pleacu** [comment]
I can't seem to reproduce this error with the latest atlasmap-1.40.x branch.  I think I remember seeing this error in the console a while back - do you have the exact many-to-one mapping ?

**Comment by igarashitm** [comment]
ATM it reproduces only in Syndesis, when I open a data mapper step.

**Comment by igarashitm** [comment]
A similar step would be to
1. put a many-to-one mapping
2. close the browser window
3. open new window
but standalone even fails to load target document, so it hits another issue...

**Comment by igarashitm** [comment]
I think we can do this to make a quick fix
```java
  static deserializeMappingServiceJSON(json: any, mappingDefinition: MappingDefinition, cfg: ConfigModel): void {
    if (!cfg.mappings) {
      cfg.mappings = mappingDefinition;
    }
```
but it's kinda bug of redundant arguments, for longer term we should remove an argument `mappingDefinition` here and enforce it to work on `cfg.mappings` anyway. Current codebase can't handle multiple MappingDefinition for sure and will need bigger refactoring.

**Comment by igarashitm** [comment]
To be safer
```java
  static deserializeMappingServiceJSON(json: any, mappingDefinition: MappingDefinition, cfg: ConfigModel): void {
    if (!cfg.mappings) {
      cfg.mappings = mappingDefinition ? mappingDefinition : new MappingDefinition;
    }
```

**Comment by pleacu** [comment]
backport complete
https://github.com/atlasmap/atlasmap/pull/1149
