### ISSUE TITLE
[backport] many-to-one mapping disappears at first attempt

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1143]
![disappear](https://user-images.githubusercontent.com/265462/62067792-8d312e00-b202-11e9-9cd8-12691e6a44a2.gif)

I don't see this on current upstream, seems to have been fixed. We have to identify the fix and backport to 1.40.x so that potential Syndesis patch release can consume it.

**Comment by pleacu** [comment]
backport complete
https://github.com/atlasmap/atlasmap/pull/1149
