### ISSUE TITLE
Hardening of UI Code

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1145]
There are several parts in UI code which induce bugs. We have actually been suffering from them, fix one bug in some class and then another bug pops up from the other side.
 For example
1. Some states are stored in a single property, but it’s always possible to calculate from other properties, where no need to cache explicitly. Then some code use the stored property and the others calculate everytime, being a source of out of sync bugs.
1. The logic spreads among component, model and services. Sometimes multiple of them have similar logic in different places, especially multiplicity transition handling and index handling.

 We have to fix and simplify those confusing bug prone code.

 In addition to that, we have to add much more unit tests and also introduce e2e test. Runtime UT coverage is now decreased to 63%, and UI UT coverage is around 30-40%.

 E2e test should cover basic import/export scenario and catch basic regressions. Currently we depend on manual tests, just clicking around the UI by hand.

 Next, conditional mapping needs to be more polished. There are several bugs left open. There must be more bugs if we test more. Also we have to support cut/copy & paste, and drag & drop should handle drop position in the widget, etc.

 Lastly, we still have many UXD issues abandoned while designs by UXD team are ready to be implemented. We implemented the biggest one which is one-to-many/many-to-one look&feel refactoring, but it’s just one of them. Those are all that both of UXD team and us AtlasMap developers agreed that we have to fix, so we should address them as soon as possible.

**Comment by riccardo-forina** [comment]
I think we're addressing a good chunk of this while migrating the UI codebase to React.

**Comment by igarashitm** [comment]
Closing as this is a bit out of date - this Epic was kinda campaign in specific sprint to more focus on UI problems, we couldn't have solved all though, we'll continue working on them individually.
