### ISSUE TITLE
[regression] No collection-related transitions in collection -> non-collection mapping of primitives

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1165]
When I specify collection->non-collection mapping (i.e List<Integer>->float ) I can't see any transitions (on source side) related to collections.. (Average, add, max etc.) This was definitely working before.

**Comment by igarashitm** [comment]
Those multiplicity transformations are no longer available for individual field. #912 will show them separately.

**Comment by mmelko** [comment]
well no multiplicity transformations are shown at all. From @912 I understand that it should be in separator place but, I have standard combine separators (space,hash,underscore etc.)
![screenshot_20190805_124214](https://user-images.githubusercontent.com/6814482/62459260-3d60e280-b77f-11e9-9ebd-62b71b9cdfba.png)

I believe this is becasue I'm mapping collection of primitive types.

**Comment by igarashitm** [comment]
#912 is still open

**Comment by mmelko** [comment]
ah, didn't noticed that..
