### ISSUE TITLE
Refactor UI state management

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1176]
ATM there's no policy for how to manage internal state at design level in the UI code and getting harder to maintain. I see a couple of offerings to solve this kind of problem

1. Redux (has to come after #874)
1. GraphQL + Relay
1. GraphQL + Apollo Client
1. React Context API + React Hooks (has to come after #874)
1. Unstated (has to come after #874)

GraphQL requires to be baked into backend. Wondering if it's better to be tackled together with on-demand inspection (#579) which also requires architectural change on both of frontend and backend.

**Comment by riccardo-forina** [comment]
For that little that I have seen of Atlasmap, a redux like approach sounds like a good idea. 

GraphQL is great if you have many api, maybe from different systems, that you need to join together and abstract to solve the presentation layer. Not sure this is the case?

**Comment by igarashitm** [comment]
Thanks for the comment! that's right AtlasMap has only a couple of API from a single backend, would be relatively simple.

**Comment by igarashitm** [comment]
The on-demand inspection #579 might change the situation a bit. As user expand the parent field, UI will have to query a next document fragment to the backend by specifying a path, while current implementation has a whole document model at UI side. But maybe also want to cache the fragment at UI side as much as possible to avoid requesting same fragment again and again.
That also requires field search to be server side (#603) and it has to walk through all the documents at server side.
With having above, @riccardo-forina do you think GraphQL is still an overkill?

**Comment by igarashitm** [comment]
https://blog.bitsrc.io/state-of-react-state-management-in-2019-779647206bbc

**Comment by riccardo-forina** [comment]
Yeah, especially with dynamic queries I wouldn’t go with GQL. Honey, even redux could be overkill. On syndesis we went without anything but React own state management and it worked just fine. Genetically speaking is a good idea to start with plain React and introduce a state management when/if it makes sense to do so.

**Comment by igarashitm** [comment]
I think `MappingDefinition` and `DocumentDefinition` are 2 big state that needs to be shared across many of components, which doesn't fit with `setState()`, so we'll need something for it. But having a slight look at Context API and Hooks, now it's not necessary to be Redux. Need to look into them deeper.

**Comment by igarashitm** [comment]
The replayable state changing event is appealing though. As a mapping editor, Undo/Redo would be a good feature we might want in the future.

**Comment by igarashitm** [comment]
We decided not to introduce 3rd party state management, `ConfigModel` and all services in AtlasMap UI are kinda central state management system and we should leverage it.
