### ISSUE TITLE
Support collection field in expression

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1185]
With transformation support in expression (#890), collection field should be able to participate in expression.

We would need to relax field type check in UI so that the collection field could be selected with other fields, but only when expression is enabled.

A question, how do we handle when:
1. Enable expression
2. Add one collection source field
3. Add one non-collection source field
4. Disable expression

This falls into error state, "collection field cannot selected with other field" in normal flow (https://docs.atlasmap.io/developer-guide/#mapping-state).

One solution is to wipe out field selection when user disables expression. In the example above, when user push the button to disable expression, show a modal window that has a warning "If you disable expression, source fields you selected are cleared out, are you sure?"
We can also stop filling initial expression when user enables the expression. Not necessary though, I don't think that initial expression just concatenating with "+" makes much sense for users.

Then, we can even enable having an expression with collection target. IOW expression mapping should allow anything other than compound target selection.

**Comment by rkorytkowski** [comment]
Shouldn't we remove the current mapping instead of removing fields alone? What's the use of a mapping without fields in it?

**Comment by igarashitm** [comment]
Right, it doesn't make sense eventually so I think it will be removed before it's saved - specifically when user focuses out from that mapping. But while it's active mapping, I would say that's a "working on it" mode, so when user enable expression, fields are to be cleared out, but the empty mapping is still activated  so that user can start typing for expression right away.
And wait, we might be able to keep target fields btw. It's source fields we have to remove for that expression enable/disable transition I think.

**Comment by rkorytkowski** [comment]
So what if a target collection is used in an expression? Do we then delete only target fields?

**Comment by igarashitm** [comment]
Target field can't be a part of expression, it's all source fields. So I believe we simply remove source fields and then any target field(s) that are left is valid for non-expression mapping.
