### ISSUE TITLE
[regression] Date transformations missing in date types

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1190]
Currently date transformations are missing for all date types marked as `DATE, DATE_TIME,TIME` (`LocalDateTime,sqlDate,JavaDate`...). They can be selected only for `DATE_TIME_TZ` types. (`ZonedDateTime,Calendar`)

**Comment by igarashitm** [comment]
Possibly `ANY_DATE` is not properly handled in UI.
