### ISSUE TITLE
Update Java, Xml and Json modules to not create validations for core field types

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#12]
@igarashitm commented on [Tue Nov 07 2017](https://github.com/atlasmap/atlasmap-runtime/issues/278)

Poor JavaModule, don't look into Constants...
![screenshot from 2017-11-07 09-53-01](https://user-images.githubusercontent.com/265462/32499990-123a9826-c3a2-11e7-96fe-12b0a2a843ba.png)

---

@igarashitm commented on [Tue Nov 07 2017](https://github.com/atlasmap/atlasmap-runtime/issues/278#issuecomment-342508247)

Don't forget to check JSON/XML modules as well

@mattrpav summarizing comments up to 12/19:

Java, Xml and Json Modules should not create validation messages for: ConstantField, PropertyField, LookupField and other common *Field types from atlas-core.

**Comment by rohanmars** [comment]
@mattrpav I had to change the validateModuleField method signature. Is this the correct approach? https://github.com/rohanmars/atlasmap/commit/13ab730590c174032d27c5007645ea0ced3c3260

**Comment by igarashitm** [comment]
Hi @rohanmars ,

It seems like you may need to hold on for this one, as it directly depends on the refactoring I'm tackling
https://github.com/atlasmap/atlasmap/issues/64
https://github.com/igarashitm/atlasmap/commit/78033e5daceec8a2c60ababcbaa9b0d7f7905bbf#diff-bc026ea7508261b7be5bdbfde51995a4

So basically Java/JSON/XML modules shouldn't look into Constants/Properties at all, as it pollutes all the module code with Constant/Property handling. Instead I'm introducing `ConstantModule` and `PropertyModule` to handle that. Then Constant/Property validation can be implemented in those special modules and completely get rid of existing Constant/Property related code from Java/JSON/XML modules.

**Comment by igarashitm** [comment]
This is now ready to work on, might need to move constant validation into ConstantModule.processPreValidation()

**Comment by mattrpav** [comment]
@igarashitm is the approach that the XmlModule and JsonModule should call the ConstantModule.processPreValidation() ?

**Comment by igarashitm** [comment]
@mattrpav nope, `processPreValidation()` is invoked for all the modules here
https://github.com/atlasmap/atlasmap/blob/master/runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java#L606-L611

ConstantModule just needs to check if it's Constants, if so validate.

FYI, #155

**Comment by mattrpav** [comment]
Ok, so to clarify the work in this task-- the JavaModule, XmlModule, and JsonModule validations need to be updated to not error if they detect a 'core *Field', such as: ConstantField, PropertyField, LookupField, etc?

However, if a JavaModule is looking at a Field for a mapping, it should throw an error if it detects non-JavaField and non-core Field types. For example, if a mapping tied to a Java docId contains a JsonField, it should return a validation error.

**Comment by igarashitm** [comment]
> Ok, so to clarify the work in this task-- the JavaModule, XmlModule, and JsonModule validations need to be updated to not error if they detect a 'core *Field', such as: ConstantField, PropertyField, LookupField, etc?

correct, however

> if a JavaModule is looking at a Field for a mapping, it should throw an error if it detects non-JavaField and non-core Field types

This shouldn't be done until #155 is addressed. ATM all fields are passed into all modules on validation. So each modules have to check if it's really supported field for that module.

**Comment by mattrpav** [comment]
Thanks, I'll break the tasks up into two tasks and update the description here with the first part.

**Comment by mattrpav** [comment]
[#155 is related](https://github.com/atlasmap/atlasmap/issues/155)
[#206 is related](https://github.com/atlasmap/atlasmap/issues/206)

**Comment by sunilmeddr** [comment]
To fix the issue,in the method BaseModuleValidationService.validateField(..) , I will remove the 2nd condition in the if block and I will update the error message.

    protected void validateField(String mappingId, Field field, FieldDirection direction, List<Validation> validations) {
        if (field == null || !getFieldType().isAssignableFrom(field.getClass())) {
            Validation validation = new Validation();
            validation.setScope(ValidationScope.MAPPING);
            validation.setId(mappingId);
            validation.setMessage(String.format("%s field %s is not supported by the %s",
                    direction.value(), getFieldName(field), getModuleDetail().name()));
            validation.setStatus(ValidationStatus.ERROR);
            validations.add(validation);
        } else {
            validateModuleField(mappingId, (T)field, direction, validations);
        }
    }

**Comment by sunilmeddr** [comment]
This  issue is resolved with the PR#213
