### ISSUE TITLE
[regression] Reset all is not working on 1.42.1

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#1215]
Tried with standalone version on Chrome

- create a data transformation
- click on reset all

--> UI is blinking but the same content is displayed

no error in browser console log
no error in output of the launch of the java -jar

**Comment by pleacu** [comment]
Corrected with https://github.com/atlasmap/atlasmap/pull/1214

**Comment by apupier** [comment]
the pointed issue is marked as fixed in 1.42.1 but I hit this problem with the 1.42.1 version.

**Comment by igarashitm** [comment]
Don't reopen just for a wrong link, what you're looking for is #1218
