### ISSUE TITLE
Update deprecated minimatch dependency

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#123]
[INFO] --- frontend-maven-plugin:1.4:npm (angular-cli install) @ atlasmap-ui ---
[...]
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by igarashitm** [comment]
See README for build instruction

**Comment by apupier** [comment]
What is the link with the build instructions?
I have not found prerequisites for the build.
The normal maven build is reporting this warning.
