### ISSUE TITLE
NUMBER FieldType in expressions not evaluating correctly.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1234]
Reference a property in a conditional expression and it will not evaluate correctly.
This should evaluate to '99-RESULT'

![sc1](https://user-images.githubusercontent.com/2981421/65433752-98ac6a00-ddeb-11e9-8e0f-ca13b907a960.png)

Either the constant in the expression or the property is confusing the runtime eval.
![sc2](https://user-images.githubusercontent.com/2981421/65434017-18d2cf80-ddec-11e9-844c-65a990bb4488.png)

**Comment by pleacu** [comment]
This issue does not apply to STRING properties/ constants.  Those work correctly.

**Comment by pleacu** [comment]
The issue is in ComparisonExpression.java in the runtime.  

https://github.com/atlasmap/atlasmap/blob/master/lib/expression/src/main/java/io/atlasmap/expression/internal/ComparisonExpression.java#L338

The comparison method doesn't deal with java.math.BigInteger - consequently all BigInteger comparisons fail.  It's late in the release to change everything required to support BigInteger - it may be safer to not use BigInteger when processing 'NUMBER' field types (the java long data type should be sufficient).

**Comment by igarashitm** [comment]
So the `Number` is a bit special FieldType which accepts all subclasses including BigInteger and BigDecimal, so if it fits with long then `LONG` FieldType have to be used.

**Comment by pleacu** [comment]
The value for BigInteger isn't kept in the value field - its kept in the 'mag' array i.e.

values.elementData[2].mag[0]: 99

We could use Java.math.BigInteger.valueOf() but we can't cast - I'm saying in order to determine the value to see if it fits in a long.

**Comment by igarashitm** [comment]
I mean, if it's only `NUMBER` FieldType that is a problem, we should keep the issue open and fix it to support BigInteger/BigDecimal. I would say `NUMBER` field should be used only when it could overflow with long/double, otherwise int/long/float/double have to be used for FieldType.

**Comment by igarashitm** [comment]
Verified there's no problem with `INTEGER`, `LONG`, `FLOAT` and `DOUBLE`. `NUMBER` FieldType have to handle BigInteger and BigDecimal.
