### ISSUE TITLE
Upgrade deprecated angular-cli

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#124]
[INFO] --- frontend-maven-plugin:1.4:npm (angular-cli install) @ atlasmap-ui ---
[INFO] Running 'npm install --no-optional -g angular-cli' in C:\git\atlasmap\ui
[WARNING] npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.

**Comment by deeleman** [comment]
The Angular CLI version currently defined on atlasmap/ui is v1.2.8. Please double check the package versions on `atlasmap/ui/package.json` and double check if those versions match the version defined in the repo.

**Comment by igarashitm** [comment]
See README for build instruction
