### ISSUE TITLE
[Windows/Build] Add build script for Windows

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#125]
currently it is failing with

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:yarn (yarn ng build) on project atlasmap-ui: Failed to run task: 'yarn aot:build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

In readme I was nop able to find instruction for normal build. There are several instructions for different target and most of them are based on launching a .sh but I'm on windows.

**Comment by igarashitm** [comment]
contributions are welcome

**Comment by apupier** [comment]
I think it would be best to get rid of platform dependent build.
