### ISSUE TITLE
Add copyTo one-to-many transformation

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1253]
Currently we only have `Split` one-to-many transformation, but sometimes we only copy the single string into the first element of target collection without splitting, say `/company/name` -> `/[0]/company`.  Having `0` as a default parameter for the index, copyTo transformation should be able to copy it into specified index in the collection.

A workaround for this is to specify a delimiter which never appears in a source String, so that the `Split` won't split anything.

**Comment by zamrokk** [comment]
Please implement this feature "CopyTo" function should be added along with the actual "Split" for One-to-many cases

**Comment by igarashitm** [comment]
Addressed by #2171
