### ISSUE TITLE
Create community release job for jenkins

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#126]
Here is the build script for monorepo, it builds everything including atlasmap/ui
https://github.com/atlasmap/atlasmap/blob/master/build.sh

**Comment by igarashitm** [comment]
@iocanel if you could help for this one that would be awesome!

**Comment by igarashitm** [comment]
maven profiles from atlasmap-runtime old job - https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/atlasmap-release/configure
```
fabric8,ci,release,community-release
```

same from camel-atlasmap old job - https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/camel-atlasmap-release/configure
```
fabric8,ci,release
```

**Comment by igarashitm** [comment]
Hi @iocanel , can you look into this? it seems we need a release soon, to have #176 for the atlasmap-maven-plugin used in syndesis pre-computed inspection.

**Comment by igarashitm** [comment]
I just noticed we need to move those release related profiles to top level pom, as we'll need to release atlasmap/parent as well. I'll try adjusting POMs and add `--release` option into build.sh which adds release specific profiles.

**Comment by rhuss** [comment]
@igarashitm Is this still a blocker for TP3 ?

**Comment by igarashitm** [comment]
@rhuss just removed the blocker tag, as I succeeded to make a 1.32.2 release manually.
