### ISSUE TITLE
Add atlasmap to Jenkins build

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#13]

**Comment by gashcrumb** [comment]
Are we using this issue to track getting the new repo building and deploying to staging?

**Comment by mattrpav** [comment]
We can.  We are are moving DM dev tickets and task tracking to GitHub, this is my reminder ticket if there is a better repo or common place to put build infra tasks, we'll move there

**Comment by rhuss** [comment]
@gashcrumb @mattrpav I added building the Docker Hub images to a circleci build. So "atlasmap/atlasmap:latest" gets recreated on every commit to master. The templates in https://github.com/syndesisio/syndesis-openshift-templates are updated too, as well as the staging environment (except the names of the objects need to be updated, too for consistency)

**Comment by rhuss** [comment]
Thinks that can be closed now. @cunningt I guess you also have pipeline builds for this repo, too, right ?
