### ISSUE TITLE
Java field inspection doesn't support Enum fields

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#13]
I suspect Enum field without getter/setter is not handled here. Add a unit test to inspect a class which has a Enum field without getter/setter, and see if it's in the inspection result. If not, implement it.

https://github.com/atlasmap/atlasmap/blob/943cab3fe8e28250a27ed1e302f3dae8378fecee/runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java#L597-L599

**Comment by igarashitm** [comment]
w/r/t not handling `JavaEnumField` in `inspectGetMethod()`, Let's talk here as it seems to be related - so as far as I can see from debugger, Enum inspection doesn't hit this method. I checked with `TargetTestClass` which has `StateEnumClassLong` Enum, and it looks successfully inspected and handled through UI. Enum might be handled somewhere else.
If so, `ClassInspectionService` code might be fishy, like entering method anyway but return without doing anything if it's Enum. It might need to be refactored.

**Comment by sunilmeddr** [comment]
Yes. I will fix the method inspection for Enum Fields along with the field
inspection.



On Thu, Dec 7, 2017 at 10:08 AM, Tomohisa Igarashi <notifications@github.com

**Comment by igarashitm** [comment]
The first step would be to add an unit test verifying field Enum inspection (i.e. inspection succeed without getter method for the Enum field), if it works, maybe you can just go over to next task... I don't yet have concrete idea how it should be refactored.

**Comment by sunilmeddr** [comment]
ok

On Thu, Dec 7, 2017 at 10:17 AM, Tomohisa Igarashi <notifications@github.com

**Comment by igarashitm** [comment]
@sunilmeddr of course if you have a good idea how to refactor `ClassInspectionService`, that would be awesome to do it!

**Comment by sunilmeddr** [comment]
I am planning to add code for the inspection of the Enum fields and in the
get and set method inspection,I will check the method parameter and return
type,if they are of the type Enum,I will update the JavaEnumField,otherwise
I will update the JavaField .

On Thu, Dec 7, 2017 at 10:21 AM, Tomohisa Igarashi <notifications@github.com

**Comment by mattrpav** [comment]
Let's clarify communication and hop on a call.. will send out some times.

**Comment by sunilmeddr** [comment]
I tested the Class Inspection by hitting the java service
http://localhost:8585/v2/atlas/java/class?className=io.atlasmap.java.test.
TargetTestClass and the response don't contain any JavaEnumFields. Enum
field(ex StateEnumClassLong) was identified as JavaField and with in the
JavaField ,it was correctly identifies as Enum. I am going to do the
following changes and I will submit a pull request by end of the weekend.

1) Add code to identify field as Enum
2) Modify the get/set method inspection to correctly identify a field as
Enum(Even though the field was Enum ,they are capturing as JavaField
instaed of JavaEnumField)
3) Add a new type Enum

**Comment by igarashitm** [comment]
Oh, this sounds scary... possibly UI can't handle if it's correctly `JavaEnumField`?
So my next question is, how UI determines it is Enum field today even if it's `JavaField`. @sunilmeddr , are you feeling OK with taking a look at from UI side? It's A-OK to put on hold and go to next issue for now. This possibly affects UI, it doesn't look trivial anymore.

**Comment by mattrpav** [comment]
In the past.. the field would have been marked with a jsonType.. io.atlasmap.java.v2.JaveEnumField

Sunil it talking about adding a property, so consumers know when to cast. The UI probably had it correct to look for the jsonType parameter.

**Comment by sunilmeddr** [comment]
It is identifying the field as Enum, But while adding the field to
JavaClass it was added as JavaField as we don't have the code to inspect
the Enum field and in the getter and setter method inspection we are not
adding the Enum field to JavaEnumFields, instead we are adding it to
javaFields, I think if we add a validation in the get/set method inspection
to identify the Enum field, Enum fields will be correctly captured in the
JavaClass.

**Comment by igarashitm** [comment]
So I guess UI is looking at `JavaClass.JavaFields.JavaField[]` in the inspection result JSON anyway, and ignoring `JavaClass.JavaEnumFields.JavaEnumField[]`. If it's true, once it's turned into `JavaEnumField`, Enum field would disappear from UI right?

**Comment by mattrpav** [comment]
@igarashitm I'm not sure out Angular and Typescript handle those types. In Java, JavaEnumField extends JavaField, so it can be worked with. Not sure how/if the type system there supports classes like that.

**Comment by igarashitm** [comment]
@mattrpav let me check UI code tomorrow, I think in TypeScript it's just a string via JSON path

**Comment by sunilmeddr** [comment]
I dont see any references for JavaClass.JavaEnumFields.JavaEnumField[]. In
the UI we are iterating the JavaClass.JavaFields.JavaField[] and if the
field is Enum we are capturing the details from the field
JavaClass.JavaFields.JavaField[]. So I think we just has to add the code to
capture the Enum field and not to make any changes to the set/get
inspections,so that we no need to modify the UI code because of the Enum
field inspection changes.

        for (const field of javaClass.javaFields.javaField) {
            this.parseJavaFieldFromDocument(field, null, docDef);
        }

             private parseJavaFieldFromDocument(field: any, parentField:
Field, docDef: DocumentDefinition): void {
        const parsedField = this.parseFieldFromDocument(field, parentField,
docDef);
        if (parsedField == null) {
            return;
        }

        //java fields have a special primitive property, so override the
"!= COMPLEX" math from parseFieldFromDocument()
        parsedField.isPrimitive = field.primitive;
        parsedField.classIdentifier = field.className;
        parsedField.enumeration = field.enumeration;

        if (parsedField.enumeration && field.javaEnumFields &&
field.javaEnumFields.javaEnumField) {
            for (const enumValue of field.javaEnumFields.javaEnumField) {
                const parsedEnumValue: EnumValue = new EnumValue();
                parsedEnumValue.name = enumValue.name;
                parsedEnumValue.ordinal = enumValue.ordinal;
                parsedField.enumValues.push(parsedEnumValue);
            }
        }

        if (field.javaFields && field.javaFields.javaField &&
field.javaFields.javaField.length) {
            for (const childField of field.javaFields.javaField) {
                this.parseJavaFieldFromDocument(childField, parsedField,
docDef);
            }
        }
    }

**Comment by igarashitm** [comment]
@sunilmeddr , oh cool, thank you for indentifying that my worry hit the fact :-)
yep agree, we would want to keep it as-is for now, maybe also keep this issue open for further discussion.

Need more investigation to see which is better:
* Use JavaEnumField
* Completely remove JavaEnumField from both of UI and backend

Both involves changing serialized inspection result contract, i.e. UI change must be involved at the same time.

**Comment by sunilmeddr** [comment]
Shall we add support for inspecting the Java Enum fields(not through the
Get/set methods) and close this issue, so that we will not have any issues
even if a class contain only Enum fields and not the set/get methods for
the Enum field. May be we can open an another issue about the usage of the
JavaEnumField.

**Comment by igarashitm** [comment]
Oops sorry, yes if the Enum field which doesn't have getter/setter is actually ignored, we need to support it. Maybe better to check first with unit test, inspecting a class which has an Enum field without getter/setter. I'll get issue desciption back.

**Comment by sunilmeddr** [comment]
I inspected a class with only Java Enum field and without get/set methods
and the inspection service is not capturing the Enum field.
