### ISSUE TITLE
json: Migrate JsonModule to use AtlasPath

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#135]
Migrate usage of io.atlasmap.core.PathUtil to AtlasPath for path segment handling.

1. JSON usage should be nearly identical to Java, as neither have namespaces
2. Report back any further usage of PathUtil for discussion of removal
3. Remove io.atlasmap.core.PathUtil class

**Comment by mattrpav** [comment]
@igarashitm please confirm requirements look good

**Comment by igarashitm** [comment]
Yeah looks good - good steps to cleaning up the code :-)
