### ISSUE TITLE
core: AtlasPath/PathUtil clean-ups

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#136]
@igarashitm @sunilmeddr identified a pre-cursor issue that the PathUtil class is used and we need to do a first pass clean-up of PathUtil -> AtlasPath, then confirm migration in the modules.

ref: https://github.com/atlasmap/atlasmap/issues/135
ref: https://github.com/atlasmap/atlasmap/issues/11

**Comment by mattrpav** [comment]
Technical requirements:

1. AtlasPath should provide an immutable 1-time parse of an atlas path expression in order to be referenced during processing by all services and modules.
2. AtlasPath should be instantiated via constructor of a valid AtlasPath string expression
3. AtlasPath should have no setter methods
4. AtlasPathTest should have 100% unit test coverage
5. All itests should pass after the re-factor

@igarashitm Questions:

Q-1: How do you want to handle AtlasPath validation?  

option 1: static method on AtlasPath class
option 2: throw exception from constructor

[option 1 variations]
option 1a. return true / false and log with any messages about invalid expressions
option 1b. Throw exception with message explaining what failed about the AtlasPath expression

**Comment by igarashitm** [comment]
@mattrpav assuming it's unexpected error path, I personally prefer option 2, throw an exception. The path expression error is likely to be a bug rather than application error as we provides UI to generate a mapping file.
