### ISSUE TITLE
AtlasService.converterCheck() contains incomplete code

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#14]
@jpav commented on [Thu Nov 02 2017](https://github.com/atlasmap/atlasmap-runtime/issues/273)

Code near the end of the method that determines whether a response should be generated indicating a converter is needed to perform a mapping has been left incomplete.  We should determine the necessity of this code and either complete its implementation or remove it from the class.

---

@igarashitm commented on [Thu Nov 02 2017](https://github.com/atlasmap/atlasmap-runtime/issues/273#issuecomment-341520887)

Weird thing is that we sometimes see "converter is not available" warning in UI. I thought it came from this converterCheck. Need to investigate.

---

@igarashitm commented on [Wed Nov 08 2017](https://github.com/atlasmap/atlasmap-runtime/issues/273#issuecomment-343008159)

I now suspect the converterCheck is not used at all. All the converter validation results I have ever seen come from validate. Make sure UI doesn't invoke it and remove.

**Comment by sunilmeddr** [comment]
AtlasService.converterCheck() is not used anywhere. Its look like we can remove AtlasService.converterCheck() and the corresponding Rest API
