### ISSUE TITLE
Separate doesn't allow adding more target fields by clicking

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#140]
_From @Stefan365 on November 30, 2017 13:18_

When "separate" action selected, 
second "target" has to be created manually.
I suppose this should be done automatically by UI.

_Copied from original issue: syndesisio/syndesis#533_

**Comment by igarashitm** [comment]
_From @zregvart on November 30, 2017 13:28_

@igarashitm doesn't Atlasmap do this if you drag the same source to two or more targets?

**Comment by igarashitm** [comment]
I think this is a separate version of atlasmap/atlasmap#95, atlasmap/ui is not handling well around combine/separate.

**Comment by pleacu** [comment]
Select the source and target elements and select the "separate' action.  Then ctrl-M1 to select the remaining components to add them to the separation.

![dm2](https://user-images.githubusercontent.com/2981421/38702471-ba4a0dc0-3e6e-11e8-85db-57eb2513f0f0.png)

**Comment by pleacu** [comment]
Fixed with compound-select commits.
