### ISSUE TITLE
Support class name completion

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1409]
When user import Java document, ATM they have to write down FQCN which is inconvenient. We have to provide typeahead search by scanning user uploaded jars.

**Comment by paoloantinori** [comment]
we did something similar in Groovy LSP, in case you want to share ideas.
To scan a classpath we have used this lib:

https://www.google.com/search?client=firefox-b-d&q=org+reflections

https://github.com/prominic/groovy-language-server/pull/14/files#diff-b1f0a074d4b3cea4a94efc94bdd1e1deR132-R136

**Comment by pleacu** [comment]
Need to add tests - check PaulsFieldAction (may not be related to this push).

![sc1](https://user-images.githubusercontent.com/2981421/68683760-5672ef80-0535-11ea-878f-1ea83deb8f00.png)

**Comment by pleacu** [comment]
@igarashitm - Hey Tomo - In the DM if I import a custom field action jar, the custom action defined by the custom class (`io.atlasmap.service.my.MyFieldActionsModel`) is automatically loaded into the field actions without having to 'enable' the class.
Is this an error or is the user supposed to enable `MyFieldActions`?

ref:

![sc1](https://user-images.githubusercontent.com/2981421/84810621-99200d00-afd9-11ea-9784-c2f8e389764a.png)

![sc2](https://user-images.githubusercontent.com/2981421/84810877-f7e58680-afd9-11ea-9029-12dac4c4204e.png)

**Comment by igarashitm** [comment]
Custom transformations doesn't have any enable/disable option, it appears where it's eligible once it's loaded. User just decides where to apply.

**Comment by pleacu** [comment]
Then do we need the Enable/Disable circleplus icon?

**Comment by igarashitm** [comment]
I don't personally think so since it's redundant. ImportJar=>applyCustomTransformation and ImportJar=>addJavaDocument looks symmetric and intuitive.

**Comment by pleacu** [comment]
Ok - so I'll bail on adding support for returning a list of loadable FQCNs and turn this into 'Remove Enable/Disable Class' icon from the Source/Target panels.

**Comment by pleacu** [comment]
Importing a jar adds it into the classpath.  The enable class icon is needed to use the class as a document (the jar could contain any number of classes, the user must choose one from them as a document).  The enable class has nothing to do with custom field actions.

![sc3](https://user-images.githubusercontent.com/2981421/84815977-d38da800-afe1-11ea-8064-010dfc0f53ee.png)

In the above case the user would import Bicycle.jar and the enable io.paul.Bicycle.
