### ISSUE TITLE
Custom field action jars are not being recognized from ADM files on init.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1415]
We should be getting a lib directory but aren't - using mockdoc.adm

![sc1](https://user-images.githubusercontent.com/2981421/67492064-e2cf7800-f643-11e9-8852-6ed2e6ca0fea.png)

**Comment by pleacu** [comment]
Extraction is okay:
[pleacu@localhost lib]$ ls
15b6b8e5-e8c4-4584-8679-274c1cf752bc.jar  47c42117-f5f2-4735-925c-0b0dba3ec0a4.jar
[pleacu@localhost lib]$ pwd
/home/pleacu/git-clone/atlasmap/standalone/target/lib

**Comment by igarashitm** [comment]
Maybe this one caused it? https://github.com/atlasmap/atlasmap/pull/1322

**Comment by pleacu** [comment]
@igarashitm 
So - there's definitely an issue with custom field actions - could be the example is just out of whack.
Look at these two files:

https://github.com/atlasmap/atlasmap/tree/master/atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/PaulsFieldActions.java
https://github.com/atlasmap/atlasmap/tree/master/atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/PaulsFieldActionsModel.java

They are built automatically - mine are in:

/home/pleacu/git-clone/atlasmap/atlasmap-maven-plugin/target/test-classes/io/atlasmap/maven/test/PaulsFieldActions.class 
/home/pleacu/git-clone/atlasmap/atlasmap-maven-plugin/target/test-classes/io/atlasmap/maven/test/PaulsFieldActionsModel.class

I can copy them to a local empty directory and simply:
`
jar cvf ../PaulsFieldActions.jar *
`
I can successfully import them and enable them (io.atlasmap.service.my.PaulsFieldActions).  My custom transform appears
in the 'Add Transformations' pulldown but I get this when I use it:

Couldn't find a metadata for transformation 'Expression'

which is weird. 

The good news is that I can build/ import/ enable/ use Bicycle.jar

https://github.com/atlasmap/atlasmap/tree/master/atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/Bicycle.java

 If you can take a look at the PaulsFieldAction java files to see if they're wrong that would be great. :)
