### ISSUE TITLE
Map multiple source elements to their own instance in a target array

### ISSUE THREAD

**Issue by Matt-204** [atlasmap/atlasmap#1418]
Being able to map multiple sources to list elements as Key/Value pairs would be nice.
Currently when mapping multiple source elements to the same target you must concatenate or Format all values together with a Template. This is fine if you're trying to map all the values to the same instance of the target.

If the target element is in an array it should allow the user to split up the multiple sources to their own instance element in the array.
The goal is to get an output like below where each Key/Value mapping is it's own `nas:nameValue` in the `nas:additionalFlightInformation` array

![image](https://user-images.githubusercontent.com/6597675/67519924-dcf28a80-f675-11e9-849a-4ed9526c397b.png)

`<nas:additionalFlightInformation`>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nas:nameValue name="cofaxAdmin" value="Joe123"`/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nas:nameValue name="cofaxCDS" value="103"`/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nas:nameValue name="cofaxEmail" value="example@email.com"`/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nas:nameValue name="cofaxTools" value="exampleTools"`/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nas:nameValue name="fileServlet" value="index.html"`/>
`</nas:additionalFlightInformation`>

**Comment by igarashitm** [comment]
This is interesting usecase. It's something similar to what we want with `java.util.Map` (#142), but in JSON/XML.

**Comment by igarashitm** [comment]
So it should be implemented on top of `Collection.MAP` support. Then when you have a collection parent in JSON/XML document, UI should show some button to choose `key` and `value` from its children, then it turns into a `Collection.MAP` field.
