### ISSUE TITLE
Export should allow choosing where to save

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1420]
Export button should show file explorer dialog and let user choose where to save.

**Comment by igarashitm** [comment]
React UI addressed it

**Comment by igarashitm** [comment]
Not sure from when, but React UI doesn't ask where to save, it always download to the browser default directory.

**Comment by pleacu** [comment]
When I first looked at thisthe convention was that web UIs should not allow saving into anything other than the browser default dir (i.e. Downlods) for security sake.
