### ISSUE TITLE
Remove deprecated MappingSerializer method deserializeFieldMappingFromType()

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1433]
Its been deprecated for a while - lets remove it and see if anything fails.  The lookupTable for the enum example seemed the most likely to fail but it seems to work fine.  I

**Comment by igarashitm** [comment]
This is to preserve backward compatibility, to parse old mapping definition which has Mapping types. So don't remove it until AtlasMap2.

**Comment by pleacu** [comment]
Ah - okay...
