### ISSUE TITLE
last deletion of mapping is ignored before exporting

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#1434]
- create a data mapping with 4 mappings
- delete 3 of them
- click on export
- then click on import
--> the last deleted one is back

tested with 1.42.10

**Comment by igarashitm** [comment]
Note that 1.42.10 doesn't contain any fixes we did recently. We can close as "wontfix" if it doesn't reproduce on master.

**Comment by apupier** [comment]
> are you sure you're importing the file you just exported?

yes sure, I was giving a specific name and I got a "are you sure to replace?" dialog when saving.

> your 4 mappings are 4 independent mappings not a single compound mapping with 4 fields, correct?

right, the 4 mappings are independent

> Note that 1.42.10 doesn't contain any fixes we did recently. We can close as "wontfix" if it doesn't reproduce on master.

when will be the next release based on master?
We are currently based on 1.42.5. So regression is between 1.42.5 and 1.42.9. As this is a part of the  basic path when doing development in VS Code, we cannot upgrade to a version with this problem.

I will try to reproduce with master and the different versions.
