### ISSUE TITLE
missing artifacts in maven central repository

### ISSUE THREAD

**Issue by jludvice** [atlasmap/atlasmap#144]
create integration build pod fails on 
```
[ERROR] Failed to execute goal on project project: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: Could not find artifact io.atlasmap:camel-atlasmap:jar:1.17.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project project: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: Could not find artifact io.atlasmap:camel-atlasmap:jar:1.17.0 in central (https://repo.maven.apache.org/maven2)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
```

What is the key in releasing versions to central?
Why some artifacts are present in version `1.10.x`, other in `1.17.x`, and some in 2 versions, some in 3 versions ??

![atlasmap-central.png](https://images.zenhubusercontent.com/5939117e51aa2c305780da73/d3faa91b-29b7-4581-9165-fd9b9797bb0a)

CC @rhuss @jimmidyson @chirino @jknetl @dsimansk

**Comment by chirino** [comment]
try the build with -U ??

**Comment by chirino** [comment]
Ah that camel-atlasmap has a different release cycle.. hum.

**Comment by jludvice** [comment]
This means we can either align releases or update  rest/project-generator to use different version for camel-atlasmap right ?

**Comment by chirino** [comment]
right.

**Comment by chirino** [comment]
I think https://github.com/syndesisio/syndesis-rest/pull/487 should resolve it

**Comment by jludvice** [comment]
@dsimansk fix verified on syndesis-qe instance (I just did update)
