### ISSUE TITLE
Lines don't update when new fields mapped via mapping-details and expression

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1442]
Currently the line machine is controlled by the document-definition component.  Since additional mapped fields can be added by the search box in the mapped details section and by the '@' insert node dropdown we must support the ability to trigger the mapping redraw event from outside of document.

Good chance to clean up the line machine a little.  Caught this is the demo prep.

**Comment by igarashitm** [comment]
Yeah that sounds bad. The mapping change event must be centralized and line machine should just subscribe it.
