### ISSUE TITLE
Support LookupTable from UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#148]
I couldn't find an entry point for adding LookupTable entry from UI

**Comment by mattrpav** [comment]
There probably isn't an 'entry point', but the enum support used lookup tables to implement enum mapping. If you look at enum handling in the UI, you should see the UI creating a lookup table.

**Comment by igarashitm** [comment]
This is the form pops up when clicking an edit link in the `Mapping Details` -> `Action` for the Java Enum mapping
![screenshot from 2017-12-05 17-30-25](https://user-images.githubusercontent.com/265462/33634599-bafb2542-d9e2-11e7-9b32-68bd3788e7d2.png)

As it's pull down boxes for Enum values, looks different from what we need for general LookupTable usage, which needs to allow adding LookupTable entries.
