### ISSUE TITLE
Enable support for mapping asymmetric nested collection where target is deeper

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#1487]
#1486 enables support the other way. It should be possible to map:

`/Person<a>/fullName to /Company<b>/Org<c>/Employee<d>/fullName`
given a=d, b=0, c=0

Consider enabling mapping from nested collection to nested collection with 0 padding in parent levels if source nest  depth < target nest depth. It needs to be clearly communicated to the user that 0 is used for parent levels.

**Comment by igarashitm** [comment]
Yes, it should add WARN in mapping validation so that it's presented in UI.
