### ISSUE TITLE
[GTKA] Add json and xml serialize+deserialize tests for 100% field coverage

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#15]
@mattrpav commented on [Wed Jul 12 2017](https://github.com/atlasmap/atlasmap-runtime/issues/22)

1. Add unit tests to serialize and deserialize reference mappings to and from JSON and XML
2. Validate all fields are processed correctly

**Comment by igarashitm** [comment]
This was unexpectedly closed as a side effect of migration - reopening

**Comment by mattrpav** [comment]
Maven modules:

- atlas-model
- atlas-java-model
- atlas-json-model
- atlas-xml-model
