### ISSUE TITLE
Enable support asymmetric nested collection where source is deeper

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1511]
Map values from a collection when source has more collections on the path than target e.g.

Patient\<a\>/personalDetails\<b\>/name\<c\>/fullName -> Person\<d\>/name\<e\>/fullName

=> By default match source and target indexes from left to right i.e. d=a, e=b*c

Add validation warning that collection indexes are mapped this way. For user defined collection index mapping, we need #781

**Comment by rkorytkowski** [comment]
PR at https://github.com/atlasmap/atlasmap/pull/1900
