### ISSUE TITLE
UI_REACT: Enable 'Show types' in main panel display.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1542]
Currently 'Show types' appears in the options pull-down menu in the react UI:
![sc1](https://user-images.githubusercontent.com/2981421/69738112-8b6d6d80-1103-11ea-8f6f-e76d6a2ce148.png)
It doesn't do anything yet.  It should display the field type as is seen with the angular UI:
![sc2](https://user-images.githubusercontent.com/2981421/69740094-d3da5a80-1106-11ea-861f-c913ffff1cae.png)

Note that the pulldown has a check box (it's toggle-able) - see the 'Toggle mappings column' option for a react equivalent.

Quick build instructions:
Clone a local atlasmap as usual - work from a dev branch off of master
`
 cd ./atlasmap
 git remote add upstream https://github.com/atlasmap/atlasmap.git
 git fetch upstream
 git pull -r upstream master
 git push origin master
 git checkout -b i1523
 ./mvnw clean install -DskipTests -Pitests 
 cd ~/git-clone/atlasmap/standalone
 ../mvnw clean spring-boot:run -Pitests

## I like to build the angular UI so I can compare
 cd ~/git-clone/atlasmap/ui
 ./build.sh --skip-tests -Pitests

## React
cd ~/git-clone/atlasmap/ui-react/
yarn
yarn build
cd ~/git-clone/atlasmap/ui-react/packages/atlasmap-standalone
yarn start
`
Ref: https://github.com/atlasmap/atlasmap/commit/165626ff596b4f0b421ac489352ead5342d37f6b for something similar

**Comment by pleacu** [comment]
@jpav - Hey - just send any questions my or Riccardo's way.

**Comment by riccardo-forina** [comment]
Actually hold on a bit, I have next in my TODO list a refactoring to move the rendering of the element to the consumer side - so, the App - to allow for any kind of visualization (the preview thingy for example)

**Comment by jpav** [comment]
@riccardo-forina I guess let me know when I can pursue this.
