### ISSUE TITLE
NullPointerException when executing syndesis twitter->salesforce integration

### ISSUE THREAD

**Issue by jknetl** [atlasmap/atlasmap#156]
When you create syndesis integration from twitter mention to salesforce create/update contact you get a following NullPointer due to atlasmap:

```
10:23:38.478 [Camel (datamapper-debug) thread #0 - twitter://timeline/mentions] ERROR io.atlasmap.java.module.JavaModule - Unexpected error occured msg=null
java.lang.NullPointerException: null
        at io.atlasmap.java.module.JavaModule.resolveGetMethod(JavaModule.java:410)
        at io.atlasmap.java.module.JavaModule.populateSourceFieldValue(JavaModule.java:220)
        at io.atlasmap.java.module.JavaModule.processInputMapping(JavaModule.java:211)
        at io.atlasmap.java.module.JavaModule.processInputMapping(JavaModule.java:182)
        at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:180)
        at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:193)
...
```

Full stacktrace can be found in the attachments.

CC @mmelko

[datamapper-stacktrace.txt](https://github.com/atlasmap/atlasmap/files/1245258/datamapper-stacktrace.txt)

**Comment by jknetl** [comment]
I tried to look into the integration bit more. The problem arises in the [JavaModule class lines 183-186:](https://github.com/atlasmap/atlasmap/blob/master/atlas-java-parent/atlas-java-module/src/main/java/io/atlasmap/java/module/JavaModule.java#L183-L186)

```Java
Object sourceObject = session.getInput();
;
if (field.getDocId() != null) {
    sourceObject = session.getInput(field.getDocId());
}
```
The `session.getInput();` returns the twitter4j status properly, so the [session object](https://github.com/atlasmap/atlasmap/blob/1e670d901e2e19a9f024dd4ff33c16437a1b393d/atlas-core/src/main/java/io/atlasmap/core/DefaultAtlasSession.java#L108) holds the input under default document id. However, the `field.getDocId()` returns "twitter4j.Status". Therefore on the [second lookup](https://github.com/atlasmap/atlasmap/blob/master/atlas-java-parent/atlas-java-module/src/main/java/io/atlasmap/java/module/JavaModule.java#L186) the source object is overwritten by a null value. Since the session object doesn't hold any input with "twitter4j.Status".

I can see two solutions to this. 

1. We could edit JavaModule to fallback to the input stored under the default key in case that data for a specific key are null. 
2. We could make sure to always store the input object under proper key in the DefaultAtlasSession, but I don't know how much code would be affected by this. In this particular case the input object is being stored by [AtlasEndpoint.java in camel-atlasmap module](https://github.com/atlasmap/camel-atlasmap/blob/master/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java)

What do you think?

**Comment by rhuss** [comment]
This is related to https://github.com/atlasmap/camel-atlasmap/issues/14

**Comment by rhuss** [comment]
Actually, it would be interesting to know what the actual logic is supposed to do, i.e. why when there is a docId set the input is not stored under this docId but the default value. So I think the second solution is the proper one.

Currently, we are trying to adapt camel-atlasmap to the new version of atlasmap, to yet another point to fix this in this module.

@jknetl Fancy doing a PR ? ;-) 

// @igarashitm

**Comment by igarashitm** [comment]
@rhuss this is actually a same issue as atlasmap/camel-atlasmap#14, and I'm not sure if camel-atlasmap have to introspect the mapping definition and seek a docId for the input object. I would expect atlasmap runtime to make it internally/automatically.

**Comment by igarashitm** [comment]
With a secound thought, no it can't be automatic. If it's a Java class and the docId is the class name it's just easy, don't even have to look into the mapping def. But what if the input is JSON/XML? maybe the targetNamespace would be the one for XML, but is there any reserved property for identifying JSON input even if there's a reserved property, should camel-atlasmap parse the XML/JSON input everytime before pass it into atlasmap runtime? No I don't think so...

So my guess is that the docId-payload map should be provided as an input body or header/property kind of thing to the camel-atlasmap endpoint, otherwise input body should be assumed as a default&single input. If input is a single object, docId should not be specified in the map, or atlasmap runtime should check if there's any input object other than default, if there isn't just use default regardless of the docId specified on that field.

It's just my guess might be wrong... I do want to know the intention around this one.

**Comment by igarashitm** [comment]
OK so here is a solution I concluded for now
atlasmap/atlasmap#159

Putting aside how camel-atlasmap should handle multiple input/output (see atlasmap/camel-atlasmap#18), #159 allows to fallback to the default input object if there's no input object with specified docId as a key.

**Comment by igarashitm** [comment]
Fixed - atlasmap/atlasmap#159

**Comment by jknetl** [comment]
@rhuss I wanted to create a PR, but I didn't know the backgroud so I wanted a feedback. Unfortunately, I was out since Thursday.

Anyway, I am happy to see the issue fixed. Thank you!

**Comment by rhuss** [comment]
Yes, just need to release atlasmap so that it bubbles up to the runtime. Just need another fix for the filter, too, but I will release soonish (today).
