### ISSUE TITLE
Ability to reference model items in field action parameters

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#158]
There are many scenarios where a user might want to reference items in the source/target models to be used within parameters for field actions.  For instance, the string used as a parameter for the StartsWith action might be the contents of another model item. Or to create a complete address that ultimately gets placed in a target as a string, many of its components may need to involve several actions.

**Comment by igarashitm** [comment]
Couldn't it be achieved chaining field actions?

**Comment by jpav** [comment]
In simple cases only.  To expound more on my first example, consider a field A that you want to use StartsWith to only retrieve the beginning of, but the substring to retrieve is determined by field B. Or the user wants to square the value of field A and add it to the squared value of field B, then store it in target field C.
