### ISSUE TITLE
Integration with Apache NiFi

### ISSUE THREAD

**Issue by AbbassFaytaroony** [atlasmap/atlasmap#1582]
Similar to Apache Camel integration, Apache NiFi [https://nifi.apache.org/](url) is a leading Data flow manager. Typically used to implement  ETL  data flows. Integrating AtlasMap with Apache NiFi will be huge in terms of simplifying data transformation tasks.

**Comment by indiealexh** [comment]
Would this be best requested here or at Nifi Side?

**Comment by AbbassFaytaroony** [comment]
> Would this be best requested here or at Nifi Side?
Initially it was opened here similar to what is done with Camel integration.

Typically this kind of integration is opened and implemented on Nifi side, where a Processor (and maybe a Controller Service) are implemented. 

But in this particular case, we have the possibility to add AtlasMap UI in the [Nifi Processor's Custom UI](https://docs.cloudera.com/HDPDocuments/HDF3/HDF-3.4.0/adding-functionality-to-apache-nifi/content/custom-processor-uis.html). But given that the application switched to react, it's a bit harder now.

This would need a deeper investigation, but for now, i think it is better to be done here, unless @igarashitm and the rest of the team have other thoughts :)
