### ISSUE TITLE
ui-react gets error where it doesn't pass mappingDefinitionId

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1585]
mappingDefinitionId, etc.
`
grep -R 'mappingDefinitionId'
services/file-management.service.ts:      const url = this.cfg.initCfg.baseMappingServiceUrl + 'mappings/' + this.cfg.mappingDefinitionId
services/file-management.service.ts:      const url = this.cfg.initCfg.baseMappingServiceUrl + 'mapping/RESET/' + this.cfg.mappingDefinitionId;
services/file-management.service.ts:    const mappingDefinitionIds: number[] = [this.cfg.mappingDefinitionId];
services/file-management.service.ts:      for (const mappingDefinitionId of mappingDefinitionIds) {
services/file-management.service.ts:        const url: string = baseURL + mappingDefinitionId;
services/file-management.service.ts:    return this.cfg.mappingDefinitionId;
services/mapping-identifier.service.ts:    const mappingDefinitionId: number = +urlMappingId;
services/mapping-identifier.service.ts:    if (isNaN(mappingDefinitionId) || mappingDefinitionId == null) {
services/mapping-identifier.service.ts:    return mappingDefinitionId;
services/initialization.service.ts:            this.cfg.mappings = new MappingDefinition(this.cfg.mappingDefinitionId);
services/initialization.service.ts:          this.cfg.mappings = new MappingDefinition(this.cfg.mappingDefinitionId);
services/initialization.service.ts:            await this.fetchMappingById(this.cfg.mappingDefinitionId);
services/initialization.service.ts:                if (!await this.fetchMappingById(this.cfg.mappingDefinitionId)) {
services/initialization.service.ts:        + this.cfg.mappingDefinitionId).toPromise()
services/initialization.service.ts:            this.cfg.mappingDefinitionId);
services/initialization.service.ts:  async fetchMappingById(mappingDefinitionId: any): Promise<boolean> {
services/initialization.service.ts:      if (mappingDefinitionId == null) {
services/initialization.service.ts:      this.cfg.mappingService.fetchMappings([mappingDefinitionId], this.cfg.mappings).toPromise()
services/mapping-management.service.ts:      const url: string = this.cfg.initCfg.baseMappingServiceUrl + 'mapping/validate/' + this.cfg.mappingDefinitionId;
utils/mapping-serializer.ts:      cfg.mappings = new MappingDefinition(cfg.mappingDefinitionId);
utils/mapping-serializer.ts:    cfg.mappings.name = this.deserializeAtlasMappingName(json, cfg.mappingDefinitionId);
utils/mapping-serializer.ts:   * Return the AtlasMap mappings file name from the specified JSON buffer or an generate it from mappingDefinitionId.
utils/mapping-serializer.ts:  static deserializeAtlasMappingName(json: any, mappingDefinitionId: number): string {
utils/mapping-serializer.ts:      return 'UI.' + mappingDefinitionId;
utils/mapping-serializer.spec.ts:    cfg.mappingDefinitionId = 0;
components/toolbar/toolbar.component.ts:        fileName = 'atlasmap-mapping-' + this.cfg.mappingDefinitionId + '.adm';
components/data-mapper-example-host.component.ts:    c.mappingDefinitionId = this.mappingIdentifierService.getCurrentMappingDefinitionId();
models/mapping-definition.model.ts:  constructor(mappingDefinitionId: number) {
models/mapping-definition.model.ts:    this.name = MappingDefinition.MAPPING_NAME_PREFIX + mappingDefinitionId;
models/config.model.ts:  mappingDefinitionId: number;
`

**Comment by igarashitm** [comment]
Talked with Paul, it should be possible to make {mappingDefinitionId} optional at backend side, and assume 0 if omitted. Real migration will be left with #1577

**Comment by AbbassFaytaroony** [comment]
@igarashitm So shall i take this? @pleacu did you start with it? I did not leave mappingDefinitionId optional at the backend to enforce all front-end API calls to include it. I will try to hurry up in #1577 to avoid such things in the future

**Comment by pleacu** [comment]
Hey @AbbassFaytaroony - I've got this one.  Can you try with the angular UI the following:
1.  Import from <clone-dir>/atlasmap/ui/test-resources/adm/mockdoc.adm
2.  Export the ADM (Export Icon on toolbar)
3.  Reset All  (Panel Settings > Reset All)
4.  Import from your Downloads folers the adm you exported in step 2

thnkx!

**Comment by igarashitm** [comment]
@AbbassFaytaroony no sweat, I think Paul is almost finishing this.

**Comment by AbbassFaytaroony** [comment]
@pleacu Ok, on it.

**Comment by AbbassFaytaroony** [comment]
#1588
