### ISSUE TITLE
Mappings of an imported ADM catalog can be lost

### ISSUE THREAD

**Issue by AbbassFaytaroony** [atlasmap/atlasmap#1588]
As @pleacu described, going through:

1. Import from /atlasmap/ui/test-resources/adm/mockdoc.adm
2. Export the ADM (Export Icon on toolbar)
3. Reset All (Panel Settings > Reset All)
4. Import from your Downloads folder the adm you exported in step 2

The resulting mapping file has no mappings inside.

**Comment by pleacu** [comment]
I'm suffering the same issue with the react UI.  This clearly used to work - don't know if it was functioning prior to your big PR (no blame - just curious when it last worked).  It appears to be related to how exportMappingsCatalog() works (and sanitizeJSON).  I think it needs a JSON styringify but it appears it is getting one...

**Comment by AbbassFaytaroony** [comment]
Actually i just saw the problem. No its backend related to how i am overwriting the current catalog.    So as soon as i push the fix it will resolve both angular and react.

**Comment by pleacu** [comment]
Cool - look forward to it! :)
