### ISSUE TITLE
Increate unit test coverage of atlas-core

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#16]
@mattrpav commented on [Wed Jul 19 2017](https://github.com/atlasmap/atlasmap-runtime/issues/36)

- [x] DefaultAtlasCombineStrategy (100%)
- [ ] DefaultAtlasContext
- [ ] DefaultAtlasContextFactory
- [ ] DefaultAtlasConversionService (74%)
- [x] DefaultAtlasPropertyStrategy (84%)
- [x] DefaultAtlasSeparateStrategy (100%)
- [x] DefaultAtlasSession (100%)
- [x] DefaultAtlasValidationService (88%)
- [x] StringDelimiter (86%)

- [x] io.atlasmap.actions (85%)
- [x] io.atlasmap.converters (99%)
- [x] io.atlasmap.validators (70%)

**Comment by igarashitm** [comment]
This was unexpectedly closed as a side effect of migration - reopening

**Comment by rohanmars** [comment]
closed by #204
