### ISSUE TITLE
Provide ability to set and use variables

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#160]
This is somewhat related to #158. Having named variables would allow intermediate results of actions to be stored for later use in subsequent action parameters. Not sure, but it might make sense to use properties for this, with the main concern being these are currently source-only entities.

**Comment by igarashitm** [comment]
Does it mean field actions are going to have dependencies each other? If so It doesn't sound good.

**Comment by mattrpav** [comment]
I understand the idea, and see parallels in other frameworks. I'd be curious to see a concrete use case.

FYI-- Properties are modeled to be mapping-wide. The PropertyField may only be processed on source right now, but it would be nominal effort to allow for PropertyField to be target-able.

**Comment by jpav** [comment]
@mattrpav, I figured we could use properties architecturally, but not sure how we'd represent them visually if they're being used as either source and target, and thus thought maybe we'd want to create a new construct for these.  Either way though.

@igarashitm, no, it does not mean the actions are dependent on each other.  It would mean that they'd have to have access to existing variables and be able to create new ones.

What I'm ultimately going for is the ability to do more advanced chaining, where results can be not only the input to a subsequent transformation, but also the input to specific parameters with subsequent transformations, allowing for multiple-parameter functions to be fed from multiple paths of logic. Consider if the user wants to map source field A to target field B only if source/target field C contains a particular value. Or he wants to total up the values from a collection of source fields, total up a separate source field collection, then store the ratio of the two in a target field. There are literally endless scenarios where this could be desired by users.

**Comment by mattrpav** [comment]
@jpav I think there is a group of scenarios that you are describing can be captured by using Source-side FieldActions in combination with Combine / Separate and then Target-side FieldActions to complete it.

Source fieldA -> FieldAction chain \
                                                           +--- Combine ---> Target fieldC -> FieldAction chain
Source fieldB -> FieldAction chain /

My sense is, there is a class of use cases that exceed the ability for the UI to effectively represent them and we can box those off in "custom processor" land. As user feedback comes in, we can be more informed about how far down the build-a-logical-workflow-UI rabbit hole we should venture.

**Comment by igarashitm** [comment]
Not sure if it fits with this case though, I introduced `AtlasInternalSession` on top of `AtlasSession`, was intended to keep engine internal stuffs. the `Head` in the session holds current mapping entry, as well as source/target field currently being processed.
https://github.com/atlasmap/atlasmap/blob/master/runtime/api/src/main/java/io/atlasmap/spi/AtlasInternalSession.java

**Comment by jpav** [comment]
@mattrpav I agree there are a group of scenarios that could be addressed with that approach, but there's many others that don't fit.  As another example, consider an action that groups information from the source, such as employee info, into the target.  The source structure might contain a department in each employee record, along with their first and last name as separate fields.  The intention for the mapping could be combine the first and last names into a single name string and finally map those names to collections inside corresponding containers named by department.

This doesn't need to be short-term, of course, but I feel that with a few enhancements like what I've proposed with variables and model references, we could avoid most scenarios where the user has no choice other than to write a custom processor while still keeping the workflow simple enough to create and understand for a citizen user.

**Comment by jpav** [comment]
Before long, we should be able to handle more complex mappings involving multiple transformations, some of which may require interim results with types that don't necessarily match either the source or the target, and thus require some type of interim variable or result support.

As an example (obviously somewhat contrived), consider a source that contains a text field containing brief car descriptions, such as '67 Chevy Camaro', and a target that needs to be populated with data about the cars, like tire size (also a text field). The tire size needs to be determined based on a lookup using the cars year make and model. But in my example, the year is only 2-digits, so it first must be parsed out of the string and converted to a 4-digit year before it can be used in conjunction with the rest of the car description to perform the lookup. This will require interim transformations that will involve this year being treated as a date or possibly a number.

Thus, we'd need to be able to specify a result or variable as a target of a transformation. This certainly will have a significant impact on the UI, so the UX team will need to be involved heavily.

**Comment by jpav** [comment]
Actually, there's a much simpler example demonstrating why we need this now. Consider if a user wants to add two numbers in two different source fields and put the result in a target field. At the moment, we can't do this. The add action that we currently have in the runtime can operate on a list or array of numbers, so once we have a 'group' transformation available (#244) and can thus group two numeric fields into an array/list, we'll be one step closer, but still not there. The problem is, the way things work today, actions are only available if the target field type matches the action result type. Even once source transformations (#278) are available, this is still an issue for this simple example since both source and target would be numbers, not array/list.
