### ISSUE TITLE
UI_REACT - Canvas display issues with older versions of Chrome and Safari

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1603]
The CanvasViewLayoutProvider object height becomes 0 if the width exceeds 752 px.  This fails with Chrome Version 71.0.3578.98 (Official Build) (64-bit) and Safari (13.0.4 - Catalina).

PF's Page/PageSection layout bit that's playing dirty tricks.

This works:
![sc1](https://user-images.githubusercontent.com/2981421/70921124-b3a90780-1ff1-11ea-9b2a-163578b24843.png)

This doesn't:
![sc2](https://user-images.githubusercontent.com/2981421/70921157-c1f72380-1ff1-11ea-8d89-bec47110b2e6.png)

**Comment by riccardo-forina** [comment]
Not stale

**Comment by riccardo-forina** [comment]
Fixed by https://github.com/atlasmap/atlasmap/pull/1816
