### ISSUE TITLE
Support new Conditional Mapping Expression

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1604]
Switch from `Expression` field action that belongs to a field to the one right under the `Mapping` which supports dynamic path resolution (#1512)
https://github.com/atlasmap/atlasmap/blob/master/lib/model/src/main/java/io/atlasmap/v2/Mapping.java#L28

New expression supports COMPLEX field as a parameter, which enables more advanced usecase like filtering #1507. 

xref: https://issues.redhat.com/browse/ENTESB-12402

**Comment by igarashitm** [comment]
Here is an example for `filter` & `select` function that relies on dynamic path expression.
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/resources/mappings/atlasmapping-expression-filter-select-java.json#L18

Note that first path expression is absolute (include documentId) and the others are relative.

**Comment by pleacu** [comment]
This epic is now complete for initial release.  Any refactoring or new ideas should be addresses by a new issue.

**Comment by igarashitm** [comment]
Reopening - primary focus for this issue is to support filter/select which requires COMPLEX field support in UI.

**Comment by pleacu** [comment]
Hey @igarashitm 

Given this as an example (from atlas-itests-core-2.1.0-SNAPSHOT-tests.jar), the user has a simple mapping
from `/someArray<>/someField` to `/someArray<>/someField`.  They then establish this conditional expression
to the mapping:

`SELECT( FILTER( ${SourceClass:/someArray<>}, ${/someField} != 'v1' ), ${/someField} )`

![sc1](https://user-images.githubusercontent.com/2981421/86836964-42ec3a00-c06c-11ea-8aae-a82014199971.png)

In this scenario, someArray needs to be selectable from the conditional expression pull-down menu not as a mappable element but as a reference component in the expression with 

field.serviceObject.status = 'SUPPORTED'
field.serviceObject.fieldType = 'COMPLEX'

, correct?  The user would see something like:

![sc3](https://user-images.githubusercontent.com/2981421/86837232-9bbbd280-c06c-11ea-80e9-71ad7142d4c4.png)

Is this accurate?

**Comment by igarashitm** [comment]
Right, I'm not sure if it should be selectable or not though. From this point, COMPLEX field does participate into mapping, but only for conditional mapping ATM.

**Comment by pleacu** [comment]
@igarashitm - Ok - so I am going to make the COMPLEX element `/someArray[]` selectable *only* from the conditional expression *@* pull down so users can add the element into their expression but not from the main source panel.

**Comment by pleacu** [comment]
Here's what I've got now:
![sc1](https://user-images.githubusercontent.com/2981421/87180978-8a163d00-c2af-11ea-8b18-5f5e9f37438e.png)

Generates:
![sc2](https://user-images.githubusercontent.com/2981421/87181005-94d0d200-c2af-11ea-8e31-eb56e260a615.png)

**Comment by pleacu** [comment]
Hey @igarashitm - a couple of questions for you.

This mapping is consumed by the backend server ok.  Note that it's passing `inputField`, not `inputFieldGroup`.  Also - the `someArray` reference is using `[]` instead of `<>`.

![sc1](https://user-images.githubusercontent.com/2981421/87557663-2f515c80-c686-11ea-8b9d-42880f4e6ca4.png)

If I modify it to pass `inputFieldGroup` instead of `inputField` (everything else the same) I get the following error:

`Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String that contains type id (for subtype of io.atlasmap.v2.FieldGroup)
 at [Source: (String)"{"AtlasMapping":{"jsonType":"io.atlasmap.v2.AtlasMapping","dataSource":`

Here's a debug capture to see the inputFieldGroup:

![sc2](https://user-images.githubusercontent.com/2981421/87559121-dedafe80-c687-11ea-96d7-8d6751b46cb1.png)

Q1: Can you see what's wrong with the `inputFieldGroup` JSON?  Is using `inputField`with a `io.atlasmap.v2.FieldGroup` field type okay or must it be `inputFieldGroup`?

Q2: Is using `[]` okay?


Thanks!

**Comment by igarashitm** [comment]
Just a wild guess, are you passing an array for `inputFieldGroup`? unlike `inputField` that is an array of `Field`, `inputFieldGroup` have to be a single field, so no array quotation `[]`.
`[]` means array and `<>` means list, it only matters for Java Document. IIRC this is optional though, both would work just fine.

**Comment by igarashitm** [comment]
So, when the expression refers to multiple `COMPLEX` fields, those have to be wrapped with a parent FieldGroup that would be anonymous wrapping one.

**Comment by igarashitm** [comment]
BTW, the "caused by" you pasted looks incomplete, as dataSource is not related to this problem. It should have more following text.

**Comment by pleacu** [comment]
Can you cobble up an example JSON mapping for multiple COMPLEX fields vs a single COMPLEX field?  (just by hand).  It's easier to adjust things with the expected results in hand.

**Comment by pleacu** [comment]
Awesome - I was passing an array for `inputFieldGroup`.  I now get no errors with:

![sc3](https://user-images.githubusercontent.com/2981421/87563188-f23c9880-c68c-11ea-8848-59397746f30d.png)

I'll next dive into multiple complex fields - if you can toss an example I'd appreciate it!  Thanks Tomo!

**Comment by igarashitm** [comment]
An example of anonymous wrapping `inputFieldGroup` is here, having `sourceFirstName` and `sourceLastName`
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-split.json#L18-L40

In case expression refers to multiple COMPLEX field, each of those have to be FieldGroup (i.e. `"jsonType" : "io.atlasmap.v2.FieldGroup"`) and wrapped with anonymous one.

**Comment by pleacu** [comment]
Anonymous mapping example looks good:

![sc4](https://user-images.githubusercontent.com/2981421/87574986-3768c680-c69d-11ea-9d13-29c071687992.png)

**Comment by pleacu** [comment]
So a single mapping (`mappedField`) with multiple complex references.  Does this make sense??

![sc5](https://user-images.githubusercontent.com/2981421/87576412-59fbdf00-c69f-11ea-8bd8-00b708b0b5d8.png)

**Comment by igarashitm** [comment]
`filter(someArray, someString !='v11')` returns filtered `someArray`, not the `someField`. it's `select()` function that extracts sub-field.
And because it's same `someArray`, inputFieldGroup only contains single `someArray`, isn't it? It might be OK to put the duplicate though.

**Comment by pleacu** [comment]
So the correct JSON would be this?  A shared `inputFieldGroup` with two fields in the `field` array - one for `someField` and one for `someString`?

`   "inputFieldGroup" : {`
`         "jsonType" : "io.atlasmap.v2.FieldGroup",`
`          "actions" : [ ],`
`          "docId" : "io.atlasmap.itests.core.SourceClass",`
`          "path" : "/someArray[]",`
 `         "fieldType" : "COMPLEX",`
 `         "field" : [ {`
 `           "jsonType" : "io.atlasmap.java.v2.JavaField",`
`            "docId" : "io.atlasmap.itests.core.SourceClass",`
 `           "path" : "/someArray[]/someField",`
 `           "fieldType" : "STRING",`
 `          "name" : "someField"`
 `         },`
 `        {`
`            "jsonType" : "io.atlasmap.java.v2.JavaField",`
`           "docId" : "io.atlasmap.itests.core.SourceClass",`
`            "path" : "/someArray[]/someString",`
`            "fieldType" : "STRING",`
`            "name" : "someString"`
`          } ] ]`

**Comment by igarashitm** [comment]
Yep that looks correct.

**Comment by pleacu** [comment]
Okay - I think I've got it.  What I'd like to do is save handling a compound conditional with complex references of two distinct complex fields (as opposed to the same complex field) for a TODO.

![sc6](https://user-images.githubusercontent.com/2981421/87701713-61d28680-c766-11ea-9875-5a17d00f3d18.png)
