### ISSUE TITLE
Add README for itests/reference-mappings

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#167]
Add README for itests/reference-mappings
https://github.com/atlasmap/atlasmap/tree/master/runtime/itests/reference-mappings

* Abstract, Concepts, Benefit
* Naming rule and what that name corresponds to
  * like autoconversion is testing type conversion, and autoconversion1 means what? then what is the difference with autoconversion2?
  * Policy for the field order in the mappings?

The immediate need would be to implement #9 , it would require to add a whole set of cross format testings on top of existing Java, Json, XML. Need enough information to do that.

**Comment by igarashitm** [comment]
Hi @mattrpav ,
Could somebody with you do this?

**Comment by jimmidyson** [comment]
@igarashitm Can this be deferred to TP4?
