### ISSUE TITLE
Enable using MANY-TO-ONE tansformations on collection fields in UI

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#1690]
It's currently supported to use a collection field together with other source fields, but one cannot apply a MANY-TO-ONE transformation such as Concatenate on a collection field in the UI, even though it is supported by the backend. Enable that in the UI.
E.g.
```
{
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputFieldGroup" : {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ {
            "Concatenate" : {
              "delimiter" : ","
            }
          } ],
          "field" : [ {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "actions" : [ {
              "Concatenate": {
                "delimiter": ","
              }
            } ],
            "docId" : "io.atlasmap.itests.core.issue.SourceClass",
            "index" : 0,
            "path" : "/sourceStringList<>",
            "fieldType" : "STRING",
            "name" : "sourceStringList"
          }, {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.itests.core.issue.SourceClass",
            "index" : 1,
            "path" : "/sourceLastName",
            "fieldType" : "STRING",
            "name" : "sourceLastName"
          } ]
        },
        "inputField" : [ ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.itests.core.issue.TargetClass",
          "path" : "/targetFullName",
          "fieldType" : "STRING",
          "name" : "targetFullName"
        }
```

**Comment by rkorytkowski** [comment]
Related to #1687

**Comment by igarashitm** [comment]
We have put a limitation to have only one multiplicity transformation as a special one and it's explicitly expressed in UI. For those complex mappings that requires to break this limitation, Conditional Mapping with expression is the way to go.

However allowing one-to-many/many-to-one as a regular field transformation for simpler usecases like this is something we can address in regular mapping as well. We might also have to reconsider about how to express multiplicity transformation in UI.

Also note that there's some feedback that having both of source and target transformation is not easy to understand. This separation only makes sense on one-to-many/many-to-one mapping - IOW, it's all about if the transformation have to be applied `before multiplicity transformation` or `after multiplicity transformation` where the multiplicity of fields to apply transformation differs. We might also have to reconsider about this mental model.
