### ISSUE TITLE
Could not find document for mapped field 'email' at URI atlas:xml:sample

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#1710]
- start AtlasMap 1.43.3 with standalone or within VS Code
- import instance of file sample.json with content for source
```
 {
    "name":"",
    "surname":"",
    "email":""
}
```
- import instance of file sample.xml with content for target:
```
<record>
    <age>40</age><first_name>Stevie</first_name><last_name>Probate</last_name><email>sprobatepm@parallels.com</email><gender>Male</gender>
</record>
```
- map name with last_name and email with email
- export
- clear mapping
- import the exported adm file

![Screenshot from 2020-01-28 15-37-21](https://user-images.githubusercontent.com/1105127/73273367-278b2200-41e4-11ea-857b-2506ef33fc15.png)

**Comment by igarashitm** [comment]
This is because the document name is conflicting, UI should assign unique document ID apart from its file name. A workaround is to use different file name even if extension is ommitted.
