### ISSUE TITLE
UI_REACT: correct main toolbar icons

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1728]
Main toolbar - react UI

* Import OK
* Export OK
* Reset All - needs an icon but functional
* Show/ Hide mapping preview - widgets active - results incorrect
* Show/ Hide mapping table - non functional
* Show/ Hide namespace table - non functional
* Show/ Hide types - enable: ok  disable: fails (show types remains)
* Show/ Hide mapped fields - OK
* Show/ Hide unmapped fields - OK
* Show/ Hide free view
  - on select - mouse wheel works but no + or - icons
  - second select - no change
  - select Show/Hide mapped fields - the +, - and Reset view icons appear
* +, - and Reset View icons work correctly when enabled
  - when the +, - and Reset view icons are visible the second select of  Show/ Hide free view works OK

**Comment by jpav** [comment]
Some of these should be separate issues, as they are either just not yet implemented, like mapping and namespace tables, or, in the case of Reset All, were intentionally implemented that way.

**Comment by jpav** [comment]
Fixed by PR #1784
