### ISSUE TITLE
Custom field action arguments fail validation

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1757]
This fails in both UIs
To reproduce:
   1.  load mockdoc.adm
   2.  change any index value
   3.  observe the backend server log output:

ref: `processActionArguments -n mapping-serializer`
https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts#L344

`javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at io.atlasmap.service.AtlasService.fromJson(AtlasService.java:1022) ~[atlas-service-1.44.0-SNAPSHOT.jar:1.44.0-SNAPSHOT]
	at io.atlasmap.service.AtlasService.validateMappingRequest(AtlasService.java:607) ~[atlas-service-1.44.0-SNAPSHOT.jar:1.44.0-SNAPSHOT]`

`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "paulsParam" (class io.atlasmap.v2.CustomAction), not marked as ignorable (5 known properties: "inputFieldType", "name", "methodName", "className", "outputFieldType"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.atlasmap.v2.AtlasMapping["mappings"]->io.atlasmap.v2.Mappings["mapping"]->java.util.ArrayList[1]->io.atlasmap.v2.Mapping["inputFieldGroup"]->io.atlasmap.v2.FieldGroup["field"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonField["actions"]->io.atlasmap.v2.CustomAction["paulsParam"])`

**Comment by pleacu** [comment]
Fixed by https://github.com/atlasmap/atlasmap/commit/e9f72cf3f03c39cee8ee57db50dc9e199988af31

**Comment by emilywwj** [comment]
@pleacu is this fixed?

**Comment by pleacu** [comment]
available in 1.44.0-M1 - I'll look at i1932 as soon as I can

**Comment by pleacu** [comment]
Need to reverify this in conjunction with i1932

**Comment by pleacu** [comment]
Hey @rkorytkowski @igarashitm - Sending to both Rafal and Tomo as both may have some insights.

I need some help defining custom field actions from the UI.  I'm using:

https://github.com/atlasmap/atlasmap/tree/master/lib/service/src/test/resources/upload/io/atlasmap/service/my/MyFieldActions.java
https://github.com/atlasmap/atlasmap/tree/master/lib/service/src/test/resources/upload/io/atlasmap/service/my/MyFieldActionsModel.java

to build a local MyFieldActions.jar.  I have a simple one-to-two mapping and then import this jar.  What's interesting about  MyFieldActions.jar is that the custom field action takes one argument.  My question is - what should the requesting JSON from the UI look like?

## Option 1:
In this example - I lead with the parameter and generate an @type containing the custom class:

`{"AtlasMapping":{"jsonType":"io.atlasmap.v2.AtlasMapping","dataSource":[{"jsonType":"io.atlasmap.json.v2.JsonDataSource","id":"s","uri":"atlas:json:s","dataSourceType":"SOURCE"},{"jsonType":"io.atlasmap.json.v2.JsonDataSource","id":"t","uri":"atlas:json:t","dataSourceType":"TARGET","template":null}],"mappings":{"mapping":[{"jsonType":"io.atlasmap.v2.Mapping","id":"mapping.698435","inputField":[{"jsonType":"io.atlasmap.json.v2.JsonField","name":"address","path":"/address","fieldType":"STRING","docId":"s","userCreated":false,`

`"actions":[{"delimiter":" ","@type":"Split"}]}],`

`"outputField":[{"jsonType":"io.atlasmap.json.v2.JsonField","name":"city","path":"/city","fieldType":"STRING","docId":"t","userCreated":false,"index":0,`

**Look here!!** *****************************
`"actions":[{"param":"car","@type":"io.atlasmap.service.my.MyFieldActionsModel","name":"io.atlasmap.service.my.MyFieldActionsModel","className":"io.atlasmap.service.my.MyFieldActionsModel","methodName":"myCustomFieldAction"}]},`

`{"jsonType":"io.atlasmap.json.v2.JsonField","name":"country","path":"/country","fieldType":"STRING","docId":"t","userCreated":false,"index":1}]}]},"name":"UI.0","lookupTables":{"lookupTable":[]},"constants":{"constant":[]},"properties":{"property":[]}}}`

This results in the following error:
   `Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid type id: io.atlasmap.service.my.MyFieldActionsModel (through reference chain: io.atlasmap.v2.AtlasMapping["mappings"]->io.atlasmap.v2.Mappings["mapping"]->java.util.ArrayList[0]->io.atlasmap.v2.Mapping["outputField"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonField["actions"])`

## Option 2:
In this example I use `CustomActio` as the type but there's no place to put the parameter.

`{"AtlasMapping":{"jsonType":"io.atlasmap.v2.AtlasMapping","dataSource":[{"jsonType":"io.atlasmap.json.v2.JsonDataSource","id":"s","uri":"atlas:json:s","dataSourceType":"SOURCE"},{"jsonType":"io.atlasmap.json.v2.JsonDataSource","id":"t","uri":"atlas:json:t","dataSourceType":"TARGET","template":null}],"mappings":{"mapping":[{"jsonType":"io.atlasmap.v2.Mapping","id":"mapping.698435","inputField":[{"jsonType":"io.atlasmap.json.v2.JsonField","name":"address","path":"/address","fieldType":"STRING","docId":"s","userCreated":false,`

`"actions":[{"delimiter":" ","@type":"Split"}]}],`

`"outputField":[{"jsonType":"io.atlasmap.json.v2.JsonField","name":"city","path":"/city","fieldType":"STRING","docId":"t","userCreated":false,"index":0,`

**Look here!!** *****************************
`"actions":[{"param":"car","@type":"CustomAction","name":"io.atlasmap.service.my.MyFieldActionsModel","className":"io.atlasmap.service.my.MyFieldActionsModel","methodName":"myCustomFieldAction"}]},`

`{"jsonType":"io.atlasmap.json.v2.JsonField","name":"country","path":"/country","fieldType":"STRING","docId":"t","userCreated":false,"index":1}]}]},"name":"UI.0","lookupTables":{"lookupTable":[]},"constants":{"constant":[]},"properties":{"property":[]}}}`

This results in the following error:
`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "param" (class io.atlasmap.v2.CustomAction), not marked as ignorable (5 known properties: "inputFieldType", "name", "methodName", "className", "outputFieldType"])`

**Note:** there is no error generated if I don't pass the user parameter.

Q:  Should I use `"@type":"io.atlasmap.service.my.MyFieldActionsModel"` and if so what's wrong with the type id or should I use `"@type":"CustomAction","name"` and if so where does the parameter get passed?  Both appear to be supported.

**Comment by igarashitm** [comment]
IIRC option1 is the way to go
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/reference-mappings/src/test/resources/javaToJava/atlasmapping-collection-fieldaction2.json#L27-L28

The error message sounds like you have `id` as a child of `/mappings/mapping[0]/outputField[0]/actions`? did you check mapping definition in the real payload UI is sending? should be visible via chrome devtool network tab.

**Comment by pleacu** [comment]
@igarashitm - this is the real payload that's failing from the network tab:
`actions: [{param: "c", @type: "io.atlasmap.service.my.MyFieldActionsModel"}]
  0: {param: "c", @type: "io.atlasmap.service.my.MyFieldActionsModel"}
    param: "c"
    @type: "io.atlasmap.service.my.MyFieldActionsModel"`
   
Error:

 `Caused by: java.lang.IllegalArgumentException: Invalid type id: io.atlasmap.service.my.MyFieldActionsModel`

Looking at your example and looking at MyFieldActions.java, MyFieldActionsModel.java I also tried these two:

'{"@type":"io.atlasmap.service.my.MyFieldActions$MyFieldActionsModel","param":"car"}'

and

'{"@type":"io.atlasmap.service.my.MyFieldActions$io.atlasmap.service.my.MyFieldActions.MyFieldActionsModel","param":"car"}'

They generate the same backend error ( Invalid type id )

**Comment by igarashitm** [comment]
I'll look into later

**Comment by pleacu** [comment]
Here's my latest attempt - similar to the example:

Source:
![sc5](https://user-images.githubusercontent.com/2981421/84198926-4cd14c00-aa72-11ea-82de-6a7955f629ca.png)


`"actions":[{"@type":"io.atlasmap.service.my.MyFieldActions$Concur","separator":"+"}]},`

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid type id: io.atlasmap.service.my.MyFieldActions$Concur (through reference chain: io.atlasmap.v2.AtlasMapping["mappings"]->io.atlasmap.v2.Mappings["mapping"]->java.util.ArrayList[0]->io.atlasmap.v2.Mapping["outputField"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonField["actions"])`
