### ISSUE TITLE
[GTKA] Add a new Field Action

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#18]
A Get-To-Know-Atlasmap (GTKA) task.

1. Select a field action to be implemented (suggest reviewing the competitive list)

2. Review Field Action design-time requirements
   - Simple or Complex field action
   - If complex, properly implement optional configuration parameters

3. Review Field Action runtime requirements

4. Code Field Action and unit test

5. Create or extend an existing itest that utilizes thew field action

**Comment by igarashitm** [comment]
OK, then I'll look into this one for now!

**Comment by mattrpav** [comment]
Suggested activities:

1. Create new class in atlas-core/... io/atlasmap/core/actions
2. Create new Action as a method
3. Annotate method accordingly to support design-time
4. Add unit test for success and failure scenarios
5. Update atlas-model/ ...  JsonSerializer and Deserializer in order to support DSL-like JSON syntax w/o verbose jsonType=".." fields

**Comment by igarashitm** [comment]
One question - the name of the field action must be unique, is that correct? Let's say if I want to add SumUp() for each of Integer, Long, Float, Double and etc, then those must have some prefix or suffix to be unique like IntegerSumUp or SumUpDouble.

**Comment by igarashitm** [comment]
If it's true the atlas actions schema is gonna be too much bigger... there would be a bunch of operations on number, like {Yard,Mile,Inch}ToMeter, LbsToGram and etc

**Comment by mattrpav** [comment]
@igarashitm The Field Actions can be complex and accept parameters. A couple of the ones we have (PadStringLeft, PadStringRight, etc) could be collapsed with the addition of params.

For a Sum operation, we should use the FieldType.Number which is the top-level numeric type. Inside the operation, we can do fine grained detection of the type and leverage the conversion service if needed.

In your unit conversion example, I'd suggest we have the units as an enum and a parameter

java.lang.Number unitConversion(java.lang.Number originalValue, Unit from, Unit to) {

}

We then define Unit as an enum w/ Yard, Mile, Inch, Cm, etc.. 

Maybe even we do MassUnit, DistanceUnit, etc.. so the ValidationService can detect unsupported conversions, such as Gram to Mile, and notify the user at design time.

**Comment by igarashitm** [comment]
Aha, I overlooked about the parameters on the action. Those sound promising, thank you for the quick and cool advices!

**Comment by mattrpav** [comment]
@igarashitm anytime!  

BTW-- when you get to step #5 let me know if you want a few minutes to walk through it.. it is a bit different if you haven't done Jackson des/ser before. It allows AtlasMap to have DSL-like syntax in JSON without chatty extra parameters normally needed for o-o style objects in JSON =)

**Comment by igarashitm** [comment]
OK it took longer though I completed up to #4. @mattrpav , I'll look into #5 for next and ask questions if I hit something, but if you could have any advice in advance that would be great!

**Comment by igarashitm** [comment]
I believe I finished through No.6 so submitted a pull request here - #145

**Comment by jpav** [comment]
@mattrpav, could you point me to the "competitive list" of field actions you mentioned in the first comment for this issue?
