### ISSUE TITLE
React - Expand tree area

### ISSUE THREAD

**Issue by paoloantinori** [atlasmap/atlasmap#1823]
![Screenshot from 2020-02-26 17-08-23](https://user-images.githubusercontent.com/1520602/75365569-aa73cb00-58bd-11ea-922f-dddc121178d1.png)

**Both source and target areas** have a large list of possible fields, but the height of the container element is just 1.5 rows, forcing the user to scroll with very little room to read the entries down the list.

**Comment by emilywwj** [comment]
mine works fine.

**Comment by riccardo-forina** [comment]
Fixed by https://github.com/atlasmap/atlasmap/pull/1816
