### ISSUE TITLE
Review method visibility and remove test only methods

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#183]
I have seen many classes have inappropriate method visibility, i.e. internal subroutines have public/protected. This makes us significantly harder to see if the method is really in use or not. As a result of this, the methods those are not used anymore are left in the code. And what is worse, unit tests are sometimes testing methods those are not used from main code.

At the same time, there are some methods which are explicitly added for test only purpose in the main code. These are just noise and make it harder to see if unit tests really cover the real usecase.

I have fixed some of them around FieldReader/FieldWriter, but there're still some more. Review the code again and fix them.

Task notes:
1. getter/setter methods should remain as they are possible entry points for externalized configuration
2. init/destroy methods should remain until service lifecycle standard is addressed
3. The focus of method visibility should be on functional method clean-up
4. The desire is for the unit test entry points to focus on simulating out consumers of a given class would operate with the class to provide a sample of "how to use this class" (private, protected and package-private methods should be tested through public methods)

**Comment by mattrpav** [comment]
Change notes: I added additional details in the "Task Notes" section of the description to provide specific detail on the taskk.
