### ISSUE TITLE
UI_REACT: how to copy css style when use standalone react ui as a component

### ISSUE THREAD

**Issue by emilywwj** [atlasmap/atlasmap#1883]
how to copy css style when use standalone react ui as a component?

I notice that the styles are injected to the index.html when loaded. How should I keep the original css styles when I try to use react map standalone component?

**Comment by riccardo-forina** [comment]
We don't have any CSS asset that needs to be included but [the ones required from PatternFly](https://www.patternfly.org/v4/get-started/developers) which is a peer dependency of the project.

Any custom styling is done using a CSS-in-JS library, also from PatternFly.
