### ISSUE TITLE
Correct indentation of all the XML/JSON/yaml and etc. files

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#189]
pom.xml, log4j2.xml, mapping files, test data, etc. Right now it's mixup of 2-spaces and 4-spaces. sometimes even `<TAB>` is used.

@mattrpav summarzing comments up to 12/19

1. Update the atlas runtime build to use the mojo xml check to validate indentation
 - http://www.mojohaus.org/xml-maven-plugin/check-format-mojo.html
2. Update the EditorConfig to enforce indentation and spacing of non-Java files
 - ref: [EditorConfig reference](http://editorconfig.org/)

**Comment by igarashitm** [comment]
I would vote on 2-spaces, but OK with 4-spaces. No <TAB>. @atlasmap/runtime thoughts?

**Comment by rhuss** [comment]
👍 for 2 spaces in XML, 4 in Java (that's what we use in syndesis)

**Comment by jpav** [comment]
I'd vote similarly: 4 in Java, 2 in everything else.  No tabs.

**Comment by igarashitm** [comment]
OK, so the indent size is:
* Java: 4-spaces, no TAB
* Others: 2-spaces, no TAB
  * XML, JSON, yaml, what else?

I think I fixed Java indentation to 4-spaces while back, but might be good to add checkstyle rule to enforce.

**Comment by igarashitm** [comment]
To everybody in @atlasmap/runtime ,

As we are working concurrently, fixing indentation at once would cause conflicts. Rather I'd like to ask you all to correct indentation when you have a chance to edit the file.

* Java: 4-spaces, no TAB
* Others: 2-spaces, no TAB
  * XML, JSON, yaml, sh, etc

However, 
### please do it in dedicated commit
You can put multiple commits in one pull request. Please separate indentation commit from anything else. That helps reviewer to see what is in that pull request, and check the indentation and the real fix separately.

**Comment by igarashitm** [comment]
It seems 4-spaces is used for shell script in Syndesis. I'd go with it.

**Comment by mattrpav** [comment]
In an effort to align dev tools-- which maven plugin or tool does Syndesis utilize to perform the spacing?

At one point Hiram had created an EditorConfig file to help with enforcement across IDE's. It might be good to revisit that to provide enforcement at development time. Thoughts?

**Comment by igarashitm** [comment]
We're already using checkstyle and Google showed this for XML - http://www.mojohaus.org/xml-maven-plugin/check-format-mojo.html

But remember you need to fix everything once you enable it.

**Comment by joeylimd** [comment]
Team,

Want to align, In eclipse, Java ->code style-> formatter->profile:

What's the maximum line width? 200? Thanks

Best regards,
Joey

On Tue, Dec 19, 2017 at 7:10 AM, Tomohisa Igarashi <notifications@github.com

**Comment by igarashitm** [comment]
No please don't do that, automatic line feed often makes ridiculous chop and reduce the readability.
I also checked Syndesis checkstyle and PMD, no line length restriction found.
