### ISSUE TITLE
UI_REACT: How to delete mapping block which doesn't have any related mapping lines?

### ISSUE THREAD

**Issue by emilywwj** [atlasmap/atlasmap#1892]
I think the isolated mapping block cannot be deleted. Because when I try to edit a mapping block and click on the trash can button in order to delete, it doesn't work.

**Comment by igarashitm** [comment]
@atlasmap/ui could anybody evaluate if it's a bug or not and put labels?

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/77179378-caeb0b80-6a9e-11ea-888b-664233e49514.png)

Verified - bug.

**Comment by jpav** [comment]
Fixed by other changes to code
