### ISSUE TITLE
[GTKA] Add a validation rule

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#19]
Atlasmap supports the ability to validate mapping files ahead of runtime execution. Additionally, these validation rules can inform the UI at design time to assist the user in correcting their mapping definition.

1. Identify a useful validation scenario
2. Identify where it should live-- core, java, xml or json modules
3. Review design-time and runtime use cases
4. Implement validation
5. Implement unit test

**Comment by igarashitm** [comment]
I'm interested in looking into this one as a starter

**Comment by igarashitm** [comment]
Hi @mattrpav ,

It seems that the mapping validation is already implemented as an API here
https://github.com/atlasmap/atlasmap/blob/master/atlas-service-parent/atlas-service/src/main/java/io/atlasmap/service/AtlasService.java#L268-L274

What else is supposed to be done with this ticket? Is this just an UI task to invoke this API at design time and show the results? If so I may took a wrong ticket as I'm at runtime side - camel related task would be better.

**Comment by mattrpav** [comment]
Hi @igarashitm,

The Validation rules are shared at design time and runtime. For example, if there is something that would cause a mapping to not be executable, it would create a Validation.ERROR and the runtime engine would not continue processing. 

If you were to have a mapping defined with a source as "atlas:json", but it referenced a XmlField, that would cause a Validation.ERROR. In the UI, it would provide an error message and at runtime it would short circuit so we don't have to handle all permutations of unpredictable errors.

A WARN would be something like a mapping instruction that is a Double -> Short. There is a probability that it works, but also a chance it causes an error at runtime. We inform the user and track it at runtime.

Make sense?

**Comment by mattrpav** [comment]
A next step would be to define a new Validation that hasn't been implemented, add it and then create a unit test to validate.

Updating the Camel Component is also a good task =)

**Comment by igarashitm** [comment]
OK so the validation feature has already been implemented and the goal of this ticket is to add more rules. Is that correct? Then I'd look into the existing rules and see if I can have another idea to add.

**Comment by mattrpav** [comment]
Yep.  Heads up.. there is a Validation refactor task that I need to get to that aligns with a AtlasMap UI integration task. I was hoping to have it wrapped today, but its looking more like M-Tu next week. 

It might make sense to pick this up mid-next week. If you are looking for an immediate task.. a Field Action would be a great thing to look into.

**Comment by mattrpav** [comment]
Tomo is working on a full-fledged Validation refactor
