### ISSUE TITLE
UI_REACT: Add filtered search dropdown to expression box

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1914]
If a user types '@' then that should trigger a source field search.

**Comment by igarashitm** [comment]
@pleacu I think it's better to switch to new expression #1604 before implement field completion.

**Comment by pleacu** [comment]
Hey @igarashitm - I was originally going to complete support using the old style expression location but I'll tackle 1604 first.  Thkx for the heads up.

**Comment by pleacu** [comment]
@igarashitm - just to be clear - there was no Angular UI support for the new expression location correct?  (i.e. expression.component.ts)

**Comment by igarashitm** [comment]
nope, angular UI only supports earlier expression (as a transformation). It's incompatible and the earlier version of expression support will be discontinued in React UI.
