### ISSUE TITLE
Conditional Mapping Expression Error

### ISSUE THREAD

**Issue by SvenC56** [atlasmap/atlasmap#1918]
## Description
Hey I encountered this behaviour in Syndesis that conditional mapping are not working for me. I get this strange error after the deployment: `TypeError: Cannot read property 'value' of undefined`. If I deploy the app and go to the result I would excpect to get `true` or `false` values. Instead it looks like this:

![image](https://user-images.githubusercontent.com/14073259/78236081-d47e6580-74d9-11ea-8b12-9d7d9ac4b56e.png)

I if query the SQL statement in the Oracle SQL Developer it looks like this:
![image](https://user-images.githubusercontent.com/14073259/78236295-0e4f6c00-74da-11ea-832b-ee68475668c5.png)

I tried to setup conditional mapping like described here: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html/integrating_applications_with_fuse_online/mapping-data_ug

Mapping:
![image](https://user-images.githubusercontent.com/14073259/78235410-e7dd0100-74d8-11ea-9576-f32b9663d8c4.png)

Error after deployment:
![image](https://user-images.githubusercontent.com/14073259/78235541-0fcc6480-74d9-11ea-8045-89e79e4b4e6b.png)

**Comment by igarashitm** [comment]
Hi @SvenC56 can you export your Syndesis integration and attach here?

**Comment by igarashitm** [comment]
@SvenC56 And which version of Syndesis do you use?

**Comment by SvenC56** [comment]
Hi @igarashitm I'm using Syndesis `1.9.0-20200402`. Attached you find the redacted export. I hope it helps.
https://svencieslok-my.sharepoint.com/:u:/g/personal/mail_svencieslok_de/EZd4wM8cPflGoT9xwTA34aMBZ-DimEKQneurAWz9DxrsJg?e=5bBKKH

**Comment by igarashitm** [comment]
Thanks @SvenC56!

OK let's debug - here is what I got so far. The error message
`Unable to map expression index "0" to field node.`
means an array of source field in the MappingModel is empty in UI code.

Here is a mapping definition extracted from Syndesis integration
https://gist.github.com/igarashitm/1ea278b05e26cc3c9a46a18a8b819b1c

I found that the source field `/<>/ANZAHL_RUECKMUST` is placed under `inputField`, but not in `inputFieldGroup`
https://gist.github.com/igarashitm/1ea278b05e26cc3c9a46a18a8b819b1c#file-atlasmapping-1918-json-L24-L39
I wonder if it prevents from populating source fields properly for expression case.

**Comment by SvenC56** [comment]
Is this the reason why it only populates the first value (this `TRUE` value)?
![this](https://user-images.githubusercontent.com/14073259/78236081-d47e6580-74d9-11ea-8b12-9d7d9ac4b56e.png)

Is there a any action for me? :slightly_smiling_face:

**Comment by igarashitm** [comment]
@SvenC56 no worries, so far it looks like a bug in our UI code we have to fix, my guess is that this happens when participating source field in expression is only one, maybe we only tested multiple fields before for expression.

**Comment by igarashitm** [comment]
source schema: https://gist.github.com/igarashitm/f99e542c409eb69a05a2fd0450f75879
target schema: https://gist.github.com/igarashitm/7936fe07a48815dcb52ced2a9cc167a7

**Comment by pleacu** [comment]
So this is interesting - when I create the conditional expression I get a warning from validation service:
![sc1](https://user-images.githubusercontent.com/2981421/78276613-45754b80-74e1-11ea-9b0a-4163b26d413e.png)

Then when I reload the existing mapping I see what Sven sees:
![sc2](https://user-images.githubusercontent.com/2981421/78276669-5b830c00-74e1-11ea-8c23-cb2c3ddbf84c.png)

Now - if you look closely at the expression box - the expression is being recreated incorrectly - it appears as:

IsNul( )ANZAHL_RUECKMUST 

instead of

IsNul( ANZAHL_RUECKMUST )

which I'm sure is causing the null field node at index 0. 

Same problem with the react UI:
![sc4](https://user-images.githubusercontent.com/2981421/78277208-20350d00-74e2-11ea-93e2-fa1694487781.png)

**Comment by SvenC56** [comment]
> Now - if you look closely at the expression box - the expression is being recreated incorrectly - it appears as:
> 
> IsNul( )ANZAHL_RUECKMUST
> 
> instead of
> 
> IsNul( ANZAHL_RUECKMUST )

Yes, this is exactly my problem. I create the mapping like `IsNul( ANZAHL_RUECKMUST )` but after I deploy the integration it looks like `IsNull( )ANZAHL_RUECKMUST`. 🙂

**Comment by pleacu** [comment]
The arning still appears from the validation:

![sc5](https://user-images.githubusercontent.com/2981421/78299909-9c404c80-7504-11ea-8504-5b9e3c254e05.png)

![sc6](https://user-images.githubusercontent.com/2981421/78299917-a1050080-7504-11ea-9c03-f4766b788d86.png)
