### ISSUE TITLE
How to build JAR file in a right way?

### ISSUE THREAD

**Issue by emilywwj** [atlasmap/atlasmap#1932]
I tried the following way to write a test file and generate a jar file. But it doesn't show on the list of actions after I follow the steps in the intro. Please tell me the right way to generate this jar file. Thank you!

![image](https://user-images.githubusercontent.com/24653223/78737701-c077af80-7982-11ea-8cc8-f71598e5066a.png)

**Comment by emilywwj** [comment]
BTW, I see the newest code test example as below.

![image](https://user-images.githubusercontent.com/24653223/78738046-7511d100-7983-11ea-90aa-fcb661b60efd.png)

**Comment by emilywwj** [comment]
I import the jar file correctly and it shows in the field actions. But I have this error:

Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "paulsParam" (class io.atlasmap.v2.CustomAction), not marked as ignorable (5 known properties: "inputFieldType", "name", "methodName", "className", "outputFieldType"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.atlasmap.v2.ProcessMappingRequest["mapping"]->io.atlasmap.v2.Mapping["inputField"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonField["actions"]->io.atlasmap.v2.CustomAction["paulsParam"])

**Comment by igarashitm** [comment]
@pleacu it seems the doc is a bit out of date? `@AtlasFieldActionInfo` has been deprecated.

**Comment by emilywwj** [comment]
The error I list upon is what I got when I try to preview the value of the action. And please help me ASAP. Thanks a lot.

**Comment by emilywwj** [comment]
Can you give a sample jar file and its source code? Therefore I can refer it and build my own functions.

**Comment by igarashitm** [comment]
Verified with mockdoc.adm which has a mapping involving custom transformation, it looks like a bug.
https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/adm/mockdoc.adm

**Comment by emilywwj** [comment]
I got error when using my custom field action.
{
  "ProcessMappingResponse" : {
      ......
      "id" : "preview"
    },
    "audits" : {
      "audit" : [ {
        "message" : "Failed to apply field action: Error processing action com.test.spi.MyCustomFieldAction - java.lang.ClassCastException@587092f6",
        "docId" : "1043",
        "path" : "/",
        "status" : "ERROR"
      } ]
    }
  }
}

**Comment by emilywwj** [comment]
?

**Comment by pleacu** [comment]
ref #1757

**Comment by igarashitm** [comment]
User Guide still needs to be updated

**Comment by pleacu** [comment]
https://github.com/atlasmap/atlasmap/issues/1757 - ref

**Comment by pleacu** [comment]
This is now verified to work correctly - please follow instructions

 http://localhost:6006/?path=/story/atlasmap-demo--wired-to-the-backend
