### ISSUE TITLE
Separate save mapping from validation REST call

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1946]
While it's implicitly saved on every UI action from user perspective, it's better to separate save mapping from validation at the server side. Let UI invoke a separate REST invocation for save, then remove save mapping operation from validate REST invocation in AtlasService.

**Comment by pleacu** [comment]
@igarashitm - so the goal is:
1.  Remove the implicit save mapping on the server side.
2.  Split the mapping/validate into /mapping/validate/0 and /mapping/0 (validate and update) on the UI side.
correct?

**Comment by igarashitm** [comment]
yep that's right
