### ISSUE TITLE
Discussion about suspicious method AtlasUtil.find(File file, String scannedPackage)

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#20]
Here https://github.com/atlasmap/atlasmap/blob/master/atlas-core/src/main/java/io/atlasmap/core/AtlasUtil.java#L261

- Class.forName is used without providing a specific ClassLoader, in OSGi environment there are good chance that it is not working

**Comment by mattrpav** [comment]
@apupier l created #21 to track OSGi compatibility tasks. At one point, I had tested installation of all the modules as bundles, but its been a while, so I'm sure there are some gaps now.

**Comment by mattrpav** [comment]
Closing this issue and tracking all OSGi related tasks in #21
