### ISSUE TITLE
Could field actions show up in UI, even if it requires type conversion ahead?

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#200]
#175 makes me wonder if these field actions could show up for the other date/time field types like FieldType.DATE and FieldType.TIME as well. It looks all other date/time fields should be converted into FieldType.DATE_TIME_TZ before field action. But is it working well today? Does UI handle it properly, i.e. showing as available transformations for other date/time field types as well?

**Comment by igarashitm** [comment]
#35 indicates that the answer is "no".

Hmm but if user need to explicitly add the type converter action for say `FieldType.DATE` => `FieldType.DATE_TIME_TZ`, that looks very low level. I'd expect implicit/automagical type conversion, at least for those date/time field types.

@mattrpav , @jpav , do you have any idea?

**Comment by igarashitm** [comment]
Or we'll have to add field actions with all the combination of those date/time field types.

**Comment by jpav** [comment]
I agree, I was also expecting auto-conversion to kick in here

**Comment by igarashitm** [comment]
So based on the chat in #35 , we'll have to add all the variation of date/time field types.

**Comment by jpav** [comment]
I think we need to keep discussing this.  Seems crazy to me to need all those variations. I'm still hoping if we implement auto-conversion differently, we can handle this without sacrificing usability, and in fact possibly increasing it.

**Comment by mattrpav** [comment]
@jpav interesting, what are you thinking in terms of implementing auto-conversion differently?

**Comment by igarashitm** [comment]
@jpav agree it's insanely annoying from engineering perspective. So the point is,
* No additional steps from user POV
* Appropriate set of field actions show up for the field type

**Comment by igarashitm** [comment]
With a bit additional chat, having an umbrella field type `FieldType.ANY_DATE` is a way to go?

**Comment by igarashitm** [comment]
@rohanmars , FYI, related to DateConverter as well

**Comment by igarashitm** [comment]
Closing - filed #205
