### ISSUE TITLE
central.maven.org (central.maven.org)... failed: Name or service not known

### ISSUE THREAD

**Issue by ranjith-murugasamy** [atlasmap/atlasmap#2017]
wget http://central.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.0.0-M.4/atlasmap-standalone-2.0.0-M.4.jar -PCentral
--2020-05-07 16:40:32--  http://central.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.0.0-M.4/atlasmap-standalone-2.0.0-M.4.jar
Resolving central.maven.org (central.maven.org)... failed: Name or service not known.
wget: unable to resolve host address ‘central.maven.org’

**Comment by riccardo-forina** [comment]
This works for me `https://repo1.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.0.0-M.4/atlasmap-standalone-2.0.0-M.4.jar`

**Comment by igarashitm** [comment]
@ranjith-murugasamy Does anybody say `central.maven.org` provides maven repo? That hostname doesn't exist through public DNS. We don't know anything about `maven.org` internal.

**Comment by igarashitm** [comment]
hmm google shows that `central.maven.org` did exist. But at least currently not accessible via public DNS. Please use other hostname.
