### ISSUE TITLE
Increase code coverage on JSON FieldReader and FieldWriter

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#202]
Add unit test coverage of JSON FieldReader and FieldWriter to cover:

1. Happy path: All primitive types within their normal operating range (short, int, long, double, etc.)
- Double: Double.MAX_VALUE, Double.MIN_VALUE
- Integer:  Integer.MAX_VALUE, Integer.MIN_VALUE
- Long:  Long.MAX_VALUE, Long.MIN_VALUE
- Short:  Short.MAX_VALUE, Short.MIN_VALUE
2. Error path(s): 
- All primitive types with values outside their range and using deci
- Test with numbers that have decimal precision going into whole numbers types
`{ integerFieldPrecisionError: 13412.4345 }` 
3. Syntax error: Put a "string" value in an integer field
`{ booleanFieldSyntaxError: abcd } `

**Comment by mattrpav** [comment]
@igarashitm please review before assignment for development

**Comment by mattrpav** [comment]
@igarashitm please review before assignment for development

**Comment by igarashitm** [comment]
+1 looks like "must have" for the tests!

**Comment by rohanmars** [comment]
closed by #215
