### ISSUE TITLE
Support classic Drag'n'drop on Destkop applications

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#2053]
Currrently, user needs to wait a certain amount of time before he/she can Drag an element. This is counter-intuitive for Desktop applications. There is no feedback or hint to help guess it.

@riccardo-forina you mentioned that it is a limitations of the UI framework used. Can you point to the upstream issue please?

**Comment by riccardo-forina** [comment]
@apupier you can test the fix directly on Atlasmap's Netlify https://atlasmap.netlify.com/

This should address your concern.
