### ISSUE TITLE
Split/concatenate on CSV rows does not work correclty

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#2069]
Currently when you have a CSV as a source and you want to concatenate /<>/first_name and /<>/last_name, it doesn't work as expected. It basically produces a simple field with only first row taken into account, whereas I would expect all fields to be concatenated. It seems that concatenate/split is broken for root level collections.

@igarashitm, one question here. From the Atlasmap model perspective, is it more correct to represent a CSV field as /<>/first_name or /first_name<> ? I chose the former, but apparently root level collections are unusual (saw only one test in json).

**Comment by igarashitm** [comment]
Strictly speaking `/<>/first_name` is the correct way to be consistent with other formats, so let's use this internally. And right, the topmost collection is unusual for other formats. We might omit showing topmost collection in UI for user convenient for CSV.

**Comment by rkorytkowski** [comment]
Thanks. I would still show /<>/ to enable the user to e.g. pick an exact row /<0>/ or a range /<0-10>/ (if eventually supported), etc.

**Comment by igarashitm** [comment]
Ah good point!

**Comment by rkorytkowski** [comment]
I fixed a simple case of concatenating all fields into a single field. The more complex issue of concatenating within a row will be addressed in #1236.

**Comment by rkorytkowski** [comment]
https://issues.redhat.com/browse/ENTESB-14600
