### ISSUE TITLE
CharacterConverter: expected behaviour ? 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#208]
Character fields are currently converted to Number-type fields as int ASCII values and to Boolean as (1character) Strings. Wouldn't be better just process char fields always as string with 1 char? 

For example I'd expect that citizen integrator expects that char field with value '5' will be mapped to int filed with value (5) and not (53) (from ASCII table).

@igarashitm @rhuss @kcbabo any toughs ? 
If current behaviour is ok, we can close it.

**Comment by igarashitm** [comment]
It sounds like a good catch, as char definitely assumes UTF-16 character map unlike byte. Just because its name is 'char'... internally it's still number though.

**Comment by igarashitm** [comment]
This is not trivial, as it eventually involves numerous expression of number characters, from many languages...
