### ISSUE TITLE
Multiplicty dropdown not removed from the mapping details when mapping simplified to "one to one"

### ISSUE THREAD

**Issue by riccardo-forina** [atlasmap/atlasmap#2083]
Ref https://issues.redhat.com/browse/ENTESB-13634

@pleacu I did some debugging and the [`transitionFieldAction`](https://github.com/atlasmap/atlasmap/blob/5795fb08b1a8f6c638c63e554f7813baf9b067ac/ui/packages/atlasmap/src/Atlasmap/useSidebar.tsx#L60) is valid when switching from a "many to one" to a "one to one". Is something missing when removing a field perhaps?

**Comment by pleacu** [comment]
Yup - looks like we need to reset transitionFieldAction when going back to
a simple mapping
  --P

**Comment by riccardo-forina** [comment]
Can I leave this to you then?

**Comment by riccardo-forina** [comment]
Also shouldn't this case be covered by the `core` package? The UI should be as dumb as possible really and just act as a proxy between the user and the `core`'s APIs.
