### ISSUE TITLE
Attach upstream master coverage report to developer guide

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2098]
Although it's already available through CircleCI build artifact, attach to developer guide for easy access.

**Comment by igarashitm** [comment]
It's failing somehow

**Comment by igarashitm** [comment]
Finally... (
https://docs.atlasmap.io/developer-guide/coverage/java/index.html
https://docs.atlasmap.io/developer-guide/coverage/ui/atlasmap/index.html
https://docs.atlasmap.io/developer-guide/coverage/ui/atlasmap-core/index.html
https://docs.atlasmap.io/developer-guide/coverage/ui/atlasmap-standalone/index.html

**Comment by riccardo-forina** [comment]
Nice!
