### ISSUE TITLE
Do not prohibit collection when non-collection is already clicked on the other side

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#210]
Part of epic #248 

Related to #209 

This turned out to be an UI bug... If you click a collection item first, the transition mode is set to collection mode and you can choose non-collection item on the other side. But if you click non-collection item first, transition mode is set to map mode and you can't choose collection item on the other side.
https://github.com/atlasmap/atlasmap/blob/d8c2b186c26aaf7a6d703118114c6a4ef17098fe/ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts#L416

**Comment by mmelko** [comment]
This currently blocks using some field actions which requires collection input type
