### ISSUE TITLE
Import catalog challenge should not appear when importing a custom JAR.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2110]
![sc1](https://user-images.githubusercontent.com/2981421/82910156-43a39380-9f38-11ea-8040-2970fab2027b.png)

**Comment by riccardo-forina** [comment]
Oh I didn’t know there was a difference in how the two formats are handled. I wonder if they shouldn’t be two different icons then, given that loading an adm catalog replaces everything whether loading a jar adds elements to the current catalog.

**Comment by igarashitm** [comment]
Yep I'd vote to have a separate import icon. The adm import is to reset everything to a saved state, while importing jar is just an addition to the existing library store.

**Comment by pleacu** [comment]
I suppose they could be two different icons.  In general your "importing"  something tool-wide.  In our case it can be either an ADM catalog file or a custom JAR file.  In the  case of the custom jar nothing visible happens on the import.  They have to "enable" the class package in either the source or target panel.

There's also a smaller issue in that you get the challenge when you have no loaded ADM file at all.

There is a big semantic difference as Tomo points out - I guess I'm neutral.  If you guys think a new icon is warranted then I'd say go for it.  Will re-assign to Riccardo as he's better at picking icons than me... :)

**Comment by pleacu** [comment]
This is now fixed.
