### ISSUE TITLE
Support COMPLEX field in expression UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2113]
Support COMPLEX field in expression UI to cover #1507.

**Comment by pleacu** [comment]
@igarashitm - is this what you're thinking of with respect to a JSON doc?
'{
  "$schema": "http://json-schema.org/schema#",
  "description": "Order",
  "type": "object",
  "properties": {
    "person": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "gender": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "department": {
            "type": "string"
          }
        }
      }
    }
  }
}
'

**Comment by pleacu** [comment]
Note: target field never appears in expression so it extracts all gender=m person, and then extracts fullName for each person.  filter() returns a list of person complex objects then select() selects a terminal field from it

**Comment by pleacu** [comment]
@igarashitm - was going to close this - is there anything left to do?

**Comment by igarashitm** [comment]
Nothing I'm aware of.

**Comment by pleacu** [comment]
This is complete.
