### ISSUE TITLE
Avoid save mapping request with invalid string "no data" from UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2127]
xref: https://issues.redhat.com/browse/ENTESB-13919

**Comment by pleacu** [comment]
xref: https://issues.redhat.com/browse/ENTESB-13932

**Comment by igarashitm** [comment]
Ugh... it sounds like an another side effect of #1946

**Comment by igarashitm** [comment]
Changed the title, due to ENTESB-13932 we can't skip save mapping. But we have to avoid sending "no data" as a mapping definition from UI.
