### ISSUE TITLE
Populating the list of available fields for the typeahead component in the mapping details is very slow for large documents

### ISSUE THREAD

**Issue by riccardo-forina** [atlasmap/atlasmap#2134]

**Comment by igarashitm** [comment]
I barely remember @pleacu added a threshould for that in angular ver? like if 100+ field is found then stop searching, isn't it Paul?

**Comment by pleacu** [comment]
Actually: private maxSearchMatch = 10000;

**Comment by riccardo-forina** [comment]
Not stale
