### ISSUE TITLE
Edit property name is not working

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#2151]
tested with version 2.0.3 in Chrome

- add a property with the + button
- click on "edit property" icon button
- change name
- click "Confirm"
--> the old value is still provided

**Comment by riccardo-forina** [comment]
@pleacu I briefly debugged this and I have a doubt, checking the [`editProperty`](https://github.com/riccardo-forina/atlasmap/blob/93aa3656fc191243fb6709741fd9039c444b7dc8/ui/packages/atlasmap/src/Atlasmap/utils/field.ts#L118-L134) function there is no way to change its name, just the value and type. So I wonder, is changing the name even supported?

**Comment by riccardo-forina** [comment]
In any case, given that `editProperty` signature the first parameter of [this line](https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx#L81) should be `property.name` and not `name`.

Then if the name can actually be edited, then a new param for it should be added to the `editProperty` signature.

**Comment by pleacu** [comment]
The angular UI could modify the name but it has the business logic alot closer to the UI components.  I actually have a fix that extends the editProperty() api to include the original prop name.  PR coming soon.
