### ISSUE TITLE
Preview mode non functional if padding fields are present

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2159]
![sc1](https://user-images.githubusercontent.com/2981421/83758998-e77bf600-a640-11ea-88d6-f588a2bd24f0.png)

**Comment by pleacu** [comment]
@igarashitm - It appears that if you have a padding field then this code will fail:
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java#L292

![sc1](https://user-images.githubusercontent.com/2981421/83768319-a1c52a80-a64c-11ea-9e13-54e8f211f66f.png)

**Comment by igarashitm** [comment]
Ugh sorry my mouse slipped... working fine for me, there should be another condition I guess?
![Screenshot from 2020-06-04 10-34-29](https://user-images.githubusercontent.com/265462/83770609-45173f00-a64f-11ea-8b08-3db45d87938e.png)

**Comment by pleacu** [comment]
Can you try a split instead of a concat (one to many)??

**Comment by igarashitm** [comment]
working fine
![Screenshot from 2020-06-04 10-46-38](https://user-images.githubusercontent.com/265462/83771953-d76c1280-a650-11ea-88de-770aded6de84.png)
I noticed showing padding field at the target side looks a bit weird though, as it just throws away, not really padding.

**Comment by pleacu** [comment]
*ugh* - can you try one more time :)
Since t his is being used in our tech doc - please try these two files only:
@igarashitm 

[s.json.txt](https://github.com/atlasmap/atlasmap/files/4730809/s.json.txt)
[t.json.txt](https://github.com/atlasmap/atlasmap/files/4730811/t.json.txt)

**Comment by pleacu** [comment]
My bad - need to enter preview input for the padding fields (i.e. rat,,bat)
