### ISSUE TITLE
Unable to download .jar file for Running AtlasMap Data Mapper UI standalone

### ISSUE THREAD

**Issue by jaboulos** [atlasmap/atlasmap#2185]
From the developer quickstart guide: https://docs.atlasmap.io/developer-guide/

I am on a mac using macOS, running the command:

`curl https://central.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.0.4/atlasmap-standalone-2.0.4.jar`

returns this response in the terminal:

`curl: (6) Could not resolve host: central.maven.org`

**Comment by pleacu** [comment]
To get you going - try downloading from 

https://repo1.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.0.4/atlasmap-standalone-2.0.4.jar

@igarashitm - central.maven,org doesn't ping.  Don't know which URL to publicize.

**Comment by igarashitm** [comment]
It seems repo1 is now called official maven central
https://mvnrepository.com/repos/central
