### ISSUE TITLE
Assign unique internal ID for Document ID apart from display name

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2198]
xref: https://issues.redhat.com/browse/ENTESB-12361

Import document in standalone UI uses class name for Java Document and schema file name for others as a Document ID, which could cause conflict. Assign unique ID internally apart from those display name.

**Comment by igarashitm** [comment]
#2242 adds `name` and `description` to the `DataSource` model object, now UI just has to populate when it imports Document.

**Comment by pleacu** [comment]
@igarashitm - can you give a brief example of exactly the format you'd like to see for doc.name and doc.description?

**Comment by igarashitm** [comment]
@pleacu doc.name could be simply a class name without package for Java (e.g. Person, Status, Employee) and file name for others (e.g. person for person.json, Status for Status.xsd). description could be longer, a couple of sentenses which describe about the document.
