### ISSUE TITLE
AtlasModelFactory - potential NullPointerException

### ISSUE THREAD

**Issue by joeylimd** [atlasmap/atlasmap#220]
in class NullPointerException.java,
1. in line 86, clone.getMappings().getMapping(), clone.getMappings() could throw NullPointerException as clone is a new object without initializing variable mappings.
2. in line 99, mapping.getMappingType().value(), if mapping.getMappingType() is null, there's  NullPointerException.
3. in line 257, unreachable condition- if (a.getInputFieldType() != null) { as it's always null
4. in line 260, unreachable condition- if (a.getOutputFieldType() != null) {as it's always null

**Comment by rohanmars** [comment]
LGTM :+1:
