### ISSUE TITLE
Add target property in UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2210]
See #2197 and #2117 

What it's trying to do with #2197 also add the needs of setting target document scoped properties - which is Camel IN message header if it runs in Camel. Add target property in UI. It also needs scope dropdown (#2209) and have a `camelExchangeProperty` scope.

**Comment by pleacu** [comment]
So - the target property doc will always exist in the target panel and operate pretty much the way the existing property doc does, correct?

![sc1](https://user-images.githubusercontent.com/2981421/88928331-b71e9580-d246-11ea-8827-2b426199b306.png)

**Comment by pleacu** [comment]
@igarashitm - so this seems to be the appropriate JSON for source/target properties:

`    "properties" : {`
`"sourceProperty" : [ {`
`       "name" : "rat",`
`        "value" : "cat",`
`        "fieldType" : "STRING",`
`        "scope" : "camelExchangeProperty"`
`      } ],`
`      "targetProperty" : [ {`
`       "name" : "ball",`
`        "value" : "10",`
`        "fieldType" : "INTEGER",`
`        "scope" : "JSONSchemaSource"`
`      }, {`
`        "name" : "isround",`
`        "value" : "true",`
`       "fieldType" : "BOOLEAN",`
`        "scope" : ""`
`      } ]`
`    },`

The `value` is kept in for now.  I think it makes the most sens to establish `sourceProperty` and `targetProperty` with `properties`.
That means that all server references post serialization:

`atlasMapping.getProperties().getProperty()` needs to become `atlasMapping.getProperties().getSourceProperty()`.

**Comment by igarashitm** [comment]
hmm... even if we remove `/atlasMapping/properties` completely with #2255? `/atlasMapping/properties` is there only to hold mapping definition level values for fallback.

**Comment by igarashitm** [comment]
If you do this before #2255, I think it's OK to share those fallback property values between source and target. But it sounds like it's better to remove values first to avoid further confusion.

**Comment by pleacu** [comment]
I need the `properties` JSON  so I can establish the `Properties` documents in the `Source` and `Target` panels without having a mapping selected.

**Comment by pleacu** [comment]
I can't see sharing property values between source and target panels - users still need to be able to select them so they can add to their mapping.  I can remove the `value` now but I think we'll still need a `sourceProperty` and `targetProperty`.

**Comment by igarashitm** [comment]
Ah OK, it still needs a place to persist property apart from mapping. Then I would add an attribute on `Property` to specify an enum value from SOURCE and TARGET, just like `io.atlasmap.v2.DataSourceType` is used for DataSource. Is there a better common name for this SOURCE/TARGET enum to share it with DataSource?
