### ISSUE TITLE
Atlasmap Support for Quarkus

### ISSUE THREAD

**Issue by rahgadda** [atlasmap/atlasmap#2251]
Hi Team,

I am trying to run a small quarkus camel project for using atlas map.
Any plans of creating a quarkus camel supporting below error.
"No endpoint could be found for: atlas://map/simple-mapping.adm, please check your classpath contains the needed Camel component jar"

<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://camel.apache.org/schema/spring"
        xsi:schemaLocation="
            http://camel.apache.org/schema/spring
            http://camel.apache.org/schema/spring/camel-spring.xsd">
    
    <route id="xml-atlasmap">
        <from uri="timer:simple?repeatCount=1"/>
        <to uri="language:constant:resource:classpath:/data/individual.xml"/>
        <to uri="atlas:map/simple-mapping.adm"/>
        <log message="result is:\n ${body}"/>
    </route>
</routes>

**Added maven dependency below**
```xml
<dependency>
      <groupId>io.atlasmap</groupId>
      <artifactId>camel-atlasmap</artifactId>
      <version>1.42.4</version>
</dependency> 
```

Regards,
Rahul

**Comment by igarashitm** [comment]
As far as I know you are the first trying it - contribution is welcome!

**Comment by rahgadda** [comment]
I am able to successfully create an application 

https://github.com/rahgadda/ApacheCamel/tree/master/03-MyDev/quarkus-no-camel/atlasmap/json-to-json/transformation

**Comment by igarashitm** [comment]
I don't think anyone have tried to get AtlasMap work with Quarkus. Reopening.

**Comment by zbendhiba** [comment]
There is a JVM support in camel-quarkus since [1.5 version](https://camel.apache.org/blog/2020/12/camel-quarkus-release-1.5.0/). You can use the camel-quarkus-atlasmap depency for Quarkus JVM mode.
I'm working currently on porting it to native mode, see [camel-quarkus-1989](https://github.com/apache/camel-quarkus/issues/1989), so it will be soon available as a stable extension.

**Comment by zbendhiba** [comment]
The [PR for native support](https://github.com/apache/camel-quarkus/pull/2237) has been merged.

**Comment by zbendhiba** [comment]
Native support has been introduced since [camel-quarkus 1.7.0 ](https://github.com/apache/camel-quarkus/milestone/11?closed=1)

**Comment by zbendhiba** [comment]
You can close this issue
