### ISSUE TITLE
UI Property: Remove 'value' field from properties dialog.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2255]
The property value embedded in a mapping definition is used as a default value, if the runtime value is not found.
The runtime value could be a Java system property, ENV with default property strategy and we're adding camel header/exchange property mapping on top of it.  Consequently anything the user typed for a 'value' could only be used as a default value in a fallback scenario.

**Comment by igarashitm** [comment]
I would vote for removing `value` completely from Properties, regardless of scope. That default value is not so intuitive and have been a source of confusion vs. Constants. We might be able to add generic default value support for any mappings instead.

**Comment by pleacu** [comment]
merged
