### ISSUE TITLE
Start/End Indexes translated as negative values when using substring before/after transformation

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#226]
Used gherkin scenario: 
  ``` When select "SubStringBefore" transformation
    And for "input-startIndex" input set "3"
    And for "input-match" input set "blah"
    And set source data
      | sourceString |
      | foobarblah   |
    And set expected data
      | targetString |
      | fo           |
    Then save and verify 
```
Following exception is thrown during processing in camel route: 

```java
 Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -3
	at java.lang.String.substring(String.java:1967)
	at io.atlasmap.actions.StringComplexFieldActions.doSubString(StringComplexFieldActions.java:316)
	at io.atlasmap.actions.StringComplexFieldActions.subStringBefore(StringComplexFieldActions.java:294)
	... 80 more

2018-01-08 14:35:49.309  INFO 55326 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4bf48f6: startup date [Mon Jan 08 14:35:40 CET 2018]; root of context hierarchy 
``` 

Created mappings.xml looks fine: 
```xml
<Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.479590" mappingType="Map">
            <InputField xsi:type="ns2:JavaField" name="sourceString" docId="io.atlasmap.qe.test.SourceMappingTestClass" path="/sourceString" fieldType="String"/>
            <OutputField xsi:type="ns2:JavaField" name="targetString" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/targetString" fieldType="String">
                <Actions>
                    <SubStringBefore startIndex="3" endIndex="0" match="blah"/>
                </Actions>
            </OutputField>
        </Mapping>
    </Mappings>
```

**Comment by igarashitm** [comment]
@mmelko are you suggesting to raise more user friendly error message like `end index should be greater than start index`?

**Comment by mmelko** [comment]
I was trying to do https://github.com/atlasmap/atlasmap/blob/master/runtime/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java#L492 however I didn't realise that there is '0' as default. So I set the End index to '5'. But still I'm getting 
```
Caused by: java.lang.IllegalArgumentException: SubStringBefore action must be specified with a positive startIndex and a string to match
	at io.atlasmap.actions.StringComplexFieldActions.subStringBefore(StringComplexFieldActions.java:283)
	... 80 more
```

**Comment by igarashitm** [comment]
Ah OK, so this happens if you specify only a start index and no end index then 0 is filled for end index? That sounds like a bug for sure.

**Comment by mmelko** [comment]
yes, but the another problem is that I'm not able to get this work. It ends at`Caused by: java.lang.IllegalArgumentException: SubStringBefore action must be specified with a positive startIndex and a string to match
	at io.atlasmap.actions.StringComplexFieldActions.subStringBefore(StringComplexFieldActions.java:283)
	... 80 more` even if I have indexes filled correctly as follows: 
startIndex = 3 
endIndex = 5 
match = 'blah'
input = 'foobarblah'. I'd expect to get substring not that exception

**Comment by igarashitm** [comment]
Yep, that also sounds like a bug. One question, are you running with older version of atlasmap? I think 1.32.2 I made a release last week would hit a different line number for that `subStringBefore`. If so can you try with latest?

**Comment by mmelko** [comment]
I've tried this with 1.33-SNAPSHOT and I have found the issue. There is wrongly formulated condition. End index is always bigger than start index when parameters are filled correctly. This was the reason of getting exception mentioned in my previous comment. 
 https://github.com/atlasmap/atlasmap/blob/master/runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java#L315
