### ISSUE TITLE
AtlasmapProvider should accept inspectionParameters for CSV

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#2265]
If I understand it correctly, AtlasmapProvider is being used by Syndesis and if we want to enable passing CSV inspectionParameters from Syndesis we need to include that field in IExternalDocumentProps.

I expect I need to adjust https://github.com/syndesisio/syndesis/blob/c55f2a94660cb2501a9ae531168165e9055b42ad/app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx as well. What's the workflow here? Do I need to wait for the release of Atlasmap, then create a PR with a new version and DataMapperAdapter change?

**Comment by rkorytkowski** [comment]
@igarashitm, @pleacu, @riccardo-forina please advise.

**Comment by igarashitm** [comment]
Yes, in order to make a change there we need to make atlasmap release first, then bump it up in Syndesis.
