### ISSUE TITLE
one_to_many mapping - repeat source value based on count 

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#2276]
Initial PR: https://github.com/atlasmap/atlasmap/pull/2049

from PR: "one_to_many mapping - repeat source value based on count of fieldPath and do the target transformation."

**Comment by rkorytkowski** [comment]
@igarashitm so I was looking into getting rid off the dropdown. The purpose of it is to point to an array to get its length and determine how many times the source value should be repeated. It's not for selecting the source value itself.

If we get rid of the dropdown, we need a different way to determine how many times to repeat the source value. I was looking into reading that info from the target side, but it may not be available at the point of setting the target field. Is that right? The target array final length could be determined after processing of all other fields.

I'm leaning towards keeping the dropdown and limiting listed fields to those of collection type. I would also include another parameter for specifying a count as an integer. The user would have to specify one or another.

Any thoughts on how to best approach it?

**Comment by shanthi4647** [comment]
I agree.. i didn't see a way to repeat source field based on target array size, as we process source fields first and then move to processing target. so went for dropdown of source fields

**Comment by igarashitm** [comment]
Sounds like it's a limited version of #781 where it only uses one of single collection length at source side, correct? so like `/foo<a>/bar<b>` => `/foo<a>` while our default index mapping is `/foo<a>/bar<b>` => `/foo<a*b>`. I don't like to introduce a separate UI for this specific asynmmetric option. So if we really want to achieve it we need generic #781 I would say.
Another option in the meantime is to do it with Conditional Mapping. It should be easier than #781 - the `length` transformation we already have could participate to get the specific collection length.

**Comment by rkorytkowski** [comment]
It's a bit different. It's /foo/bar -> /foo<a>/bar, where you would basically put the value of bar "a" times.

**Comment by igarashitm** [comment]
Ah OK, then it's just `length(/some/array<a>)` which is used as a parameter for that repeat action, should be possible with Conditional Mapping I guess?

**Comment by igarashitm** [comment]
Yet another option is, at the runtime side, internally group these kind of repeating mapping depends on target array size, postpone them until other mapping finishes and then repeat for each target item that is already established by other mappings. An idea that the target array size is determined by the other mapping.

**Comment by igarashitm** [comment]
The reason why I don't like to introduce this field dropdown is that, it then have to provide dynamic variable for transformation parameter which is not currently suported. If we go this route, we have to design generic dynamic transformation parameter support head of it.

**Comment by rkorytkowski** [comment]
So the proposed solution is to introduce a repeat action, which could be called from a conditional mapping as follows to achieve what you intend:

repeat(/field, count(/array<>/field))

**Comment by igarashitm** [comment]
Sounds good, note that we already have a `length()` transformation
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/main/java/io/atlasmap/actions/ObjectFieldActions.java#L85

**Comment by rkorytkowski** [comment]
@shanthi4647, an updated fix for nested action calls are in the following commits:
https://github.com/rkorytkowski/atlasmap/commit/0c9b3336c36bd120db72c55446246aaa8415e037
https://github.com/rkorytkowski/atlasmap/commit/71b33bd54f5ce9b24e40f9fddcf021069907856b

TODO:
1. Rename action to "repeat"
2. Cleanup json test files to only include items relevant for the test
3. Add tests for some edge cases e.g. repeat(3, field), repeat(1, field), repeat(3, field_nested_in_a_few_collections)
4. Remove UI changes
5. Squash all commits and create a PR
