### ISSUE TITLE
Unexpected exception is thrown while reading source field

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2277]
Community version of https://issues.redhat.com/browse/ENTESB-14432

**Comment by pleacu** [comment]
@igarashitm  - I've got a simple fix for this but need your opinion.  When I reference the COMPLEX array in the conditional expression the generated mapping transition is `FOR_EACH`.  A mapping from two array elements to a target string generates a `MANY_TO_ONE` mapping transition.  The fix is then just to limit the conditional expression COMPLEX array refs to `FOR_EACH`:

![sc1](https://user-images.githubusercontent.com/2981421/89792633-d47b1b80-daf2-11ea-8a89-8975c98bdb03.png)

Can `FOR_EACH` be generated by a standard mapping action?

**Comment by igarashitm** [comment]
So I think this `MappingMode` is only used in UI, to determine how Mapping Details need to be shown. I think it doesn't really make sense for Conditional Mapping, or we could introduce `MappingMode.EXPRESSION` maybe?
