### ISSUE TITLE
Even when CopyTo is used, it's impossible to define multiple mappings on the same target array element

### ISSUE THREAD

**Issue by vratojr** [atlasmap/atlasmap#2281]
Currently it's impossible to define multiple mappings on the same target array to avoid overwriting previous mappings.
With the introduction of copyto, it should be possible since the mapping may refer to different elements in the same array.
Change the current behavior to display a warning instead of forbidding the mapping.

**Comment by igarashitm** [comment]
@pleacu one question, is there a side effect if we relax "one mapping for each target field"? This issue will allow multiple mappings on a target collection field.
https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap-core/src/services/mapping-management.service.ts#L415
I can't remember how we migrated mapping selection modal in React UI, which might be affected.

**Comment by pleacu** [comment]
I think we saw it as not logical.  I'm not aware of any specific code that relies on there only being "one mapping for each target field".

**Comment by riccardo-forina** [comment]
On the ui there is some check about not allowing a connected target here https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx#L480

**Comment by vratojr** [comment]
@riccardo-forina I tested it and it doens't seem to apply to our case.
@igarashitm same for your proposition.

**Comment by igarashitm** [comment]
https://github.com/atlasmap/atlasmap/pull/2290

**Comment by vratojr** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1368836/90421085-26a2da80-e0b9-11ea-9edb-81dced013268.gif)

Hello,

**Comment by pleacu** [comment]
@vratojr @igarashitm - Hey - I'm back! :)
I restricted the multiple target selection to collections only.  The example seems to show a simple STRING property being targeted.  @vratojr - could you enable type display (the `i` icon on the main toolbar).  Do we essentially want to allow multiple targeting for any target type?

**Comment by igarashitm** [comment]
But the parent is a collection isn't it?

**Comment by pleacu** [comment]
The target appears to be a simple property - are you asking about the source side?

**Comment by igarashitm** [comment]
Can't see the field name as resolution is too low, but I can see the parent fieid of the target it is mapping to in the gif is a collection.

**Comment by igarashitm** [comment]
To be clear, condition is "at least one of the field in the path is a collection". But not "terminal field is a collection".

**Comment by pleacu** [comment]
Ah - the example has a document named `Properties` or something close - you can see the real `Properties` at the top.  Also - d&d doesn't seem to work on Linux.  @vratojr - could you attach your .adm so I can be certain of your example?
