### ISSUE TITLE
When given target data, those un-mapped data should reserved.

### ISSUE THREAD

**Issue by MingningShao** [atlasmap/atlasmap#2299]
I noticed that, the Json writer always created by a default constructor, well, it has no root element.
So, it created root element for a mapping.
When given a target data, we should not use an default writer to create a new root node and overwrite un-mapped data.
This's not reasonable.
The Json reader is a good example to read the root element by source data.
If no source data provide, it's OK.
But a given target data means we want those un-mapping data.

// source code in Json Module.
JsonFieldWriter writer = new JsonFieldWriter();
session.setFieldWriter(getDocId(), writer);

**Comment by MingningShao** [comment]
I noticed that, the Json writer always created by a default constructor, well, it has no root element.
So, it created root element for a mapping.
When given a target data, we should not use an default writer to create a new root node and overwrite un-mapped data.
This's not reasonable.
The Json reader is a good example to read the root element by source data.
If no source data provide, it's OK.
But a given target data means we want those un-mapping data.

// source code in Json Module.
 JsonFieldWriter writer = new JsonFieldWriter();
 session.setFieldWriter(getDocId(), writer);

**Comment by igarashitm** [comment]
What do you mean by `un-mapped data`? Target document is always empty untill you have explicit mapping as AtlasMap performs data mapping field by field. It's not a whole document transformation.

**Comment by MingningShao** [comment]
If we do not provide a target data, it will create a new file by mapping, that's fine. But, if we have a target data, just want map some of the fields, then, just crate a new empty overwrite target data, will not reasonable.

There are two user Scenarios, 
1. just create an empty file by mapping, only have mapping fields; 
2. just update some fields by mapping, un-mapped fields still exists in target file.

We usually use data mapper to do some integrations, take an example, System A -> System B,  we only need two fields from A mapping to B, and the other fields in B do not need a map, they are correct values, and still necessary for B.

If we just create an empty file by mappings, those un-mapped data(fields) are lost, and not a valid data for B.

**Comment by igarashitm** [comment]
`if we have a target data` doesn't make sense in AtlasMap. Target document in AtlasMap is created as a result of mappings. All the document to map from are source document.

**Comment by MingningShao** [comment]
An user can provide a template with default values as an target file, only some of the fields need a mapping, the others are regard as default values, reserved.

AtlasMap provide functions like constant, properties, to map those default values. 
If we have lots of items only two fields need a mapping, we can just use a sample target file as a template, provide default values.

What's more, the target data maybe complex, and we can't just create a mapping by drag lines.
And, those data we usually do not want do anything with them, just standalone.
We have schema both of source and target, we know what we want, we can have a target data.

Let user decide to provide a default template or not. 
Convenient and reasonable.

**Comment by igarashitm** [comment]
Ah OK, so what you want to do is to feed a template target document data. Similar enhancement request to #719 but with user uploaded template. Can you rewrite the issue title and description?
