### ISSUE TITLE
Target property modal shows source document in scope dropdown

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2308]
e.g. `JSONInstanceSource` is shown with this ADM
https://github.com/atlasmap/atlasmap/blob/master/camel3/src/test/resources/atlasmap-mapping.adm

Rather since we don't support multiple target documents when it runs with Camel, we should not show document names for target properties, i.e. only current message header and exchange property are possible.

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/91450754-a44daf80-e84a-11ea-9c89-416c0a0b603c.png)
