### ISSUE TITLE
Is it possible to bring HL7 v2 message structures into atlasmap?

### ISSUE THREAD

**Issue by kesavkolla** [atlasmap/atlasmap#2324]
I was trying to import hapi-structures-v25-2.3.jar into atlasmap and do mapping for some of the HL7 messages. It fails to load the java class by throwing error saying

```
Internal
Could not load JAVA document. Document is not found: ca.uhn.hl7v2.model.v25.message.ORU_R01

```

Didn't understand the meaning of document not found. This class showed up in the UI when I try to to import java class

![image](https://user-images.githubusercontent.com/274645/92084651-57874d00-ede5-11ea-821c-52ab0c9e359d.png)

Has anyone solved this HL7v2 messages in atlasmap?

**Comment by igarashitm** [comment]
Do you see any errors at backend side when you import jar and/or add Java class as a Document?

**Comment by kesavkolla** [comment]
There are no errors on backend.
