### ISSUE TITLE
D&D doesn't work for property>property mapping

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2330]
The source property `id` can't be dropped to target property `order-id`. Create new Mapping > select `/id` from candidate in Mapping Details works.
![Screenshot from 2020-09-03 10-49-29](https://user-images.githubusercontent.com/265462/92130885-3fa6cd80-edd3-11ea-9e42-e2b617dd6549.png)

**Comment by pleacu** [comment]
typo on PR - this is still an issue
