### ISSUE TITLE
Source Properties break after reload

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2332]
2 `id` properties were actually scoped to different source Documents and mapped to different target properties (order-id and contact-id) when it's created, but after reload scope for all source properties are reset to `Current Message Header` and mappings are broken.
![Screenshot from 2020-09-03 11-03-55](https://user-images.githubusercontent.com/265462/92132552-4afaf880-edd5-11ea-9502-575fe81be20f.png)

**Comment by pleacu** [comment]
fixed by https://github.com/atlasmap/atlasmap/pull/2339
