### ISSUE TITLE
Change separator from UI during combine/separate doesn't have any effect 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#234]
Space is still used no matter what separator is selected. Generated mapping XML file looks fine (strategy is defined), so the problem is probably not in UI. 
```<Mappings>
        <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.7287" strategy="Colon" mappingType="Combine">
            <InputField xsi:type="ns2:JavaField" name="sourceString" docId="io.atlasmap.qe.test.SourceMappingTestClass" index="0" path="/sourceString" fieldType="String"/>
            <InputField xsi:type="ns2:JavaField" name="sourceChar" docId="io.atlasmap.qe.test.SourceMappingTestClass" index="1" path="/sourceChar" fieldType="Char"/>
...
```

**Comment by igarashitm** [comment]
This is actually not implemented yet at runtime side, nothing invokes `Mapping.getStrategy()`.

And I think this `strategy` attribute shouldn't be a part of `Mapping` element from model POV. Instead we should have something like this so that the custom strategy could receive arbitrary properties.
```xml
<Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.7287" mappingType="Combine">
    <Strategy className="DefaultAtlasPropertyStrategy" >
        <property name="delimiter" value=":" />
    </Strategy>
    <InputField xsi:type="ns2:JavaField" name="sourceString" docId="io.atlasmap.qe.test.SourceMappingTestClass" index="0" path="/sourceString" fieldType="String"/>
    <InputField xsi:type="ns2:JavaField" name="sourceChar" docId="io.atlasmap.qe.test.SourceMappingTestClass" index="1" path="/sourceChar" fieldType="Char"/>
```

**Comment by igarashitm** [comment]
Moreover I prefer to introduce field grouping on field action described in #27 and get rid of {Combine|Separate}Strategy which is way more straightforward. #210 and some field actions expect a collection as an input also relevant here. @jpav WDYT?

**Comment by jpav** [comment]
I completely agree.  The separation of an action-like mapping from the other mappings has always seemed confusing to me. Creating a grouping action makes much more sense to me. The only thing I think would be even easier is if the user could directly reference items from sources in fields somehow, which should obviate the need for grouping in many cases. But that's probably a longer term goal even if that makes sense to everyone else.

**Comment by igarashitm** [comment]
Yep, so for me it makes much more sense with `One-to-One`, `One-to-Many`, `Many-to-One` vs. `MAP`, `SEPARATE`, `COMBINE`.

**Comment by jpav** [comment]
I was actually talking about getting to a position where everything is considered just a mapping, allowing for individual fields or groups on source or target, so the user doesn't have to specify that at all (including the multiplicities you've suggested). The grouping action would then be a way to not only deal with an initial combine/separate case, but also later on in a transformation chain. But maybe I'm going on too different direction on what you were first suggesting.

**Comment by igarashitm** [comment]
I think that's a good idea if we can solve UXD part. @jpav can you file another issue so that we can discuss with UXD team?

**Comment by jpav** [comment]
Field under issue #244

**Comment by igarashitm** [comment]
As we are running out of time for enhancements, we should make short term fix for this, i.e. get separator delivered to the strategy, without model change.

**Comment by igarashitm** [comment]
Oh actually `Mapping.getDelimiter()` is invoked and delivered to the strategy... it's UI's fault placing delimiter as a strategy.

It even should place `delimiter=":"` instead of `...="Colon"`...

**Comment by igarashitm** [comment]
Also `MultiSpace` is not supported by runtime at all...
