### ISSUE TITLE
Remove docker dependency for release process

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2369]
Currently we use fabric8-maven-plugin which uses docker to build images ~~and push~~ to dockerhub. Since minishift has been deprecated and we are migrating to crc for developer environment, we have to follow that direction.
cf. #2368

Pushing image is actually done in release.sh, so no problem to replace with oc push. It's only about building an image in maven build.

**Comment by igarashitm** [comment]
First question is: can we build&push an image without docker? it might be related to #2368 
If no, do we have an alternative to dockerhub? https://github.com/atlasmap/atlasmap-operator pulls the image from dockerhub

@jamesnetherton do you have any idea around that?

**Comment by jamesnetherton** [comment]
> Can we build&push an image without docker?

Not sure I get this part...

You'll need something to build & push the image. So that usually means Docker, Podman etc. I think [Jib](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#quickstart) can do deamonless build / push if you need that. I've not looked at jkube enough to know whether it can do likewise.

> do we have an alternative to dockerhub

I guess the natural alternative to dockerhub is [quay.io](https://quay.io/). But all of the tools I mentioned above can push to any registry, whether its dockerhub or quay is not important.

**Comment by igarashitm** [comment]
Assuming to have crc on each developer's hand, would be good if we can do that with podman instead as a part of AtlasMap release process. I googled a bit and found a few issues pushing images to dockerhub with podman/buildah, not yet sure if it affects us.

**Comment by jamesnetherton** [comment]
What's the significance of Minishft Vs CRC for AtlasMap releases?

Were you using the Minishift Docker deamon to do the image build and push?

**Comment by igarashitm** [comment]
Yes, the fabric8-maven-plugin we use to build&push docker images to dockerhub, depends on local docker instance. And I use the docker env in minishift when I run AtlasMap release.
https://github.com/eclipse/jkube still states docker and no podman... use oc:push instead? would require crc(or openshift) to be installed then.

**Comment by jamesnetherton** [comment]
I can think of a few ways around this...

* Install docker on your host (I'm assuming you're using Mac?. Docker should run ok on OS X)

* Run a lightweight Linux VM with docker, and expose the daemon to your host

* skip the f-m-p plugin execution by default and have CircleCI or a GitHub action do the docker build & push whenever a new git tag is created

* Explore deamonless builds with Jib

* There's also `crc podman-env` but I've never got it to work in any meaningful way

**Comment by igarashitm** [comment]
Thanks! alright I'll explore those, Jib sounds interesting. Also look at https://github.com/eclipse/jkube if it allows to build an image with only what I have from crc.

**Comment by igarashitm** [comment]
It looks like jkube is already doing something with Jib
https://github.com/eclipse/jkube/issues?q=is%3Aissue+sort%3Aupdated-desc+jib+

**Comment by igarashitm** [comment]
hmm... building docker image through jkube+Jib succeeded, but it's tarball. I can't find a way to upload this tarball to dockerhub.
