### ISSUE TITLE
Atlasmap scoped field support - refactor.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2382]
Source paths can now be decorated with GUID identifiers.  This appears to conflict with collection index IDs:

`Caused by: java.lang.NumberFormatException: For input string: "XMLSchemaSource-532be975-9508-449f-8cff-7b883baa9d8e"`
	`at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_232]`
	`at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_232]`
	`at java.lang.Integer.valueOf(Integer.java:766) ~[na:1.8.0_232]`
	`at io.atlasmap.core.AtlasPath$SegmentContext.getCollectionIndex(AtlasPath.java:489) ~[atlas-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]`
	`at io.atlasmap.core.AtlasPath$SegmentContext.<init>(AtlasPath.java:379) ~[atlas-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]`
	`at io.atlasmap.core.AtlasPath.createSegmentContext(AtlasPath.java:348) ~[atlas-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]`
	`at io.atlasmap.core.AtlasPath.parse(AtlasPath.java:337) ~[atlas-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]`

To test:
1.  Import a source and target file (ref attachment)
2.  Create a target property whose scope is based on the imported target file.
3.  Create a mapping from any source field to the target property.

![sc1](https://user-images.githubusercontent.com/2981421/94567735-c7002900-0239-11eb-9462-102db21c172f.png)

Also - @igarashitm - wdyt about the property scope with the generated UUID appearing in the panel.  It's correct in that it's required if you have multiple properties referencing different imported source files with the same name.  Referencing camel exchange or current header looks fine.

**Comment by igarashitm** [comment]
Not sure why `Document ID` is passed into AtlasPath - isn't `:` or `/` character contained in a generated Document name?
I would prefer showing Document name as opposed to Document ID for labels. This generated ID should be internal use only. Eventually user should be able to edit Document name in UI to whatever user likes. In the meantime we might be OK to show Document ID with a tooltip in case user adds same name documents. We allow duplicated Document name and avoid errors with assigning GUID, but it's user's responsibility to use appropriate names they can manage.

**Comment by pleacu** [comment]
Are you saying that if I passed `/XMLSchemaSource-dbba273d-ea1a-4aec-95b7-bbeceeda6993` (preceeding slash) that it would work?  I'll try that if so.  Also -  agree with the GUID decorated properties.  It'll look better with the extended format visible in the tooltip only.

**Comment by igarashitm** [comment]
> Are you saying that if I passed `/XMLSchemaSource-dbba273d-ea1a-4aec-95b7-bbeceeda6993` (preceeding slash) that it would work?
No, it has a different meaning then, saying `XMLSchemaSource-dbba273d-ea1a-4aec-95b7-bbeceeda6993` is a root field in some document. Full path expression looks like `DocumentName:/field1/field2[]/field3<>/...` and `AtlasPath` only handles fields part. Document name should be removed before it is passed into `AtlasPath`. The error looks like the Document ID is passed into as if it's a part of field name, or even as a collection index quoted with `< > [ ]`.

**Comment by igarashitm** [comment]
so, I suspect `<XMLSchemaSource-dbba273d-ea1a-4aec-95b7-bbeceeda6993>` is passed into as a field path.

**Comment by pleacu** [comment]
Ok - I'm using the <scope> to differentiate the same-named properties in the field arrays.  I'll look at it from the front end.

**Comment by pleacu** [comment]
Hey @igarashitm you were right - the use of `<>` in the field name tricked the runtime atlas-path code to get triggered.  So what I've done is to use `name|scope` for the property names.  It's a small pain to have to clean up the labels that are viewed but there are multiple (3) arrays used in atlasmap core that rely on unique names.  One uses the name as the accessor value (index).  Rewriting those to take a name, scope duple would be much more difficult/ error prone.  So - I've removed the default display of the decorated properties - just using the user property name and using the decorated scoped names in the tooltips.  That leaves us with something like this:

![sc1](https://user-images.githubusercontent.com/2981421/94600525-fcb80880-025f-11eb-9b9b-f5efda404a3a.png)

![sc2](https://user-images.githubusercontent.com/2981421/94600759-60dacc80-0260-11eb-8d05-24d5ed3a5326.png)

**Comment by igarashitm** [comment]
hmm I'd want to see Document name... say having 5 HTTP requests and gather HTTP response code, it'd have 5 HttpResponseCode in source Properties and you have to look at tooltip to see which is what. Property name conflict is far more common than document name conflict. But if it requires major refactoring, you might file an another issue to show document name and go with this in the meantime.

**Comment by igarashitm** [comment]
I wonder why you need to create a concatenated single string to compare - isn't it possible to create a PropertyIdentifier object which has scope and name as its member and both of scope and name have to be equal, just like we usually do in Java by overriding `equals` method?

**Comment by pleacu** [comment]
It's basically all of document-definition.model.ts - if you look here:

https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap-core/src/models/document-definition.model.ts#L462

These three arrays get updated whenever you add or update a field:
`    this.fieldPaths.push(field.path);`
`    this.allFields.push(field);`
 `   this.fieldsByPath[field.path] = field;`

The `fieldByPath` actually uses the field path as an index and `fieldPaths` pushes just the path.  It's designed to take and operate on string names.  Even the alphabetize function throws out duplicate names.  It's a pain for the UI code but I''d have to refactor the whole thing if I pass an object instead of a string down to document-definition.model.

**Comment by igarashitm** [comment]
Can't you split into multiple property documents corresponding to each scope?

**Comment by pleacu** [comment]
sure - would you display them seperately?  Property current, Property Camel Exchange, PropertymyJSONdoc

**Comment by igarashitm** [comment]
You could have a 2nd level separator showing scope, but it still has to be under Properties 1st level container.

**Comment by pleacu** [comment]
Right - you can only add properties from the one Property (per panel) container.  I guess how it's displayed is less important than the idea of having multiple property documents under the Property "container" document.  That could be the default document.  Then we'd only create/add the new prop docs if the user created a property that was scoped there.  Then duplicate property names would not be a problem w/ different docs.  You might have something there Tomo!  I'll look into it

**Comment by pleacu** [comment]
As it turns out there were bugs in the document definition field arrays that needed to be addressed and establishing multiple property documents caused headaches for the mapping serializer.  So - I addressed the issues with the the document definition model and was able to use the path/scope duple as the key for the `fieldByPath` array.  This isolated the changes and looks like the best fix.
