### ISSUE TITLE
Update screenshots on docs.atlasmap.io

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2385]
Those screenshots are from old v1 Angular UI, should be updated to the latest.

Separated www.atlasmap.io website issue
https://github.com/atlasmap/atlasmap.io/issues/5

**Comment by gashcrumb** [comment]
Also I wonder if we should consider using screenshots from either standalone or vscode.

**Comment by igarashitm** [comment]
It seems #2782 and atlasmap/atlasmap.io#5 removed invalid screenshots - used standalone one for www.atlasmap.io
