### ISSUE TITLE
Get Document ID copied to clipboard

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2389]
cf. https://issues.redhat.com/browse/ENTESB-14896

#2198 introduced UUID added to the Document ID while Document name is shown in UI. In order to put the mapping into Camel Route, user need a Document ID string to handle multiple source documents. Add some way to copy Document ID to their clipboard.

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/95616014-27137e00-0a37-11eb-9d71-b0ce0239d9cf.png)

![sc2](https://user-images.githubusercontent.com/2981421/95616030-2d095f00-0a37-11eb-8929-4b5ca21c70a9.png)

**Comment by igarashitm** [comment]
Looks cool - I think `Extended document name` should be `Document ID`

**Comment by pleacu** [comment]
Ok

**Comment by pleacu** [comment]
![sc3](https://user-images.githubusercontent.com/2981421/95618134-8a52df80-0a3a-11eb-8624-5bfcdae4311c.png)

**Comment by brunoNetId** [comment]
How do you copy to the clipboard the Document ID?
I don't see the option running AtlasMap in VSCode
