### ISSUE TITLE
UI: Disable multiplicity transformations when expression box enabled

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2412]
ref: https://issues.redhat.com/browse/ENTESB-13996

Generate mappings which reference the expression when the expression box is enabled.  Generate multiplicity transformations when the expression box is disabled.

**Comment by pleacu** [comment]
Hey @igarashitm  - wanted to capture this in the non-ENTESB issue.  If a user types into the expression box :

`sourceInteger * sourceDouble"`

then should the UI translate that int the multiplicity transformation

`Multiply(sourceInteger, sourceDouble)'

specifically

  `"Mapping" : {`
 `   "jsonType" : "io.atlasmap.v2.Mapping",`
`    "inputFieldGroup" : {`
`      "jsonType" : "io.atlasmap.v2.FieldGroup",`
`      "actions" : [ {`
 `       "@type" : "Multiply"`
`      } ],`
`      "field" : [ {`
 `       "jsonType" : "io.atlasmap.json.v2.JsonField",`
  `      "value" : "23.0",`
 `       "docId" : "sourceJson",`
 `       "index" : 0,`
  `      "path" : "/sourceJsonDouble",`
 `       "fieldType" : "NUMBER",`
`        "name" : "sourceJsonDouble",`
`        "userCreated" : false`
`      }, {`
`        "jsonType" : "io.atlasmap.json.v2.JsonField",`
 `       "value" : "22",`
`        "docId" : "sourceJson",`
`        "index" : 1,`
`        "path" : "/sourceJsonInteger",`
 `       "fieldType" : "INTEGER",`
`        "name" : "sourceJsonInteger",`
`        "userCreated" : false`
`      } ]`
`    },`
 `   "inputField" : [ ],`
`    "outputField" : [ {`
 `     "jsonType" : "io.atlasmap.java.v2.JavaField",`
 `     "value" : "23.022",`
`      "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",`
 `     "path" : "/targetString",`
`      "fieldType" : "STRING",`
`      "name" : "targetString"`
`    } ],`
`    "id" : "preview"`
`  }`

 (similar for Subtract, Divide).  The issue there is that the UI doesn't parse the expression string.  It sends the expression back to the runtime server to be parsed whole.

`  "Mapping" : {`
 `   "jsonType" : "io.atlasmap.v2.Mapping",`
`    "expression" : " ${sourceJson:/sourceJsonDouble}  * ${sourceJson:/sourceJsonInteger}",`
`...`

So the UI is not equipped to generate anything other than 'Concatenate' as a multiplicity transformation.

 From a user perspective, if a they type "sourceInteger + sourceDouble" then that means expression-string-concat and if they want 'add' they should type in "Add(sourceInteger, sourceDouble)", is that correct?

So - this is the most immediate issue.  The user has a many-to-one mapping.  They enable the expression box.  They then change the `sourceInteger + sourceDouble` to `sourceInteger * sourceDouble`.  They should no longer get the `Concatenate` auto generated multiplicity field action.  In fact...

*If the user makes any edit change to the expression box then the auto-generate concatenate multiplicity field action should be removed.*

The runtime should get the expression and the associated field nodes.

wdyt?

**Comment by igarashitm** [comment]
I can't really remember but the expression `sourceInteger + sourceDouble` might perform numerical calculation. The operator `=` in expression is not an equivalent to `Concatenate`. You have to put `Concatenate()` in expression to be exactly same.
> If the user makes any edit change to the expression box then the auto-generate concatenate multiplicity field action should be removed.
No, multiplicity transformation has to be removed immediately once expression is enabled. Runtime ignores transformations in the mapping definition if expression is available.

**Comment by pleacu** [comment]
Hey @igarashitm - first question.  in this example I have a simple `sourceJsonDouble + 1.0 ` expression.  The preview results don't show the expression result correctly (don't get 100.0).  Do you see any issue with the preview request? 

<pre><font color="#1E8C32">2020-10-13 10:05:59.889 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15727</font> --- [  XNIO-1 task-5] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Preview request: {
  &quot;Mapping&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
    &quot;expression&quot; : &quot;${sourceJson:/sourceJsonDouble}+ 1.0&quot;,
    &quot;inputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;value&quot; : &quot;99.0&quot;,
      &quot;docId&quot; : &quot;sourceJson&quot;,
      &quot;path&quot; : &quot;/sourceJsonDouble&quot;,
      &quot;fieldType&quot; : &quot;NUMBER&quot;,
      &quot;name&quot; : &quot;sourceJsonDouble&quot;,
      &quot;userCreated&quot; : false
    } ],
    &quot;outputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;value&quot; : &quot;99.0&quot;,
      &quot;docId&quot; : &quot;targetJson&quot;,
      &quot;path&quot; : &quot;/targetJsonString&quot;,
      &quot;fieldType&quot; : &quot;STRING&quot;,
      &quot;name&quot; : &quot;targetJsonString&quot;,
      &quot;userCreated&quot; : false
    } ],
    &quot;id&quot; : &quot;preview&quot;
  }
}
<font color="#1E8C32">2020-10-13 10:05:59.889 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15727</font> --- [  XNIO-1 task-5] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Preview outcome: {
  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;${sourceJson:/sourceJsonDouble}+ 1.0&quot;,
      &quot;inputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;value&quot; : 99.0,
        &quot;docId&quot; : &quot;sourceJson&quot;,
        &quot;path&quot; : &quot;/sourceJsonDouble&quot;,
        &quot;fieldType&quot; : &quot;NUMBER&quot;,
        &quot;name&quot; : &quot;sourceJsonDouble&quot;,
        &quot;userCreated&quot; : false
      } ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;value&quot; : &quot;99.0&quot;,
        &quot;docId&quot; : &quot;targetJson&quot;,
        &quot;path&quot; : &quot;/targetJsonString&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;targetJsonString&quot;,
        &quot;userCreated&quot; : false
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ ]
    }
  }
}
</pre>

**Comment by igarashitm** [comment]
Ah, simply it's not implemented yet, `processPreview()` doesn't look at expression at all
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java#L255

**Comment by pleacu** [comment]
ok - but the mapping is correct otherwise?  Also - second question - if I have two source fields, should that always be an input field group or just two input field array elements?  i.e. is this correct for `sourceJsonDouble + sourceJsonInteger`?

<pre><font color="#1E8C32">2020-10-13 10:25:07.401 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15727</font> --- [  XNIO-1 task-3] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Preview outcome: {
  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;${sourceJson:/sourceJsonDouble}+ ${sourceJson:/sourceJsonInteger}&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : 99.0,
          &quot;docId&quot; : &quot;sourceJson&quot;,
          &quot;index&quot; : 0,
          &quot;path&quot; : &quot;/sourceJsonDouble&quot;,
          &quot;fieldType&quot; : &quot;NUMBER&quot;,
          &quot;name&quot; : &quot;sourceJsonDouble&quot;,
          &quot;userCreated&quot; : false
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;sourceJson&quot;,
          &quot;index&quot; : 1,
          &quot;path&quot; : &quot;/sourceJsonInteger&quot;,
          &quot;fieldType&quot; : &quot;INTEGER&quot;,
          &quot;name&quot; : &quot;sourceJsonInteger&quot;,
          &quot;userCreated&quot; : false
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;targetJson&quot;,
        &quot;path&quot; : &quot;/targetJsonString&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;targetJsonString&quot;,
        &quot;userCreated&quot; : false
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ ]
    }
  }
}
</pre>

**Comment by igarashitm** [comment]
IIRC wrapping with `FieldGroup` is recommended, but an array of inputField would still work for backward compatibility.
