### ISSUE TITLE
Translate current mapping transformations when expression is enabled

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2413]
Pre Condition:
1. Have source fields `firlstName` and `lastName`
1. Both of source fields have `Capitalize` transformation
1. many-to-one transoformation `Concatenate` is selected with a delimiter ` `(white space)

Expected default expression when expression is enabled:
`Concatenate(Capitalize(/path/to/firstName), Capitalize(/path/to/lastName), ' ')`

We could add a REST endpoint that translates a mapping into expression, if not appropriate to calculate in UI directly.

**Comment by pleacu** [comment]
Hey @igarashitm - I've got most of the infrastructure set up to send the mappings down to the runtime service to have them translated *but* I'm now thinking it's a lot of work and time.  I'm now thinking it's really not a big deal to just have the UI create the expression from the mappings.  Will go that route.

**Comment by pleacu** [comment]
Hey @igarashitm - just to verify - having multiple transformations results in nested function calls.  i.e.
![cap0](https://user-images.githubusercontent.com/2981421/100663088-c7916a80-3323-11eb-8682-f04a102a275e.png)
Should result in:
![cap1](https://user-images.githubusercontent.com/2981421/100663112-d37d2c80-3323-11eb-9b84-de9f4e07edc9.png)

**Comment by igarashitm** [comment]
@pleacu yep, but maybe `Capitalize` and `Append` is opposite, `Capitalize` should come first? Not sure if it really matters though.

**Comment by pleacu** [comment]
Ya - they should appear in the order they were specified I would think.  The real point is that all of the specified field actions should appear as function return results.  i.e.

Concatenate (Capitalize (Append (someField, 'rat'))), Lowercase (someString), ' ') 

So - another example:
![sc3](https://user-images.githubusercontent.com/2981421/100752300-6f577880-33b6-11eb-9261-1704795fed9c.png)
Would result in this expression:
`Concatenate (Capitalize( Normalize( PadStringLeft(Append (someField, 'rat'), '!', 5)))), Lowercase (someString), ' ')`

**Comment by pleacu** [comment]
@igarashitm - question - what does the expression look like for padded mappings?
![sc5](https://user-images.githubusercontent.com/2981421/100895262-5a004e00-348b-11eb-8401-b3a081707128.png)
something like:
`Concatenate ('', stringPrimitive, '' , stringPrimitive, '', Prepend (orderId, 'hat'), '#')`
??

**Comment by igarashitm** [comment]
It would be `null` instead of empty string to reflect original behavior.
