### ISSUE TITLE
Disable transformation if expression is enabled

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2416]
If expression is enabled, transformations defined under field won't be used. All transformation has to be invoked in expression as a function. Therefore we should disable transformation in Mapping Details if expression is enabled.

**Comment by pleacu** [comment]
The cleanest way is to not show the transformation icon/ content/ padding fields if the user toggles on the condition expression box.

![sc1](https://user-images.githubusercontent.com/2981421/96000851-59d9bf80-0e05-11eb-9b3f-92487d215c51.png)

![sc2](https://user-images.githubusercontent.com/2981421/96000879-6100cd80-0e05-11eb-9bf7-91817345ab13.png)
