### ISSUE TITLE
Update atlasmap config object to accept step IDs, labels, etc

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap#242]
On the UI side of things we've this issue -> https://github.com/syndesisio/syndesis/issues/1137 (data structure not finalized), this issue is for updating the datamapper API to accept this data structure in some form.

Right now the syndesis UI goes and makes function calls to add input and output documents, we could either update those functions or consider migrating to one function that accepts an object containing the input and output documents to maybe simplify the interface between components.

**Comment by igarashitm** [comment]
@gashcrumb how about this? Having a single model object (just Documents?) holding a list of source & target docs.

```json
{
  "sourceDocuments": [
    {
      "name": "Salesforce (Step 1)",
      "id": "<generated>",
      "kind": "json-schema",
      "specification": "...", // JSON Schema payload for the Salesforce object
    },
    ...
  ],
  "targetDocuments": [
    {
       "name": "Twitter (Step 2)",
       "id": "<generated>",
       "kind": "java",
       "specification": "twitter4j.Status",
       "inspectionOutcome": "...", // inspection result content which is computed ahead via maven plugin. In Syndesis we are holding it in the DataShape.specification for now.
    },
    ...
  ]
}
```
Syndesis right now doesn't need multiple target documents, but AtlasMap supports it, so let's add it. Syndesis can just pass a single target document.

A small difference in the term, I want to avoid putting inspection results into specification like in Syndesis today. Instead added a `inspectionOutcome` to hold pre-computed inspection result. Then specification is defined as a "Source of inspection" in AtlasMap. The property name might be even "inspectionSource".

**Comment by igarashitm** [comment]
Noticed that the `ConfigModel` already holds lists of sourceDocs/targetDocs. Might be better to refactor a bit to map between Syndesis DataShape smoothly.

**Comment by igarashitm** [comment]
weird, auto close didn't work. closing
