### ISSUE TITLE
"User defined" separator not working

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#2424]
Related to [ENTESB-14107](https://issues.redhat.com/browse/ENTESB-14107)

**Comment by igarashitm** [comment]
First I tried the user defined delimiter with "-" and found that a space ('\u0000') character is already in the user defined delimiter input box. If I delete the space character after I put the "-", the dropdown changes to predefined dash and it works as expected. Note that as soon as you delete the default space character without putting anything, i.e. make the input box empty, the pulldown box changes to `None` and can't put the user defined delimiter.
So, we need to use `onblur` instead for editing user defined delimiter I guess?

![atlasmap](https://user-images.githubusercontent.com/265462/124783176-df147f80-df12-11eb-85b0-54e8851cb6ce.gif)

**Comment by pleacu** [comment]
Sounds like the input needs a trim().

**Comment by igarashitm** [comment]
trim would break if user really want to use the space.
