### ISSUE TITLE
Distinguish 'empty' from 'not-specified' for transformation parameter

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#243]
Forked from #229
Also related to #25 

Some of field actions potentially require to distinguish `empty` from `not-specified` for its parameters, which requires yet another trick in UI to reflect user's intention they want to put an empty value. This involves UXD consideration on how to display/capture in UI.

We'll also need fair amount of use cases to determine how we address this.

**Comment by jpav** [comment]
Null values vs. empty values can definitely be treated differently by whatever applications end up consuming XML documents. I don't know specific use-cases, but I've seen this distinction many times in the past in various documents, and the distinction is addressed both in the XSD spec as well as the XSD spec primer I believe. Having said that, it's probably okay for now to defer until we have more customer feedback/use-cases.

**Comment by jpav** [comment]
From a UI entry standpoint, maybe we need some type of 'X' symbol next to field that can take null values, where pressing the 'X' will set the value to null?

**Comment by nding-anges** [comment]
Hi Tomo 
@igarashitm  Could you please make a example of use case that could help me better understanding the difference between Empty and not-specified? I have a little bit confuse with them. And Null Value is 0 or invalid value?

**Comment by igarashitm** [comment]
Please put this on hold, I can't remember which transformation exactly need to distinguish `empty` from `not-specified`.
