### ISSUE TITLE
Reinstate the 'Overwrite selected document' challenge.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2432]
You can import sample.json and then sample.xml with no modal but you should still get the challenge if you re-import the exact same file name.

![sc1](https://user-images.githubusercontent.com/2981421/96907537-554a8200-1469-11eb-97f5-19d78fad51aa.png)

**Comment by igarashitm** [comment]
Since we introduced unique ID for document import, while showing a warning might be still good, but we would have to allow importing same file as a different instance instead of overwriting.

**Comment by pleacu** [comment]
Do you think it's worth an actual challenge dialog (like is shown) ot should we just display an info toast letting them know that the same file name has been imported more than once?
 @igarashitm

**Comment by igarashitm** [comment]
Hmm, as a user I'd prefer to have a dialog saying like "Document 'address' already exists, do you want to import another one?" maybe?

**Comment by igarashitm** [comment]
btw #2433 would improve UX around this I think.

**Comment by pleacu** [comment]
Yup - saw that - not really a fan  of "Document 'address' already exists, do you want to import another one?" because a 'No" answer means go ahead and import.  I'll tweek the current challenge modal - maybe:

*Confirm document import*

The document sample.json has already been imported into the selected panel.  This file will appear in addition the the pre-existing file.

**Comment by igarashitm** [comment]
Ah OK, I think now I learnt more precise nuance of "another" :-D

**Comment by pleacu** [comment]
![sca](https://user-images.githubusercontent.com/2981421/97001537-8331d400-1506-11eb-8518-3d4fe5c6dded.png)

**Comment by igarashitm** [comment]
Now I wonder one thing, we're not really sure if it's really a same file, are we? we can only get to know the file name is the same, but it could be a different file in the different directory. We might only want to say document name is going to be duplicated, but we don't say if the contents are same or not maybe?

**Comment by pleacu** [comment]
How about:

 `A document with the selected name has already been imported into the specified panel.  It will appear in addition to the pre-existing document.`

That's probably the best we can do.

**Comment by igarashitm** [comment]
Sounds good!
