### ISSUE TITLE
Replace combine/separate mappings with ability to group source/target fields

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#244]
Part of epic #248 

It has always seemed confusing to me that we've give the user the ability to combine or separate source or target fields via mappings, but all other types of transformations are accomplished via later field actions.  I would rather see a more generic ability to group fields from source or target via an action and eliminate the user's need to specify a specific type of mapping. Thus, for example, to combine source fields into a single target field, the user would still use the same DnD/selection process they do now to indicate when multiple fields are involved, but we'd simply automatically create a grouping action containing the source fields instead of creating a special combine mapping. This would simplify the details view, and a longer-term goal would be this generic grouping action could also be used later in the action chain.

**Comment by igarashitm** [comment]
+1, choosing from `MAP`, `SEPARATE` and `COMBINE` makes less sense if we can provide a way to select multiple fields in source and/or target.

A couple of concerns:
* Do we disallow Many-to-Many mapping in the UI?
* In this way at least one field action is required for the One-to-Many and Many-to-One mapping. How do we show that in UI?
   * We might want to add default field action which corresponds to DefaultCombineStrategy and DefaultSeparateStrategy

**Comment by jpav** [comment]
- I guess it depends a bit on what constitutes a many-to-many mapping. Would item-to-array or array-to-array count?
- Not sure if I'm answering your question properly, but I was envisioning the initial selection/DnD of multiple source/target items would cause the automatic creation of a grouping action.

**Comment by igarashitm** [comment]
Let's put aside the Many-to-Many for now, it opens up a can of worms... good news is that we don't support it today and no requirement ATM. Let's just prohibit it at first and see. Then that automatically adding default action would be feasible.

**Comment by pleacu** [comment]
See comments from #95
i.e.
This is what I've got - if a user attempts multiple mappings (map mode) to the same target element then it's flagged with an error. In this example I have an existing mapping beween source element *addressLine1* and target element *fullAddress* and then attempt to map *addressLine2* to* fullAddress*:
![am0](https://user-images.githubusercontent.com/2981421/38197105-9ff2efea-3654-11e8-9fef-9595b92ca971.png)
If a user attempts multiple combine-mode mappings to a single target then it's allowed. The user specifies the compound-selection by using M1 for the first element and ctrl-M1 for each subsequent element. The combine index is calculated as +1 from them previous index:
![am1](https://user-images.githubusercontent.com/2981421/38197108-a57a1ea2-3654-11e8-825a-6f2046f52919.png)
If a user wishes to de-select an element then they press ctrl-M1 on a previously selected element:
![am2](https://user-images.githubusercontent.com/2981421/38197113-ab1344f6-3654-11e8-8014-fb2362d389a7.png)
Note that the user must be in *Combine* mode.

*Q: If a user is not in combine mode and presses ctrl-M1 - should we automatically change into combine mode as a convenience or should we flag an error?*

*Q: How should the index be refactored if a user removes an element in the middle from a combine? If element 3 is removed should we just leave the generated XML as specifying 1,2,4,5?*

A similar (not yet prototyped) effort would occur for *Separate* mode where a single Source element would separate into multiple Target elements via ctrl-M1.

**Comment by pleacu** [comment]
Since we support the ability for the user to designate a separator token in both combine and separate modes, we'll still need the action defined in the mapping details section of the UI.  The other related item we support is the ability to order - not just group - the elements.  This appears to me to be the most clumsy part.  What if we remove the Index and allow the users to drag the elements into the desired order with the mapping details section?

**Comment by igarashitm** [comment]
Yep, separate/combine requires a special mapping action which would have delimiter as a parameter. It would require a significant UX change there. And +1 on removing row index input from form and rely on drug&drop for the field order.

One thing we also need to support is to allow skipping some of those, e.g:
* split one string into 5, but only want 2 and 4 at target side
* combine 3 string source fields and generate a CSV line at target side, but want to leave 3rd and 5th empty

**Comment by igarashitm** [comment]
By the way, although current separate/combine only supports simplest delimiter stuff, #46 is also going to be one of action we should support for the combine case.

**Comment by deernano** [comment]
@jpav @igarashitm @pleacu 
Hi, I create a wireframe for this issue, https://redhat.invisionapp.com/share/W2O9AZS8Y4G#/322055380_One-To-One1
This version is update based on our last UX review meeting.
Please help to review it. Thank you~

**Comment by igarashitm** [comment]
Thanks @deernano, added 2 comments - I think we're almost there :)

**Comment by deernano** [comment]
@igarashitm @jpav @pleacu @heiko-braun 
Hi, I updated the wireframe for this issue to the latest version. https://redhat.invisionapp.com/share/W2O9AZS8Y4G#/322055150_Design-Change1
Please review and confirm it. Thank you~

**Comment by heiko-braun** [comment]
@igarashitm Is this something you plan for 7.4?

**Comment by igarashitm** [comment]
Yes, @pleacu is already working on this.

**Comment by igarashitm** [comment]
I think now main part is done, leftovers from design sketch are #895 and #912 but we can say these are separated enhancements. Moving this to Done.
