### ISSUE TITLE
Enablement of imported Java inner class without dependant JARs should give a more precise message.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2442]
1.  Import camel-profobuf2avro-producer-1.0.jar
2.  Enable demo.camel.TransactionProtos$Transaction

![sc1](https://user-images.githubusercontent.com/2981421/97308565-6283ba00-1837-11eb-9ab7-7a726ce0a904.png)

![sc2](https://user-images.githubusercontent.com/2981421/97308587-69aac800-1837-11eb-9f3f-b01cf6350679.png)

[camel-profobuf2avro-producer-1.0.jar.zip](https://github.com/atlasmap/atlasmap/files/5445661/camel-profobuf2avro-producer-1.0.jar.zip)

**Comment by pleacu** [comment]
As Tomo has found - there's a CNFE on `message:com/google/protobuf/MessageOrBuilder`

<pre><font color="#1E8C32">2020-10-27 14:23:09.087 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">27565</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.service.AtlasLibraryLoader  </font> : Class not found: [ClassLoader:java.net.URLClassLoader@5b84fbae, Class name:demo.camel.TransactionProtos$Transaction, message:com/google/protobuf/MessageOrBuilder]
<font color="#1E8C32">2020-10-27 14:23:09.087 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">27565</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.service.AtlasLibraryLoader  </font> : Class not found: [ClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2, Class name:demo.camel.TransactionProtos$Transaction, message:demo.camel.TransactionProtos$Transaction]
<font color="#1E8C32">2020-10-27 14:23:09.088 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">27565</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.java.service.JavaService    </font> : Class inspection response: {
  &quot;ClassInspectionResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.java.v2.ClassInspectionResponse&quot;,
    &quot;javaClass&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.java.v2.JavaClass&quot;,
      &quot;status&quot; : &quot;NOT_FOUND&quot;,
      &quot;className&quot; : &quot;demo.camel.TransactionProtos$Transaction&quot;,
      &quot;javaEnumFields&quot; : {
        &quot;javaEnumField&quot; : [ ]
      },
      &quot;javaFields&quot; : {
        &quot;javaField&quot; : [ ]
      }
    },
    &quot;executionTime&quot; : 27
  }
}
</pre>

**Comment by igarashitm** [comment]
https://github.com/atlasmap/atlasmap/blob/1f337c962c663fe34ac4a346d9389e30e9e1b5b1/lib/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java#L161
```
2020-10-27 14:23:26.229 DEBUG 371809 --- [  XNIO-1 task-4] io.atlasmap.service.AtlasLibraryLoader   : Class not found: [ClassLoader:java.net.URLClassLoader@67407c08, Class name:demo.camel.TransactionProtos$Transaction, message:com/google/protobuf/MessageOrBuilder]
```
I suspect `AtlasLibraryLoader` can't resolve transitive dependency from other jar ATM.

**Comment by pleacu** [comment]
Import the jar  https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.13.0/protobuf-java-3.13.0.jar then enable `demo.camel.TransactionProtos$Transaction`

![sca](https://user-images.githubusercontent.com/2981421/97347757-98d72e80-1863-11eb-95d0-39caa7b7b1cc.png)

**Comment by igarashitm** [comment]
It worked once you Uploaded dependency jars - #2447 should help a bit to see what jar is missing.
