### ISSUE TITLE
CSV - "ignoreHeaderCase" is not reflected in the UI

### ISSUE THREAD

**Issue by kuhy** [atlasmap/atlasmap#2454]
I expect that when I import a CSV file with the `ignoreHeaderCase` parameter, then headers will be in lower case, but they are not.

Steps to reproduce:
1. Import following CSV file with `Default` format and parameter `firstRecordAsHeader` and `ignoreHeaderCase`:
```
sourceCsvIgnoreHeaderCaseString,sourceCsvIgnoreHeaderCaseNumber,sourceCsvIgnoreHeaderCaseDecimal,sourceCsvIgnoreHeaderCaseDate,sourceCsvIgnoreHeaderCaseBoolean
csv0,0,0.0,1989-05-05,true
csv1,10,10.0,1989-05-05,true
csv2,20,20.0,1989-05-05,true
csv3,30,30.0,1989-05-05,false
csv4,40,40.0,1989-05-05,false
```
![image](https://user-images.githubusercontent.com/3624908/97699912-3a03f600-1aab-11eb-9439-14b3f14c2892.png)

**Comment by igarashitm** [comment]
Hi @rkorytkowski can you take a look at this #2454 and #2455? and put some issue labels once identified.

**Comment by rkorytkowski** [comment]
IgnoreHeaderCase is not meant to apply a lower case transformation. The purpose of it is that if you map headers from a given  file and then run the transformation against a different file that has headers in different case it will still match the same headers and do the right thing.

However, I don't see we have a test case for that feature so I'll use this issue to write one.
