### ISSUE TITLE
Publish a schema for Atlasmap mapping file?

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2480]
tduval-xtensible @tduval-xtensible 16:01
we're generating mappings through automation we want to import in bulk to the tool and then have someone go in manually after to map the items not picked up through automation
it'd be great if you published the schema for the internal .json file with each release and gave us the ability to import mappings in bulk. muy productivity enhancer!
we'll be branching the code soon and persisting mappings in a graph store real time rather than stateful saves like .adm...
but still it'd be a great feature!

**Comment by igarashitm** [comment]
The schema for AtlasMapping is this Java class. We're using jackson to serialize to/deserialize from JSON.
https://github.com/atlasmap/atlasmap/blob/master/lib/model/src/main/java/io/atlasmap/v2/AtlasMapping.java
You would be able to generate a JSON schema file by yourself from this class.

**Comment by tduval-xtensible** [comment]
Or let me ask the bulk import question another way.
I assume there is an API the UI is calling to create the mappings on the server.
Is that something we could do at ‘automation time’ (send a request to an API) rather than crack open the .adm file and hack the .json file? API calls to server seem a little more ‘best practice’ and cleaner.

If we can send mappings to server via API call, is there any information in Dev Guide for this?
If not, can you please reply with some guidance?

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by igarashitm** [comment]
Nope, what you're trying to do is a hack which won't be covered by documents. You'd need to understand the source code and possibly make some enhancements.

We have an idea of having Java API to create/modify mapping definition without UI in case creating complex/huge mapping (e.g. #1514), I'll keep the bulk import thing in mind for that.

**Comment by tduval-xtensible** [comment]
Thanks...
Ok...so what is the openapi REST api intended for? Which was where I was looking to go

**Comment by igarashitm** [comment]
just to get it working via browser.

>

**Comment by tduval-xtensible** [comment]
Ok...are there any samples besides the getFieldActions in restTest.java?
I’ve successfully got that created and looking to know how to create mappings through REST API, sorry, I should have been more clear in my ask.

You can see I’m asking in the Gitter community with my other account name

Sorry for any confusion.  We have a bulk of mappings we want to get into the structure, so looking for something in the interim while we wait on the update.

Tim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by igarashitm** [comment]
I don't remember something else, I would start from looking at REST service
https://github.com/atlasmap/atlasmap/blob/master/lib/service/src/main/java/io/atlasmap/service/AtlasService.java

**Comment by tduval-xtensible** [comment]
Ok...want to stay within the intended way of using the tool (no hacks ;) )

Do you know who worked on the AtlasService? Maybe they could clear some things up for me? Are they on the Gitter community?

I will look into that code more deeply as well

Thank you very much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
