### ISSUE TITLE
Support on-demand loading of document tree

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#2494]
Some documents (like FHIR resources) may be too big to load at once by UI and show as a tree. Some may have recursive fields, which makes them impossible to load at once. 

Nested fields should be loaded only when expanded. To start with all fields at the expanded level should be fetched.

We will not address an issue of too many fields at a level at this point as it's a very rare use case.

Implement a REST service and modify UI code to call it.

**Comment by rkorytkowski** [comment]
@pleacu @igarashitm We need to introduce caching of a processed document in order to respond with a portion of a document without having to inspect it all over. I don't see us using any caching solution in Atlasmap (correct me if I'm wrong) so I'd just use Spring Cache with ehcache implementation. When requesting a new portion of a document tree, we will be passing a key in a form of uuid assigned when first inspecting a new document. We will expire the cache automatically after 24 hours from the last access. Does it sound right to you? If the cached entry expires, we would respond with 204 and the client would have to send the document for inspection again.

**Comment by igarashitm** [comment]
Having serverless & container environment as a primary target, I would rather go with chunked inspection result persisted into multiple files, maybe 1 file for 1 complex field. Then inspection query for the fragment read only 1 file at a time.

**Comment by igarashitm** [comment]
Or jsondb might help to establish the store without inventing our own file linking structure, but I have heard that they hit some disadvantage on using jsondb, can't remember specific...

**Comment by rkorytkowski** [comment]
In order to support container environment and scaling we should really be moving away from a simple file storage to some more advanced storage solution supporting remote and concurrent access. Spring's caching gives an abstraction layer, which allows us to switch from ehcache (local cache) to memcahce/redis (distributed cache) which is more suitable for container environment.

Using a regular DB (non-relational or relational) is also an option, which could be adopted for the purpose of this issue. It is worth considering if in the foreseeable future we want to provide the user a way to save mappings on the server and return back to work after some time. We would not be introducing then yet another dependency for caching, but use the same solution i.e. DB...

As discussed on the call I can implement the file based solution following the practice used in Atlasmap so far, but I do feel that in the long run we should be moving away from that.

**Comment by igarashitm** [comment]
IMO we would want to revisit it once we need multitenancy support. ATM we have no plan for that, AtlasMap stays as a personal tool for design time, sometimes work within an IDE like VSCode. We might want to integrate with external schema registry someday, but it's about entire schema but not already inspected/chunked AtlasMap internal format.

**Comment by rkorytkowski** [comment]
All right!
