### ISSUE TITLE
Properties of child elements not represented in UI properly?? Impact to actual mapping

### ISSUE THREAD

**Issue by MartyStache** [atlasmap/atlasmap#2503]
Here are two sample files. The 'resource' property is not a property of Equipment. In the files 'resource' is a property of Equipment.Container which is a child element of Equipment.

I was putting together a sample for the truncation issue in Docker and noticed this problem. We will have a lot of Equipment in our XML like this where they have a Equipment.Container resource="" pattern which creates a relationship to another Equipment ID="" property that is the container for the equipment. 

![image](https://user-images.githubusercontent.com/62360524/102417365-878be200-3fc9-11eb-8ff8-bbbdf9afbadd.png)

**SOURCE FILE:**
[SOURCE.txt](https://github.com/atlasmap/atlasmap/files/5705954/SOURCE.txt)
**TARGET FILE:**
[TARGET.txt](https://github.com/atlasmap/atlasmap/files/5705956/TARGET.txt)

**Comment by igarashitm** [comment]
Can you upload the schema?

**Comment by MartyStache** [comment]
well duh!
![image](https://user-images.githubusercontent.com/62360524/102501278-40463580-404b-11eb-9f39-9fffcdf72e42.png)

When I use the schema it works fine! Should have tried that first. Thanks! Please close.
