### ISSUE TITLE
Enhancement Request: Include a comments field for each mapping 

### ISSUE THREAD

**Issue by MartyStache** [atlasmap/atlasmap#2504]
We have a need to capture comments for particular mappings to provide the 'mapper' to 'comment their code'. This would be used when someone needs to document what, in human terms, the mapping is doing and why they went about it the way they did. The idea being to keep the documentation as close to the code as possible.

We envision this property would be housed in the JSON right above the id property

![image](https://user-images.githubusercontent.com/62360524/102547142-bd42d080-4086-11eb-9271-ba1e19b44fff.png)

**Comment by tduval-xtensible** [comment]
Will this be included in the next iteration? Any eta?
