### ISSUE TITLE
Make user-friendly the task of picking a class from a pre-loaded JAR file

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#2505]
At present, when you want to select a class as source/target in AtlasMap, you need to:

1) load the JAR file

2) type in the class to choose

The above step 2) is cumbersome as you need to manually type in the full package name and class name, which is prone to mistakes and frustration, as you see in the picture below:

![image](https://user-images.githubusercontent.com/1105127/102602436-d64c8f80-4121-11eb-9649-1758f48dfa9d.png)

A suggested approach would be to disply the available classes to pick one and include a filter text box where we can type to search/narrow-down the list of available classes. The user can then click on the class.

initially reported by Bruno here https://issues.redhat.com/browse/FUSETOOLS2-931

**Comment by pleacu** [comment]
Hey @apupier - this is already supported.  The menu pulldown will contain all user-defined class names.

![sc1](https://user-images.githubusercontent.com/2981421/102620517-1dc82100-410c-11eb-8d0b-5ef0c1e2f36f.png)

**Comment by apupier** [comment]
ok, so either, Bruno was using a too old version or there is a bug in the context it was used.

@pleacu Can you precise since which version it is supported?
@brunoNetId Can you precise with which version you tried? have you tried in VSCode? with standalone? inside Syndesis? Fuse online?

**Comment by pleacu** [comment]
This was made available with AtlasMap 2.1.0 on October 7 2020

**Comment by brunoNetId** [comment]
@apupier This was with AtlasMap in VSCode v0.0.6 (latest)

**Comment by apupier** [comment]
ahah, or the a last possibility, the feature is in a version of VS Code AtlasMap not yet released https://github.com/jboss-fuse/vscode-atlasmap/blob/master/Changelog.md#007

@brunoNetId Just need to wait next release (how efficient we are :-) )

thanks for the answers @pleacu and @brunoNetId

**Comment by brunoNetId** [comment]
That's very much appreciated !
Thanks @pleacu @apupier
