### ISSUE TITLE
Mapping Path Truncates (from the left) on Browser Refresh

### ISSUE THREAD

**Issue by MartyStache** [atlasmap/atlasmap#2507]
I was finally able to get some time to document an example and show you the 'truncation' issue we have been experiencing.
I was hoping that using XSD's for the multiple namespace source and target files would eliminate the issue. I find that it can be demonstrated using "standalone".  Essentially, the left most portion of the path is truncated, so mappings sort of 'derail' from the structure into the root and each refresh seems to make it more protracted. I know an answer is '_don't refresh the browser'!!_ but wanted to see if there is anything that can be done about this behavior. 

Here is a video demonstration of the behavior and the files used. 
https://user-images.githubusercontent.com/62360524/102819665-e4a8de80-43a1-11eb-81c1-8710a114a9de.mp4

[Source.txt](https://github.com/atlasmap/atlasmap/files/5726400/Source.txt)
[Target.txt](https://github.com/atlasmap/atlasmap/files/5726402/Target.txt)

Thanks!

**Comment by pleacu** [comment]
Hey Marty - please give this another try - I believe I've fixed this recently:

`wget https://repo1.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.1.1/atlasmap-standalone-2.1.1.jar`
`http://localhost:8585/`

Let me know or just close the issue if it works for you.
Thkx!

**Comment by MartyStache** [comment]
That looks like it! Can you let me know when this will get into the master repository/branch? 
I will keep you posted if the behavior returns

**Comment by pleacu** [comment]
Sure - it's on master now.  I'll close this and we can reopen if you run into the ssue again.
