### ISSUE TITLE
Document use of camel-atlas component

### ISSUE THREAD

**Issue by brunoNetId** [atlasmap/atlasmap#2508]
xref: https://issues.redhat.com/browse/ENTESB-15463

The documentation here:
https://docs.atlasmap.io/developer-guide/#camel-atlasmap
... would need guidance on how to use Camel properties to pass multiple sources.

Please also document any other relevant aspects on how to operate the camel-atlas component

**Comment by rahgadda** [comment]
Also please add an example in https://github.com/atlasmap/atlasmap/tree/master/examples with quarkus.

I tried to create an example https://github.com/rahgadda/ApacheCamel/tree/master/03-MyDev/quarkus-camel-component/atlasmap

Getting below error message.

Please advice.

Thanks & Regards,
Rahul

https://user-images.githubusercontent.com/13075415/103476335-a3b9bc80-4dda-11eb-9c29-25a94dc517fa.mp4

**Comment by igarashitm** [comment]
Better to be in user-guide - https://docs.atlasmap.io/#running-atlasmap-with-apache-camel
seems like that section in the developer-guide is a duplicate.

**Comment by brunoNetId** [comment]
I've noticed in the following Atlasmap example here:
https://github.com/atlasmap/atlasmap/blob/master/examples/camel-example-atlasmap-multidoc/src/main/java/io/atlasmap/examples/camel/main/Application.java

the following code:
```
        from("direct:order-producer")
            .setProperty("order-schema", simple("resource:classpath:data/order.json"))
            .log("-->; Order: [${exchangeProperty.order-schema}]");
        
        from("direct:contact-producer")
            .setProperty("contact-schema", simple("resource:classpath:data/contact.xml"))
            .log("-->; Contact: [${exchangeProperty.contact-schema}]");
```
I'm assuming here the convention is to use `FILENAME-schema` when setting a property.

What happens then when the filename is the same for both XML and JSON? 
As things stand it appears there would be a clash.

**Comment by igarashitm** [comment]
There's no convention there. You just have to use Document ID (id property on DataSource) that is used in the mapping definition.

**Comment by brunoNetId** [comment]
As I understand it, in the UI the Document ID becomes the input filename (without the extension).
Would 2 same filenames with different extension (eg. order.xml and order.json) produce the same Document ID?
If so, I guess that would be a conflict, is that something we could prevent?

**Comment by igarashitm** [comment]
Current version assigns generated GUID like ID apart from display name. See #2198 and #2389
