### ISSUE TITLE
XSD Enumeration Values not present in UI

### ISSUE THREAD

**Issue by MartyStache** [atlasmap/atlasmap#2521]
Greetings!

Noticed that when specifying an enumeration in an XSD that the list of enumerated values are not present in the UI for mapping. Here is how the enum is spec'd in the xsd and what the thinking of what it might look like if there's the ability to map  an enum value in a source to something in the target (an enum value or something else). Interested in your thoughts/feedback.

Thanks!

Here's the enum in the xsd:
![image](https://user-images.githubusercontent.com/62360524/104770908-57a63a80-573f-11eb-8872-724ee679e3de.png)

Here's how it looks when it loads up into the UI:
![image](https://user-images.githubusercontent.com/62360524/104770963-70aeeb80-573f-11eb-91a8-48e6e35e4158.png)

Thinking here's what it would be like if had ability to map (with @ signs thanks to Pleacu!) - sorry for the namespaces:
![image](https://user-images.githubusercontent.com/62360524/104771143-cd120b00-573f-11eb-950f-2ea6be09233b.png)

**Comment by igarashitm** [comment]
We have LookupTable to handle enum but it only supports Java so far. Let's use this issue to track supporting enum on XML. Also LookupTable might not be implemented in current React UI yet. @pleacu do you know?

**Comment by pleacu** [comment]
#2603
