### ISSUE TITLE
Gray out the field with FieldType.UNSUPPORTED

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2531]
If the `FieldType` is `UNSUPPORTED`, gray it out and make it unselectable in UI.

**Comment by pleacu** [comment]
Hey @igarashitm - just to be sure - any field with type UNSUPPORTED is disabled - like these attribute fields.

![sc1](https://user-images.githubusercontent.com/2981421/105221543-40908f80-5b27-11eb-9a47-9d0a0af1f033.png)

**Comment by igarashitm** [comment]
Looks goood!
