### ISSUE TITLE
Make toolbar function button show available functions

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#2538]
There is no way for a user to know which functions are supported in the function field, other than via RTFM. Clicking the button should show what we support (which is currently just IF and ISEMPTY).

**Comment by pleacu** [comment]
The transformation list (functions available to f(x) expression box) is documented here:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/html/integrating_applications_with_fuse_online/mapping-data_ug#available-transformations_map
And defined here:
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/main/java/io/atlasmap/actions

**Comment by jpav** [comment]
I understand there is documentation for the functions, that was my reference to RTFM. But there is nothing the user has available while using the tool to let him know what functions are available. Think of Excel without any in-app help for functions. I don't think we will be able to get by without any inline help for functions without the user being disgruntled about it.

Regarding the function button's current function, the idea was to address that via #2537

**Comment by igarashitm** [comment]
I think #982 in #2403 is enough for that purpose

**Comment by jpav** [comment]
Ah, didn't see that. Closing this as a duplicate.
