### ISSUE TITLE
XML namespace not persisted into DataSource

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2563]
Seeing weird issue with this XML schema 
https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/xml/schema/po-example-schema.xsd

the target namespace `http://tempuri.org/po.xsd` should be persisted into DataSource in the mapping definition, but not
```json
{
  "jsonType" : "io.atlasmap.v2.DataSource",
  "id" : "po-example-schema-953958cd-728b-48bb-b62c-01eb54816471",
  "name" : "po-example-schema",
  "description" : "Source document po-example-schema type: XSD",
  "uri" : "atlas:xml:po-example-schema-953958cd-728b-48bb-b62c-01eb54816471",
  "dataSourceType" : "SOURCE"
}
```

Note that it does with this schema https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/xml/schema/XMLSchemaSource.xml
```json
{
  "jsonType" : "io.atlasmap.xml.v2.XmlDataSource",
  "id" : "XMLSchemaSource-857eba0d-d35b-442c-9af2-064b059c16ff",
  "name" : "XMLSchemaSource",
  "description" : "Source document XMLSchemaSource type: XML",
  "uri" : "atlas:xml:XMLSchemaSource-857eba0d-d35b-442c-9af2-064b059c16ff",
  "dataSourceType" : "SOURCE",
  "xmlNamespaces" : {
    "xmlNamespace" : [ {
      "alias" : "tns",
      "uri" : "http://syndesis.io/v1/swagger-connector-template/request"
    } ]
  }
}
```
I can see inspection returns namespace in this test, so it looks like an UI issue.
https://github.com/atlasmap/atlasmap/blob/master/lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java#L182

**Comment by igarashitm** [comment]
Oh wait look at that, its `jsonType` shows `io.atlasmap.v2.DataSource` while it should be `io.atlasmap.xml.v2.XmlDataSource` like XMLSchemaSource. Something wrong.

**Comment by pleacu** [comment]
We were only pushing XML files into DataSource as `io.atlasmap.xml.v2.XmlDataSource`, not XSD.

Now it looks like this:

<pre>   &quot;dataSource&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.xml.v2.XmlDataSource&quot;,
      &quot;id&quot; : &quot;XMLSchemaSource-009254a4-c135-4149-a2aa-38275e20562d&quot;,
      &quot;name&quot; : &quot;XMLSchemaSource&quot;,
      &quot;description&quot; : &quot;Source document XMLSchemaSource type: XML&quot;,
      &quot;uri&quot; : &quot;atlas:xml:XMLSchemaSource-009254a4-c135-4149-a2aa-38275e20562d&quot;,
      &quot;dataSourceType&quot; : &quot;SOURCE&quot;,
      &quot;xmlNamespaces&quot; : {
        &quot;xmlNamespace&quot; : [ {
          &quot;alias&quot; : &quot;tns&quot;,
          &quot;uri&quot; : &quot;http://syndesis.io/v1/swagger-connector-template/request&quot;
        } ]
      }
    }, {
      &quot;jsonType&quot; : &quot;io.atlasmap.xml.v2.XmlDataSource&quot;,
      &quot;id&quot; : &quot;po-example-schema-a3c04e65-1bb1-4f1e-8479-bab5929b67af&quot;,
      &quot;name&quot; : &quot;po-example-schema&quot;,
      &quot;description&quot; : &quot;Target document po-example-schema type: XSD&quot;,
      &quot;uri&quot; : &quot;atlas:xml:po-example-schema-a3c04e65-1bb1-4f1e-8479-bab5929b67af&quot;,
      &quot;dataSourceType&quot; : &quot;TARGET&quot;,
      &quot;xmlNamespaces&quot; : {
        &quot;xmlNamespace&quot; : [ {
          &quot;alias&quot; : &quot;tns&quot;,
          &quot;uri&quot; : &quot;http://tempuri.org/po.xsd&quot;
        } ]
      }
    } ],
</pre>

**Comment by igarashitm** [comment]
Raising to p0 as it potentially affects https://issues.redhat.com/browse/ENTESB-15747
