### ISSUE TITLE
Better error message when Atlasmap Service is not running

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap#257]
When the atlasmap pod/service is not running because of some reason, the error message that happens when opening the datamapper is quite obscure:

![image](https://user-images.githubusercontent.com/99080/35480694-37a5b0d4-0414-11e8-9bbc-7846b06c7c05.png)

It would be much better if there was a dedicated error message that the mapping service was not reachable. Maybe this could be also communitcated back in an error dialog instead of an inline error ?

See also https://github.com/syndesisio/syndesis/issues/1273 where it has been discovered first.

**Comment by igarashitm** [comment]
Ah given that we'll embed AtlasMap runtime into other pod in Syndesis, priority is a bit lower now I guess.
