### ISSUE TITLE
Property names should be flagged if illegal at the dialog, Constant `name:` label should be `Value:`

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2570]
You can basically enter anything in the name field and it will take it.  

![sc1](https://user-images.githubusercontent.com/2981421/107525684-16117f80-6b85-11eb-9246-dd1755a21ebc.png)

**Comment by pleacu** [comment]
Okay - so the constant value can be anything.  The property name should be restricted - like:

`(/\$\{[a-zA-Z0-9._-]+\}/) `

Now can the property name (not value) have '@'???

**Comment by igarashitm** [comment]
yep, it would be better to allow it.
