### ISSUE TITLE
Collection indicator is no longer added to the field path

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2571]
xref: https://issues.redhat.com/browse/ENTESB-15756 https://issues.redhat.com/browse/ENTESB-15747

Using modified FHIR schema here - https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/xml/schema/fhir-patient.xsd

If I map to FHIR `Patient/name<>/given<>/@value`, the collection indication `<>` is not added in the field path
```json
        "outputField" : [ {
          "jsonType" : "io.atlasmap.xml.v2.XmlField",
          "docId" : "fhir-patient-a867c126-694b-4987-8ed9-9df7334cfea0",
          "index" : 0,
          "path" : "/tns:Patient/tns:name/tns:given/@tns:value",
          "fieldType" : "STRING",
          "name" : "value",
          "attribute" : true
        } ]
```
which causes runtime to handle it non-collection.

**Comment by igarashitm** [comment]
Looking at https://issues.redhat.com/browse/ENTESB-15756, it's really weird that `<>` is missing for source Java
```json
"path" : "/sheets/title",
```
but there is for the target JSON
```json
"path" : "/sheets<>/sheet",
```

**Comment by pleacu** [comment]
A little too aggressive on when to populate parent field paths.  Even if the paths exist they made need post-processing to add collection decoration, etc.  Here is the updated mapping output:

<pre>   &quot;mappings&quot; : {
      &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;inputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.xml.v2.XmlField&quot;,
          &quot;actions&quot; : [ {
            &quot;delimiter&quot; : &quot; &quot;,
            &quot;@type&quot; : &quot;Split&quot;
          } ],
          &quot;docId&quot; : &quot;XMLSchemaSource-7b7c49e7-0008-45df-876c-bd57c22ba1c2&quot;,
          &quot;path&quot; : &quot;/tns:request/tns:body/Pet/name&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;name&quot;,
          &quot;userCreated&quot; : false,
          &quot;attribute&quot; : false
        } ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.xml.v2.XmlField&quot;,
          &quot;docId&quot; : &quot;fhir-patient-3e0679c2-26d5-49b2-9366-c865d09a9dc2&quot;,
          &quot;index&quot; : 0,
          &quot;path&quot; : &quot;/tns:Patient/tns:name&lt;&gt;/tns:given&lt;&gt;/@tns:value&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;value&quot;,
          &quot;attribute&quot; : true
        } ],
        &quot;id&quot; : &quot;mapping.898069&quot;
      } ]
    },
</pre>
