### ISSUE TITLE
Add `merge` many-to-one transformation

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2580]
xref: https://issues.redhat.com/browse/ENTESB-12357

Merge multiple source collection fields into target collection. Which is the best action name, merge or join?
```
/Address1<a>/line1 => /TargetAddr<b>/line1
/Address1<a>/line2 => /TargetAddr<b>/line2
...
/Address2<c>/line1 => /TargetAddr<b>/line1
/Address2<c>/line2 => /TargetAddr<b>/line2
```
where `b = a + c`

**Comment by pleacu** [comment]
append implies order where merge just implies they're all  in one bucket.

**Comment by igarashitm** [comment]
Good point, plus `Append` action already exists for string. Let's avoid it.

**Comment by Shrishti1234** [comment]
I also needed this feature in my use case. When this feature we get released or there is some another way to handle the same scenario?
