### ISSUE TITLE
LookupTable for enum support is missing

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2589]
We used to have LookupTable to configure enum mapping in Angular version of UI, but now it's missing in React UI. This Java class could be used for testing - https://github.com/atlasmap/atlasmap/blob/master/lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/TargetTestClass.java

It seems there's no option to configure LookupTable
![Screenshot from 2021-02-24 09-48-17](https://user-images.githubusercontent.com/265462/109018080-ca330000-7685-11eb-92ee-0292683eea67.png)

**Comment by pleacu** [comment]
Hey @igarashitm - I remember this in the back of my head but I can't seem to find it in the last (1.44) version of the angular UI.  Do you recall where the icon was to trigger the lookup table?

**Comment by igarashitm** [comment]
This one looks like it - https://github.com/atlasmap/atlasmap/issues/148#issuecomment-349470623

**Comment by igarashitm** [comment]
Verified with 1.43.4 - I only see a few milestone releases for 1.44.0, IIRC that eventually turned into 2.0.
![Screenshot from 2021-02-24 11-46-18](https://user-images.githubusercontent.com/265462/109035126-50efd900-7696-11eb-9aa1-6ee5999dcce7.png)

**Comment by pleacu** [comment]
Hey @igarashitm - last dumb question:)  please identify the jar file you imported and the class package name that you specified.  It's in lib somewhere...
thkx!

**Comment by igarashitm** [comment]
It's `lib/modules/java/test-model/target/atlas-java-test-model-2.2.0-SNAPSHOT.jar` and `io.atlasmap.java.test.TargetTestClass`

**Comment by pleacu** [comment]
thkx - that did it!

**Comment by pleacu** [comment]
Hey @igarashitm - is many-to-one enum field mapping supposed to work?  It allows it in the angular UI but then fails to aggregate the enums.  i.e.

![sca](https://user-images.githubusercontent.com/2981421/109058975-ab4a6300-76b1-11eb-8b53-cacbf7c04894.png)

only shows the short state enums (i.e. no difference from just selecting the 1-1 short state to long state).

Given it's not working in the old UI I'd suggest we limit the enum field mapping to 1-1.  It already restricts the mapping to enum to enum on the angular side (which is expected).

**Comment by igarashitm** [comment]
Right, lookup table mapping only works between enum and it's always 1-1.

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/110139811-70c38300-7da1-11eb-98e4-a2c6b5f7a79d.png)

![sc2](https://user-images.githubusercontent.com/2981421/110139895-8769da00-7da1-11eb-8a5d-2a48c4a906a0.png)
