### ISSUE TITLE
Fails to read constant in expression

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2618]
xref: https://issues.redhat.com/browse/ENTESB-16033

The expression processor doesn't read constant value, causes following error
```
java.lang.IllegalArgumentException: Unexpected null Field was passed in
	at io.atlasmap.core.DefaultAtlasFieldActionService.buildAndProcessAction(DefaultAtlasFieldActionService.java:670) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasFunctionResolver.lambda$resolve$0(DefaultAtlasFunctionResolver.java:98) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasFunctionResolver.lambda$resolve$0(DefaultAtlasFunctionResolver.java:70) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasExpressionProcessor.processExpression(DefaultAtlasExpressionProcessor.java:60) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasContext.processSourceFieldMapping(DefaultAtlasContext.java:398) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:348) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.itests.core.issue.MultiplicityTransformationRepeatConstantTest.testRepeatConstant(MultiplicityTransformationRepeatConstantTest.java:48) [test-classes/:?]
```

**Comment by igarashitm** [comment]
@pleacu turned out it's an UI issue - constant field is missing in the `inputFieldGroup` here for expression
https://gist.github.com/igarashitm/00fc42f07b05f1997581ba99abd8579c#file-atlasmapping-2618-json-L44-L56

**Comment by igarashitm** [comment]
I also wonder, could UI put just a terminal field `/addressList<>/state` but not wrapped with the parent `/addressList<>`? https://gist.github.com/igarashitm/00fc42f07b05f1997581ba99abd8579c#file-atlasmapping-2618-json-L49
Unlike filter/select usecase which does consume parent COMPLEX field, this expression only uses `/addressList<>/state` field.

**Comment by igarashitm** [comment]
Here is an expected mapping definition
https://github.com/atlasmap/atlasmap/pull/2619/files#diff-036d0ac2e7b821f94c8d22d0197ffcbb935d255a8d149773f71b7a1ee02ad480R43-R69

**Comment by pleacu** [comment]
@igarashitm  Ah - the `TransitionMode.FOR_EACH` was not correctly accounted for.  This is what I generate now - it also doesn't generate the path for the input field group.  WDYT?


<pre>    &quot;mappings&quot; : {
      &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;repeat(count(${JSONSchemaSource-8bb5e554-4adc-4860-8b1a-2573fe3e1751:/addressList&lt;&gt;/state}), ${DOC.Constants.576172:/constant-test})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-8bb5e554-4adc-4860-8b1a-2573fe3e1751&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;state&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
            &quot;value&quot; : &quot;constant-test&quot;,
            &quot;docId&quot; : &quot;DOC.Constants.576172&quot;,
            &quot;path&quot; : &quot;/constant-test&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-43964748-55ec-4824-b4a5-3afb740ab55a&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;state&quot;
        } ],
        &quot;id&quot; : &quot;mapping.682359&quot;
      } ]
    },
</pre>

**Comment by igarashitm** [comment]
This looks good. In this case the root FieldGroup doesn't have path as it's just a wrapper to group multiple fields, unlike the parent COMPLEX field which hold sub fields.
