### ISSUE TITLE
UI: Create custom icons for create constant and create props in the mapping details sidebar

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2660]
There is the plus icons and circle plus icon now.
ref:
![sc5](https://user-images.githubusercontent.com/2981421/114577280-df6de900-9c49-11eb-8e15-c0026924e849.png)

**Comment by pleacu** [comment]
@riccardo-forina - hey - we were considering creating custom icons for the plus and circle-plus icons in the mapping details sidebar above.  Something like `+C` and `+P`.  Any idea on the degree of difficulty?  Any examples you can think of?  Random thoughts?
thkx

**Comment by gashcrumb** [comment]
Does clicking on either of those bring up a dialog?  I'd suggest having just the one icon and then choosing the type in the resulting dialog where you'd enter the key/value.  That way you can use a select control and regular text which might be easier for folks to understand.

**Comment by pleacu** [comment]
Clicking on the plus icon gets you to the create constant dialog, clicking on the circle-plus icon gets you to the create property dialog.  Each dialog is different (they really can't be merged).  The idea of having these buttons in the mapping details sidebar was to have a quick way of creating and mapping a new property or constant in one click.  Plus we'd want to continue to leverage the same dialogs that exist if you click the plus icon in the property or constant document in the source/target panels.  Basically I think if we have to go through multiple levels to get to the correct dialog it loses it's usefulness.

**Comment by riccardo-forina** [comment]
Uhm, the PatternFly way of having multiple actions in a “card” is to have
them as entries in a drop down selector, activated by a caret icon.

Would that work here?

Il giorno mer 14 apr 2021 alle 16:21 Paul Leacu ***@***.***>
ha scritto:

**Comment by pleacu** [comment]
That would work - just adds a second selection - wdyt @igarashitm ?

**Comment by igarashitm** [comment]
That works, not ideal tho.
