### ISSUE TITLE
Wrong field path for `count()` function

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2662]
xref: https://issues.redhat.com/browse/ENTESB-16033

It shows just `${/city}` where it should be absolute path with DocID like `${JsonSchemaSource:/addressList<>/city}`
![Screenshot from 2021-04-14 10-37-55](https://user-images.githubusercontent.com/265462/114729472-0392fe00-9d0e-11eb-9aaa-68fe2640a669.png)

**Comment by pleacu** [comment]
Here's what I've got:

![sc1](https://user-images.githubusercontent.com/2981421/114736103-cf224080-9d13-11eb-8bad-641854cbdc9f.png)
The preview outcome (including audit):
<pre>  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}),  ${DOC.Constants.988033:/test})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
          &quot;fieldType&quot; : &quot;COMPLEX&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          } ]
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.988033&quot;,
          &quot;path&quot; : &quot;/test&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-8fcb15cb-9683-4b82-b324-947f9cd8f46a&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}),  ${DOC.Constants.988033:/test})]: Unexpected null Field was passed in&quot;,
        &quot;docId&quot; : &quot;repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}),  ${DOC.Constants.988033:/test})&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
    }
  }
</pre>

The error from the server:

<pre>java.lang.IllegalArgumentException: Unexpected null Field was passed in
	at io.atlasmap.core.DefaultAtlasFieldActionService.buildAndProcessAction(DefaultAtlasFieldActionService.java:669) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasFunctionResolver.lambda$resolve$0(DefaultAtlasFunctionResolver.java:98) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasFunctionResolver.lambda$resolve$0(DefaultAtlasFunctionResolver.java:70) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasExpressionProcessor.processExpression(DefaultAtlasExpressionProcessor.java:60) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasContext.processSourceFieldMapping(DefaultAtlasContext.java:399) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasPreviewContext.processPreview(DefaultAtlasPreviewContext.java:93) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.service.AtlasService.processMappingRequest(AtlasService.java:554) [atlas-service-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
...
</pre>

And the mapping:

<pre> &quot;Mapping&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
    &quot;expression&quot; : &quot;repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}),  ${DOC.Constants.988033:/test})&quot;,
    &quot;inputFieldGroup&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
      &quot;actions&quot; : [ ],
      &quot;field&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
        &quot;fieldType&quot; : &quot;COMPLEX&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ]
      }, {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
        &quot;value&quot; : &quot;test&quot;,
        &quot;docId&quot; : &quot;DOC.Constants.988033&quot;,
        &quot;path&quot; : &quot;/test&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;
      } ]
    },
    &quot;inputField&quot; : [ ],
    &quot;outputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;docId&quot; : &quot;JSONSchemaSource-8fcb15cb-9683-4b82-b324-947f9cd8f46a&quot;,
      &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
      &quot;fieldType&quot; : &quot;STRING&quot;,
      &quot;name&quot; : &quot;city&quot;
    } ],
    &quot;id&quot; : &quot;preview&quot;
  }
}
</pre>

Where is `city` bad?

**Comment by igarashitm** [comment]
It turned out this one reproduces only after #2662, after #2662, change from `addressList<>` to `addressList<>/city` and then `city` doesn't get the full path.

**Comment by pleacu** [comment]
Ok - I can reproduce this - here's the preview outcome:

<pre>  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}), ${DOC.Constants.988033:/test})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
            &quot;actions&quot; : [ ],
            &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
            &quot;path&quot; : &quot;/addressList&lt;0&gt;&quot;,
            &quot;fieldType&quot; : &quot;COMPLEX&quot;,
            &quot;field&quot; : [ {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;bbb&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;city&quot;
            } ]
          } ]
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.988033&quot;,
          &quot;path&quot; : &quot;/test&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-8fcb15cb-9683-4b82-b324-947f9cd8f46a&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}), ${DOC.Constants.988033:/test})]: Unexpected null Field was passed in&quot;,
        &quot;docId&quot; : &quot;repeat(count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}), ${DOC.Constants.988033:/test})&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
    }
</pre>

So in the expression `city` appears as `${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList<>/city}`.  Is the issue `addressList<>` shopuld be `addressList<0>` or should the inner field `path` contain the docId (even though the docId exists in the `field` def?

**Comment by pleacu** [comment]
Hey @igarashitm - I'm still not seeiing what specifically is wring with htis:

<pre> &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;repeat( count( ${JSONSchemaSource-d977f822-7d14-4401-a36f-171ddf8a1c24:/addressList&lt;&gt;/city}), ${DOC.Constants.398997:/test})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-d977f822-7d14-4401-a36f-171ddf8a1c24&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
            &quot;actions&quot; : [ ],
            &quot;docId&quot; : &quot;JSONSchemaSource-d977f822-7d14-4401-a36f-171ddf8a1c24&quot;,
            &quot;path&quot; : &quot;/addressList&lt;0&gt;&quot;,
            &quot;fieldType&quot; : &quot;COMPLEX&quot;,
            &quot;field&quot; : [ {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;b&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-d977f822-7d14-4401-a36f-171ddf8a1c24&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;city&quot;
            } ]
          } ]
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.398997&quot;,
          &quot;path&quot; : &quot;/test&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-2d018373-816d-4ad1-babe-35f68eeda425&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [repeat( count( ${JSONSchemaSource-d977f822-7d14-4401-a36f-171ddf8a1c24:/addressList&lt;&gt;/city}), ${DOC.Constants.398997:/test})]: Unexpected null Field was passed in&quot;,
        &quot;docId&quot; : &quot;repeat( count( ${JSONSchemaSource-d977f822-7d14-4401-a36f-171ddf8a1c24:/addressList&lt;&gt;/city}), ${DOC.Constants.398997:/test})&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
    }
</pre>

**Comment by igarashitm** [comment]
You have `/addressList<>` parent field while the expression refers to `/addressList<>/city`

**Comment by igarashitm** [comment]
Here is the expected payload - https://github.com/atlasmap/atlasmap/pull/2669/files#diff-42f1c9eba5cf5df2606ae2e49eb523f457e3e32f5fdce3563cee428c2ea074d7

**Comment by pleacu** [comment]
Okay - I think this is now correct - no errors - however no audit response data.

<pre>  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;repeat(count(${JSONSchemaSource-8942d2e4-a7f0-4a20-b2ae-6820d0b095b5:/addressList&lt;&gt;/city}), ${DOC.Constants.29358:/test})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-8942d2e4-a7f0-4a20-b2ae-6820d0b095b5&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;bbb&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-8942d2e4-a7f0-4a20-b2ae-6820d0b095b5&quot;,
            &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          } ]
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.29358&quot;,
          &quot;path&quot; : &quot;/test&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-d6442056-c61a-4499-bae1-70b4295449e2&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.SimpleField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-d6442056-c61a-4499-bae1-70b4295449e2&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ]
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ ]
    }
  }
</pre>

**Comment by igarashitm** [comment]
Audit is empty when it succeeds, you successfully got a response value on `/addressList<0>/city` target field, the `value` is `test`
