### ISSUE TITLE
Unexpected COMPLEX wrapping in expression

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2664]
xref: https://issues.redhat.com/browse/ENTESB-16033

Unlike `filter()/select()` usecase in #2607 which does leverage COMPLEX field, since `count()` refers to `/addressList<>/city` directly, it shouldn't be wrapped with `addressList`.
![atlasmap](https://user-images.githubusercontent.com/265462/114744764-085eae80-9d1c-11eb-97f3-7de6152e063f.gif)

**Comment by pleacu** [comment]
This generated mapping no longer fails:

<pre>   &quot;mappings&quot; : {
      &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;repeat( count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}), ${DOC.Constants.819197:/test})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;b&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
            &quot;value&quot; : &quot;test&quot;,
            &quot;docId&quot; : &quot;DOC.Constants.819197&quot;,
            &quot;path&quot; : &quot;/test&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-8fcb15cb-9683-4b82-b324-947f9cd8f46a&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ],
        &quot;id&quot; : &quot;mapping.809462&quot;
      } ]
    },
</pre>

However it doesn't generate any preview output:

<pre> &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;repeat( count(${JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46:/addressList&lt;&gt;/city}), ${DOC.Constants.819197:/test})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;b&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-364b5c43-fea5-49b8-aff9-3651e907ed46&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.819197&quot;,
          &quot;path&quot; : &quot;/test&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-8fcb15cb-9683-4b82-b324-947f9cd8f46a&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ ]
    }
  }
</pre>

Just to recap - the complex collection layers should only be added:
* In preview mode
* when a transformation function has an argument that in a complex field
*  when a transformation function also passes a parameter that is a cild of the complex field

is that right?  

Also - what is expected as output for this expression?

**Comment by igarashitm** [comment]
If you mean collection "instance" layer (indexed collection path in the middle, e.g. addressList<n>) by "complex collection layers", then we could say so at this moment. The collection instance is only needed for preview, not for mapping definition. But if `addressList<>` complex collection is referred from expression, it has to be populated in definition, not only in preview.
On the other hand...
in this specific usecase, `city` field would need the path `/addressList<0>/city` in preview request, and we have to once we support #531. It'll send multiple `/addressList<n>/city` in the preview request by wrapping them up with anonymous FieldGroup.

**Comment by igarashitm** [comment]
Expected preview output from this expression is the value of target field "/addressList<0>/city" being "test". I'll look at runtime side and see if it works with the expected preview request with collection instance.

**Comment by igarashitm** [comment]
Ah wait, the source field has to have the path `/addressList<>/city`, no indexed one to exactly match with the field reference in the expression. In order to send multiple collection instance to support #531, it should be a FieldGroup with the path `/addressList<>/city` which contains instance subfields with the path `/addressList<n>/city`. I'll make a required change for that at runtime side.

**Comment by igarashitm** [comment]
I don't think this is fixed, I still get `/addressList<>` COMPLEX field in `inputFieldGroup` while the expression refers to `/addressList<>/city`
```json
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "expression" : "repeat(count(${JSONSchemaSource-68eba361-91c7-4baa-82e8-5c6620d15065:/addressList<>/city}), ${DOC.Constants.330076:/testv})",
        "inputFieldGroup" : {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ ],
          "field" : [ {
            "jsonType" : "io.atlasmap.v2.FieldGroup",
            "actions" : [ ],
            "docId" : "JSONSchemaSource-68eba361-91c7-4baa-82e8-5c6620d15065",
            "path" : "/addressList<>",
            "fieldType" : "COMPLEX",
            "field" : [ {
              "jsonType" : "io.atlasmap.json.v2.JsonField",
              "value" : "",
              "docId" : "JSONSchemaSource-68eba361-91c7-4baa-82e8-5c6620d15065",
              "path" : "/addressList<>/city",
              "fieldType" : "STRING",
              "name" : "city"
            } ]
          }, {
            "jsonType" : "io.atlasmap.v2.ConstantField",
            "value" : "testv",
            "docId" : "DOC.Constants.330076",
            "path" : "/testv",
            "fieldType" : "STRING"
          } ]
        },
        "inputField" : [ ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.json.v2.JsonField",
          "value" : "",
          "docId" : "JSONSchemaSource-327d08aa-5d2b-428c-a763-f75bc36aee79",
          "path" : "/addressList<>/city",
          "fieldType" : "STRING",
          "name" : "city"
        } ],
        "id" : "mapping.69478"
      } ]
    },
```

**Comment by igarashitm** [comment]
Weirdly it's correct in preview request with a collection instance (`/addressList<0>/city` under `/addressList<>/city`). In mapping definition it should be just `/addressList<>/city`, exactly what is referred from expression. Not `/addressList<>` in this case.

**Comment by pleacu** [comment]
Did you start from scratch - not use an existing mapping?  I imported the `JSONSchemaSource` in source and target and retyped the conditional expression.  I'm getting:

<pre>  &quot;Mapping&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
    &quot;expression&quot; : &quot;repeat( count( ${JSONSchemaSource-1bbfa6fe-6c00-4690-9549-03cc47fd268c:/addressList&lt;&gt;/city}), ${DOC.Constants.546268:/test})&quot;,
    &quot;inputFieldGroup&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
      &quot;actions&quot; : [ ],
      &quot;field&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;docId&quot; : &quot;JSONSchemaSource-1bbfa6fe-6c00-4690-9549-03cc47fd268c&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;COMPLEX&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;b&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-1bbfa6fe-6c00-4690-9549-03cc47fd268c&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ]
      }, {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
        &quot;value&quot; : &quot;test&quot;,
        &quot;docId&quot; : &quot;DOC.Constants.546268&quot;,
        &quot;path&quot; : &quot;/test&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;
      } ]
    },
    &quot;inputField&quot; : [ ],
    &quot;outputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;value&quot; : &quot;&quot;,
      &quot;docId&quot; : &quot;JSONSchemaSource-9b89529e-a37f-427c-a364-562c5078f666&quot;,
      &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
      &quot;fieldType&quot; : &quot;STRING&quot;,
      &quot;name&quot; : &quot;city&quot;
    } ],
    &quot;id&quot; : &quot;preview&quot;
  }
}
</pre>

and

<pre> &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;repeat( count( ${JSONSchemaSource-1bbfa6fe-6c00-4690-9549-03cc47fd268c:/addressList&lt;&gt;/city}), ${DOC.Constants.546268:/test})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-1bbfa6fe-6c00-4690-9549-03cc47fd268c&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;COMPLEX&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;b&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-1bbfa6fe-6c00-4690-9549-03cc47fd268c&quot;,
            &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          } ]
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.546268&quot;,
          &quot;path&quot; : &quot;/test&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-9b89529e-a37f-427c-a364-562c5078f666&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.SimpleField&quot;,
          &quot;value&quot; : &quot;test&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-9b89529e-a37f-427c-a364-562c5078f666&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ]
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ ]
    }
  }
</pre>

**Comment by igarashitm** [comment]
So... until I enable preview mode, wrong `/addressList<>` COMPLEX field is filled. As soon as I play with preview, even the mapping definition is also corrected to have `/addressList<>/city`. It shouldn't depend on preview to correct it though.

**Comment by pleacu** [comment]
AH - ok - I see it too.  So what specifically should be different with the mapping with preview on or off?  Is the mapping https://github.com/atlasmap/atlasmap/issues/2664#issuecomment-825157184 correct (with `/addressList<>/city` above `/addressList<0>/city`?

**Comment by igarashitm** [comment]
The only difference is that preview requires a collection instance, that's it. The structure remains same. So mapping definition doesn't contain collection instance.

**Comment by igarashitm** [comment]
So what is sent for preview is not really a mapping definition, it's created from mapping definition but actually it's an instance of source document.

**Comment by pleacu** [comment]
So what I have for a mapping above is actually wrong since it has the instance.  The preview stuff is right.

**Comment by igarashitm** [comment]
Ah right, mapping definition shouldn't have a collection instance.

**Comment by pleacu** [comment]
One last time (not to be pedantic) :)  Is t his exactly what we want?

<pre>     &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;repeat( count( ${JSONSchemaSource-46db6ef3-99d9-4eaf-8ec7-acba2affaf0a:/addressList&lt;&gt;/city}), ${DOC.Constants.220132:/test})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
            &quot;actions&quot; : [ ],
            &quot;docId&quot; : &quot;JSONSchemaSource-46db6ef3-99d9-4eaf-8ec7-acba2affaf0a&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;COMPLEX&quot;,
            &quot;field&quot; : [ {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-46db6ef3-99d9-4eaf-8ec7-acba2affaf0a&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;city&quot;
            } ]
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
            &quot;value&quot; : &quot;test&quot;,
            &quot;docId&quot; : &quot;DOC.Constants.220132&quot;,
            &quot;path&quot; : &quot;/test&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-25f73887-1d31-476e-ae7a-360d88e91ba2&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/zip&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;zip&quot;
        } ],
        &quot;id&quot; : &quot;mapping.844786&quot;
      } ]
</pre>

**Comment by igarashitm** [comment]
I see `/addressList<>/city` has a child `/addressList<>/city`, which has to be just `/addressList<>/city` with `STRING` field type, without child, no nested&duplicated.

**Comment by igarashitm** [comment]
The target field `/addressList<>/zip` is filled as expected here. The source field should have same structure.

**Comment by pleacu** [comment]
Ok - this appears now to be correct:

## mapping - no preview enabled:

<pre>     &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;repeat( count(${JSONSchemaSource-d51ed586-7bc9-416a-a473-17e5a020e5d9:/addressList&lt;&gt;/city}), ${DOC.Constants.151230:/test})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-d51ed586-7bc9-416a-a473-17e5a020e5d9&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
            &quot;value&quot; : &quot;test&quot;,
            &quot;docId&quot; : &quot;DOC.Constants.151230&quot;,
            &quot;path&quot; : &quot;/test&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-1fd16d14-5f9f-4b7d-b0fa-b52a94a85264&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/zip&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;zip&quot;
        } ],
        &quot;id&quot; : &quot;mapping.499554&quot;
      } ]
    },
</pre>

## mapping - preview enabled:

<pre>  &quot;Mapping&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
    &quot;expression&quot; : &quot;repeat( count(${JSONSchemaSource-d51ed586-7bc9-416a-a473-17e5a020e5d9:/addressList&lt;&gt;/city}), ${DOC.Constants.151230:/test})&quot;,
    &quot;inputFieldGroup&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
      &quot;actions&quot; : [ ],
      &quot;field&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;docId&quot; : &quot;JSONSchemaSource-d51ed586-7bc9-416a-a473-17e5a020e5d9&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;COMPLEX&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;b&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-d51ed586-7bc9-416a-a473-17e5a020e5d9&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ]
      }, {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
        &quot;value&quot; : &quot;test&quot;,
        &quot;docId&quot; : &quot;DOC.Constants.151230&quot;,
        &quot;path&quot; : &quot;/test&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;
      } ]
    },
    &quot;inputField&quot; : [ ],
    &quot;outputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;value&quot; : &quot;&quot;,
      &quot;docId&quot; : &quot;JSONSchemaSource-1fd16d14-5f9f-4b7d-b0fa-b52a94a85264&quot;,
      &quot;path&quot; : &quot;/addressList&lt;&gt;/zip&quot;,
      &quot;fieldType&quot; : &quot;STRING&quot;,
      &quot;name&quot; : &quot;zip&quot;
    } ],
    &quot;id&quot; : &quot;preview&quot;
  }
}
</pre>

**Comment by igarashitm** [comment]
Just to make sure, mapping definition shouldn't change no matter if preview is enabled or not. So if `mapping - preview enabled` is a mapping definition, it shouldn't have a collection instance. But it's correct if it's a preview request.

**Comment by igarashitm** [comment]
Also, `value` on the field shouldn't persisted into mapping definition. It's supposed to be placed only on preview request. I think there was a flag to "ignore field value" to distinguish them in UI code when it serializes.
