### ISSUE TITLE
Build ISSUE ::::: AtlasMap Data Mapper UI -

### ISSUE THREAD

**Issue by tamilvanan-v-104** [atlasmap/atlasmap#2684]
not able to install yarn and getting below issue.
===============================
[INFO] ----------------------< io.atlasmap:atlasmap-ui >-----------------------
[INFO] Building AtlasMap Data Mapper UI 2.1.6                            [1/11]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ atlasmap-ui ---
[INFO]
[INFO] --- frontend-maven-plugin:1.11.0:install-node-and-yarn (install yarn) @ atlasmap-ui ---
[INFO] Installing node version v12.16.3
[INFO] Copying node binary from C:\Users\tamilvanan.v\.m2\repository\com\github\eirslett\node\12.16.3\node-12.16.3-win-x64.exe to C:\Users\tamilvanan.v\SourceCode\DataMapper\atlasmap-atlasmap-2.1.6\ui\node\node.exe
[INFO] Installed node locally.
[INFO] **Installing Yarn version v1.22.4**
[INFO] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz to C:\Users\tamilvanan.v\.m2\repository\com\github\eirslett\yarn\1.22.4\yarn-1.22.4.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for AtlasMap Data Mapper UI 2.1.6:
[INFO]
[INFO] AtlasMap Data Mapper UI ............................ FAILURE [  3.881 s]
[INFO] AtlasMap Standalone Application .................... SKIPPED
[INFO] Unit Test Coverage Report .......................... SKIPPED
[INFO] AtlasMap Examples .................................. SKIPPED
[INFO] Camel :: Example :: AtlasMap ....................... SKIPPED
[INFO] Camel :: Example :: AtlasMap :: Multidoc ........... SKIPPED
[INFO] Camel :: Example :: AtlasMap :: Message Map ........ SKIPPED
[INFO] Camel :: Example :: AtlasMap :: OSGi ............... SKIPPED
[INFO] Example :: AtlasMap runtime API .................... SKIPPED
[INFO] Example :: AtlasMap runtime API + ADM .............. SKIPPED
[INFO] AtlasMap Documentation ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.520 s
[INFO] Finished at: 2021-04-22T16:13:41+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.0:install-node-and-yarn (install yarn) on project atlasmap-ui: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target** -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by igarashitm** [comment]
I haven't ever heard such error, sounds like a environment specific problem (windows). I wonder if there's anybody developing AtlasMap on windows, who might be able to help.

**Comment by gashcrumb** [comment]
Could it be a TLS 1.3 related issue when building with Java 8 -> https://stackoverflow.com/a/57110547

**Comment by tamilvanan-v-104** [comment]
@gashcrumb  how we can proceed to fix this build issue in my local (WIndows).

**Comment by tamilvanan-v-104** [comment]
> Could it be a TLS 1.3 related issue when building with Java 8 -> https://stackoverflow.com/a/57110547
@gashcrumb how we can proceed to fix this build issue in my local (WIndows).

**Comment by gashcrumb** [comment]
It's really going to depend on what JDK you're using.  On that stackoverflow page I read that a couple vendors have backported support for TLS 1.3, so you'd want to be sure you're running openjdk jdk8u292-b10 or Oracle's JDK 8u291.  It looks like they default to TLS 1.3 out of the box but you'll probably want to double-check that.

**Comment by tamilvanan-v-104** [comment]
> It's really going to depend on what JDK you're using. On that stackoverflow page I read that a couple vendors have backported support for TLS 1.3, so you'd want to be sure you're running openjdk jdk8u292-b10 or Oracle's JDK 8u291. It looks like they default to TLS 1.3 out of the box but you'll probably want to double-check that.
Thanks @gashcrumb
