### ISSUE TITLE
Build Issue : UI Module - 2.1.6 version : UI/packages/atlasmap :  semantic error TS2322

### ISSUE THREAD

**Issue by tamilvanan-v-104** [atlasmap/atlasmap#2691]
Hi ,

Can anyone suggest how to fix this issue ?

[INFO] @atlasmap/atlasmap: ⠙ Building modules
[INFO] @atlasmap/atlasmap: ⠹ Building modules
[INFO] @atlasmap/atlasmap: ⠸ Building modules
[INFO] @atlasmap/atlasmap: ⠼ Building modules
[INFO] @atlasmap/atlasmap: ⠴ Building modules
[INFO] @atlasmap/atlasmap: ⠦ Building modules
[INFO] @atlasmap/atlasmap: ⠧ Building modules
[INFO] **@atlasmap/atlasmap: (typescript) Error: C:/Users/abc/atlas-mapper-2.1.6-1/ui/packages/atlasmap/src/UI/AutoDropdown.tsx(17,6): semantic error TS2322: Type** '{ isOpen: boolean; onSelect: () => Promise<void>; toggle: ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)>; ... 365 more ...; key?: string | ... 2 more ... | undefined; }' is not assignable to type 'IntrinsicAttributes'.
[INFO] @atlasmap/atlasmap:   Types of property 'key' are incompatible.
[INFO] @atlasmap/atlasmap:     Type 'string | number | null | undefined' is not assignable to type 'string | number | undefined'.
[INFO] @atlasmap/atlasmap:       Type 'null' is not assignable to type 'string | number | undefined'.
[INFO] @atlasmap/atlasmap: Error: C:/Users/tamilvanan.v/SourceCode/DataMapper/data-mapper-2.1.6-1/ui/packages/atlasmap/src/UI/AutoDropdown.tsx(17,6): semantic error TS2322: Type '{ isOpen: boolean; onSelect: () => Promise<void>; toggle: ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)>; ... 365 more ...; key?: string | ... 2 more ... | undefined; }' is not assignable to type 'IntrinsicAttributes'.
[INFO] @atlasmap/atlasmap:   Types of property 'key' are incompatible.
[INFO] @atlasmap/atlasmap:     Type 'string | number | null | undefined' is not assignable to type 'string | number | undefined'.
[INFO] @atlasmap/atlasmap:       Type 'null' is not assignable to type 'string | number | undefined'.
[INFO] @atlasmap/atlasmap:     at error (C:/Users/abc/atlas-mapper-2.1.6-1\ui\node_modules\rollup\dist\shared\node-entry.js:5400:30)
[INFO] @atlasmap/atlasmap:     at throwPluginError (C:/Users/abc/atlas-mapper-2.1.6-1\ui\node_modules\rollup\dist\shared\node-entry.js:11878:12)
[INFO] @atlasmap/atlasmap:     at Object.error (C:/Users/abc/atlas-mapper-2.1.6-1\ui\node_modules\rollup\dist\shared\node-entry.js:12912:24)
[INFO] @atlasmap/atlasmap:     at Object.error (C:/Users/abc/atlas-mapper-2.1.6-1\ui\node_modules\rollup\dist\shared\node-entry.js:12081:38)
[INFO] @atlasmap/atlasmap:     at RollupContext.error(C:/Users/abc/atlas-mapper-2.1.6-1\uiui\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:17194:30)
[INFO] @atlasmap/atlasmap:     at (C:/Users/abc/atlas-mapper-2.1.6-1\ui\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24994:23

[INFO] @atlasmap/atlasmap: error Command failed with exit code 1.
[INFO] @atlasmap/atlasmap: error Command failed with exit code 1.@atlasmap/atlasmap: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] lerna ERR! yarn run build:module exited 1 in '@atlasmap/atlasmap'
[INFO] error Command failed with exit code 1.
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by igarashitm** [comment]
Can you use Gitter (https://gitter.im/atlasmap/community) or Google Group (https://groups.google.com/d/forum/atlasmap) to ask these kind of questions? Please file an issue here once you make sure there's something we have to change in AtlasMap code.

Also, as you can see here https://circleci.com/gh/atlasmap/atlasmap https://github.com/atlasmap/atlasmap/blob/master/.circleci/config.yml CircleCI build works fine and it builds fine for us. Please start from there and see what's different from it, and describe as much as possible. I don't see any clue from your post here about what's wrong.

**Comment by tamilvanan-v-104** [comment]
okay thanks @igarashitm
