### ISSUE TITLE
UI unit tests for recent bug fixes

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2693]
We should add UT/IT to avoid regression on followings, so it never fails again.
* expression with `select(filter())` and `repeat(count())`
* #2662 #2663 #2664 #2665 #2689 #2706

Especially verify expected mapping definition and preview request are serialized correctly.

**Comment by pleacu** [comment]
@igarashitm - running into an issue with the latest folder refactoring.  I'm getting this error:

`File '/home/pleacu/git-clone/atlasmap/ui/test-resources/mapping/atlasmapping-test.json' is not under 'rootDir' '/home/pleacu/git-clone/atlasmap/ui/packages/atlasmap-core/src'. 'rootDir' is expected to contain all source files.ts(6059)`

Should I establish a `'/home/pleacu/git-clone/atlasmap/ui/packages/atlasmap-core/src/test-resource` - wdyt?

**Comment by igarashitm** [comment]
How can I see that error? build or lint?

**Comment by igarashitm** [comment]
Other tests like document-management.service.spec.ts use the files from test-resources but I don't see any error in neither build or lint.

**Comment by pleacu** [comment]
Never mind - it's VSCode - it's picking out the new files I've added and flagging them but not other files in the same directory.  It doesn't affect the actual build.

**Comment by igarashitm** [comment]
Ah I just found the same vsc error, can you file a techdebt issue separately? I'll look at if tsconfig.json can be more vsc friendly.

**Comment by pleacu** [comment]
ok - #2735
