### ISSUE TITLE
Regression: constant value is missing

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2706]
xref: https://issues.redhat.com/browse/ENTESB-16300

Constant used to store a value in a mapping field but now it's empty. This value is used at runtime.
![Screenshot from 2021-04-27 07-07-19](https://user-images.githubusercontent.com/265462/116232075-a6447700-a727-11eb-9206-b44c5e262d3f.png)
Both of `testv` constant and `/primitives/stringPrimitive` target field has empty value on mapping field.
```json
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.v2.ConstantField",
          "value" : "",
          "docId" : "DOC.Constants.760088",
          "path" : "/testv",
          "fieldType" : "STRING"
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.json.v2.JsonField",
          "value" : "",
          "docId" : "JSONSchemaSource-50a01b0d-e834-4eec-9ad7-d71ddb117328",
          "path" : "/primitives/stringPrimitive",
          "fieldType" : "STRING",
          "name" : "stringPrimitive"
        } ],
        "id" : "mapping.167313"
      } ]
    },
```

However, We also have `/AtlasMapping/constants` in the mapping definition and it still has a value.
```json
   "constants" : {
      "constant" : [ {
        "name" : "testv",
        "value" : "testv",
        "fieldType" : "STRING"
      } ]
    },
```

So, the option is either
1. Place constant value on a mapping field just like before
2. Let runtime use `/AtlasMapping/constants` to get the constant value

WDYT from UI perspective @pleacu ? either way UI should have a unit test to verify constant value is placed as expected in a serialized mapping definition.

**Comment by pleacu** [comment]
Small tweek to the serializer fixes this issue:

<pre>     &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;inputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;testv&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.277163&quot;,
          &quot;path&quot; : &quot;/testv&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        } ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-6e10edec-a909-4cce-b508-892e0251c2ae&quot;,
          &quot;path&quot; : &quot;/primitives/stringPrimitive&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;stringPrimitive&quot;
        } ],
        &quot;id&quot; : &quot;mapping.500671&quot;
      } ]
</pre>
