### ISSUE TITLE
Align UI test directory structure

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2717]
Some article says having separate test directory from src like we do in `@atlasmap/atlasmap-core` is an old way. It actually has a disadvantage that the import should have like `../../../src/foo/bar/Testee` vs. `./Testee` if it's next to the source file. `@atlasmap/atlasmap` has a few test files next to the source file. One option is to have unit tests next to the testee source file and use separate directory for integration tests.
WDYT @gashcrumb @riccardo-forina @pleacu ?

Also it's better to align a suffix for the test file, we currently have `*.spec.[ts|tsx]` in `@atlasmap/atlasmap-core` and `*.test.[ts|tsx]` in `@atlasmap/atlasmap`.

**Comment by pleacu** [comment]
Sure - I like the idea of mapping-serializer.test.ts next to mapping-serializer.ts - it acts as a good and convenient reminder as well.

**Comment by igarashitm** [comment]
I'd vote for `*.spec.[ts|tsx]` as we already have more than `*.test.[ts|tsx]`.

**Comment by igarashitm** [comment]
It seems Syndesis UI has a separate `__tests__` directory

**Comment by riccardo-forina** [comment]
[this](https://github.com/atlasmap/atlasmap/tree/master/ui/packages/atlasmap/test) is just setup stuff, then tests (the few that are there) are next the source [like this one](https://github.com/atlasmap/atlasmap/blob/06d680ade7f55150a20567edc61fc42a1517b770/ui/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.test.tsx)
