### ISSUE TITLE
DataSourceMetadata: isSource parameter name problematic while reflection

### ISSUE THREAD

**Issue by zbendhiba** [atlasmap/atlasmap#2722]
For `camel-quarkus `project, we need to register for reflection all the classes used to serialize/deserialize data on runtime.
To have better performance, we register methods or fields. Since the fields are not public, I registred only methods.
I had a problem with the `DataSourceMetadata` class, because of the name of property is `isSource` does not match with getter/setter names. 
So for this class we need to register both methods and fields, to include the `@JsonProperty("isSource")`.

**Comment by zbendhiba** [comment]
Is it possible to modify this class without impact?

**Comment by igarashitm** [comment]
I think there's no problem changing getter/setter to `getIsSource()/setIsSource()`, is that what you want?

**Comment by zbendhiba** [comment]
Yes. I can do it and send a PR.
