### ISSUE TITLE
UI: Mapping for a collection reference expression missing reference layer input field group (non-preview).

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2729]
This is incorrect - needs second `io.atlasmap.v2.FieldGroup` layer for reference.

<pre>       &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;select( filter( ${JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b:/addressList&lt;&gt;}, ${/city} != &apos;Boston&apos;), ${/state})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;state&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-c5195cfb-3ec0-4397-ab9e-0393e2eea5fa&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ],
        &quot;id&quot; : &quot;mapping.240376&quot;
</pre>

ref #2693

**Comment by pleacu** [comment]
@igarashitm - Hey Tomo - please take a close look at this and verify it's correct.  This is a result of my latest changes.  thkx!

#### Reference collection mapping for `select( filter( addressList<>, city != 'Boston'), state)`

<pre>     &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;select( filter( ${JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b:/addressList&lt;&gt;}, ${/city} != &apos;Boston&apos;), ${/state})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
            &quot;actions&quot; : [ ],
            &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
            &quot;fieldType&quot; : &quot;COMPLEX&quot;,
            &quot;field&quot; : [ {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;city&quot;
            }, {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;state&quot;
            } ]
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-c5195cfb-3ec0-4397-ab9e-0393e2eea5fa&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/zip&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;zip&quot;
        } ],
        &quot;id&quot; : &quot;mapping.779216&quot;
      } ]
</pre>

#### Reference collection preview request for `select( filter( addressList<>, city != 'Boston'), state)`

This works when tested.

<pre>  &quot;Mapping&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
    &quot;expression&quot; : &quot;select( filter( ${JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b:/addressList&lt;&gt;}, ${/city} != &apos;Boston&apos;), ${/state})&quot;,
    &quot;inputFieldGroup&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
      &quot;actions&quot; : [ ],
      &quot;field&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
        &quot;fieldType&quot; : &quot;COMPLEX&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;&quot;,
          &quot;fieldType&quot; : &quot;COMPLEX&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;Bosto&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;MA&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;state&quot;
          } ]
        } ]
      } ]
    },
    &quot;inputField&quot; : [ ],
    &quot;outputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;value&quot; : &quot;MA&quot;,
      &quot;docId&quot; : &quot;JSONSchemaSource-c5195cfb-3ec0-4397-ab9e-0393e2eea5fa&quot;,
      &quot;path&quot; : &quot;/addressList&lt;&gt;/zip&quot;,
      &quot;fieldType&quot; : &quot;STRING&quot;,
      &quot;name&quot; : &quot;zip&quot;
    } ],
    &quot;id&quot; : &quot;preview&quot;
  }
}
</pre>

#### Reference collection mapping for `repeat( count(city), const-str)`

<pre>     &quot;mapping&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;expression&quot; : &quot;repeat( count( ${JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b:/addressList&lt;&gt;/city}), ${DOC.Constants.716098:/const-str})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
            &quot;value&quot; : &quot;const-str&quot;,
            &quot;docId&quot; : &quot;DOC.Constants.716098&quot;,
            &quot;path&quot; : &quot;/const-str&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-c5195cfb-3ec0-4397-ab9e-0393e2eea5fa&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;state&quot;
        } ],
        &quot;id&quot; : &quot;mapping.166221&quot;
      } ]
</pre>

#### Reference collection preview request for `repeat( count(city), const-str)`

<pre>  &quot;Mapping&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
    &quot;expression&quot; : &quot;repeat( count( ${JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b:/addressList&lt;&gt;/city}), ${DOC.Constants.716098:/const-str})&quot;,
    &quot;inputFieldGroup&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
      &quot;actions&quot; : [ ],
      &quot;field&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;COMPLEX&quot;,
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;b&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-5c0ba2d9-4453-4fa9-a6f1-783817a6893b&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        } ]
      }, {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
        &quot;value&quot; : &quot;const-str&quot;,
        &quot;docId&quot; : &quot;DOC.Constants.716098&quot;,
        &quot;path&quot; : &quot;/const-str&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;
      } ]
    },
    &quot;inputField&quot; : [ ],
    &quot;outputField&quot; : [ {
      &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
      &quot;value&quot; : &quot;&quot;,
      &quot;docId&quot; : &quot;JSONSchemaSource-c5195cfb-3ec0-4397-ab9e-0393e2eea5fa&quot;,
      &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
      &quot;fieldType&quot; : &quot;STRING&quot;,
      &quot;name&quot; : &quot;state&quot;
    } ],
    &quot;id&quot; : &quot;preview&quot;
  }
}
</pre>

This works when tested.

**Comment by igarashitm** [comment]
LGTM - does the `repeat/count` usecase stay same? unlike this `filter/select` usecase which uses COMPLEX field and the relative path field in the expression, `repeat/count` usecase we have uses terminal field and it has to have `/addressList<>/city` field directly under `inputFieldGroup`.

**Comment by igarashitm** [comment]
Ah overlooked `repeat/count` example is there as well, yes LGTM.

**Comment by pleacu** [comment]
Yes - about to reply - no change to repeat/count mapping.
