### ISSUE TITLE
UI: Old jest is installed

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2737]
It seems the old version of jest is used despite of specifying newer in the package.json. It might need the yarn.lock to be regenerated.
> [INFO] @atlasmap/atlasmap: ts-jest[versions] (WARN) Version 24.9.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=26.0.0 <27.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.

**Comment by igarashitm** [comment]
@pleacu I got this error after yarn.lock is regenerated - i.e. some dependencies might have been upgraded
> [INFO] @atlasmap/atlasmap: (typescript) Error: /home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/packages/atlasmap/src/Views/SourceMappingTargetView.tsx(71,15): semantic error TS2783: 'onMouseOver' is specified more than once, so this usage will be overwritten.
Actually the `{...mappingEvents}` contains `onMouseOver` and `onMouseOut` so it is duplicate. Which should I keep here?

**Comment by pleacu** [comment]
Not sure - I'd remove the duplicates it's saying it's going to overwrite and see what happens...

**Comment by gashcrumb** [comment]
I'd also make sure to align the versions in the package.json files under packages/* with the top-level package.json, install and then check with `yarn list` that the packages being pulled in are as expected.

**Comment by igarashitm** [comment]
We have to stay with jest 24.9.0, see #2778
