### ISSUE TITLE
UX: mapping details aren't opened right after creation of repeating mapping  

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#274]
Currently when simple mapping (between primitives) is created mapping details are opened when user can easily add transformations etc.  But for repeating mapping is displayed only :
<img width="288" alt="screen shot 2018-02-08 at 16 00 11" src="https://user-images.githubusercontent.com/6814482/35979826-9b21b92c-0ce9-11e8-8f0b-8f9170c32d52.png"> <img width="288" alt="screen shot 2018-02-08 at 15 59 57" src="https://user-images.githubusercontent.com/6814482/35980437-fc84b4de-0cea-11e8-9609-9817fff77b71.png">
For adding transformation user has to click on (tiny) edit icon and then details are displayed. 
<img width="285" alt="screen shot 2018-02-08 at 16 00 17" src="https://user-images.githubusercontent.com/6814482/35979916-cbed9de6-0ce9-11e8-89ea-3a3e606b3bf4.png">
 Wouldn't be better to use the same details page? Or is there any reason (from UI perspective) why repeating mapping is different?

**Comment by pleacu** [comment]
I guess from an expediency perspective users might want whatever the default mapping is with the main 'Repeating Mapping' dialog is given.  I used stringArray to stringPrimitive:

`    <Mappings>
        <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Collection" collectionType="List" mappingType="Collection">
            <Mappings>
                <Mapping xsi:type="Mapping" id="mapping.486626" mappingType="Map">
                    <InputField xsi:type="ns4:JsonField" name="stringArray" userCreated="false" docId="JSONSchemaSource" path="/primitiveArrays/stringArray&lt;&gt;" fieldType="String"/>
                    <OutputField xsi:type="ns4:JsonField" name="stringPrimitive" userCreated="false" docId="JSONSchemaTarget" path="/primitives/stringPrimitive" fieldType="String"/>
                </Mapping>
            </Mappings>
        </Mapping>
    </Mappings>`

Then they can specify particular mapping actions if they want with the edit icon.  I do agree that the edit icon is way too tiny and some hover help would be useful.

**Comment by igarashitm** [comment]
Filed a uxd issue separately - #294
