### ISSUE TITLE
UI: Imported CSV files disappear on reload.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2744]
ref: https://issues.redhat.com/browse/FUSEQE-12547

**Comment by pleacu** [comment]
@igarashitm - Hey Tomo - having trouble with imports - I modified `file-management.service.ts` to add `DocumentType` to the imports.  It now looks like:

<pre>import {
  ErrorInfo,
  ErrorLevel,
  ErrorScope,
  ErrorType,
} from &apos;../models/error.model&apos;;

import { DocumentType, InspectionType } from &apos;../common/config.types&apos;;

import { ConfigModel } from &apos;../models/config.model&apos;;
import { DataMapperUtil } from &apos;../common/data-mapper-util&apos;;
import { DocumentManagementService } from &apos;./document-management.service&apos;;
import { Observable } from &apos;rxjs&apos;;
import { gzip } from &apos;pako&apos;;
import ky from &apos;ky&apos;;
import log from &apos;loglevel&apos;;
import { timeout } from &apos;rxjs/operators&apos;;
</pre>

But I'm getting 
<pre><font color="#34E2E2"><b>@atlasmap/core</b></font>: /home/pleacu/git-clone/atlasmap/ui/packages/atlasmap-core/src/services/file-management.service.ts
<font color="#34E2E2"><b>@atlasmap/core</b></font>:   23:1  error  Imports should be sorted alphabetically  sort-imports
</pre>

If I put the import in alphabetical order I get:
<pre><font color="#34E2E2"><b>@atlasmap/core</b></font>: /home/pleacu/git-clone/atlasmap/ui/packages/atlasmap-core/src/services/file-management.service.ts
<font color="#34E2E2"><b>@atlasmap/core</b></font>:   24:1  error  Expected &apos;multiple&apos; syntax before &apos;single&apos; syntax  sort-imports
</pre>

wdyt?

**Comment by igarashitm** [comment]
multiple import should come first and then single, where each group (multiple, single) should be sorted alphabetically. Not across multiple and single.

**Comment by pleacu** [comment]
Yup - needed to move `import { DocumentType, InspectionType } from '../common/config.types';` to the top - thkx!
