### ISSUE TITLE
Post PF4: Font for MappingDetails/Sources and Targets

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2764]
Following up #2186 and #2752
Font looks smaller, would be better to be like before.
![Screenshot from 2021-05-11 13-47-15-details](https://user-images.githubusercontent.com/265462/117862556-c7957f00-b260-11eb-84fd-014882dda17d.png)

**Comment by pleacu** [comment]
@igarashitm  - does this looks about right?

![sc-med](https://user-images.githubusercontent.com/2981421/120333476-b8cd4580-c2bd-11eb-823d-cd18a7754517.png)

**Comment by igarashitm** [comment]
LGTM :+1:
