### ISSUE TITLE
UI: Establish spec unit tests infrastructure for dialogs

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2766]
There are currently no dialog based unit tests.  Start with the CSV dialog.

**Comment by pleacu** [comment]
@igarashitm - Hey Tomo - I'm fighting with the mapping spec test and it occurred to me that the mapping JSON the UI is generating might be wrong.  Here is the mapping for a many-to-one concatenate action:

<pre>       &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ {
            &quot;delimiter&quot; : &quot;:&quot;,
            &quot;delimitingEmptyValues&quot; : true,
            &quot;@type&quot; : &quot;Concatenate&quot;
          } ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-6e49188c-31e0-44a9-ba4b-e7e7f7105b45&quot;,
            &quot;index&quot; : 0,
            &quot;path&quot; : &quot;/order/contact/firstName&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;firstName&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-6e49188c-31e0-44a9-ba4b-e7e7f7105b45&quot;,
            &quot;index&quot; : 1,
            &quot;path&quot; : &quot;/order/contact/lastName&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;lastName&quot;
          } ]
        },
        &quot;inputField&quot; : [ ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-6d71c237-90d9-45f3-9c54-67f28c7985e0&quot;,
          &quot;path&quot; : &quot;/order/orderId&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;orderId&quot;
        } ],
        &quot;id&quot; : &quot;mapping.583892&quot;
</pre>

Here is the mapping JSON for a one-to-many split:

<pre>       &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
        &quot;inputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;actions&quot; : [ {
            &quot;delimiter&quot; : &quot;:&quot;,
            &quot;@type&quot; : &quot;Split&quot;
          } ],
          &quot;docId&quot; : &quot;JSONSchemaSource-6e49188c-31e0-44a9-ba4b-e7e7f7105b45&quot;,
          &quot;path&quot; : &quot;/primitives/stringPrimitive&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;stringPrimitive&quot;
        } ],
        &quot;outputField&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-6d71c237-90d9-45f3-9c54-67f28c7985e0&quot;,
          &quot;index&quot; : 0,
          &quot;path&quot; : &quot;/order/contact/firstName&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;firstName&quot;
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;docId&quot; : &quot;JSONSchemaSource-6d71c237-90d9-45f3-9c54-67f28c7985e0&quot;,
          &quot;index&quot; : 1,
          &quot;path&quot; : &quot;/order/contact/lastName&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;lastName&quot;
        } ],
        &quot;id&quot; : &quot;mapping.883086&quot;
</pre>

The concat is using an input field group where the split is using just a simple input field.  Everything pvalidates ok - should the split be an input field group??  wdyt?  thkx!

**Comment by igarashitm** [comment]
As `Split` action is for one-to-many, i.e. applies to a single field, I think it's fine to use `inputField` as opposed to the `Concatenate`many-to-one transformation which consumes a group of fields.

**Comment by igarashitm** [comment]
Most of the dialogs have story for it, so the UT should just use it. For example
https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap/src/UI/ColumnMapper/Column.spec.tsx
https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap/src/UI/ColumnMapper/Column.stories.tsx
