### ISSUE TITLE
Visualise mapping details as mapping (message) flow 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#277]
I'd be good if Mapping details windows will be visualised more like mapping/message flow (similar to syndesis ). This could help to understand users how and data are actually processed and mapped (i.e  when transformations is applied..)

This might not require too much work. Mapping details has elements ordered in correct way (source -> action[map,separate,combine..]  -> target -> transformation) but nothing really indicates that it's data "flow". 

It's might be even more helpful when "source" transformations will be implemented.

**Comment by igarashitm** [comment]
We actually need source side transformation to utilize some of them. (#278)

**Comment by nding-anges** [comment]
Hi everyone, @igarashitm @amysueg @jpav @mmelko Please find some basic UI pages design of Detail pannel, and I will continue to make the iteration design based on that, thanks ;-) : 

![empty status - creat a new mapping-](https://user-images.githubusercontent.com/34368385/43131322-587d4762-8f6b-11e8-991d-edba3221425e.png)
![normal mapping detail](https://user-images.githubusercontent.com/34368385/43131369-727b9498-8f6b-11e8-9655-7fda0c68496e.png)
![notification](https://user-images.githubusercontent.com/34368385/43131392-7ec2f890-8f6b-11e8-929f-6a29f51998b4.png)

**Comment by igarashitm** [comment]
I think this is good at this point. We'll need to unify the `Action` with `Transformation` eventually (#244).

**Comment by nding-anges** [comment]
@igarashitm  OK👌，we will also think about the use case of Repeat mapping for next step.

**Comment by amysueg** [comment]
I like this direction as it helps to visually tie together the mapping details design with the IVP in Syndesis. @sjcox-rh @dongni any thoughts?

**Comment by deernano** [comment]
@mmelko @igarashitm @amysueg 
When autometic transition is implemented
The Action section will no longer exist.
The UI will change as following:
- When no source is added
<img width="729" alt="2018-08-21 4 24 16" src="https://user-images.githubusercontent.com/5396309/44389439-6d5aaa00-a55d-11e8-82de-be92f4a6d9d6.png">

-When source is added (The '+' icon will change)
<img width="365" alt="2018-08-21 4 24 27" src="https://user-images.githubusercontent.com/5396309/44389467-806d7a00-a55d-11e8-871a-c90d424e8e7a.png">

**Comment by igarashitm** [comment]
implemented
