### ISSUE TITLE
Post PF4: expression field candidate list too wide

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2771]
need some CSS adjustment after #2752
![Screenshot from 2021-05-14 08-25-21](https://user-images.githubusercontent.com/265462/118270447-15db9580-b48e-11eb-9a72-1ab85d744cd1.png)

**Comment by pleacu** [comment]
![sca](https://user-images.githubusercontent.com/2981421/119863290-653ab080-bee7-11eb-9973-db4d9e8dc3b5.png)
