### ISSUE TITLE
Post PF4: Mapping Details pane doesn't use lower space

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2772]
need some adjustment after #2752
![Screenshot from 2021-05-14 08-28-43](https://user-images.githubusercontent.com/265462/118270834-8b476600-b48e-11eb-8759-4aea94dbec48.png)
![Screenshot from 2021-05-14 08-28-50](https://user-images.githubusercontent.com/265462/118270848-8f738380-b48e-11eb-90f7-49ebbf52f55b.png)
![Screenshot from 2021-05-14 08-28-55](https://user-images.githubusercontent.com/265462/118270883-99958200-b48e-11eb-980a-0261ac1bf042.png)

**Comment by pleacu** [comment]
![ok1](https://user-images.githubusercontent.com/2981421/120501469-a15e8d00-c38f-11eb-92f1-c7ea6eb0f889.png)
