### ISSUE TITLE
Support XML schemas without namespaces

### ISSUE THREAD

**Issue by zregvart** [atlasmap/atlasmap#282]
With #266 we now have support for a schema set containing multiple target namespaces. How difficult would be to match the imported schema with the schema in the `additionalSchemas` using `id` instead of namespaces? Turns out specifying XML namespaces in Swagger documents is optional, and the specification could contain non-namespaced elements mixed with namespaced elements. 

Something like:
```xml
<atlas:SchemaSet xmlns:atlas="http://atlasmap.io/xml/v2/schemaset" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:schema>
    <xs:import namespace="ns1"/>
    <xs:import id="id2"/>
    ...
  </xs:schema>
  <atlas:AdditionalSchemas>
    <xs:schema targetNamespace="ns1">
      ...
    </xs:schema>
    <xs:schema id="id2">
      ...
    </xs:schema>
  </atlas:AdditionalSchemas>
</atlas:SchemaSet>
```

If it would be simpler/easier perhaps we could rely just on the `id`s, i.e. not support matching by `namespace` at all; something like:

```xml
<atlas:SchemaSet xmlns:atlas="http://atlasmap.io/xml/v2/schemaset" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:schema>
    <xs:import id="id1" namespace="ns1"/>
    <xs:import id="id2"/>
    ...
  </xs:schema>
  <atlas:AdditionalSchemas>
    <xs:schema id="id1" targetNamespace="ns1">
      ...
    </xs:schema>
    <xs:schema id="id2">
      ...
    </xs:schema>
  </atlas:AdditionalSchemas>
</atlas:SchemaSet>
```

**Comment by zregvart** [comment]
See this https://gist.github.com/zregvart/4ab273a55641c06c654559512a6f4542 for example of this idea.

**Comment by igarashitm** [comment]
Hi @zregvart - If I understand correctly your example is equal to having
```xml
...
<xs:schema id="id2" targetNamespace="">
...
```
I think I handled it wrong at first place, but not that hard to fix. I'll look into today.

`xs:import` (and `xs:include`) require EntityResolver to handle it, but currently we don't do that. This is required when we need to resolve the schema from external resource. As far as we can pass all the dependent `xs:schema` at once, apparently we don't need it.

**Comment by zregvart** [comment]
@igarashitm yeah, with the difference that I don't think that empty namespace makes much sense. If I'm understanding [this](https://tools.ietf.org/html/rfc2396#appendix-C.2) correctly, it would reference the current document, might that expand into the namespace of SchemaSet?

I'm might be typing gibberish, but I do think that having empty `targetNamespace` might cause problems.

**Comment by igarashitm** [comment]
So you want to inherit the namespace from root Schema (`/atlas:SchemaSet/xs:schema`)? just like `xs:include`? hmm that's another problem then... I can't remember where is it described, but I think there is a gotcha that the default namespace is empty in XML schema.

**Comment by zregvart** [comment]
@igarashitm oh no, I want to `import` a schema from `additionalSchemas` that has no `targetNamespace` defined. I'm afraid that setting `targetNamespace` to `""` will lead to trouble, that's all. And I'm suggesting that we use `schemaLocation` on `import` and `id` on `schema` elements in `additionalSchemas` to link those. Does that make sense?

**Comment by igarashitm** [comment]
OK then it'll get back to my first comment, IIRC getting targetNamespace of the owner schema which doesn't have it specified, returns empty string, so technically it's same with `targetNamespace=""`. I'll test both cases.

**Comment by zregvart** [comment]
We discussed this on the IRC, and the `<xsd:import>` is not needed at all, so this is not an issue.

**Comment by igarashitm** [comment]
I think there's a bug handling sub schemas which doesn't have targetNamespace specified right now, I'll test those cases and fix today.
