### ISSUE TITLE
UI: Tweek the lookup table/enum mapper dialog

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2858]
After the PF4 upgrade the dialog needs a small tweek:

original:

![image](https://user-images.githubusercontent.com/2981421/119660817-a6ef2c80-bdfd-11eb-995c-128c8e53e12c.png)

current:

![sca](https://user-images.githubusercontent.com/2981421/119661000-d736cb00-bdfd-11eb-9be9-bd1ec1de3656.png)

**Comment by pleacu** [comment]
@igarashitm - wdyt?  

![ok1](https://user-images.githubusercontent.com/2981421/119723461-775f1500-be3b-11eb-84fc-3e6add67c77f.png)

**Comment by igarashitm** [comment]
LGTM :+1:
