### ISSUE TITLE
Metadata version mismatch building desktop app

### ISSUE THREAD

**Issue by ruzkant** [atlasmap/atlasmap#286]
I followed the instructions to build the desktop app [here](https://github.com/atlasmap/atlasmap/tree/master/app).

Ran the following build command: npm run electron:prod

And it results in:
ERROR in Error: Metadata version mismatch for module atlasmap-app/node_modules/@atlasmap/atlasmap.data.mapper/node_modules/@angular/core/core.d.ts, found **version 4, expected 3**, resolving symbol DataMapperModule in atlasmap-app/node_modules/@atlasmap/atlasmap.data.mapper/atlasmap.data.mapper.d.ts, resolving symbol DataMapperModule in atlasmap-app/node_modules/@atlasmap/atlasmap.data.mapper/atlasmap.data.mapper.d.ts

The instructions seem to still refer to the separate atlasmap-app repository, but I get the same problem running it from the main atlasmap repo's app folder.

It seems that the atlasmap.data.mapper module is using angular 5 yet the app package.json is using 4. Being more server side java dev, I am not very familiar with angular, npm or yarn. I did a lot of searching and experimentation and tried updating the angular dependencies to 5 which also hit all kinds of other problems.

**Comment by igarashitm** [comment]
Unfortunately desktop app is far behind from core development at this point. Although we don't have plan to catch up soon though, contributions are always welcome!
