### ISSUE TITLE
[Discuss] Consider support for AutoConversion support of java.lang.Object

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#287]
Discuss the approach about whether to support AutoConversion of java.lang.Object for JavaToJava mapping scenarios. 

IMHO, the guiding principal for AtlasMap should be to not support java.lang.Object. If there is a need to do an object "pass through" or support for munging objects that doesn't fit within the current AtlasMap convention, the discussion should include looking at solving that issue within Camel before and/or after an AtlasMap processing.  For example, Camel could prep a java.lang.Object into a second type-aware document, or temporarily stash the object and enrich the created target object after it has exited an AtlasMap processing step.

Related to #269 and #280 

Including my comments from #280 below as reference:

// Begin general discussion on AutoConversion

Remember-- each mapping definition is expecting known types ahead of time. The intent of AtlasMap is to be very type-specific and type-aware. This is complimentary (but different) from Camel, where you could have a process flow auto-detect and auto-convert based on multiple datatypes coming through. Another way to look at it is that AtlasMap should be deterministic.

The main goal of AutoConversion is to prevent having to have really verbose mapping definition files. Imagine having to do:

<InputField type="Integer"... path="myInt" ../>
<convert method="integerToString" ../>
<OutputField type="String" .. path="otherString" />

For every field mapping! Yikes. AutoConversion eliminates a lot of redundant declarations in the mapping definition.

However, AutoConversion is not intended to support things like reading from a JMS Queue and auto-converting different source types to the same target type based on the payload. I'd put forth that in that use case, a Camel route should do CBR and pass the messages to separate AtlasMapping steps based on the supported content types.

FieldType.COMPLEX is intended to define a non-primitive type, or a collection of fields. Its primary use is inspection and design time. Other than being a marker for 'unsupported' it shouldn't be that useful at runtime.

To define a conversion of non-primitive Java classes, like 'com.company.Order to com.company.Invoice', the information needed to pull in the right AutoConversion is the classname. If FieldType.COMPLEX is used, the unique identifier is a composite key of "FieldType.COMPLEX + com.company.Order" to "FieldType.COMPLEX + com.company.Invoice", which can just be reduced to "com.company.Order to com.company.Invoice", since that provides enough uniqueness to identify a proper conversion method. Therefore, declaring or annotating support for FieldType.COMPLEX really doesn't provide any meaning or value.

I think we should resist having any java.lang.Object defined converters as long as possible (or at least until there is a very specific customer use case defined), b/c it breaks the "strongly-typed-we-know-exactly-what-we-are-converting" deterministic paradigm.

As far as the idea of a FieldType.ANY or FieldType.ALL, I think I'd want to understand some specific use cases. In general, I think if we mix and match strongly-typed with loosely-typed the framework becomes difficult to define and extend.

IMHO AtlasMap should be opinionated in that if we get something unexpected, or unsupported that we fail early and provide a clear message-- "No converter found for com.company.Order to com.company.Invoice". This is clean. If we have an Order as a field in a mapping and want to convert it to an Invoice as field in a target type, the user should clearly declare that intent at design time, and reflected in the AtlasMapping definition file. If something isn't defined or a converter is not wired in correctly, we should error out.

I think there are a number of concepts you bring up here, that I'd be happy to talk through, but it is probably to big a convo for just a GitHub discussion. I'd be happy to have a call later today or tomorrow to talk through.

TLDR; Camel for loosely typed non-deterministic conversions, AtlasMap for strongly typed deterministic conversions.

**Comment by igarashitm** [comment]
Just to make sure, I would say having java.lang.Object as a parameter for TypeConverter is **Secret Backdoor** which we never recommend at first place. Oops, I shouldn't have said it loud.

**Comment by igarashitm** [comment]
Closing for now as it only makes sense on custom TypeConverter which we haven't implemented yet.
