### ISSUE TITLE
[Discuss] The concept of a FieldType.ANY or FieldType.ALL

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#288]
@igarashitm brought up the concept of supporting a "pass through" object and/or the ability for AutoConverters to support a FieldType.ANY or FieldType.ALL. 

Related to #280 #269 #287

**Comment by igarashitm** [comment]
In current implementation, anything other than atlas primitives are marked as `FieldType.COMPLEX`, but we terminate the inspection at `java.*` packages/classes. Then if the document has `java.lang.Object` field, it is `FieldType.COMPLEX` which has expand arrow, but can't be expanded as it doesn't contain field info. We should map all the "not atlas primitive, but don't want to inspect" kind of fields into `FieldType.ANY`.

Thing is worse for non-terminal class. If document has `com.fasterxml.jackson.databind.ObjectMapper` as a field, then class inspection provides internal detail of this class and show fields in UI, which is ridiculous. We should either provide an option to mark it as a "atlasmap transient" so it won't appear in the UI, or mark as `FieldType.ANY`.

**Comment by igarashitm** [comment]
Of course that `com.fasterxml.jackson.databind.ObjectMapper` needs to be added as a terminal class beforehand.

**Comment by mattrpav** [comment]
For both scenarios described above, I don't think a new FieldType is needed. Instead, check out the FieldStatus enum and related features.

For something like java.* packages, the user would end up with an inspection FieldStatus of FieldStatus.BLACKLIST. The UI currently does not display any field with that status, since we blacklist the Jdk 8 packages by default.

Ref: [JDK 8 Package blacklist](https://github.com/atlasmap/atlasmap/blob/master/runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/JdkPackages.java)

For something like com.fasterxml.jackson.databind.. the ClassInspectionRequest provides a list of package names that Syndesis can specify to BLACKLIST.

Another option, is to provide a list of FieldNameBlacklist as part of the ClassInspectionRequest. This is used to block the display of fields, such as "serialVersionUID", which is a valid type (long), but not something desirable in the UI.

Ref: [ClassInspectionRequest]
(https://github.com/atlasmap/atlasmap/blob/master/runtime/modules/java/model/src/main/resources/atlas-java-model-v2.xsd#L123)

Hope this helps!

**Comment by igarashitm** [comment]
> For something like java.* packages, the user would end up with an inspection FieldStatus of FieldStatus.BLACKLIST. The UI currently does not display any field with that status, since we blacklist the Jdk 8 packages by default.

This is not correct. Before I mapped date/time related class to `FieldType.DATE_TIME_TZ` and like that, java inspection was looking into the `java.util.Date` internal fields as it's `FieldType.COMPLEX`.

`FieldType.BLACKLIST` sounds it shouldn't be shown in UI, which might be used for the "transient" case in my comment, but not for `FieldType.ANY` case which we do want to show in UI, but don't want to expand and show the child fields.

**Comment by mattrpav** [comment]
If the JDK packages blacklist is not working, than that is probably a minor wiring issue with the ClassInspectionService. The JDKPackages class is there to provide blacklisting of JDK packages to the ClassInspectionService.

Do you have a use case for this 'transient' / 'pass through' use case? I think it would help to see an example to understand all the impacts-- inspection, runtime, FieldActions, etc.

**Comment by igarashitm** [comment]
Think about user is providing a custom connector and it's input and/or output is custom Java class in Syndesis. We shouldn't add any restriction on the class. We can just pass through in AtlasMap runtime if we don't support that field, but we can never say "since this field type is not supported by AtlasMap, you shouldn't have it".

**Comment by mattrpav** [comment]
If the class shouldn't have any mapping occur on it, under what condition would it make sense to event pass it into a mapping step of the integration?

**Comment by igarashitm** [comment]
Why do you hate that much to just copy something AtlasMap doesn't aware from source to target? Do you think there's no usecase that the connector have some proprietary object as a field and just want to pass that object through to the target?

**Comment by mattrpav** [comment]
@igarashitm I do not hate anything, I'm just trying to help by pointing out existing features that may cover the described use cases without any code changes.

What I am hearing from the last comment is the following:
1. User provides customized component that includes custom models
2. One (or more) of the models contains a child field that is complex, but doesn't contain any fields desirable for mapping and the child field needs to be attached to a target object's child field.
3. The non-expanded source and target child fields are the exact same class type.

It sounds like there would be a chicken-and-egg problem. If the class is customized, Syndesis and AtlasMap ClassInspection have no way of knowing ahead of time that the specific field on the customized class should be displayed, but not expanded, and labeled as FieldType.ANY without some additional metadata to be merged with the ClassInspection response.

Would the user provide that metadata when they add the custom component? Perhaps there is an alternate approach I'm not seeing?

**Comment by igarashitm** [comment]
First of all this is for post GA thing, I don't think we have time to achieve this before GA.

Sure they would need to provide a list of custom packages/classes which should be terminal. Same for BLACKLIST I guess? They need to provide a list of packages/classes which should be filtered out in UI so integrator won't see those fields in UI at all. IMHO anything should **NOT** be in BLACKLIST by default, but should be terminal.

**Comment by mattrpav** [comment]
The intent for the the UI (Syndesis) to be able to provide Blacklist (package or field names) was that Syndesis already *knows* about many of the objects (Twitter, SFDC, etc), so the Syndesis connector developers would be readily available to add the metadata ahead of time to get the desired Mapping UI and runtime behaviors.

Your hypothetical use case here identifies a gap, but I think a similar approach to how FieldStatus.BLACKLIST works is the way to go:

1. Add add'l enum to FieldStatus (perhaps FieldStatus.NO_CHILD, or similar)
2. Update ClassInspectionRequest to include something akin to Blacklist.. maybe provide a map of AtlasPath coordinates and a FieldStatus, so all sorts of combinations would work. The Java InspectionService would then merge this fieldStatusMap into the generated output.
3. The user would provide this mapping when they register their connector (and models)
4. Add a FieldAction called "Link, Direct, Reference, Pass through" or similar to provide the direct mapping

Sample ClassInspectionRequest map:
>
>   {  "ClassInspectionRequest": {
>      ...     
>      fieldStatusMap: { 
>      ...
>      "/MyCustomSource/Foo": "NO_CHILD",
>      "/MyCustomSource/serialVersionUid": "BLACKLIST",
>      etc.." }

Sample mapping:

>   <sourceField  "/MyCustomSource/Foo" fieldType="Complex" className="c.company.Foo" ..>
>   <DirectReference ..>
>   <targetField "/MyCustomTarget/Foo" fieldType="Complex" className="c.company.Foo" ..>

**Comment by igarashitm** [comment]
Is there any benefit to choose it vs. having FieldType.ANY? I don't like having fieldType="Complex" there. I would prefer having FieldType.COMPLEX only as a expandable one in UI.

**Comment by mattrpav** [comment]
Yes, the benefit is that we would not be mixing *facts* and *behaviors*. Field Types are a *fact*. Field Status and Field Actions influence *behavior*.

The situation you are describing sounds like a *behavior* and not a new *type*. The *fact* is that the type is Complex. The desire is to dictate a *behavior* of the UI-- do not allow mapping of child fields of a *subset* of complex types. The desired runtime *behavior* is to link a reference from a source object directly to a target object.

FieldStatus is defining inspection behaviors already, and then adding a FieldAction would define the runtime behavior to support the defined use case.

**Comment by igarashitm** [comment]
That doesn't sound intuitive for me. At runtime Object can contains atlas primitives as well under the cover, so COMPLEX doesn't sound right.

**Comment by mattrpav** [comment]
@igarashitm I do not understand what you mean when you said:

> At runtime Object can contains atlas primitives as well under the cover

When you say "Object" do you mean the literal 'java.lang.Object', or a general complex, non-primitive object that contains one or more primitives and/or complex members?

What do you interpret 'FieldType.COMPLEX' to mean?

**Comment by igarashitm** [comment]
java.lang.Object. According to what is suggested from you, java.lang.Object is marked as a FieldType.COMPLEX right? And also note that the FieldType is shown in the UI, so it's user facing label.

**Comment by igarashitm** [comment]
Introduced `FieldType.ANY`, but only maps to `java.lang.Object`. User defined terminal type would map to `FieldType.COMPLEX`.
