### ISSUE TITLE
Qualified namespace handling

### ISSUE THREAD

**Issue by zregvart** [atlasmap/atlasmap#290]
I have a mapping:

<details>
<summary>mapping.json</summary>
<pre>
{
  "AtlasMapping": {
    "jsonType": "io.atlasmap.v2.AtlasMapping",
    "dataSource": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-L5T7PW_IfASsJJ8g5pN",
        "uri": "atlas:json:-L5T7PW_IfASsJJ8g5pN",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.xml.v2.XmlDataSource",
        "id": "-L5T7SjaIfASsJJ8g5pN",
        "uri": "atlas:xml:-L5T7SjaIfASsJJ8g5pN",
        "dataSourceType": "TARGET",
        "template": null,
        "xmlNamespaces": {
          "xmlNamespace": [
            {
              "alias": "tns",
              "uri": "http://syndesis.io/v1/swagger-connector-template/request",
              "targetNamespace": true
            }
          ]
        }
      }
    ],
    "mappings": {
      "mapping": [
        {
          "jsonType": "io.atlasmap.v2.Mapping",
          "mappingType": "MAP",
          "id": "mapping.501850",
          "inputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "last_name",
              "path": "/last_name",
              "fieldType": "STRING",
              "docId": "-L5T7PW_IfASsJJ8g5pN",
              "userCreated": false
            }
          ],
          "outputField": [
            {
              "jsonType": "io.atlasmap.xml.v2.XmlField",
              "name": "name",
              "path": "/request/body/Pet/name",
              "fieldType": "STRING",
              "docId": "-L5T7SjaIfASsJJ8g5pN",
              "userCreated": false
            }
          ]
        }
      ]
    },
    "name": "UI.676698",
    "lookupTables": {
      "lookupTable": []
    },
    "properties": {
      "property": []
    }
  }
}
</pre>
</details>

<p>

That was influenced by the SchemaSet for the target document:

<details>
<summary>schemaset.xml</summary>
<pre>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;d:SchemaSet xmlns:d=&quot;http://atlasmap.io/xml/schemaset/v2&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
  &lt;xsd:schema targetNamespace=&quot;http://syndesis.io/v1/swagger-connector-template/request&quot; elementFormDefault=&quot;qualified&quot;&gt;
    &lt;xsd:element name=&quot;request&quot;&gt;
      &lt;xsd:complexType&gt;
        &lt;xsd:sequence&gt;
          &lt;xsd:element name=&quot;body&quot;&gt;
            &lt;xsd:complexType&gt;
              &lt;xsd:sequence&gt;
                &lt;xsd:element ref=&quot;Pet&quot; /&gt;
              &lt;/xsd:sequence&gt;
            &lt;/xsd:complexType&gt;
          &lt;/xsd:element&gt;
        &lt;/xsd:sequence&gt;
      &lt;/xsd:complexType&gt;
    &lt;/xsd:element&gt;
  &lt;/xsd:schema&gt;
  &lt;d:AdditionalSchemas&gt;
    &lt;xsd:schema&gt;
      &lt;xsd:element name=&quot;Pet&quot;&gt;
        &lt;xsd:complexType&gt;
          &lt;xsd:sequence&gt;
            &lt;xsd:element name=&quot;id&quot; type=&quot;xsd:decimal&quot; /&gt;
            &lt;xsd:element name=&quot;Category&quot;&gt;
              &lt;xsd:complexType&gt;
                &lt;xsd:sequence&gt;
                  &lt;xsd:element name=&quot;id&quot; type=&quot;xsd:decimal&quot; /&gt;
                  &lt;xsd:element name=&quot;name&quot; type=&quot;xsd:string&quot; /&gt;
                &lt;/xsd:sequence&gt;
              &lt;/xsd:complexType&gt;
            &lt;/xsd:element&gt;
            &lt;xsd:element name=&quot;name&quot; type=&quot;xsd:string&quot; /&gt;
            &lt;xsd:element name=&quot;photoUrl&quot;&gt;
              &lt;xsd:complexType&gt;
                &lt;xsd:sequence&gt;
                  &lt;xsd:element name=&quot;photoUrl&quot; type=&quot;xsd:string&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot; /&gt;
                &lt;/xsd:sequence&gt;
              &lt;/xsd:complexType&gt;
            &lt;/xsd:element&gt;
            &lt;xsd:element name=&quot;tag&quot;&gt;
              &lt;xsd:complexType&gt;
                &lt;xsd:sequence&gt;
                  &lt;xsd:element name=&quot;Tag&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
                    &lt;xsd:complexType&gt;
                      &lt;xsd:sequence&gt;
                        &lt;xsd:element name=&quot;id&quot; type=&quot;xsd:decimal&quot; /&gt;
                        &lt;xsd:element name=&quot;name&quot; type=&quot;xsd:string&quot; /&gt;
                      &lt;/xsd:sequence&gt;
                    &lt;/xsd:complexType&gt;
                  &lt;/xsd:element&gt;
                &lt;/xsd:sequence&gt;
              &lt;/xsd:complexType&gt;
            &lt;/xsd:element&gt;
            &lt;xsd:element name=&quot;status&quot; type=&quot;xsd:string&quot; /&gt;
          &lt;/xsd:sequence&gt;
        &lt;/xsd:complexType&gt;
      &lt;/xsd:element&gt;
    &lt;/xsd:schema&gt;
  &lt;/d:AdditionalSchemas&gt;
&lt;/d:SchemaSet&gt;
</pre>
</details>

<p>

I would expect the resulting XML to look like:

<details>
<summary>expected.xml</summary>
<pre>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;p:request xmlns:p=&quot;http://syndesis.io/v1/swagger-connector-template/request&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://syndesis.io/v1/swagger-connector-template/request request.xsd &quot;&gt;
  &lt;p:body&gt;
    &lt;Pet&gt;
      &lt;name&gt;Jackson&lt;/name&gt;
    &lt;/Pet&gt;
  &lt;/p:body&gt;
&lt;/p:request&gt;
</pre>
</details>

<p>

Instead I receive this:

<details>
<summary>received.xml</summary>
<pre>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;request xmlns:tns=&quot;http://syndesis.io/v1/swagger-connector-template/request&quot;&gt;
  &lt;body&gt;
    &lt;Pet&gt;
      &lt;name&gt;Jackson&lt;/name&gt;
    &lt;/Pet&gt;
  &lt;/body&gt;
&lt;/request&gt;
</pre>
</details>

So this places all elements in the default namespace and just declares the namespace `http://syndesis.io/v1/swagger-connector-template/request` with prefix `tns`.

I would expect that the `request` and `body` elements are using the `tns` prefix, and that the `Pet` and its children are in default namespace.

**Comment by igarashitm** [comment]
UI is still doing wrong with namespace handling. I'll continue on that.

**Comment by igarashitm** [comment]
I'll submit a PR for syndesis once circleci publishes the npm package for this commit.
