### ISSUE TITLE
Set the Content-Type message header

### ISSUE THREAD

**Issue by zregvart** [atlasmap/atlasmap#291]
I think it would be good to set the `Exchange.CONTENT_TYPE` (`Content-Type`) on the message headers so that any processor after AtlasComponent doesn't have to guess the format of the message body.
Not sure how this would affect the multiple output use-case, perhaps another exchange property keyed by document id with content type would be one solution?

**Comment by igarashitm** [comment]
Implemented for a single target document - let's just wait until we see a usecase for multiple target doc.
