### ISSUE TITLE
TS2688: Cannot find type definition file for '@emotion/core'

### ISSUE THREAD

**Issue by jeroenvlek** [atlasmap/atlasmap#2922]
I'm trying to build up an Atlasmap UI in a React + single-spa + npm based micro-frontend. To start, I just loosely copied the _atlasmap-standalone_ setup and have a _root.component.tsx_ that does this:

```
export default function Root(props) {
  return (
    <AtlasmapProvider
      baseJavaInspectionServiceUrl={"/v2/atlas/java/"}
      baseXMLInspectionServiceUrl={"/v2/atlas/xml/"}
      baseJSONInspectionServiceUrl={"/v2/atlas/json/"}
      baseCSVInspectionServiceUrl={"/v2/atlas/csv/"}
      baseMappingServiceUrl={"/v2/atlas/"}
    >
      <Atlasmap />
    </AtlasmapProvider>
  );
}
```
Building this with _webpack 4_ yields several errors, but I keep this issue constrained to just this one:

_ERROR in /home/jvlek/dev/heimdall/mapping-definition-manager/data-mapping-mf/node_modules/@atlasmap/atlasmap/dist/Atlasmap/utils/useToggle.d.ts_
_ERROR in /home/jvlek/dev/heimdall/mapping-definition-manager/data-mapping-mf/node_modules/@atlasmap/atlasmap/dist/Atlasmap/utils/useToggle.d.ts(3,23):
TS2688: Cannot find type definition file for '@emotion/core'._

_ERROR in /home/jvlek/dev/heimdall/mapping-definition-manager/data-mapping-mf/node_modules/@atlasmap/atlasmap/dist/UI/Canvas/Movable.d.ts_
_ERROR in /home/jvlek/dev/heimdall/mapping-definition-manager/data-mapping-mf/node_modules/@atlasmap/atlasmap/dist/UI/Canvas/Movable.d.ts(2,23):
TS2688: Cannot find type definition file for '@emotion/core'._

_ERROR in /home/jvlek/dev/heimdall/mapping-definition-manager/data-mapping-mf/node_modules/@atlasmap/atlasmap/dist/UI/Canvas/NodeRef.d.ts_
_ERROR in /home/jvlek/dev/heimdall/mapping-definition-manager/data-mapping-mf/node_modules/@atlasmap/atlasmap/dist/UI/Canvas/NodeRef.d.ts(3,23):
TS2688: Cannot find type definition file for '@emotion/core'._

If you look in these files you see indeed:

`/// <reference types="@emotion/core" />`

I have installed:

```
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.4.0",
    "@emotion/types": "^0.7.0",
```

But to no avail. The weird thing is that the _package.json_ files in _atlasmap, atlasmap-core_ and _atlasmap-standalone_ also not state _@emotion/core_ as a dependency?

I've also tried adding the _@emotion/types_ library explicitly in my _tsconfig.json_:

```
{
  "extends": "ts-config-single-spa",
  "compilerOptions": {
    "jsx": "react",
    "sourceMap": true,
    "noEmit": false,
    "esModuleInterop": true
  },
  "include": ["src/**/*", "node_modules/@types", "node_modules/@emotion/types/"],
  "exclude": ["src/**/*.test*"]
}

```

And for completeness sake also the _webpack.config.js_:

```
const { merge } = require("webpack-merge");
const singleSpaDefaults = require("webpack-config-single-spa-react-ts");

module.exports = (webpackConfigEnv, argv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "SphereMall",
    projectName: "data-mapping-mf",
    webpackConfigEnv,
    argv,
  });

  delete defaultConfig.devServer.disableHostCheck;
  // for debugging uncomment the line below
  //  console.log(JSON.stringify(defaultConfig));

  return merge(defaultConfig, {
    module: {
      rules: [
        {
          test: /\.(png|svg|jpg)$/,
          use: ["file-loader"],
        },
        {
          test: /\.tsx?$/,
          loader: "ts-loader",
        },
      ],
    },
    resolve: {
      extensions: [".tsx", ".ts", ".js"],
    },
  });
};
```

I've looked into the docs, but could not find it, however, if there is a guide on how to use (elements of) the Atlasmap UI into a custom frontend, that would be really appreciated. If there isn't and I figure this out, then I'm happy to write one :)

**Disclaimer**: I'm not an experienced Typescript developer, so I might be doing something obviously wrong, but so far I haven't been able to google my way out of it.

**Comment by igarashitm** [comment]
It doesn't look like an AtlasMap issue. Please use https://gitter.im/atlasmap/community or https://groups.google.com/d/forum/atlasmap for general question/discussion.

I would start from looking at what is different from @atlasmap/standalone. And check if there's any version conflict with `yarn list` and `yarn why` when I hit this kind of weird transitive dependency error. The react-scripts has super strict dependency rule and we try to align with it.

**Comment by jeroenvlek** [comment]
For future readers: I solved it by installing all the dependencies for standalone:

`[jvlek@rick-sanchez data-mapping-mf]$ npm install --save-exact @patternfly/react-core@^3.77.2 @patternfly/react-icons@^3.10.15    @patternfly/react-styles@^3.5.7  @patternfly/react-table@^2.28.29    @patternfly/react-topology@^2.8.65    @types/d3-scale@^2.1.1    @types/d3-shape@^1.3.2    @types/jest@25.2.3    @types/node@13.7.1    @types/react@16.9.34    @types/react-dom@16.9.6    d3-scale@^3.2.0    d3-shape@^1.3.5    http-proxy-middleware@^0.20.0    ky@^0.17.0    lodash.clamp@^4.0.3    react@^16.13.1    react-dnd@^10.0.2    react-dnd-html5-backend@^10.0.2    react-dnd-touch-backend@^10.0.2    react-dom@^16.13.1    react-file-picker@0.0.6    react-scripts@3.4.1    react-use-gesture@^7.0.4    rxjs@^6.2.2`
