### ISSUE TITLE
Remove MappingType.Collection and Repeating Mapping component from UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#294]
Derived UXD issue from #274

So at least currently the "Repeating Mapping" component doesn't make any sense. One possible implication is to support indexed source item in the collection (#30), which might need this component as it's going to contain multiple mapping entries.

**Comment by igarashitm** [comment]
Even so, current look&feel is confusing if you want to map whole collection. We might need a checkbox or something to switch whole mapping vs. indexed entry mapping.

**Comment by igarashitm** [comment]
As of today noone could justify bundling mappings just because one of the field is a part of same collection. If we bundle by collection, why don't we bundle by complex field? For me it's really inconsistent.

**Comment by deernano** [comment]
@igarashitm 
Based on the dev review, 
- We do not need a different UI for repeating mapping
- Remove repeating mode and called 'Mapping details' for all mode based on automatic transition.
Once automatic transition is able to release, we recommend to use this new UI at the same time.
- We do not need 'grouping function particularly for repeating mode. It is better to let the user group mapping if the fields belong to the same parent if we remain grouping function.
Here is the wireframe link: https://redhat.invisionapp.com/share/7RNJ944PFH9#/screens/314527595
- From the competitive research, we haven't found the other products having 'grouping mapping' function.

**Comment by igarashitm** [comment]
Sounds good - so let's start from removing "grouping mapping" and wait for the time we actually find a obvious reason we want to implement "grouping mapping". My bet is we don't need it.

**Comment by igarashitm** [comment]
Note that we no longer need to wrap with `MappingType.Collection` mapping. Runtime is already doing nothing for it, just peel off and throw away.

Also it seems `MappingModel` and `FieldMappingPair` is going to be 1-to-1 once we remove collection mapping model. Remove following unneccesary code.
https://github.com/atlasmap/atlasmap/blob/32156f8644c293877270e90f2b5413755823d3b4/ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts#L494-L495
https://github.com/atlasmap/atlasmap/blob/32156f8644c293877270e90f2b5413755823d3b4/ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts#L346-L353

**Comment by igarashitm** [comment]
Clearing assignee - now this is ready to be implemented in UI. Thanks for the UXD assessment @deernano !
