### ISSUE TITLE
Mapping preview fails

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2977]
Mapping preview is generating this error:
<pre>      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [if ( ${DOC.Properties.704068:/JSONSchemaSource/prop-city} == ${DOC.Constants.801708:/Boston}, ${JSONInstanceSource:/order/address/city}, ${JSONInstanceSource:/order/address/state})]: null&quot;,
        &quot;docId&quot; : &quot;if ( ${DOC.Properties.704068:/JSONSchemaSource/prop-city} == ${DOC.Constants.801708:/Boston}, ${JSONInstanceSource:/order/address/city}, ${JSONInstanceSource:/order/address/state})&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
</pre>

ref:
![err1](https://user-images.githubusercontent.com/2981421/122560639-d402b980-d00e-11eb-8855-c0e177480e7c.png)

mapping:
<pre>    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;if ( ${DOC.Properties.704068:/JSONSchemaSource/prop-city} == ${DOC.Constants.801708:/Boston}, ${JSONInstanceSource:/order/address/city}, ${JSONInstanceSource:/order/address/state})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.PropertyField&quot;,
          &quot;value&quot; : &quot;&quot;,
          &quot;docId&quot; : &quot;DOC.Properties.704068&quot;,
          &quot;path&quot; : &quot;/prop-city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;prop-city&quot;,
          &quot;scope&quot; : &quot;JSONSchemaSource&quot;
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.ConstantField&quot;,
          &quot;value&quot; : &quot;Boston&quot;,
          &quot;docId&quot; : &quot;DOC.Constants.801708&quot;,
          &quot;path&quot; : &quot;/Boston&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;&quot;,
          &quot;docId&quot; : &quot;JSONInstanceSource&quot;,
          &quot;path&quot; : &quot;/order/address/city&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;city&quot;
        }, {
          &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
          &quot;value&quot; : &quot;&quot;,
          &quot;docId&quot; : &quot;JSONInstanceSource&quot;,
          &quot;path&quot; : &quot;/order/address/state&quot;,
          &quot;fieldType&quot; : &quot;STRING&quot;,
          &quot;name&quot; : &quot;state&quot;
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.xml.v2.XmlField&quot;,
        &quot;actions&quot; : [ {
          &quot;string&quot; : &quot;RESULT&quot;,
          &quot;@type&quot; : &quot;Append&quot;
        }, {
          &quot;string&quot; : &quot;&quot;,
          &quot;@type&quot; : &quot;Append&quot;
        } ],
        &quot;docId&quot; : &quot;XMLInstanceSource&quot;,
        &quot;path&quot; : &quot;/ns:XmlOE/ns:Address/ns:addressLine1&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;addressLine1&quot;,
        &quot;userCreated&quot; : false,
        &quot;attribute&quot; : false
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
</pre>

To reproduce:
1. Import `.../ui/test-resources/adm/mockdoc.adm`
2. select the mapping that uses `prop-city` - I changed the type to be `string`
3. enter preview mode - error will appear

There's an odd `null` trailing the expression.

**Comment by igarashitm** [comment]
So it fails because the path for the property field doesn't match, the field doesn't have scope while expression does have scope in the path.
