### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError appears on startup

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#304]
#### Error detail:
ng:///DataMapperModule/DataMapperAppComponent.ngfactory.js:154 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'.
    at viewDebugError (webpack-internal:///../../../core/esm5/core.js:9710)
    at expressionChangedAfterItHasBeenCheckedError (webpack-internal:///../../../core/esm5/core.js:9688)
    at checkBindingNoChanges (webpack-internal:///../../../core/esm5/core.js:9857)
    at checkNoChangesNodeInline (webpack-internal:///../../../core/esm5/core.js:13870)
    at checkNoChangesNode (webpack-internal:///../../../core/esm5/core.js:13842)
    at debugCheckNoChangesNode (webpack-internal:///../../../core/esm5/core.js:14650)
    at debugCheckDirectivesFn (webpack-internal:///../../../core/esm5/core.js:14552)
    at Object.eval [as updateDirectives] (ng:///DataMapperModule/DataMapperAppComponent.ngfactory.js:176)
    at Object.debugUpdateDirectives [as updateDirectives] (webpack-internal:///../../../core/esm5/core.js:14534)
    at checkNoChangesView (webpack-internal:///../../../core/esm5/core.js:13682)

**Comment by igarashitm** [comment]
I got this
> Expression has changed after it was checked. Previous value: 'lineMachine: undefined'. Current value: 'lineMachine: [object Object]'.

This looks very weird to me, as it's saying the @ViewChild `lineMachine` in the `DataMapperAppComponent` is populated after the check...
But this might go away once line machine handling turns into event handling model. Let's see...

**Comment by pleacu** [comment]
Worked with Tomo on this.  The issue is this line:

 `<div class="row" style="height:calc(100% - 32px); position:relative; padding-top:10px;" *ngIf="hasSourceDoc && hasTargetDoc">`

Removing the `*ngIf="hasSourceDoc && hasTargetDoc"` corrects this issue.  The bigger issue is that this *ngIf is needed so that users starting the DM with no files aren't shown empty 'Sources' and 'Targets' in the display.  There is dependency from the `DataMapperAppComponent` to the `LineMachine` that needs to be teased apart.  Also - this code as is will *not* show the error if no source/target file is specified (remove the mock file to test).

**Comment by igarashitm** [comment]
Hi @deeleman, do you have any idea for this? I have no idea why `@ViewChild lineMachine` is not populated at the first check...

**Comment by deeleman** [comment]
Either `hasSourceDoc`or `hasTargetDoc` are changed as the result of a new value injected through any `@Input` property during the `OnLoad` step.

In other words... This block is the culprit:

```typescript
this.hasSourceDoc = this.getConfig().sourceDocs && this.getConfig().sourceDocs.length > 0;
this.hasTargetDoc = this.getConfig().targetDocs && this.getConfig().targetDocs.length > 0;
```

Workaround: Make these fields observable:

```
// Please note we'll want to use now Finnish notation here
hasSourceDoc$: Observable<boolean>;
hasTargetDoc$: Observable<boolean>;

ngOnInit() {
  this.hasSourceDoc$ = Observable.from(this.getConfig().sourceDocs).map(sourceDocs => sourceDocs.length > 0);
  this.hasTargetDoc$ = Observable.from(this.getConfig().targetDocs).map(targetDocs => targetDocs.length > 0);
}
```

Then apply the proper `async` pipe and you're done. Ideally you should combine these two observables into one:

```
this.hasDocs$ = Observable.forkJoin(this.hasSourceDoc$, this.hasTargetDoc$);
``` 

and then bind that value to the template conditional like `*ngIf="hasDocs$ | async"`.

I've coded all this without testing it but that should work.

**Comment by pleacu** [comment]
Hey @deeleman - so I tried this:
```
  hasSourceDoc$: Observable<boolean>;
  hasTargetDoc$: Observable<boolean>;
  hasDocs$: Observable<[boolean, boolean]>;

  loadingStatus = 'Loading.';

  constructor(public detector: ChangeDetectorRef) { }

  getConfig(): ConfigModel {
    return ConfigModel.getConfig();
  }

  ngOnInit(): void {
    this.hasSourceDoc$ = Observable.from(this.getConfig().sourceDocs).map(sourceDocs => this.getConfig().sourceDocs.length > 0);
    this.hasTargetDoc$ = Observable.from(this.getConfig().targetDocs).map(targetDocs => this.getConfig().targetDocs.length > 0);
    this.hasDocs$ = Observable.forkJoin(this.hasSourceDoc$, this.hasTargetDoc$);

    this.getConfig().initializationService.systemInitialized$.subscribe(() => {
      this.updateFromConfig();
    });

    this.getConfig().initializationService.initializationStatusChanged$.subscribe(() => {
      this.loadingStatus = this.getConfig().initCfg.loadingStatus;
      setTimeout(() => {
        this.detector.detectChanges();
      }, 10);
    });
  }
```
and then in the template:
```
 <div class="row" style="height:calc(100% - 32px); position:relative; padding-top:10px;" *ngIf="hasDocs$ | async">
```
resulting in the same error:
```
DataMapperAppComponent.html:12 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'lineMachine: undefined'. Current value: 'lineMachine: [object Object]'.
    at viewDebugError (core.js:9775)
    at expressionChangedAfterItHasBeenCheckedError (core.js:9753)
    at checkBindingNoChanges (core.js:9920)
    at checkNoChangesNodeInline (core.js:13970)
    at checkNoChangesNode (core.js:13942)
    at debugCheckNoChangesNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14673)
    at Object.eval [as updateDirectives] (DataMapperAppComponent.html:12)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14655)
    at checkNoChangesView (core.js:13780)```
```
Am i referencing the hasDocs$ correctly in the html?
