### ISSUE TITLE
Cannot import Soap-envelope schema into UI

### ISSUE THREAD

**Issue by ronMilne** [atlasmap/atlasmap#3048]
UI Version: 2.2.2
Runtime Version: 2.2.2

I've downloaded the schema from

http://www.w3.org/2003/05/soap-envelope

After fixing the xs:import schemalocation to https://www.w3.org/2004/10/xml.xsd

The UI states it's be imported but no elements are available for mapping?

Regards,
Ron

**Comment by igarashitm** [comment]
Please use https://gitter.im/atlasmap/community or https://groups.google.com/d/forum/atlasmap for question/discussion.

Resolving external schema is not yet supported in AtlasMap. You'd need to pack dependencies up into `SchemaSet` single file. Here is an example
https://github.com/atlasmap/atlasmap/blob/master/lib/modules/xml/core/src/test/resources/inspect/multiple-namespaces-schemaset.xml
