### ISSUE TITLE
UI Does not display second <xs:element>

### ISSUE THREAD

**Issue by ronMilne** [atlasmap/atlasmap#3054]
Given the following schema definition the UI doesn't display **businessDocumentHeader**

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="uri:types.asic.gov.au" elementFormDefault="qualified" attributeFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:types="uri:types.asic.gov.au">

  <xs:complexType name="businessDocumentRequestHeaderType">
    <xs:sequence>
      <xs:element name="ServiceName" type="xs:string"   />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="businessDocumentHeaderType">
    <xs:sequence>
      <xs:element name="ServiceName" type="xs:string"   />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="businessDocumentRequestHeader" type="types:businessDocumentRequestHeaderType"/>
  <xs:element name="businessDocumentHeader" type="types:businessDocumentHeaderType"/>

</xs:schema>

**Comment by igarashitm** [comment]
Duplicate of #1407
