### ISSUE TITLE
Support double quote to quote string literal in expression

### ISSUE THREAD

**Issue by ronMilne** [atlasmap/atlasmap#3134]
Given the simple IF statement defined within the standalone UI.

![atlas-if-error](https://user-images.githubusercontent.com/24907744/126579093-d5544719-43bc-428e-bff9-3ba9997a0a38.png)

The runtime generates the following exception.

io.atlasmap.api.AtlasException: Errors: [**Expression processing error** [IF(${DOC.Properties.59756:/current/IdentifierType} == "ABN", ${DOC.Properties.59756:/current/Identifier}, null)]: IF(${DOC.Properties.59756:/current/IdentifierType} == "ABN", ${DOC.Properties.59756:/current/Identifier}, null): Document='null(ID:IF(${DOC.Properties.59756:/current/IdentifierType} == "ABN", ${DOC.Properties.59756:/current/Identifier}, null))', path='null'],

At the time this exception is raised the following values are within the camel exchange.
INFO  Exchange[Id: 66FD187A9BCF2B4-0000000000000000, ExchangePattern: InOnly, Properties: {CamelTimerCounter=1, CamelTimerFiredTime=Thu Jul 22 11:16:58 AEST 2021, CamelTimerName=myTimer, CamelTimerPeriod=1000}, Headers: {CamelMessageTimestamp=1626916618314, firedTime=Thu Jul 22 11:16:58 AEST 2021, **Identifier**=123456789, **IdentifierType**=ABN}, BodyType: null, Body: [Body is null]]

To Reproduce 
Compile Model and install to local m2 repository.
Compile & run camel mapping

[model.zip](https://github.com/atlasmap/atlasmap/files/6859521/model.zip)
[camelampping.zip](https://github.com/atlasmap/atlasmap/files/6859528/camelampping.zip)

The .adm file is within the camelmapping project in src\data\Test-Condition-mapping.adm

Expected behaviour the simple expression should evaluate correctly

Environment 
Camel 3.11.0
Java 8

Regards,
Ron Milne.

**Comment by ronMilne** [comment]
You can replicate it within the standalone UI without any code.
![atlas-if-error UI](https://user-images.githubusercontent.com/24907744/126587596-cd747b97-4e44-4875-ad37-4b60775baf83.png)

**Comment by igarashitm** [comment]
It turned out the double quote is not allowed ATM. It works if you use single quote. Changing this to a RFE to support double quote to quote string literal.
