### ISSUE TITLE
[BUG] expression field search doesn't establish mapped field as expected

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3135]
**Describe the bug**
It seems to be a regression after refactoring
![atlasmap-fail](https://user-images.githubusercontent.com/265462/126645706-c5a3684d-84a8-41d8-b8da-e0b68325c148.gif)

It works fine if mapping is established through dnd and convert it to conditional mapping
![atlasmap](https://user-images.githubusercontent.com/265462/126646335-a081ba2f-c951-48fb-9f79-b8515b10fc63.gif)

**Comment by pleacu** [comment]
Working on this now

**Comment by pleacu** [comment]
Next PR addresses this:

![sc0](https://user-images.githubusercontent.com/2981421/126776477-f172dbd3-f7ce-46fc-bdd8-02429e7946ca.png)

![sc1](https://user-images.githubusercontent.com/2981421/126776808-b7e612d0-97d8-4837-8afb-19dec67ef955.png)
