### ISSUE TITLE
[BUG] Wrong path for Java collection field

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3141]
**Describe the bug**
Java collection field gets wrong field path in the mapping. It doesn't reproduce with JSON.
 
**To Reproduce**
1. Import java test-model jar (https://github.com/atlasmap/atlasmap/tree/master/lib/modules/java/test-model)
2. Add `io.atlasmap.java.test.TargetTestClass` as a Document
2. Map `contactList<>/firstName`
3. See mapping definition sent to backend, field path is `/contact/firstName` while it's supposed to be `contactList<>/firstName`
```json
{
  "AtlasMapping" : {
    "jsonType" : "io.atlasmap.v2.AtlasMapping",
    "dataSource" : [ {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.java.test.TargetTestClass",
      "name" : "TargetTestClass",
      "description" : "Java document class io.atlasmap.java.test.TargetTestClass",
      "uri" : "atlas:java:io.atlasmap.java.test.TargetTestClass?className=io.atlasmap.java.test.TargetTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.java.test.TargetTestClass",
      "name" : "TargetTestClass",
      "description" : "Java document class io.atlasmap.java.test.TargetTestClass",
      "uri" : "atlas:java:io.atlasmap.java.test.TargetTestClass?className=io.atlasmap.java.test.TargetTestClass",
      "dataSourceType" : "TARGET"
    } ],
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputFieldGroup" : {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ ],
          "field" : [ {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.java.test.TargetTestClass",
            "path" : "/contact/firstName",
            "fieldType" : "STRING",
            "name" : "firstName"
          } ]
        },
        "inputField" : [ ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.java.test.TargetTestClass",
          "path" : "/contact/firstName",
          "fieldType" : "STRING",
          "name" : "firstName"
        } ],
        "id" : "mapping.192219"
      } ]
    },
    "lookupTables" : {
      "lookupTable" : [ ]
    },
    "constants" : {
      "constant" : [ ]
    },
    "properties" : {
      "property" : [ ]
    },
    "name" : "UI.0"
  }
}
```
UI still shows that the mapped field is under `contactList`
![Screenshot from 2021-07-23 07-33-24](https://user-images.githubusercontent.com/265462/126777193-63d04904-630f-49a1-bef9-be8d8b2f292d.png)

**Comment by pleacu** [comment]
I can take a look at this one.

**Comment by pleacu** [comment]
> @pleacu #3141 seems to be rather Java side issue, Java inspection doesn't have collection suffix on the field path as
> expected. This PR will add TargetTestClass to be inspected and generate ui/test-resources/inspected/atlasmap-inspection-
>  io.atlasmap.java.test.TargetTestClass.json

Hey @igarashitm - I've rebased with your latest Java inspection fix.  Not sure how this affects this issue.

**Comment by igarashitm** [comment]
It only added a test-resource, you can see `contactList` in the inspection result doesn't have a collection suffix `<>` in the path.
