### ISSUE TITLE
[BUG] Windows checked workflow PR run fails to build

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#3144]
This error appears in the maven build of windows-latest / Java8 and windows-latest / Java11

`[INFO] @atlasmap/atlasmap: (typescript) Error: D:/a/atlasmap/atlasmap/ui/packages/atlasmap/src/impl/utils/ui.ts(344,33): `
`semantic error TS2339: Property 'addFieldToExpression' does not exist on type 'MappingExpressionService'. [INFO] @atlasmap/atlasmap: Error: D:/a/atlasmap/atlasmap/ui/packages/atlasmap/src/impl/utils/ui.ts(344,33): semantic error TS2339: Property 'addFieldToExpression' does not exist on type 'MappingExpressionService'.

The issue appears to be related to the change of name of the mapping-expression service `addField` to `addFieldToExpression`
ref `ui.ts`.  The Linux and MacOS build are okay.

**Comment by igarashitm** [comment]
Windows build failure went away after some dependabot PRs, which suggests something was wrong with `node_modules` cache. In theory it shouldn't though because atlasmap sub packages should be built everytime into each `dist/` dir and never rely on `node_modules` cache. Weird.
