### ISSUE TITLE
[TASK] Find a way to show that a JAR file has been imported

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#3171]
Currently, to use a Java class as a source or target in AtlasMap, the user must first import a JAR using the AtlasMap menu, then subsequently use buttons on the Sources and/or Targets columns to select the Java classes to use as Source(s) and/or Target(s), respectively. However, after performing the initial import from the AtlasMap menu, there is no visual indication that this action has been performed. Thus the user, if interrupted for some reason, has no indication to remind them that Java classes are available for selection, nor which JAR file they would be selected from.

**Comment by pleacu** [comment]
Closing this as the `Load Java Document From Custom Class` dialog lists all downloaded classes/ jars.
![sc1](https://user-images.githubusercontent.com/2981421/158392758-595bb576-a08f-4e24-bcfa-cc92dbd60845.png)
