### ISSUE TITLE
Inherited Properties Duplicated Within UI

### ISSUE THREAD

**Issue by ronMilne** [atlasmap/atlasmap#3197]
The UI Editor duplicates properties from the base class (i.e. extends) In the screen shot below the properties are private the setter/getter public, but the properties are duplicated (UserIdentity, TransactionId, SessionId) are defined within the base
![duplicateUI](https://user-images.githubusercontent.com/24907744/129275867-ed85bf3c-bb27-43f6-bbd8-b9c18ca9237e.png)

the attached zip includes the loaded type
[searchNniName-model.zip](https://github.com/atlasmap/atlasmap/files/6978794/searchNniName-model.zip)

AtlasMap 2.2.1

**Comment by igarashitm** [comment]
Can you upload ADM file?
