### ISSUE TITLE
[TASK] another slight patternfly dependency alignment

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap#3252]
With the dependency adjustments in Syndesis underway we found there needs to be some additional alignments on the atlasmap side, namely [these patternfly dependencies](https://github.com/syndesisio/syndesis/pull/9708/files#diff-4bacc066a2f9fc8622c8b8c5e5a728bfd4a67568e9e99e21190bc9698b6dbb6dR56-R60) need to be aligned and we'll need to make a release to get Syndesis updated.

Probably be good to check with @seanforyou23 if there's any questions.

**Comment by igarashitm** [comment]
@gashcrumb do we need to align with, e.g. the older `@patternfly/react-core 4.135.0` as opposed to the latest `@patternfly/react-core: 4.152.4` we already have in upstream master? in that case we'd have to cut a branch and downgrade those.

**Comment by gashcrumb** [comment]
I'd rather avoid the downgrade probably.

**Comment by igarashitm** [comment]
It just reminded me that we now have patternfly dependencies in `peerDependencies`, so the host app i.e. Syndesis can override those version.
https://github.com/atlasmap/atlasmap/commit/695bc8af1e15a8e6e4f0930385253aa3e7c7e8c4
So we might not really need to explicitly align here. Assuming they are compatible though... better to be closer in practice.

**Comment by gashcrumb** [comment]
Probably it'd be good to align it on a bugfix branch so it's close to what'll be used in Syndesis, that'll likely introduce the least amount of surprises when our release gets integrated there.

**Comment by igarashitm** [comment]
done
