### ISSUE TITLE
[BUG] XML schema import not working with xsd:import/xsd:include tag

### ISSUE THREAD

**Issue by bitsInnovate00** [atlasmap/atlasmap#3257]
Not able to load XML Schema  having import/include tag to atlasmap. See one sample 
[samplexsd.zip](https://github.com/atlasmap/atlasmap/files/7111439/samplexsd.zip)
Due to this , we need to manually flatten the schema which is cumbersome

**Comment by igarashitm** [comment]
You need to wrap it with `SchemaSet`
https://github.com/atlasmap/atlasmap/blob/master/lib/modules/xml/core/src/test/resources/inspect/multiple-no-namespace-root-schema.xml
