### ISSUE TITLE
[BUG] Minor data integrity issue when creating mappings and exporting the adm file

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap#3300]
Following this sequence of steps I can fairly consistently get an error when trying to export an adm file after creating some mappings

1) Import the jar flle: [rest-1.0.0.zip](https://github.com/atlasmap/atlasmap/files/7217080/rest-1.0.0.zip)
2) Add a source document, I picked org.example.s2.S2Request
3) Add a target document, I picked io.swagger.client.model.DemoData
4) Click and drag from param1 in source to data1 in target (don't click anywhere else)
5) Click and drag from param2 in source to data2 in target (again don't click anywhere else)
6) Click on Atlasmap and export, at this point I can get this error:

![image](https://user-images.githubusercontent.com/351660/134496948-e43ead90-b585-4ceb-b565-198e1c4d6153.png)

Note that interacting with the UI such as closing the mapping details or I suspect even clicking in the window between steps 5 and 6 will likely mask the problem.

**Comment by igarashitm** [comment]
@gashcrumb there seems to be more condition to reproduce, it doesn't for me with upstream master. Did you get it with some specific version?
![atlasmap](https://user-images.githubusercontent.com/265462/134673200-e9dd330f-c298-4b42-953f-db16c111e56f.gif)

**Comment by gashcrumb** [comment]
Hmm, yeah this was on a build of master as of a couple days ago.  For me it also didn't happen every time, I think I went through this sequence to iron out the steps probably around 15 times and it happened I'd say 2 out of 3 times for me.  Reeks of a timing issue.

There's no difference if you drag from the row text vs the "create new mapping" icon, is there?  That's the only thing that comes to mind looking at your gif.

**Comment by igarashitm** [comment]
Hmm... trying many times and still doesn't reproduce for me even once, also tried using create new mapping button with no luck. Could it be Mac OS + Chrome specific? I do know the GH action build intermittently fails on Mac OS, it seems the e2e test sometimes hangs there.
@pleacu do you have a chance to try reproducing?

**Comment by pleacu** [comment]
Tried it and I'm okay as well.  Any output from the server?

**Comment by gashcrumb** [comment]
Yeah for me it's fedora 34 and chrome.  I'll reconfirm first off that I can reproduce it and post the log if so.  Thanks for checking!
