### ISSUE TITLE
[BUG] Example code build failure, mvn compile fails

### ISSUE THREAD

**Issue by GerryOnGithub** [atlasmap/atlasmap#3354]
**Describe the bug**
This test fails: 
https://github.com/atlasmap/atlasmap/tree/master/examples/camel-example-atlasmap

**Relevant errors**
[WARNING] The POM for io.atlasmap:camel-atlasmap:jar:2.3.0-SNAPSHOT is missing, no dependency information available

[ERROR] Failed to execute goal on project camel-example-atlasmap: Could not resolve dependencies for project io.atlasmap.examples:camel-example-atlasmap:jar:2.3.0-SNAPSHOT: Could not find artifact io.atlasmap:camel-atlasmap:jar:2.3.0-SNAPSHOT in maven-restlet (https://maven.restlet.com) -> [Help 1]

**To Reproduce**
run mvn compile in the appropriate folder, start with a empty maven repo.

**Expected behavior**
Should compile.

**Screenshots**
![atlas-build-error](https://user-images.githubusercontent.com/23443806/135877192-3f99419c-340d-43bd-afa4-54b8c304c327.png)

**Environment (please complete the following information):**
 - OS: Windows 
 - Browser: n/a
 - Version: see link above

**Additional context**
I think you get the idea.

**Comment by igarashitm** [comment]
Build camel-atlasmap component beforehand, or use released version.
