### ISSUE TITLE
[TASK] Put CSV body and parameters into CsvInspectionRequest

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3392]
Currently it uses query parameters for parameters and body for CSV payload, unlike other formats. Align CSV to put everything into CsvInspectionRequest JSON. Don't forget to change the contentType at backend side from `text/csv` to JSON.

**Comment by igarashitm** [comment]
It's OK to separate the parameters from CSV payload, but need to put under `CsvInspectionRequest` as opposed to the individual URL parameters currently we do. So send a single JSON body just like this without any URL parameters:
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/json/model/src/main/java/io/atlasmap/json/v2/JsonInspectionRequest.java#L34-L46
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/json/service/src/main/java/io/atlasmap/json/service/JsonService.java#L112

while for CSV the parameters are URL parameters not wrapped in a JSON request object - sending multiple parameters and a CSV body together in a POST request
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/csv/service/src/main/java/io/atlasmap/csv/service/CsvService.java#L117

**Comment by rkorytkowski** [comment]
The thing I'm talking about is https://github.com/atlasmap/atlasmap/blob/main/lib/modules/json/service/src/main/java/io/atlasmap/json/service/JsonService.java#L113 which makes us parse the whole payload to extract parameters and body with json parser i.e. read the whole payload. On the other hand when you pass a CSV in body and parameters as URL params then I simply read URL params and just the first line of CSV from the body and I'm done.

Are you saying to move the logic to javascript and get just the first line in js and send it for inspection?

**Comment by igarashitm** [comment]
Ah OK maybe not feasible to stream JSON payload. And yes, take the header at UI side and discard the rest is the option. But... no we don't want to think about the line breaks and etc at UI side...

This sounds like a wider spread problem, actually it's same for JSON/XML instance inspection. And even if it managed to perform inspection, the huge instance file will be stored into the `DataSourceMetadata` contained in .adm file so it makes .adm file bigger.

That said, I would say, don't upload a real huge file for the inspection, that's just an example to inspect...

**Comment by rkorytkowski** [comment]
Yeah, in case of CSV it's simple for the end user to crop the file. In case of JSON/XML instance it might not be that easy so I would actually move towards the approach I used for CSV, i.e. have the file in body and any parameters as URL parameters. That said we are not yet parsing JSON/XML instances/schemas as streams so we would not benefit until it is re-implemented.

**Comment by igarashitm** [comment]
Yeah ATM it's too far before doing it - at least runtime should support huge file with streaming, and then .adm file has to be restructured to store inspection result and discard inspection source so that the repeating element could be thrown away when it's stored in datasource metadata, etc.
Anyway, this issue is not worth doing with that direction, hopefully the parameters won't change much anymore as it changes REST interface everytime. Closing.
