### ISSUE TITLE
[BUG] UI got stuck when import a new schema.

### ISSUE THREAD

**Issue by likaihe** [atlasmap/atlasmap#3504]
**Describe the bug**
UI got stuck when import a new schema.

 
**Attach debug logs**
in consolo log:
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'docId')
 
**To Reproduce**
Steps to reproduce the behavior in AtlasMap Data Mapper UI standalone with version 2.3.2.:
1.in the target, import any json schema file.
2.select one of the filed and click create a new mapping
3.in the target, import another json schema file.
   Then the screen will hang there

**Expected behavior**
The screen should not hang there 

**Additional context**
the exception (like a null point exception) is thrown in [`mapping-util.ts`](https://github.com/atlasmap/atlasmap/blob/main/ui/packages/atlasmap-core/src/utils/common-util.ts) because of `mappingField` is missing when try to access a docId from it.

I am looking at [`MappedField` ](https://github.com/atlasmap/atlasmap/blob/main/ui/packages/atlasmap-core/src/models/mapping.model.ts). It says once `field` is populated and `mappingField` should not be used. Looks like there are logic in `mapping-util.ts` that when filed is populated and we still use mappingField

**Comment by pleacu** [comment]
<pre>
Uncaught (in promise) TypeError: Cannot read property 'docId' of undefined
    at Function.updateMappedFieldsFromDocuments (mapping-util.ts:85)
    at Function.updateMappingsFromDocuments (mapping-util.ts:44)
    at InitializationService.updateStatus (initialization.service.ts:368)
    at document.ts:219
    at <anonymous>
</pre>
