### ISSUE TITLE
Expression box in safari acts really weird[BUG] 

### ISSUE THREAD

**Issue by YevhenTarashchyk** [atlasmap/atlasmap#3509]
https://user-images.githubusercontent.com/29583265/143012808-1dae9c38-d5cd-4aa7-98c6-b1f7e61b50e8.mp4

I saw several topics about this and it seems they are fixed but for chrome not safari. Cursor acting weird sometimes it jumps at start sometimes at the end + cursor not respond to position where I am typing.

**Comment by igarashitm** [comment]
We don't test with Safari. Contributions are always welcome.
