### ISSUE TITLE
Would like mappings between enums to work inline with the page like other mappings

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#353]
_From @syndesis-bot on November 15, 2017 20:42_

|<img src="https://avatars0.githubusercontent.com/u/437085?v=4" valign="middle" width="22px"></img> @jpav | [2017-07-21](https://github.com/syndesisio/syndesis-ux/issues/19) | Data Mapper  |
|-|-|-|

Mappings between enums currently involves a pop-up where the user can "map" the translation from source enum values to target enum values, e.g., mapping individual state postal codes in a source enum to state names in a target enum. To avoid issues with pop-ups regarding modality and smaller windows that need to be scrolled more or resized, and more importantly to make the mapping experience more similar to other mappings, it would be nice to see the value mappings moved to the mapping detail area in some type of table-like form that uses dropdowns where the user can select these associations.

_Copied from original issue: syndesisio/syndesis#324_

**Comment by igarashitm** [comment]
_From @gashcrumb on March 15, 2018 18:1_

@igarashitm is this issue already in the atlasmap repo?  I can move it if not...

**Comment by deernano** [comment]
@igarashitm sure, the previous work for this task is just a demo to show how will enlarge mapping panel be used in real example. Since this one is not a big issue, we take this task an example to be dicussed.
