### ISSUE TITLE
[BUG] - Remove in-line comment support from cond expr editor

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#3579]
**Describe the bug**
In-line comments are not supported by the runtime server (block comments work fine).  Remove support for in-line comments from the  monaco conditional expression editor.

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/146005480-34f03461-b9c4-4eb9-8acb-b976cd6c67a0.png)

<pre>    &quot;audits&quot; : {
      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [if ((${DOC.Properties.578580:/current/prop-city} == ${DOC.Constants.10788:/Boston}),  // inline comment\n/*\n  Block comment!\n*/\n   ${JSONInstanceSource:/order/address/city},\n   lowercase(${JSONInstanceSource:/order/address/state})\n)\n]: if ((${DOC.Properties.578580:/current/prop-city} == ${DOC.Constants.10788:/Boston}),  // inline comment\n/*\n  Block comment!\n*/\n   ${JSONInstanceSource:/order/address/city},\n   lowercase(${JSONInstanceSource:/order/address/state})\n)\n&quot;,
        &quot;docId&quot; : &quot;if ((${DOC.Properties.578580:/current/prop-city} == ${DOC.Constants.10788:/Boston}),  // inline comment\n/*\n  Block comment!\n*/\n   ${JSONInstanceSource:/order/address/city},\n   lowercase(${JSONInstanceSource:/order/address/state})\n)\n&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
</pre>

**Comment by igarashitm** [comment]
IMO we could even remove comment support completely, because: 
* The conditional mapping expression is basically just a single chain of function call, i.e. it's logically one line
  * More complex usecase would need Java DSL
* We could have a comment support on the mapping - https://github.com/atlasmap/atlasmap/issues/2504

**Comment by pleacu** [comment]
Since the block comments appear to work fine I think it adds a bit of readability to users writing conditional expressions.  I also agree that we need #2504 - I'd like for now to just remove the in-line comment (I'd even suggest enhancing the RT to support it).
