### ISSUE TITLE
Support conditional mapping for each collection item

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3611]
**Describe the bug**
Conditional mapping is not working in case of collection to collection mapping in atlasmap 2.3.4. It is throwing an error at run time.

 
**To Reproduce**

1. Create a mapping spec by using collection to collection mapping.
2. Specify one conditional mapping 
3. Export .adm file.
4. Transform your request using this mapping spec.

**Expected behavior**

Conditional mapping should also work with collection to collection mapping.

**Screenshots**
Collection-Collection mapping:
![image](https://user-images.githubusercontent.com/39737814/146875156-e80c2f23-0dba-4653-b6b6-16ab7cd62176.png)

One-One mapping:
![image](https://user-images.githubusercontent.com/39737814/146876151-e4e05ab3-22bb-4ad3-b15a-cb5f5ad11af1.png)

TrueValue and FalseValue the constants which I have declared is of Integer type.

**Comment by pleacu** [comment]
Please include your adm and json files.

**Comment by Shrishti1234** [comment]
> Please include your adm and json files.

Hi @pleacu,
I have attached zip file which have mapping file, request json and output xml file.
[sample request file.zip](https://github.com/atlasmap/atlasmap/files/7837005/sample.request.file.zip)

**Comment by igarashitm** [comment]
This `conditional expression for each collection item` is not supported yet.
As `IF()` function itself doesn't consume a collection, we can assume that it is expected to evaluate for each collection item, but ,would need a deeper surgery.

**Comment by igarashitm** [comment]
Duplicates of #3357
