### ISSUE TITLE
Why dependency on com.sun.xsom:xsom:jar:20140925.0.0.redhat-1 ?

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap#366]
I wonder where there is a dependency on `com.sun.xsom:xsom:jar:20140925.0.0.redhat-1` from the Red Hat Maven Repository:

```
[INFO] +- io.atlasmap:atlas-xml-module:jar:1.34.0:runtime
[INFO] |  +- io.atlasmap:atlas-xml-model:jar:1.34.0:compile
[INFO] |  \- io.atlasmap:atlas-xml-core:jar:1.34.0:compile
[INFO] |     \- com.sun.xsom:xsom:jar:20140925.0.0.redhat-1:compile
[INFO] |        \- relaxngDatatype:relaxngDatatype:jar:20020414:compile
```

This is the *only* dependency in Syndesis and Atlasmap which points to Red Hat productised dependency. Is there a way how we could avoid this ?

**Comment by rhuss** [comment]
btw, a version `20140925.0.0.redhat-1` sounds also quite old to me.

**Comment by rhuss** [comment]
The dependency is defined here --> https://github.com/atlasmap/atlasmap/blob/e9598992bd9ca74021490f63f541bfc0ae2b8392/parent/pom.xml#L87

**Comment by rhuss** [comment]
@igarashitm couldn't we use the plan 20140925 version (https://search.maven.org/#artifactdetails%7Ccom.sun.xsom%7Cxsom%7C20140925%7Cjar) for the community atlasmap ?

**Comment by mattrpav** [comment]
@rhuss some background for you:

* xsom library is used for xml inspection
* 20140925 is the latest upstream version ref [xsom](https://mvnrepository.com/artifact/com.sun.xsom/xsom)
* the usage of the Redhat productized version was used as requested

There shouldn't be any issue to flip it to the non-rh version in AtlasMap community

**Comment by rhuss** [comment]
@mattrpav that would be awesome, as this is the only dependency we have in upstream on any Red Hat artefact. We just had the case where this repository were down and prevented an upstream release.

Typically versions get replaced during the productisation process anyway, so no need to use them in upstream.

Thanks !
