### ISSUE TITLE
[RFE]  Field name mapping In Json Request

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3678]
**Is your feature request related to a problem? Please describe.**
Currently in atlasmap there is no operation for mapping field name itself for JSON request. In many of my use cases there is requirement to also map fieldname.

**Describe the solution you'd like**
For eg. I have json request
```json
{
"param1" : "value1",
"param2" : "value2"
}
```

I want to convert this JSON structure to
```json
params:[
{
  "name" : param1",
  "value" : "value1"
},
{
  "name" : param2",
  "value" : "value2"
}]
```
In above example I need to also map fieldname of JSON i.e. "param1" and "param2" to "name" field of JSON Target document. 
This should also be allowed in JSON to XML transformation not only in JSON to JSON transformation.

**Comment by igarashitm** [comment]
Interesting. This could be achieved with a **Field Name** transformation. However currently field action cannot access such metadata, it only receives the value of the field. Similar to #1269, we might want to add `@Field` injection to the field action.

**Comment by igarashitm** [comment]
I thought it twice and found that the field names are already shown in UI, so that it's possible to use `Constants` and put the field name manually.
`@Field` injection would be still helpful for some more advanced usecases. Any example for the usecase would be appreciated.

**Comment by Shrishti1234** [comment]
> I thought it twice and found that the field names are already shown in UI, so that it's possible to use `Constants` and put the field name manually. `@Field` injection would be still helpful for some more advanced usecases. Any example for the usecase would be appreciated.

But using constants it would be risky as all paramters all not mandatory. If we try to map constant in target document we use copyTo function which is hardcoding indexing. I think it will create null value. Please correct me If my understanding is wrong.
I have attached sample file for source and target document.

[Sample.zip](https://github.com/atlasmap/atlasmap/files/8093548/Sample.zip)
