### ISSUE TITLE
[BUG] Collection problem with JSON request

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3685]
**Describe the bug**
I am doing JSON to JSON transformation in which I found one issue with collection. In JSON Request if structure is different for objects in collection then only atlasmap read first object structure and populate in GUI interface.
 
 
**To Reproduce**

1. Go to atlasmap GUI
2. Import this JSON request on GUI:
```json
{
	"attrs": [
		{
			"name": "orderType",
			"value": "NCR"
		},
		{
			"name": "aucProvisionParams",
			"value": {
				"k4sno": "1",
				"cardType": "USIM",
				"alg": "MILENAGE",
				"opsno": "1",
				"amfsno": "1",
				"keyType": "ClearKey"
			}
		},
		{
			"name": "hssProvisioningParams",
			"value": {
				"tplId": "200",
				"tplType": "NORMAL",
				"hlrsn": "1"
			}
		}
	]
}
```
3. Attrs field of JSON request shows name(string) and value(String) in atlasmap but value field have different combination.

**Expected behavior**
All value data types should be  visible as I am not able to do mapping for source and target document.

**Screenshots**
![image](https://user-images.githubusercontent.com/39737814/150512166-6c14afc5-5e6b-455d-b9c9-e6894ca1c44d.png)

**Comment by igarashitm** [comment]
This won't work with AtlasMap as we expect the schema is well defined. In this case the `/attrs<>/value` could be a string or a complex object, which is not allowed in AtlasMap.
