### ISSUE TITLE
[RFE] Support Multi Users access

### ISSUE THREAD

**Issue by nguyen-vo** [atlasmap/atlasmap#3744]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

As of right now, we containerize the whole Atlas Map package and deploy it with Cloud Run on GCP. The only issue we have is that when there are more than 2 users accessing the Atlas Map UI the mapping becomes buggy. So my question is that is there a way for us to support multi-user or sessions.

**Comment by igarashitm** [comment]
AtlasMap UI was designed to serve one user/session at a time. You need to bootstrap dedicated instance for each user.
