### ISSUE TITLE
[BUG] CVS parameters handling in document URI

### ISSUE THREAD

**Issue by zregvart** [atlasmap/atlasmap#3747]
**Describe the bug**

When changing the CVS parameters the document URI accumulates previously set parameters. This leads to unwanted parameters remaining, or more than one value for a parameter being used.

For example having chosen `headers` parameter with the value `A,B,C`, saved the mapping, loaded it again to set different `headers` parameter (e.g. `A,B,C,D`) and adding `allowMissingColumnNames=true` parameter; if I save the mapping now both versions of the `headers` parameter will be configured on the document URI. If I subsequently remove the `allowMissingColumnNames` parameter it will still be present on the URI. And, if I set the `allowMissingColumnNames` to `false` both `allowMissingColumnNames=true` and `allowMissingColumnNames=false` parameters will be set on the document URI.

**To Reproduce**

See above

**Expected behavior**

Have the document URI set with only the chosen parameters.

**Comment by igarashitm** [comment]
Fixed with #3745
