### ISSUE TITLE
XSD Issue with attribute in xml

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3784]
**Describe the bug**
I find some issue with XSD when xml element have also attribute paramter. Atlasmap doesn't read it correctly.

**Attach .adm file and source document examples**
I have attached XML sample and its XSD document. In XML sample there is one field Password which have Type attribute and it also have some value. I have  higlighted both the paramters below.
  <wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsse:Username>ERICSSON</wsse:Username>
            <wsse:Password **Type**="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText"> **Ericsson2020** </wsse:Password>
         </wsse:UsernameToken>

But atlasmap is not showing password field with string datatype so I am not able to map password in target document.
![image](https://user-images.githubusercontent.com/39737814/154263141-fb736605-812d-4080-b6a0-0accb6ecf558.png)
Left doc is XSD and right one is XML.

**To Reproduce**
1. Import XML and XSD sample attached.
2. See the difference b/w structure in XML password field with string datatype is visible but not in XSD .

**Comment by igarashitm** [comment]
Unfortunately this is not yet supported, there're some restrictions on XML structure - we'll track it on #3785
