### ISSUE TITLE
[RFE] Version Compatibility Check

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3812]
**Is your feature request related to a problem? Please describe.**

Sometimes user uses the newer version of AtlasMap UI (maybe through vscode extension) and let the older version of AtlasMap runtime comsume it, which often causes a conflict. We should embed a version number into Mapping Definition and let runtime check the compatibility. The rule of thumb is it doesn't work if major.minor version is different, i.e. the .adm created with v2.3 doesn't work with v2.2 runtime. Note that we try to keep backward compatiblity for minor version, so the .adm created with v2.3 should work with v2.4 runtime.

**Comment by pleacu** [comment]
@igarashitm, @lhein 

   On AtlasMap startup:
   - UI and RT version is the same:
     Ping/ pong messages to INFO.  Messages will contain the versions just as a visual verification.
ref:
<pre>
2022-03-15 15:14:32.635 DEBUG 1590558 --- [  XNIO-1 task-2] io.undertow.request.security             : Authentication result was ATTEMPTED for /v2/atlas/ping
2022-03-15 15:14:32.664 DEBUG 1590558 --- [  XNIO-1 task-2] io.atlasmap.service.AtlasService         : Ping...  responding with 'pong'.
</pre>

   - UI version > RT version
     UI Error dialog - `Incompatible Atlasmap runtime (2.13.12) detected (2.13.17 expected) at port 8585.`
     RT log error stating the same
    It's important to reference the port in case they have multiple instances of the AtlasMap RT running.
   - UI version < RT version
     INFO - `Atlasmap runtime (2.13.12) detected (2.13.11 expected) at port 8585.`
     This will keep things working if VSCode AtlasMap UI is a little older.
 
   ADM version field on init (JSON deserialization):
   - `undefined` works with RT and UI.  UI will update ADM with the UI version field (e.g. '2.3.17')
   - '2.3.12'
     UI or RT version >= 2.3.12 will work (newer UI/RT can handle older ADM)
     UI or RT version < 2.3.12 will fail (older UI/RT can't handle future ADM)

Ref: 
Will add `version?: string;`
https://github.com/atlasmap/atlasmap/blob/44745c3b1e3d8b9250b6ceb3cb4602a97a841b59/ui/packages/atlasmap-core/src/contracts/mapping.ts#L44-L56

Will add `version: string | null = null;`
https://github.com/atlasmap/atlasmap/blob/44745c3b1e3d8b9250b6ceb3cb4602a97a841b59/ui/packages/atlasmap-core/src/models/mapping-definition.model.ts#L24-L30

**Comment by igarashitm** [comment]
Note that `runtime` is a confusing word in AtlasMap, we should distinguish the design time backend and the actual runtime. The actual runtime means when user runs the mappings, often through camel-atlasmap.
All of following 3 could be different.
1. UI vs. design time backend
2. UI vs. runtime
3. design time backend vs. runtime

Maybe just UI version could be persisted to the `MappingDefinition` and then the runtime only tests No.2.
Showing a warning for incompatible No.1 was removed due to Fuse Online product versioning, where it adds product revision only to the Java build, then it gets slightly different from UI version.
In any case, we'd want to error out, if the major.minor version is a future version, e.g. 2.4 vs. 2.3. Although patch level difference should be always fine, e.g. 2.3.16 vs. 2.3.3.

**Comment by pleacu** [comment]
So specifically:
  If the version from the mapping in the ADM is in the future with respect to the current UI, we issue an error:
  * UI version < Persisted UI version in `MappingDefinition`
    UI Error dialog - Incompatible Atlasmap ADM file (2.3.13) detected (2.13.17 expected) at port 8585.

  If the version from the mapping is in the future with respect to the current runtime (not design time backend):
  * AtlasMap Runtime (RT)  < Persisted UI version in `MappingDefinition`
    Runtime error from atlasmap-camel.  Is there a centralized location where the RT version is kept?

And that's it for now.

**Comment by pleacu** [comment]
UI check:
![sc1](https://user-images.githubusercontent.com/2981421/159025952-27e5d0d7-53a2-4a06-80d6-1a7ed63d0609.png)
