### ISSUE TITLE
[BUG] Target output XML not contain some namespace prefixs

### ISSUE THREAD

**Issue by mronconis** [atlasmap/atlasmap#3826]
**Describe the bug**

Using a two mappings created with the ui (tested with visual studio) [atlasmap-mappings.zip](https://github.com/atlasmap/atlasmap/files/8213389/atlasmap-mappings.zip) (zip with both .adm files)
- first one (atlasmapping-from-xml-schema.adm) created with source as xsd schema and target as schema-set:
`-` source [person.xsd.zip](https://github.com/atlasmap/atlasmap/files/8214173/person.xsd.zip)
`-` target [customer-schemaset.xml.zip](https://github.com/atlasmap/atlasmap/files/8214178/customer-schemaset.xml.zip)
- second one (atlasmapping-from-xml-instance.adm) created with source as xsd schema and target as xml instance:
`-` source [person.xsd.zip](https://github.com/atlasmap/atlasmap/files/8214173/person.xsd.zip)
`-` target [customer-instance.xml.zip](https://github.com/atlasmap/atlasmap/files/8214183/customer-instance.xml.zip)

The first mapping produce an xml output without some namespace prefixs.
 
**To Reproduce**
Execute the unit test by the [sample project on github](https://github.com/mronconis/quarkus/tree/main/atlasmap), the unit test with name mappingFromXmlSchemaTest fail
````
mvn clean package
````

With the .adm (atlasmapping-from-xml-schema.adm) the wrong output is:
````
<?xml version="1.0" encoding="UTF-8"?>
<envelop xmlns="it.redhat.atlasmap.sample/env">
   <customer xmlns="it.redhat.atlasmap.sample/customer">
      <name xmlns="">Mario</name>
   </customer>
</envelop>
````

**Expected behavior**
With the .adm (atlasmapping-from-xml-instance.adm) the right output is:
````
<?xml version="1.0" encoding="UTF-8"?>
<envelop xmlns:cus="it.redhat.atlasmap.sample/customer">
   <cus:customer>
      <cus:name>Mario</cus:name>
   </cus:customer>
</envelop>
````

**Additional Info**
I unzipped the atlasmapping-from-xml-schema.adm and found that atlasmapping-UI.0.json contain wrong xpath expression for target xml.

I edited a new atlasmapping-UI.0.json and rezziped in a new [atlasmapping-from-xml-schema-mod.adm.zip](https://github.com/atlasmap/atlasmap/files/8213683/atlasmapping-from-xml-schema-mod.adm.zip) (just rezziped) modifying:

from:
````
...output omit...
"xmlNamespace" : [ {
          "alias" : "cus",
          "uri" : "it.redhat.atlasmap/customer"
        }, {
          "alias" : "tns",
          "uri" : "it.redhat.atlasmap/env"
        } ]
...output omit...
"path" : "/tns:envelop/cus:customer/name",
...output omit...
````
to:
````
...output omit...
"xmlNamespace" : [ {
          "alias" : "cus",
          "uri" : "it.redhat.atlasmap/customer"
        } ]
...output omit...
"path" : "/envelop/cus:customer/cus:name",
...output omit...
````
and the output has correct namespace prefixs but log the following warning
````
[main] WARN  io.atlasmap.xml.module.XmlModule  - Declaration of the root element ':envelop' was not found in the schema
````
**Environment**
Atlasmap: Runtime Version: 2.3.16
JDK: openjdk version "11.0.2" 2019-01-15
OS: Macosx

**Comment by igarashitm** [comment]
Turned out the schema is wrong, it needs `elementFormDefault="qualified"` to propagate the namespace to the sub elements. See https://github.com/atlasmap/atlasmap/pull/3827/files#diff-c1296c525418f30ed1abf29ab30bf99bbbc743be70bd779df58e484ca63b2d89R17

**Comment by mronconis** [comment]
Hi,
I tried to modify the schema by adding elementFormDefault = "qualified" but the output xml does not have the namespaces prefixes, it seems to me that it is using the default namespace:
````
<?xml version="1.0" encoding="UTF-8"?>
<envelop xmlns="it.redhat.atlasmap.sample/env">
   <customer xmlns="it.redhat.atlasmap.sample/customer">
      <name>Mario</name>
   </customer>
</envelop>
````

I have updated the sample project on github.

Br,
Marco.
