### ISSUE TITLE
[RFE] Add "Delete mappings"

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3865]
**Describe the solution you'd like**

Add "Delete mappings" menu in the UI. Currently we only have "Reset All", which removes all mapping definitions, Documents as well as libraries. If the user want to start creating mappings from start, but with the same libraries and Documents, "Delete mappings" is more helpful.
The REST target would be
`DELETE /v2/atlas/project/{mappingDefinitionId}/mapping`
on `MappingService`

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/160888893-b932af2b-3b6a-4bf7-8db5-82776e11d904.png)
![sc2](https://user-images.githubusercontent.com/2981421/160888916-8e9b1206-0a01-4fd2-8eb7-a079d4f6d520.png)
![sc3](https://user-images.githubusercontent.com/2981421/160889035-2aff6461-54e2-4ee4-8ebd-1f344bd92860.png)
![sc4](https://user-images.githubusercontent.com/2981421/160889021-a4499fba-304d-41ad-94a7-fd10afdfb415.png)

**Comment by pleacu** [comment]
Hey @igarashitm - having difficulty with the `mapping-management.service.spec.ts`.  For `removeAllMappings` test the build fails with:
<pre>
@atlasmap/core: FAIL src/services/mapping-management.service.spec.ts (9.803s)
@atlasmap/core:   ● MappingManagementService › removeAllMappings()
@atlasmap/core:     TypeError: globals.Request is not a constructor
@atlasmap/core:       171 |         '/mapping';
@atlasmap/core:       172 |       this.api
@atlasmap/core:     > 173 |         .delete(url)
@atlasmap/core:           |                ^
@atlasmap/core:       174 |         .then((res: Response) => {
@atlasmap/core:       175 |           this.cfg.logger!.debug(`Delete Mappings Response: ${res.ok}`);
@atlasmap/core:       176 |           this.notifyMappingUpdated();
@atlasmap/core:       at new Ky (../../node_modules/ky/umd.js:243:19)
@atlasmap/core:       at Function.ky.<computed> [as delete] (../../node_modules/ky/umd.js:456:37)
@atlasmap/core:       at src/services/mapping-management.service.ts:173:16
</pre>
The new `removeAllMappings`  function looks like this:
<pre>
  removeAllMappings(): Promise<boolean> {
    return new Promise<boolean>((resolve) => {
      for (const mapping of this.cfg.mappings!.getAllMappings(true)) {
        this.cfg.mappings!.removeMapping(mapping);
      }
      this.deselectMapping();
      const url: string =
        this.cfg.initCfg.baseAtlasServiceUrl +
        'project/' +
        this.cfg.mappingDefinitionId +
        '/mapping';
      this.api
        .delete(url)
        .then((res: Response) => {
          this.cfg.logger!.debug(`Delete Mappings Response: ${res.ok}`);
          this.notifyMappingUpdated();
          resolve(true);
        })
        .catch((error: any) => {
          this.cfg.errorService.addBackendError(
            'Error occurred while deleting mappings.',
            error
          );
        });
      resolve(false);
    });
  }
</pre>
I see stubs for `post` and `get` but none for `delete` which is what my issue is above (I believe).  Do we have a `delete` spyOn example?  thkx!

**Comment by igarashitm** [comment]
like this? https://github.com/igarashitm/atlasmap/commit/06b94eac5bed8fc5d6aaead39eb50d6d165d5aa4#diff-085bad6f900e462b2d30382513edfbc350f11d87e1e41807209bc14e8592509bR190
