### ISSUE TITLE
[TASK] - Refactor removeAllMappings() to use Backend service.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#3905]
Refactor `removeAllMappings()` to use a new UI core mapping service pull routine and to use the backend service to retain the current mappings.

**Comment by pleacu** [comment]
@igarashitm - Hey Tomo - so here's my issue.  The backend service function `removeMappingRequest` does its job correctly.  However, when I perform a `getMappingRequest` call I get the original mappings because it calls `ADMArchiveHandler admHandler = this.atlasService.loadExplodedMappingDirectory(mappingDefinitionId);` - ref https://github.com/atlasmap/atlasmap/blob/main/lib/service/src/main/java/io/atlasmap/service/MappingService.java#L135
It appears I need to modify the contents of the explodedMappingsDirectory to remove just the mappings so subsequent `get` mappings will not find the old info.  wdyt?

**Comment by igarashitm** [comment]
That sounds like a bug in backend, this `persist()` should persist to the mapping definition file held in explodedMappingsDirectory - https://github.com/atlasmap/atlasmap/blob/main/lib/service/src/main/java/io/atlasmap/service/MappingService.java#L111

**Comment by igarashitm** [comment]
Yes It has to invoke `ADMArchiveHandler#setMappingDefinition()` explicitly before `persist()` to clear the cache of serialized one.
https://github.com/atlasmap/atlasmap/blob/main/lib/core/src/main/java/io/atlasmap/core/ADMArchiveHandler.java#L278
