### ISSUE TITLE
Incorrect Transformation options can be selected in UI for some mappings

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#393]
Please review some of those might be actually correct: 
- **List of (Strings,numbers) -> String** : 
  - Concatenate (Source transformation shouldn't be enabled)
- **String -> String **
- **List of Strings  ->Integer**
  - Add
  - Average 
  - Divide 
  - Length 
  - Maximum
  - Minimum 
  - Multiply 
  - Subtract
- **String -> Number (Integer,Double, Float, Long)**
  - Add 
  - Average 
  - Divide 
  -  ~~IndexOf~~
  -  ~~LastIndexOf~~
  - Maximum
  - Minimum 
  - Multiply 
  - Subtract
-  ~~**Number types -> Number types**~~
  -  ~~IndexOf~~
  -  ~~LastIndexOf~~
- **Char -> Char**
  - looks like there are string transformations that don't make sense (concat,append, fileExtension etc..)

**Comment by jpav** [comment]
@mmelko There is definitely a problem with List<?> -> String and ? -> Char. 
The actions you questioned about Number -> Number are valid; you can find the index of digits within a number. These actions 'stringify' the data, so will work on any type.
However, I'm not seeing any of the numeric functions you listed show up for the List<String> -> Number or String -> List<Number>. Can you verify how you are seeing these?

**Comment by mmelko** [comment]
I'm seeing those for: List of Strings -> Number types. Just create mapping, click on "Edit mapping" and you can Add transformation.  I haven't mentioned any String -> List mapping. And I'm not sure what I meant by **String -> String **, it is some typo :)
