### ISSUE TITLE
[TASK] - Refactor reordering of mapped fields - pull from backend service.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#3935]
The UI function `handleIndexChange` processes a mapped field index change.  The source field is represented by
 the current index.  The target index is represented either by a number or by a mapped field (depending on whether the index was physically modified or d&d modified).

**Comment by pleacu** [comment]
@igarashitm - having trouble coming up with the simplest way to transfer the target mapping field index to the backend service with the REST API as a request payload.  Do you have an example where a simple integer is passed? Do I need a full headers definition for it in JSON?  I'd like to keep it just as a parameter (`@Parameter`)
<pre>
@Parameter(description = "Target Mapped Field Index") @PathParam("targetFieldIndex") Integer targetFieldIndex
</pre>

**Comment by igarashitm** [comment]
The "RESTful" manner is to use request body but not the URL parameter for other than `GET` method. You should remove both of `@Parameter` and `@PathParam`. Here is an example of sending simple string body.
https://github.com/igarashitm/atlasmap/blob/3750/lib/service/src/main/java/io/atlasmap/service/DocumentService.java#L119-L128
https://github.com/igarashitm/atlasmap/blob/3750/ui/packages/atlasmap-core/src/services/document-management.service.ts#L990
