### ISSUE TITLE
[TASK] Modify mapping service test infrastructure to add ability to push a primitive data value with a URL request.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#3967]
It's possible to send a simple string through the REST interface along with a URL.  i.e.

URL: `http://localhost:8585/v2/atlas/project/0/mapping/mapping.193473/field/TARGET/0/index`

sent via a `put` call.  i.e.

`      this.api.put(url, { body: targetFieldIndex.toString() })`

The backend mapping service test harness:
https://github.com/atlasmap/atlasmap/blob/main/lib/service/src/test/java/io/atlasmap/service/MappingServiceTest.java
Test support utilities:
https://github.com/atlasmap/atlasmap/blob/main/lib/service/src/test/java/io/atlasmap/service/TestUriInfo.java

The goal would be to modify `TestUriInfo.java` to add the ability to set a body request value and to call that function from `MappingServiceTest.java`.

**Comment by igarashitm** [comment]
@pleacu Is this still an issue?
