### ISSUE TITLE
String > int/long converter fails with decimal expression

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#408]
Can't even get what was the intention, but at least this doesn't work with decimal expression... it should work with rounding.
https://github.com/atlasmap/atlasmap/blob/914b68d3719ef959cc31792a0cbb62aead0be550/runtime/core/src/main/java/io/atlasmap/converters/StringConverter.java#L203-L206
https://github.com/atlasmap/atlasmap/blob/914b68d3719ef959cc31792a0cbb62aead0be550/runtime/core/src/main/java/io/atlasmap/converters/StringConverter.java#L246-L249

**Comment by mattrpav** [comment]
The converter checks for Min and Max Long bounds. Detecting for decimals isn’t handled, and makes sense be as a use case w specific detection and behavior.

**Comment by igarashitm** [comment]
@paoloantinori I think this is a blocker though, wonder if we want to backport to 1.34.x branch.
