### ISSUE TITLE
Investigate UX improvements to Atlasmap

### ISSUE THREAD

**Issue by amysueg** [atlasmap/atlasmap#429]
Conduct UX research to make recommendations and wireframe designs to improve various aspects of user experience for the UI.

Review previous design documents and input, conduct competitive research, review field enablement feedback and more. The goal is to identify areas for improvement, work with community and others to prioritize, and create wireframes with alternative designs.

@dongniwang fyi

**Comment by heiko-braun** [comment]
Closing as out-of-date
