### ISSUE TITLE
[RFE] Standalone server is stateful

### ISSUE THREAD

**Issue by MatWein** [atlasmap/atlasmap#4295]
**Is your feature request related to a problem? Please describe.**
The standalone server of atlasmap seems to have a target/lib and target/mappings folder which keeps the current browser state. But what if multiple users want to work on different adm files at the same time? I tried it with different browsers at the same time but they influence each other which leads to problems like:
![image](https://user-images.githubusercontent.com/35470253/185656748-392b2f1f-e595-43d2-a47f-6188bfe897b5.png)
if I edit my mappings in chrome but at the same time doing a reset in firefox, because this will delete my JAR files from the lib folder.

**Attach .adm file and source document examples if you are looking at specific current behavior**
[upload.zip](https://github.com/atlasmap/atlasmap/files/9383386/upload.zip)

**Describe the solution you'd like**
I think it would be better to have:
1. a static lib folder which the user cannot change. In Our case we have non-technical users and they dont know about JAR files. We want them to provide a JAR with additional custom transformations/actions one time at the deployment. After deployment the classpath should no more change.
2. Keep the mapping in browser storage and not in the target/mappings folder, so multiple users can work at the same time
3. Avoid states / stateful backend services

**Describe alternatives you've considered**
I think if we really have the use case that the user needs to upload its own libs we have to do it in another way than the current one.

**Additional context**
If we use the solution described above, it is no more neccessary to save the libs into the adm file. Apache Camel does also currently NOT use this stored libs because I have to have the classes in my own classpath. Otherwise loading of the adm file fails, see https://github.com/atlasmap/atlasmap/issues/4294

**Comment by igarashitm** [comment]
This is by design. AtlasMap was designed to be a personal tool including backend services, but not for multi-users. Storing at the backend is also by design.
