### ISSUE TITLE
Support nested collection

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#435]
AtlasMap doesn't support nested collection like `/list1<>/list2<>` at all. Everything in current code assumes collection field is only one in the path. Just do it and elliminate this limitation.

**Comment by igarashitm** [comment]
It might be better to even eliminate wrapping `<Mapping mappingType="Collection"...` as this is the root cause of #430 as well. `collectionClassName` could be migrated under `JavaDataSource` with path expression. I'll make it as a part of #430.

**Comment by igarashitm** [comment]
Plus due to #431 bug, `collectionClassName` is not really in use ATM.

**Comment by mrakibhasan** [comment]
How soon we can expect to support nested collection?

**Comment by igarashitm** [comment]
I can't guarantee, but planning to get it shipped around October.

**Comment by zamrokk** [comment]
please work on this. It is a huge missing feature that is blocking us for some cases

**Comment by igarashitm** [comment]
1st interation completed - track with individual issues after now.
