### ISSUE TITLE
Provide a button to trigger an auto-mapping of fields

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#436]
when mapping data from 2 metamodel that are quite close, there are often same naming used between several fields of source and target.

It would be nice to provide a way to trigger an auto-mapping for all fields that have the same name. It can save a lot of time to users.

Thinks to consider:
- different data type? maybe first version only when same data type and a second providing a transformation automatically also when possible or do the mapping and user will have validation error to fix?
- match ignoring case?
- do the mapping only when there is no ambiguity?

**Comment by igarashitm** [comment]
You'd want to implement metadata model analyzer engine first, and then AtlasMap would be able to leverage it. I don't think we want to implement it inside AtlasMap. Closing.
