### ISSUE TITLE
Support data preview in UI

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#441]
This probably should be something the user could toggle off, but once available, I'd expect this Initially to be toggled on. We could do this in phases by starting with just supporting the auto-generation of data in the source, then editing of that data, and finally importing actual files that are backed by the models being mapped.

**Comment by igarashitm** [comment]
Do you mean #78?

**Comment by jpav** [comment]
Sorry, yes, this is a duplicate of #78
