### ISSUE TITLE
Atlasmap - Mapping Details Section - change 'Add Transformation' button to a link

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#443]
![dm1](https://user-images.githubusercontent.com/2981421/40723509-0f6f75f8-63ed-11e8-9189-556025e25d1f.png)

Note the 'Add Transformation' button - it should just be an icon on the main bar next to the trash can

**Comment by jpav** [comment]
Not sure if I understand this. Do you mean on the 'Mapping Details' bar or the main bar of each target? If the former, how would the user identify to which target a new transformation is going to apply?

**Comment by jpav** [comment]
Ah, okay, that makes sense.

**Comment by jpav** [comment]
Two suggestions:

1.  I'd add some type of * or + decoration to the add transformation icon (→), similar to this new folder icon: ![image](https://user-images.githubusercontent.com/437085/40805705-bb022e2c-64e4-11e8-996d-763d1e2c1fa1.png)

1. The abbreviated 'i:' looks strange now in italics, so i'd change that to a regular font.
