### ISSUE TITLE
Can't combine fields when working with Array[BUG] 

### ISSUE THREAD

**Issue by akshaygarg** [atlasmap/atlasmap#4456]
Hi,

I started exploring AtlasMap and found a bug. Kindly close it if you think this is as per design.

Source :

[{
	"firstName" : "Tom",
	"LastName"  : "Hanks"
}]

Target : 

[
{
       "Name" : "Tom Hanks"
}]

If i use standalone mapping tool to combine first name and last name, it doesnt work. I dont get option to link them.
![image](https://user-images.githubusercontent.com/3895934/203346756-5dc69538-997a-4f85-b421-4fab0b8302e3.png)

**Comment by igarashitm** [comment]
Duplicate of #1236
