### ISSUE TITLE
Account for gaps when mapping components in separate or combine modes.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#449]
Hiram brings up a good point about being able to specify gaps.  I'm not sure how common this would be
but... consider the following fullAddress format:

  ZIP:ZIP+4:Country:State:County:City:AddressLine1:AddressLine2
  i.e.
  01568:4114:USA:MA:Worcester:Upton:186 Elm St::

All the user really wants is:

  01568:MA:Upton:186 Elm St:

The user selects 'fullAddress' and then ctrl-selects the address components that they know they need
(addressLine1, city, state, zipCode).  They then drag&drop into the correct canonical order (zipCode,
state, city, addressLine1) but they still need to indicate indices where the split-string elements are
to be skipped.  The question is - how does the user most intuitively specify where those gaps are?

I believe the "Mapping Details" section of the Data Mapper should accurately reflect all the fields of
the format of the originating datum.  That would appear something like:

  i: 1  zipCode
  i: 2  <skip>
  i: 3  <skip>
  i: 4  state
  i: 5  <skip>
  i: 6  city
  i: 7  addressLine1
  i: 8  <skip>

I'd like to avoid having the user be able to hand-modify any index.  We'd have to provide the ability
to create a dummy element and then they would need to hand-edit the index into one of the skip fields.

That leaves one obvious place to specify all of the gaps - the Action window.  The user would see 
something like:

  Action
   Separate

  Separator
   Colon [:]

  Skip Indices
   2,3,5,8

  * It creates a single point where all of the gap indices are specified, isolating a complex part of
    the mapping.
  * It provides for an uninterrupted display in the mapping details, 1 through 8.
  * It's less invasive to the UI.

**Comment by igarashitm** [comment]
reopened just for showing up as a "Epic - Done", closing again.
