### ISSUE TITLE
Support data preview - single mapping entry

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#451]
## Feature Owner: Tomo

Support single entry version of #78. We'd like to add data preview mode in AtlasMap UI. This ticket focuses on having a data preview only for the active mapping.

## User Stories: 
- https://github.com/syndesisio/syndesis/issues/2906
- https://github.com/syndesisio/syndesis/issues/2909

#### Demo animations for the prototype:
* Preview: https://vimeo.com/277359816
* Preview Error: https://vimeo.com/277359824
* Preview in table view: https://vimeo.com/277386378

**Comment by igarashitm** [comment]
Hi @gaughan,
Cc: @paoloantinori 

I found the current data preview is partially working even for collection fields, as if it's non-collection fields. Attached a screenshot. It means you can put only one element into a source field and show only one element for a target field. So you can only simulate for collection size=1. But since this is not failing nor wrong, I think we can ship it without waiting for full collection support (#501) which will eventually involve a major overhaul for collection mapping.

![screenshot from 2018-08-06 13-52-17](https://user-images.githubusercontent.com/265462/43732875-d17dc708-9980-11e8-829a-898c87aca39a.png)

**Comment by gaughan** [comment]
@igarashitm LGTM!

**Comment by heiko-braun** [comment]
@igarashitm Are we ready to include this in syndesis master?

**Comment by igarashitm** [comment]
@heiko-braun I believe the PR syndesisio/syndesis#3518 enabled data preview by default with final design.

**Comment by mmelko** [comment]
Verified
