### ISSUE TITLE
Regressions after combine/separate changes

### ISSUE THREAD

**Issue by mcada** [atlasmap/atlasmap#456]
After last changes to separate/combine functionality there are now useless buttons which create irrevertible state (one must delete current mapping and start it over). Just click on button "add source" or "add target".

Overall data mapper is not intuitive - no info that user must hold ctrl to do combine/separate.

Drag and drop does not work to change index positions as it says in the tooltip - there is no option to do it.

Tested on syndesis master.

**Comment by igarashitm** [comment]
Do you mean "Add Source" / "Add Target" buttons are not working? can you be more specific?

**Comment by igarashitm** [comment]
At least works for me in standalone.
