### ISSUE TITLE
Scope CSS selectors

### ISSUE THREAD

**Issue by michael-coker** [atlasmap/atlasmap#457]
https://github.com/syndesisio/syndesis/issues/2760

Ideally, if all of these styles in [data-mapper-app.component.css](https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css) are inside `.DataMapperUI` then all CSS should be scoped to that class so the styles don't apply to other elements outside of the data mapper.

The specific lines that are causing a problem are at [214 and 215](https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css#L214-L215). 

Once this stylesheet is loaded into the syndesis app, those lines will change all `.alert` and `.alert-info` elements in syndesis.

@igarashitm can you check this out? I'm not sure where these alerts are generated in the data mapper. I don't see them in the source when I load the data mapper in syndesis, so I'm not sure what selector to use to properly scope them.

**Comment by igarashitm** [comment]
@pleacu can you take this?

**Comment by pleacu** [comment]
![dm1](https://user-images.githubusercontent.com/2981421/41057251-9fb93214-6994-11e8-9998-7b3b2b559673.png)
