### ISSUE TITLE
Need version attribute to be stored in mapping files

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#460]
We need to store a version in our mapping files so that we can handle recognizing when older mapping files don't support some newer feature that we provide in the future, or if we introduce something that involves a 'breaking' change and thus requires us to perform some type of migration.

**Comment by mattrpav** [comment]
This is already handled in the design! The models are versioned by package name to specifically for this reason. By using separate packages, the engine can support mapping multi-version.

Simply, create new models under io.atlasmap.v3.. io.atlasmap.java.v3.. etc when the definitions have a breaking change.

Bonus-- migrating mappings from v2 -> v3 can be done using stylesheets, or even by writing an AtlasMap mapping definition to do it =)

**Comment by jpav** [comment]
Ah, I was looking at the mapping files directly, but I didn't even consider looking at the version embedded in the namespace.
