### ISSUE TITLE
Can't add transformation for collection mapping

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#462]
Add Transformation link doesn't work for Repeating Mapping
![screenshot from 2018-06-08 16-19-49](https://user-images.githubusercontent.com/265462/41179340-632c1db6-6b38-11e8-9063-2f3433e1cff8.png)

**Comment by pleacu** [comment]
Transformations enabled on arrays/ collections:

![dm1](https://user-images.githubusercontent.com/2981421/41600338-aec8e678-73a3-11e8-82b1-0be1a001ada6.png)

Generated XML:

![dm2](https://user-images.githubusercontent.com/2981421/41600689-8d03cb10-73a4-11e8-9208-5b0b18fb85c5.png)
