### ISSUE TITLE
Trying to run AtlasMap standalone on local side

### ISSUE THREAD

**Issue by BuildDream18** [atlasmap/atlasmap#4623]
Hello, everyone.

I cloned the atlasmap project and ran the Java project on Windows 11's WSL today.

$ cd ${ATLASMAP}
$ ./mvnw clean install -DskipTests -Pitests

Encountered Non-parseable POM issues.

![image](https://github.com/user-attachments/assets/2af08319-ca82-4d97-a926-ad3e5ed9709f)

I hope someone will help me. Thanks.

**Comment by yatharth01** [comment]
Try deleting .m2 folder.

**Comment by BuildDream18** [comment]
Hi, 

I fixed the maven issue after modification of pom.xml in parent file.
The main issue is that the project is using the deprecated and unsupported repositories. 
So I commented the unsupported repositories like that.
![image](https://github.com/user-attachments/assets/70abbaec-727b-444f-9325-539b7fcb138a)

Thanks.
