### ISSUE TITLE
‘Add Transformation’ button icon is a bit hard for users to notice.

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#487]
## This is a...

<pre><code>
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

'Add transformation' button icon is not very obvious for users to notice at the first glance.
- The arrow icon is not easy to associate with the meaning of  'transformation', which is hard to let the user notice.
- The clicking area is a bit small

## Screenshot
![transformation-button](https://user-images.githubusercontent.com/5396309/42205910-43884742-7ed8-11e8-9795-22df336a8417.png)

## Expected behavior

It is better to use a more appropriate icon + text label to describe the transformation button.

## Related Issues
1. #72 Add tooltip for data transformation icon 
2. #98  In Targets panel users choose the wrong action
3. #492 Redesign the 'delete' & remove action button

**Comment by jpav** [comment]
If we add back the Add Transformation button, we should add the lightning bolt icon to it since that's what we use in the source/target trees to indicate transformations are involved in a mapping.

**Comment by pleacu** [comment]
When we met with UXD it was decided that the 'Add Transformation' button was too big and that a simple icon with appropriate tooltip help would be better.  The button is especially awkward when performing multiple cascading transformations (and you get a 'Add Transformation' button in each block.

**Comment by deernano** [comment]
@jpav @pleacu @igarashitm 
Hi everyone,
Here is the design solution for this task: https://redhat.invisionapp.com/share/BQMZW7N8CJV#/309112230_AddTransformation

The main design purpose is to 
- reduce the use of redundant icons
- Simplify the ‘add transformation’ process, let the user easily adding transformation.
- Prepare for the next step of unifying the ‘transformation’ process of repeating mode (to redesign the 'Add source' workflow of repeating mode, also in repeating mode we already have a 'add mapping' button)

Currently, when adding transformation,
- The icon is not very obvious for users to notice at the first glance. 
- The clicking area is a bit small
<img width="342" alt="2018-07-13 6 25 06" src="https://user-images.githubusercontent.com/5396309/42811399-164042a6-89ed-11e8-8194-24f20ddb759e.png">

When adding more transformation,
- It is not very obvious for users to notice that clicking again could add another FeildAction.
<img width="334" alt="2018-07-13 6 27 38" src="https://user-images.githubusercontent.com/5396309/42811457-42480d3e-89ed-11e8-9e11-f82a37f72c5e.png">

In repeating mode,
There are too much icons on screen. Also, if we use 'button' style,   in Targets panel users choose the wrong action , as the #98 indicates.
<img width="310" alt="2018-07-13 6 33 07" src="https://user-images.githubusercontent.com/5396309/42811525-642861f6-89ed-11e8-9a75-9f6e01d88769.png">

To see the design process, you could also refer to the competitive research as below:
https://docs.google.com/document/d/1EXAZ1bxn7-vgd-0bTBgllR2l7puEmg9H6zBZyTVRvAk/edit?usp=sharing

**Comment by deernano** [comment]
@jpav @pleacu @igarashitm 
The transformation wireframe is updated as below
https://redhat.invisionapp.com/share/BQMZW7N8CJV#/309112230_AddTransformation

**Comment by igarashitm** [comment]
implemented
