### ISSUE TITLE
Transformation behaviour in Repeating mapping is inconsistent with transformation behaviour in other mappings

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#488]
## This is a...

<pre><code>
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently, the transformation behaviour has inconsistency in different mappings.
- In repeating mapping, the user 
1)clicks 'Edit' icon
![datamapper-488-1](https://user-images.githubusercontent.com/5396309/42206713-86659df6-7eda-11e8-84ee-f31c9ce9854c.png)

2. clicks 'Add transformation' icon
![datamapper-488-2](https://user-images.githubusercontent.com/5396309/42206720-8d4d425e-7eda-11e8-961d-46fe2fc0c71b.png)

- In other mappings, the user clicks 'Add transformation' icon directly
![transformation-button](https://user-images.githubusercontent.com/5396309/42206742-9e8aaf8e-7eda-11e8-9e52-9e5b46eb08b9.png)

## Expected behavior

It is better to use the same transformmation workflow.

## Related Issues
1. #274 UX: mapping details aren't opened right after creation of repeating mapping 
2. #294 [UI] Do we really need "Repeating Mapping" component? 
3. #502  ‘Edit Details’ Close button icon has the meaning of ‘Remove

**Comment by igarashitm** [comment]
So the initial intention seems to be to bundle mappings which involve fields in a same collection. So if we really need to bundle them, I would say this is a natural behavior. But IMHO the bundling itself doesn't make sense like I said in #294.

**Comment by deernano** [comment]
@igarashitm Yes, this two tasks are related to this issue.  I will do a reaserch of transformation workflow later in this sprint. Maybe could have a comprehansive consideration afterwards :)

**Comment by deernano** [comment]
@igarashitm 
Based on the dev review, 
- We do not need a different UI for repeating mapping
- Remove repeating mode and called 'Mapping details' for all mode based on automatic transition.
Once automatic transition is able to release, we recommend to use this new UI at the same time.
- We do not need 'grouping function particularly for repeating mode. It is better to let the user group mapping if the fields belong to the same parent if we remain grouping function.
Here is the wireframe link: https://redhat.invisionapp.com/share/7RNJ944PFH9#/screens/314527595
- From the competitive research, we haven't found the other products having 'grouping mapping' function.

**Comment by igarashitm** [comment]
Closing - #294 removed "Repeating Mapping" component.
