### ISSUE TITLE
Search consistency with Patternfly 

### ISSUE THREAD

**Issue by nding-anges** [atlasmap/atlasmap#490]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

UI and interaction of Search is inconsistency with Patternfly, usability issues summarized as below:

- The search bar is not always anchored, user need to click the icon for enabling search.
- Currently on Data mapper , “ x “ is to close search barre. But on "cleaning text input" is missing.

## Expected behavior
**Search behavior:**
- If "Search" is a  high frequency used by the user, the search bar should be always enable for user type.
- Provide cleaning text input function.

There are two variations of search See  example : 
http://www.patternfly.org/pattern-library/widgets/#search
http://www.patternfly.org/pattern-library/forms-and-controls/find/#design

## Screenshot
<img width="1239" alt="2018-07-06 2 10 23" src="https://user-images.githubusercontent.com/34368385/42366022-afa937d6-8132-11e8-9734-bdead372bf09.png">

**Comment by nding-anges** [comment]
Considering two different use cases, I uploaded two alternative design .
Option A :  If "Search" is a high frequency used by the user, the search bar should be always enable for user type.

![search a](https://user-images.githubusercontent.com/34368385/42366137-067bf242-8133-11e8-98ef-5360b82c1dd6.png)

Option B :  If "Search" is a Low frequency used by the user, the search could  be toggled based on the user needs.
![search b](https://user-images.githubusercontent.com/34368385/42366520-f946e234-8133-11e8-85f4-0dd1a765b81f.png)

**Comment by nding-anges** [comment]
@igarashitm Hi Tomo, please help to review the above behavior. Thank you~!

**Comment by igarashitm** [comment]
Thanks! both looks good, I prefer Option B a bit as vertical space is limited, but PM might have different opinion.

**Comment by sjcox-rh** [comment]
@kcbabo Is this something you are Gary can provide an opinion on?  Thanks so much!

**Comment by kcbabo** [comment]
@gaughan - I'm good with what Gary prefers.

**Comment by gaughan** [comment]
Option B fits the current behavior (low freq). I think we should keep this unless there is a strong request to change.
The way option B is currently written tho doesn't match patternfly. 
- Do we need 'clear' vs the patternfly 'X'? 
- Position and results count are also nice to have but might be a lot to implement everywhere.

**Comment by igarashitm** [comment]
#2116 will address it in React UI
