### ISSUE TITLE
Error notification will not  automatically be hidden

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#491]
## This is a...

<pre><code>
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
- When the error notification shows,

![datamapper-491-1](https://user-images.githubusercontent.com/5396309/42209033-37830ccc-7ee0-11e8-817a-e5eae46f0125.png)

   if the user create a new mapping, the error notification will not automatically be hidden. The user may misunderstand the the new mapping is incorrect as well.

![datamapper-491-2](https://user-images.githubusercontent.com/5396309/42209038-3ac5cc9e-7ee0-11e8-82ea-5bb55252101d.png)

- When more errors occur, the user will need to manually close the error messages one by one.  

<img width="713" alt="datamapper-489-3" src="https://user-images.githubusercontent.com/5396309/42209186-9ed20f2c-7ee0-11e8-93ff-f0526b38bc3e.png">

## Expected behavior
- It is better to autometically hide the error notification after the user start a new mapping / delete the current mapping

- When the error notification shows, It is better to change the invalidate mapping clicked color to a warning color in order to better warn the user.

![datamapper-491-4](https://user-images.githubusercontent.com/5396309/42209090-646d1110-7ee0-11e8-960a-037c151e484d.png)

## Related Issues
1. #375 Improve error diagnostic if a user attempts multiple mappings (map mode) to the same target element

**Comment by deernano** [comment]
@igarashitm Hi Tomo, please help to review the above behaviour. Thank you~!

**Comment by igarashitm** [comment]
Ugh I misread at first glance, this is a nasty bug apparently. Just because this error message doesn't belong to any mapping, it's shown in the global error area, while those belong to the specific mapping are shown only for active (focused) mapping.
@pleacu can we make this instant and remove in a few seconds? even better if we can remove it as soon as user click the other field.
