### ISSUE TITLE
Redesign the 'delete' & remove action button

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#492]
## This is a...
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Overuse of 'trash can' icon for delete and remove action may feel a bit redundant on screen.
  
## Screenshot
![datamapper-492-1](https://user-images.githubusercontent.com/5396309/42210011-b4bf1684-7ee2-11e8-857c-2abdf76acab4.png)
![datamapper-492-2](https://user-images.githubusercontent.com/5396309/42210016-b73c670e-7ee2-11e8-9f07-e43743f9dbe7.png)

## Expected behavior
Use different icon for 'delete' and 'remove' action
- 'Trash can' icon--'Delete' action
'Trash can' icon can be used as 'Delete' action. 'Delete' action needs users's confirm before next step by poping up a message dialog. 

Example: 
![datamapper-492-3](https://user-images.githubusercontent.com/5396309/42210624-11349aaa-7ee4-11e8-85d4-e54d06f3dc08.png)

- 'X'icon ---'Remove' action
'X'icon can be used as 'Remove' action. 'Remove' action will be activated directly witout user's confirm . It is suitable for actions that can be easily recoverd.

Example: Remove a target/ Remove a srouce

**Comment by deernano** [comment]
@igarashitm 
To align with #487,
- To remain 'Trash can' icon as 'Delete mapping' action

![deleteicon-1 2x](https://user-images.githubusercontent.com/5396309/42927190-43c702b2-8b66-11e8-96dc-cc457f86afef.png)

- Since we have two 'remove' action
  -  Use 'Remove' text as Remove source / target. 
  - Use 'x' action as Remove FeildAction.

![deleteicon-2 2x](https://user-images.githubusercontent.com/5396309/42927355-d8a8ce24-8b66-11e8-880b-1989523ff7ab.png)

**Comment by deernano** [comment]
@igarashitm @gaughan 
Based on the mapping flow change, the Button UI will change as following:
![actionbutton 2x](https://user-images.githubusercontent.com/5396309/44214290-5f460b80-a1a2-11e8-8c3f-d1b791810f6a.png)

**Comment by igarashitm** [comment]
implemented
