### ISSUE TITLE
The namespace list header icon should align with the namespace toggle button icon

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#496]
## This is a...

<pre><code>
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently, the namespace list header icon is not consist with the namespace toggle button icon.

## Screenshot
<img width="655" alt="datamapper-496" src="https://user-images.githubusercontent.com/5396309/42212448-b9fa43c0-7ee8-11e8-89d1-d3abcbd5991b.png">

## Expected behavior
It is better to change the namespace list header icon to '' </>'' .

**Comment by deernano** [comment]
@igarashitm Hi Tomo, please help to review the above behaviour. Thank you~!

**Comment by igarashitm** [comment]
I think I'm not so good to comment for this TBH :-)
So yeah, `</>` icon seems to be expressing it is related to XML, so using it would be fine. On the other hand, the current icon seems to be expressing it is table. Yes it's a table view showing a list of namespaces. Hmm. I'm fine with either way. So if it looks confising for you, let's change it to `</>`.

**Comment by deernano** [comment]
@igarashitm From UI espect,  we can either remove the icon in namespace table, or change it to</>. This is just a small detail to be consistent :)

**Comment by pleacu** [comment]
Changed icon to match toolbar (fa-code):

![sc1](https://user-images.githubusercontent.com/2981421/62943659-01460700-bda9-11e9-8efb-3420e82c18a9.png)
