### ISSUE TITLE
Modifier width of Dropdown Menu

### ISSUE THREAD

**Issue by nding-anges** [atlasmap/atlasmap#497]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
While on small screen, the drop down menu in mapping panel is not wide enough to see the whole source.

## Expected behavior
- Modifier width of Dropdown Menu that keep the same width with Search barre.
- Add an responsive status to Dropdown Menu and the text in menu may need to be truncated. Refer to: https://www.patternfly.org/styles/terminology-and-wording/#truncation

## Screenshot
<img width="356" alt="2018-07-03 5 44 12" src="https://user-images.githubusercontent.com/34368385/42212456-c07e4a2a-7ee8-11e8-872c-66f506212233.png">

**Comment by nding-anges** [comment]
@igarashitm Hi Tomo, please help to review the above UI design. Thank you~!

**Comment by jpav** [comment]
The actual paths in the dropdown can be very long, so we'd need to also allow for the tooltip (i.e., responsive status) to be positioned appropriately to the left to allow for the entire path to be shown. I was thinking that wrt what's shown in the dropdown, we could always show the entire last segment in the path, preceded by ellipses as necessary, and the preceded by however much of the beginning of the path fits. Might also be able to leave off the last segment in the tooltip in that case if we display 'Path: /blah/blah'

**Comment by pleacu** [comment]
This is what I've implemented:
1.  For the conditional expression search box - the pull-down  menu is 100 characters wide.  Paths exceeding that will have the leaf plus as much of the start as can fit (+ ...).  Once selected - a hover over the expression component will show the entire path.

![sc0](https://user-images.githubusercontent.com/2981421/62893994-d2348480-bd19-11e9-8e36-e7f712be9b05.png)

2.  For the Mapping Details Sources/Targets search boxes the horizontal space is limited.  Paths are limited to 40 characters.  Paths exceeding that will have the leaf plus as much of the start as can fit (+ ...).

![sc1](https://user-images.githubusercontent.com/2981421/62894210-50912680-bd1a-11e9-95a6-b80f0d67d4a0.png)

**Comment by igarashitm** [comment]
cool!
