### ISSUE TITLE
After clicking ''add new mapping'' button,  the mapping panel header is better to be ''New Mapping''

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#498]
## This is a...

<pre><code>
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently,  ''Add new mapping'' panel header is the same as the ''Show/hide mapping details'' panel header.

## Screenshot
''Show/hide mapping details'' panel header
![datamapper-498-1](https://user-images.githubusercontent.com/5396309/42212879-f172b0f2-7ee9-11e8-8d2e-bae4e44124fa.png)

 ''Add new mapping'' panel header
![datamapper-498-2](https://user-images.githubusercontent.com/5396309/42212890-f883e668-7ee9-11e8-9e13-00ac98602b90.png)

## Expected behavior
It is better to change the mapping panel header from 'Mapping Details' to 'New Mapping''.

![datamapper-498-3](https://user-images.githubusercontent.com/5396309/42213206-b246e26c-7eea-11e8-827d-c8d5fd14984b.png)

**Comment by deernano** [comment]
@igarashitm Hi Tomo, please help to review the above behaviour. Thank you~!

**Comment by igarashitm** [comment]
Do you mean having `New Mapping` label only while it doesn't have any source/target fields? It's actually going to be `Mapping Details` once you define a mapping by selecting fields. Does it mean we want to change the label once user add at least one field? Hmm for me it's a bit too busy.

**Comment by deernano** [comment]
@igarashitm  I mean when the user clicks '+' to add a new mapping, the title could change to 'New mapping'. When the user add at least one field, the mapping remain 'mapping details'. This is to differ the action between '+' action to 'activate mapping' action.
