### ISSUE TITLE
Add "Drag and drop" action to change the index in separate mode or the tooltip need to be removed

### ISSUE THREAD

**Issue by nding-anges** [atlasmap/atlasmap#500]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In separate mode, the tooltip shows that user could drag and drop to change the index, which is not working. If it is a new function, the tooltip need to be removed from the current version to avoid misleading users. 

## Expected behavior
- Add "Drag and drop" action to change the index in separate mode or if the function is not publish at the moment, it is better to change the tooltips to the relevant text to avoid misleading users.

## Screenshot
<img width="601" alt="2018-07-03 6 00 29" src="https://user-images.githubusercontent.com/34368385/42213312-ff6c9bfe-7eea-11e8-9728-4c84c9547de1.png">

**Comment by pleacu** [comment]
Hey Agnes - looks like you're using an out-of-date DataMapper - this is what it should look like - d&d should be fully functional -- @nding-anges 

![dm1](https://user-images.githubusercontent.com/2981421/42221227-6734c4ba-7e9f-11e8-9696-96f91c71114c.png)

**Comment by igarashitm** [comment]
Works for me - @nding-anges let us know if you had a problem running latest upstream master version of AtlasMap.

**Comment by nding-anges** [comment]
@igarashitm @pleacu Get the Drag&Drop functionality after updated Data Mapper, thanks a lot!
