### ISSUE TITLE
‘Edit Details’ Close button icon has the meaning of ‘Remove’

### ISSUE THREAD

**Issue by deernano** [atlasmap/atlasmap#502]
## This is a...

<pre><code>
[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The ‘x’ icon has the meaning of ‘remove’. The user may misunderstand it to be  ‘remove’ button rather than ‘go back’. 

## Screenshot
 <img width="185" alt="datamapper-502" src="https://user-images.githubusercontent.com/5396309/42256806-d10d8b2e-7f85-11e8-84b8-588247935a97.png">

## Expected behavior
The repeating mode UI is better to align with the other mode. The 'x' button will no longer exist afterwards.

**Comment by deernano** [comment]
@gaughan In the new design, the repeating mapping mode will align to the other mapping mode. So the 'x' will not existing. The new design version 2 will be sent today. I was thinking to reply this issue after we review the design with dev together.

**Comment by gaughan** [comment]
@deernano great thanks!

**Comment by igarashitm** [comment]
repeating mapping component has been removed
