### ISSUE TITLE
Source / Trget selecting action improvement

### ISSUE THREAD

**Issue by nding-anges** [atlasmap/atlasmap#503]
## This is a...

<pre><code>

[X] Enhacement
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently, when the user click and select an item on source/ target by mistake, there is no way to revoke the select action.

## Expected behavior
 - It is better that  provide a “on click away” or “click twice the item selected” to let user dis-select.
- This improvement of clicking action will also address to "Clicking a row on Mapping List View" and "Clicking a line of active mapping" ,see related issue[ #474](https://github.com/atlasmap/atlasmap/issues/474) 

## Screenshot

<img width="920" alt="2018-07-04 1 54 58" src="https://user-images.githubusercontent.com/34368385/42259159-de7a4be2-7f91-11e8-8f62-cda4c211e096.png">

**Comment by nding-anges** [comment]
Uploaded detailed design solution:
<img width="920" alt="cliking" src="https://user-images.githubusercontent.com/34368385/42310893-19d9faba-806f-11e8-8e7d-3fce74b24c1b.png">

**Comment by nding-anges** [comment]
@igarashitm Hi Tomo, please help to review the above behavior. Thank you~!

**Comment by igarashitm** [comment]
implemented
