### ISSUE TITLE
Drag and drop doesn't work in Firefox 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#504]
I'm unable to use drag n drop when creating mapping or changing indexes in combine/separate. I have Firefox 61

**Comment by igarashitm** [comment]
Verified it doesn't work on firefox, I'm on Fedora28.

**Comment by pleacu** [comment]
https://support.mozilla.org/en-US/questions/1166501#answer-983577

**Comment by igarashitm** [comment]
escalated to p1 - a bit more love to firefox users ;-) but anyway if it's firefox bug we don't have much we can do.

**Comment by mmelko** [comment]
Hi it still doesn't work (1.35.7 in syndesis)

**Comment by igarashitm** [comment]
Verified it now works fine on both of master and atlasmap-1.35.7 tag of AtlasMap, with Fedora28 firefox (61.0.2).

**Comment by pleacu** [comment]
thkxTomo!

**Comment by igarashitm** [comment]
@mmelko do you still see this?

**Comment by mmelko** [comment]
I'm still not able to create mapping by drag'n'drop. I can switch indexes in combine/separate though.

**Comment by igarashitm** [comment]
OK so you mean drag source field and drop into target to create a mapping. @pleacu do we have same problem there with what you already fixed for combine/separate index?

**Comment by pleacu** [comment]
I've got a fix once my previous push has cleared.

**Comment by igarashitm** [comment]
great! will merge it after release work completes.

**Comment by pleacu** [comment]
This is now fixed - please verify.
