### ISSUE TITLE
Add a common area for error message display - follow syndesis model

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#516]
Curently error messages are cascaded  onto the top of the data mapper UI - need a dedicated area for error diagnostics.

**Comment by jpav** [comment]
I'd agree we need a dedicated area for messages. There could easily be way too many to deal with with just floating notifications. Maybe we should have a type of status bar at the bottom that allows for expanding/collapsing a message area, and normally shows just counts for errors and warnings. we could even add a count for things like the number of unmapped target fields. Thoughts?

**Comment by igarashitm** [comment]
We should leverage PatternFly offering as much as possible

**Comment by pleacu** [comment]
Actually you can't proceed to a new mapping while having an existing error.  Too avoid confusion - the old errors are now cleared so there should be fewer messages stacked up.

**Comment by jpav** [comment]
That would certainly help, so maybe this is just a concern for the future, but there are still other things:

- Warnings due to whatever (auto-conversions?, etc.)
- Not so much an issue now, but potentially multiple errors due to existing older incompatible or possibly corrupted or modified mapping files.

But like I said, maybe my concerns are just a future thing to address once these scenarios get realized.

**Comment by pleacu** [comment]
Here's what we've got:
![err0](https://user-images.githubusercontent.com/2981421/57630244-402aad80-756b-11e9-9c5e-74e9cf972512.png)

![err1](https://user-images.githubusercontent.com/2981421/57630275-4e78c980-756b-11e9-8751-805cb8563a41.png)

![err2](https://user-images.githubusercontent.com/2981421/57630284-546eaa80-756b-11e9-844b-c15e62ac9a03.png)

![err3](https://user-images.githubusercontent.com/2981421/57630291-5b95b880-756b-11e9-9c48-51833f297e25.png)

![err4](https://user-images.githubusercontent.com/2981421/57630311-5fc1d600-756b-11e9-82ca-ef89a9b30fcb.png)

![err5](https://user-images.githubusercontent.com/2981421/57630325-65b7b700-756b-11e9-9420-0c01f696e5c3.png)

**Comment by pleacu** [comment]
STill need to add a tag with a number indicating the number of erros/ warnings that will appear next to the error text window when not expanded.  Will add that as an additional enhancement.
