### ISSUE TITLE
Multi-select fields does not work with drag-and-drop

### ISSUE THREAD

**Issue by kcbabo** [atlasmap/atlasmap#540]
The multi-select stuff is amazing.  I noticed one small problem when trying to use multi-select fields with drag-and-drop though.  If I click on a target field with multiple source fields selected, it works as expected (multiple source fields defaulted to combine mapping).  But if I try to drag the source fields over, only one field is mapped.

**Comment by pleacu** [comment]
Hey @kcbabo - okay - just to be clear - you compound-select lets say three source elements:

![dm1](https://user-images.githubusercontent.com/2981421/43662351-98e1e09a-9733-11e8-9d75-a8cacfd3041e.png)

you then d&d one of the three (lets say 'city') over to a target field.  The current result is just one connection.  You'd prefer the semantics to be for all three (all previously selected elements) to be mapped to the target.  i.e. not this:

![dm2](https://user-images.githubusercontent.com/2981421/43662553-4bb7f15a-9734-11e8-94db-9eacbc7d37e5.png)

but this:

![dm3](https://user-images.githubusercontent.com/2981421/43662562-520c166c-9734-11e8-96c7-f6f6b4ead34d.png)

correct?  Sounds good to me... :)

**Comment by kcbabo** [comment]
Yep, spot on!
