### ISSUE TITLE
Create initial design for standalone only part in UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#543]
![standalone](https://user-images.githubusercontent.com/265462/44594494-55b93680-a794-11e8-9342-096550baed91.png)

Right now, standalone UI is showing a "Syndesis mock up" in the standalone only part which is top 2 bars.

Things to consider:
* Left top: The label `AtlasMap Data Mapper UI` is fine
* Right top: We don't have `Status` nor user account. We should remove it
* Second top bar: This breadcrumb makes no sense. `Dashboard` and `integration` are Syndesis word which we shouldn't show for AtlasMap standalone. We should remove it
* #377 might require some room there instead of those mock up

**Comment by pleacu** [comment]
![i377-7](https://user-images.githubusercontent.com/2981421/44597194-d5e39a00-a79c-11e8-9fe9-5ea820a9ac5b.png)

**Comment by igarashitm** [comment]
Hi @deernano,

Paul's design above looks good to me. Unlike Syndesis, Import/Export are the top level menu for AtlasMap standalone mode. User starts to use AtlasMap from importing Document, create mappings in the UI, then they export mapping definition into the file. It's just like Open/Save for the text editor.

**Comment by deernano** [comment]
@igarashitm 
If so, I recommend to place the button to the far left,  move the import icon 5-10px left in order to avoid users clicking the wrong icon. Others are fine.
<img width="669" alt="2018-08-28 10 14 29" src="https://user-images.githubusercontent.com/5396309/44696328-c076b480-aaa9-11e8-8cf5-3ae3d4ee589d.png">

**Comment by pleacu** [comment]
Corrected icon locations as instructed.  Please review import/export pulldowns and icon positioning.
@deernano 

![i543-1](https://user-images.githubusercontent.com/2981421/45774273-903eb380-bc1a-11e8-80ea-834c878426b5.png)
![i543-2](https://user-images.githubusercontent.com/2981421/45774283-92a10d80-bc1a-11e8-9caf-c3ff1e290b7c.png)
![i543-3](https://user-images.githubusercontent.com/2981421/45774293-959bfe00-bc1a-11e8-8e4c-9612f941988e.png)

**Comment by igarashitm** [comment]
Closing - as we got UXD approval :-)
