### ISSUE TITLE
Let UI use FieldGroup and combine/separate FieldAction instead of COMBINE/SEPARATE mapping mode

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#551]

**Comment by igarashitm** [comment]
@pleacu FYI: `Concatenete` and `Split` are the equivalents to combine and separate mode, IIRC I couldn't use separate/combine name due to some name conflict.

 - Concatenete
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java#L68

 - Split
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java#L248

**Comment by igarashitm** [comment]
An example for concatenate/split
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-split.xml

**Comment by pleacu** [comment]
Closing this as implemented  - the patternfly combobox has a lib build issue in atlasmap - see 
https://github.com/atlasmap/atlasmap/issues/884

ref:

https://github.com/atlasmap/atlasmap/pull/883
