### ISSUE TITLE
Move from registry.access.redhat.com to registry.redhat.io

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#555]
see https://issues.jboss.org/browse/CLOUD-2751 and https://issues.jboss.org/browse/ENTESB-9319

it is used  here https://github.com/atlasmap/atlasmap/blob/dc61f11c0cf9250427496c7ce93aba62f66d0167/runtime/pom.xml#L35

**Comment by heiko-braun** [comment]
@igarashitm Looks like an atlasmap issue. Can we still tackle this for 7.3?

**Comment by igarashitm** [comment]
Yeah not a big deal if it just works - @apupier which image URI exactly we should use instead?

**Comment by apupier** [comment]
> @apupier which image URI exactly we should use instead?

I don't know. I just know that registry.access.redhat.com is moving to registry.redhat.io as mentioned in the pointed JIRA issues.
I expect it should to just be a matter of replacing registry.access.redhat.com by registry.redhat.io

**Comment by apupier** [comment]
seems the case https://github.com/minishift/minishift/blob/master/addons/xpaas/v3.10/xpaas-streams/fis-image-streams.json#L56

**Comment by igarashitm** [comment]
@heiko-braun Do we need immediate release and/or to be reflected in Syndesis?

**Comment by igarashitm** [comment]
It seems that registry URL requires some credential

[ERROR] DOCKER> Unable to pull 'registry.redhat.io/jboss-fuse-6/fis-java-openshift:2.0' from registry 'registry.redhat.io' : Get https://registry.redhat.io/v2/jboss-fuse-6/fis-java-openshift/manifests/2.0: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531 (Internal Server Error: 500) [Get https://registry.redhat.io/v2/jboss-fuse-6/fis-java-openshift/manifests/2.0: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531 (Internal Server Error: 500)]

**Comment by igarashitm** [comment]
Should we just use openjdk:8-jdk or something as a base image? I don't think it's right thing to use closed image for community upstream.
