### ISSUE TITLE
AtlasMap standalone

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#560]
Let's make AtlasMap standalone fully functional for users. Since it has been a developer only mode, We have several things to do.

**Comment by heiko-braun** [comment]
@pleacu I see 5 open subtasks. Does this correctly reflect the state of affairs?

**Comment by apupier** [comment]
Why this issue has been put back to Backlog?
having the standalone mode working is awaited to integrate Atlasmap in VS Code and Che.
