### ISSUE TITLE
Support importing Java classes/jars

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#561]
Support adding Java Document by uploading Java classes/jars so they can be delivered to backend Java inspection service and inspected. We should implement #29 before that.

In addition to the Java Document, we also need to support importing custom transformations. IMO user would want to have Document object and transformation in the same project, thus Document and transformations needs to be added in a single upload.

An option in my mind is to add "Upload jar" into main toolbar, i.e. at the same level of "Export mappings". Then in the "Import Document" menu, user would only specify a class name to add a Java Document into Sources/Target. It means that the AtlasMap design runtime should keep uploaded jar and look into them when Java inspection & transformation search happens instead of upload everytime.

**Comment by igarashitm** [comment]
@pleacu added a bit more in the issue description - WDYT?

**Comment by pleacu** [comment]
I like the idea of adding an 'upload jar' - or multipel jars - and then using it as a mini-repo for finding specific  custom transformations and associated schema.  An on-demand style would be much more efficient.
