### ISSUE TITLE
Line machine is broken with data preview enabled

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#565]
![screenshot from 2018-09-12 10-46-20](https://user-images.githubusercontent.com/265462/45433196-9d3b3000-b679-11e8-9320-4cf2294685f0.png)

Once I click the text field, lines are redrawn, seems just a timing issue.

**Comment by mmelko** [comment]
for me it's enough to do some scroll and then lines are re-drawn.
