### ISSUE TITLE
atlasmap window become inactive after add constant/property

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#572]
![1537446308445 0](https://user-images.githubusercontent.com/6814482/45818561-5c2ec580-bce2-11e8-98c3-79e197f8cd07.png)

**Comment by igarashitm** [comment]
It seems #567 causes this behavior. Not yet have nailed down to the exact lines...

**Comment by pleacu** [comment]
I have it working but the dialog is partially obscurred.  Will report back shortly.
