### ISSUE TITLE
Add constant/property dialog need a bit of aligning

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#576]
`Value Type` dropdown box is a bit too long to right
![screenshot from 2018-09-20 15-53-47](https://user-images.githubusercontent.com/265462/45843597-06601a80-bcee-11e8-989b-dcfc2704ee05.png)
![screenshot from 2018-09-20 15-54-24](https://user-images.githubusercontent.com/265462/45843604-08c27480-bcee-11e8-82c0-9b4d8fa6f097.png)

**Comment by igarashitm** [comment]
Also wondering the label position, should it be on top just like input field above?

**Comment by heiko-braun** [comment]
@igarashitm Is this still an issue?

**Comment by igarashitm** [comment]
yep.
