### ISSUE TITLE
UI freezes after showing previews in mapping table

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#621]
If there is no mapping specified, and I'm in mappings table view,  after show mapping preview UI will freeze on both Firefox and Chrome.

#### steps to reproduce
1. run atlasmap 
2. click on mapping table 
3. click on Show mappings preview 
4. try to add new mapping 

This might freeze also in different steps, but key is to NOT have specified any mapping. If I create mapping before enabling preview, everything works fine.

**Comment by igarashitm** [comment]
#563?
