### ISSUE TITLE
Mappings previews displayed incorrectly in mapping table 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#622]
If I have one source field mapped to several targets. Preview for source is displayed only in last row of mapping table. I'd expect to display source preview for every row where is involved. 
![bug2](https://user-images.githubusercontent.com/6814482/46877360-fe088480-ce40-11e8-932c-93ca1acb0042.gif)

**Comment by igarashitm** [comment]
Mapping Preview only handles active mapping. What is wrong is that the non-active source fields shouldn't have input fields, IOW should be hidden. Maybe a bug when a same source field participate in multiple mappings.
