### ISSUE TITLE
Mapping preview is empty for gaps in mapping table

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#623]
when Gaps are involved into separate and mapping previews are enabled they are empty. Question is if they are empty if it's necessary to even show the preview. If yes we should also display value which will end in gap.
![screenshot_20181012_171129](https://user-images.githubusercontent.com/6814482/46877814-001f1300-ce42-11e8-9148-b7b60171c1bc.png)

**Comment by igarashitm** [comment]
duplicates #601

**Comment by igarashitm** [comment]
@mmelko could you move this capture to #601 for completion? Thanks!
