### ISSUE TITLE
Creating a constant in Data Mapper briefly shows an error message that the constant already exists

### ISSUE THREAD

**Issue by asmigala** [atlasmap/atlasmap#633]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating a constant in the Data Mapper, an error message is very briefly shown between clicking the Save button and the modal disappearing. See screenshot and video.

## Screenshot
![vlcsnap-2018-10-16-14h11m25s947](https://user-images.githubusercontent.com/9480152/47015692-ef2a1680-d14d-11e8-9af6-eb0564edc5a7.png)
![constant](https://user-images.githubusercontent.com/9480152/47015663-e20d2780-d14d-11e8-9319-d806241b4cf7.gif)

**Comment by igarashitm** [comment]
There seems to be some timing issue, the duplication error is evaluated against the value which is just about to be added... when there actually is a duplicate, error message appears correctly and `save` button is disabled.
