### ISSUE TITLE
Fix "Select Mapping" behavior conflicting with preview

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#635]
If one source field participates into multiple mappings, clicking that source field shows a modal window to select one of existing mappings. IMHO this modal is really annoying and prefer some one-click action to switch the mappings. Once we implement #474 we might want to remove this modal window. Maybe we can add one more option to select a mapping from multiple, like by clicking blue dot at the right edge of the source field, and just rotate to next mapping.
![ezgif-3-09b6f0da5491](https://user-images.githubusercontent.com/265462/47098061-91a2d200-d200-11e8-964b-63cfae409afa.gif)

Also it looks weird that the source field turns to blue only when last mapping is selected. It should be blue for all participating mapping I think.
-> this is from same root cause with #622, will be addressed as a part of #622

**Comment by igarashitm** [comment]
@deernano WDYT?

**Comment by deernano** [comment]
@igarashitm Hi Tomo,
we will think about this and make a design solution for you in sprint 37~ （Start from 29th)

**Comment by deernano** [comment]
@igarashitm 
Reply the question:
1."Maybe we can add one more option to select a mapping from multiple, like by clicking blue dot at the right edge of the source field, and just rotate to next mapping."
------If we let the user to click the blue dot to rotate mapping, the clicking area is a bit small. I would recommend to remain clicking the whole box but change to modal to dropdown to reduce one step.

2."Also it looks weird that the source field turns to blue only when last mapping is selected. It should be blue for all participating mapping I think."
------I gree with you that if the user select multi mappings, all  participating mappings should be hightlighted.
Following is the design solution:
![switch-source1 2x](https://user-images.githubusercontent.com/5396309/47703184-6dacab00-dc5a-11e8-9834-3d861042614a.png)

![switch-source2 2x](https://user-images.githubusercontent.com/5396309/47703202-77361300-dc5a-11e8-9c53-5ccbd3361ae8.png)

![switch-source3 2x](https://user-images.githubusercontent.com/5396309/47703207-7bfac700-dc5a-11e8-9d6d-7110593d2467.png)

![switch-source4 2x](https://user-images.githubusercontent.com/5396309/47703214-81581180-dc5a-11e8-832b-ee307c6396ec.png)

![switch-source5 2x](https://user-images.githubusercontent.com/5396309/47703218-85842f00-dc5a-11e8-9152-b8f1eb9c6136.png)

What do you think?

**Comment by igarashitm** [comment]
Ah thanks, I almost forgot we have #474. #474 addresses line click bits, and your dropdown design will make it even better!

**Comment by igarashitm** [comment]
Sorry I should have noticed earlier - so that dropdown still conflicts with data preview. When I first click the source field to activate the mapping, dropdown would show, which is fine. But when I click the data preview text field to input something, mapping selector come up again, which is redundant. Hmm, not so easy.

**Comment by igarashitm** [comment]
I wonder if it's possible to disable this dropdown when data preview text field is clicked. IOW user needs to click outside of text field if they want to switch to another mapping. It's HTML/CSS/JavaScript thing.

**Comment by deernano** [comment]
@igarashitm Yes, its confilicts. Sorry for not cover the data preview... I will talk with Agnes together tmr and reply you the solution (She is PTO today...)

**Comment by igarashitm** [comment]
Thanks! no rush, as we developer are far behind from what you've already done, queue is still really long :)

**Comment by deernano** [comment]
@igarashitm 
Current problem is:
- When data preview function is open, when user clicking the source box, the pop-up dialog for selecting mapping and data preview behaviour will both activate.
- If we change the pop up dialog to dropdown menu, there is confilict between these two actions too.
<img width="1428" alt="2018-11-09 2 43 27" src="https://user-images.githubusercontent.com/5396309/48257990-0c9d8800-e44f-11e8-984c-13358487b894.png">

After discussing, we change the design as following:
- In normal status, the swiching mapping remain as above drop down menu design.
- In Data preview open status, we combine these two actions. Separate the swich mapping action (hover& click source box) and data preview action (hover& click input box) 
![switch-dp-1 2x](https://user-images.githubusercontent.com/5396309/48258991-8b93c000-e451-11e8-8bf2-dedab8abfd8f.png)

![switch-dp-2 2x](https://user-images.githubusercontent.com/5396309/48258996-8df61a00-e451-11e8-823f-0c13e3e9b0cd.png)

![switch-dp-3 2x](https://user-images.githubusercontent.com/5396309/48258488-1ffd2300-e450-11e8-99c9-3e7ecef84e45.png)

![switch-dp-4 2x](https://user-images.githubusercontent.com/5396309/48258804-04464c80-e451-11e8-96b3-7cea5b3b689f.png)

![switch-dp-5 2x](https://user-images.githubusercontent.com/5396309/48258808-07d9d380-e451-11e8-87d6-f6189a3e85f7.png)

![switch-dp-6 2x](https://user-images.githubusercontent.com/5396309/48258812-0ad4c400-e451-11e8-8c60-197b5c2ef364.png)

![switch-dp-7 2x](https://user-images.githubusercontent.com/5396309/48259113-fb09af80-e451-11e8-8ac9-7abdf281dda1.png)

![switch-dp-8 2x](https://user-images.githubusercontent.com/5396309/48259117-fe9d3680-e451-11e8-83f3-d2a9c293c5d9.png)

**Comment by igarashitm** [comment]
Looks good for direction! however I think it's going to be more tricky to highlight both of mappings, as it's tightly coupled with `Active Mapping`, which is shown in `Mapping Details` pane. I think it's better to stay with activating only one of them.

**Comment by deernano** [comment]
@igarashitm  I change the highlight both mapping as following:
![switch-dp-2 2x](https://user-images.githubusercontent.com/5396309/48406977-c313ac80-e770-11e8-9559-e7a944f650ad.png)

Also update  the above wireframe, WDYT?

**Comment by igarashitm** [comment]
Thanks @deernano! LGTM, so `Mapping Details` pane won't show until we select one of them.

**Comment by igarashitm** [comment]
React UI solved the problem
