### ISSUE TITLE
build/run issues with master

### ISSUE THREAD

**Issue by rohanmars** [atlasmap/atlasmap#642]
I'm trying to build/run off master.

When I try to run "../../mvnw -Pitests spring-boot:run" in runtime/runtime

`rohan@xenial:/opt/customers/sempre/atlasmap/runtime/runtime$ ../../mvnw -Pitests spring-boot:run
/opt/customers/sempre/atlasmap/runtime
[INFO] Scanning for projects...
Downloading: https://jcenter.bintray.com/org/apache/maven/plugins/maven-checkstyle-plugin/2.17/maven-checkstyle-plugin-2.17.pom
Downloaded: https://jcenter.bintray.com/org/apache/maven/plugins/maven-checkstyle-plugin/2.17/maven-checkstyle-plugin-2.17.pom (13 kB at 12 kB/s)
Downloading: https://jcenter.bintray.com/org/apache/maven/plugins/maven-checkstyle-plugin/2.17/maven-checkstyle-plugin-2.17.jar
Downloaded: https://jcenter.bintray.com/org/apache/maven/plugins/maven-checkstyle-plugin/2.17/maven-checkstyle-plugin-2.17.jar (109 kB at 335 kB/s)
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Atlas :: Runtime 1.39.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://jcenter.bintray.com/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.pom
Downloaded: https://jcenter.bintray.com/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.pom (7.0 kB at 26 kB/s)
Downloading: https://jcenter.bintray.com/org/codehaus/mojo/keytool/1.5/keytool-1.5.pom
Downloaded: https://jcenter.bintray.com/org/codehaus/mojo/keytool/1.5/keytool-1.5.pom (7.1 kB at 22 kB/s)
Downloading: https://jcenter.bintray.com/org/codehaus/mojo/mojo-parent/32/mojo-parent-32.pom
Downloaded: https://jcenter.bintray.com/org/codehaus/mojo/mojo-parent/32/mojo-parent-32.pom (26 kB at 99 kB/s)
Downloading: https://jcenter.bintray.com/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar
Downloaded: https://jcenter.bintray.com/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar (44 kB at 154 kB/s)
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.5.13.RELEASE:run (default-cli) > test-compile @ runtime >>>
Downloading: http://maven.restlet.com/io/atlasmap/atlas-parent/1.39.0-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.jboss.org/nexus/content/groups/ea/io/atlasmap/atlas-parent/1.39.0-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.restlet.com/io/atlasmap/atlas-parent/1.39.0-SNAPSHOT/atlas-parent-1.39.0-SNAPSHOT.pom
Downloading: https://repository.jboss.org/nexus/content/groups/ea/io/atlasmap/atlas-parent/1.39.0-SNAPSHOT/atlas-parent-1.39.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.516 s
[INFO] Finished at: 2018-10-22T16:12:56-07:00
[INFO] Final Memory: 26M/284M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project runtime: Could not resolve dependencies for project io.atlasmap:runtime:jar:1.39.0-SNAPSHOT: Failed to collect dependencies at io.atlasmap:atlas-java-module:jar:1.39.0-SNAPSHOT: Failed to read artifact descriptor for io.atlasmap:atlas-java-module:jar:1.39.0-SNAPSHOT: Could not find artifact io.atlasmap:atlas-parent:pom:1.39.0-SNAPSHOT in maven-restlet (http://maven.restlet.com) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

Then I manually add the parent to module on the runtime pom.xml (hack), but then when I run that I get:

`[INFO] Attaching agents: []
Listening for transport dt_socket at address: 8000
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: io/atlasmap/api/AtlasException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.atlasmap.api.AtlasException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.044 s
[INFO] Finished at: 2018-10-22T16:20:34-07:00
[INFO] Final Memory: 30M/265M`

Is there something I'm missing?

**Comment by igarashitm** [comment]
You just need to `mvn install` in parent before you build runtime. Or use build.sh in the top directory.

**Comment by rohanmars** [comment]
I tried the "mvn install" in parent on two machine without luck. After running build.sh that solves the problem.

Thanks @igarashitm
