### ISSUE TITLE
Upgrade to Angular 7

### ISSUE THREAD

**Issue by seanforyou23** [atlasmap/atlasmap#658]
Need that full Shadow DOM V1 support

https://github.com/angular/angular/blob/master/CHANGELOG.md#700-2018-10-18

**Comment by igarashitm** [comment]
Hi @seanforyou23, do you say this is a bug fix so we can squeeze in to 7.2, or post 7.2 thing? I'm gonna release today for 7.2 RC build and wonder if we want this in.

**Comment by igarashitm** [comment]
Given this is a major upgrade, maybe better to have it post 7.2

**Comment by seanforyou23** [comment]
@igarashitm totally something that can wait. Not a bug, just an enhancement :)

**Comment by igarashitm** [comment]
merged to master.
