### ISSUE TITLE
IndexOf and LastIndexOf are possible only as target transformation

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#661]
I have simple <Double> -> <Double> mapping and it's no longer possible to add IndexOf and LastIndexOf transformations on source. Is it intentional?

**Comment by pleacu** [comment]
Hey Matej -
       The transformation actions are based on target mapping type if
specified.  Try just a source-side transformation (no target selected)
first.
   --paull

**Comment by igarashitm** [comment]
Verified it appears if I choose String source field and integer target field

**Comment by igarashitm** [comment]
@mmelko seems it's working as expected, can you verify?
