### ISSUE TITLE
source-side transformations depends on target-type

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#670]
I believe source-side transformations should take into account only source type. Currently we have different  source transformations in Number->String mappings than Number -> Number mappings. I don't see any reason why I cannot use i.e unit conversions on source side during Number -> String mapping.

**Comment by pleacu** [comment]
I guess the logic was that if you select a string source-side object and you select a target side object to complete the mapping that it makes sense to restrict the available transformations to those that match the target.  If you're adding a transformation and a string -> string mapping it doesn't make sense to add an absolute-value transformation.  If however you have in mind a multi-stage source-side transformation then you could simply not choose a target mapping and have the full range of transformations available.

**Comment by mmelko** [comment]
in that case .. isn't it really just another target-side transformation? It looks like you are transforming source as target type. Maybe I'm looking at it wrong way, but from my POV you can do everything just on target then and source side transformation is not needed as you are always get only subset of target transformations.

**Comment by pleacu** [comment]
The other side of that coin is the user should perform all transformations on the source side and then do a single mapping to the target.  The way it is provides two knobs to turn that hopefully makes some logical sense to use.

**Comment by mmelko** [comment]
Totally agree. In current design however it looks like first step is convert source to target and then do some transformations related to target type, which seems to be not ideal approach.(at least for me).

**Comment by igarashitm** [comment]
So to summarize:
Now the source transformations are:
 * if target field is selected
   * show transformations which has source field type as an input type **AND** target-field-type as an output
 * else (target field is not selected)
   * show transformations which has source field type as an input type

The other option to consider:
  * show transformations which has source field type as an input type, no matter what the target field type is

**Comment by pleacu** [comment]
@mmelko - please try this out now - ref PR https://github.com/atlasmap/atlasmap/pull/676
