### ISSUE TITLE
Decouple from yarn to run the standalone process

### ISSUE THREAD

**Issue by paoloantinori** [atlasmap/atlasmap#683]
suggestions are to base it on mvn or pure java. 

this is a prerequisite for embedding AtlasMap in vscode

**Comment by igarashitm** [comment]
Do you mean running yarn via maven frontend plugin is enough, or needs to get rid of yarn usage completely? No idea how to build TypeScript application without yarn.

**Comment by igarashitm** [comment]
And doesn't all-in-one docker image (#557) work?

**Comment by apupier** [comment]
> And doesn't all-in-one docker image (#557) work?

for VS Code, I think we can't rely on a docker image easily.

**Comment by igarashitm** [comment]
Closing as it has been addressed via #557, atlasmap-standalone.jar is now a spring-boot uber jar which contains both of UI and backend
