### ISSUE TITLE
Long processing of xsds

### ISSUE THREAD

**Issue by rkorytkowski** [atlasmap/atlasmap#696]
The processing of FHIR xsds takes a lot of time. When running within Syndesis it occasionally times out even after increasing the timeout to 60s. I did a bit of profiling and XSOMParser can be blamed for that (https://github.com/atlasmap/atlasmap/blob/master/lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/SchemaInspector.java#L203)

I see a number of solutions:
1. Provide a pre-processed xml document in AtlasMap format instead of XSD. This way we won't have to use XSOMParser at runtime to process complex XSDs (in other words provide what is returned from https://github.com/atlasmap/atlasmap/blob/8af7337b3eebca2ac510e40d29eea9a34b949cc0/lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlInspectionService.java#L85 instead of XSD).
2. Cache once processed XSD so that when trying to map the same XSD again it is much faster.
3. Change to some other XSD processing solution e.g. http://ws.apache.org/xmlschema/ (unsure how much faster it is) or a regular XML SAX parser (increases complexity, but is extremely fast).

I'd vote for 1 since it seems to be quite easy to achieve. My other vote is 3 with the SAX parser as it's the most robust, but rather complex to achieve. @igarashitm, thoughts?

**Comment by rkorytkowski** [comment]
@igarashitm, great! Could you please advise on how to do the pre-computation with Syndesis?

**Comment by igarashitm** [comment]
It seems this plugin is invoked somehow for Java DataShape, no idea when/how
https://github.com/syndesisio/syndesis/blob/master/app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java

And then if you put `inspectionResult` ahead, AtlasMap will skip invoking inspection
https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L396

Maybe better to involve Syndesis backend guy to move forward.

**Comment by rkorytkowski** [comment]
Thanks! I'll try that! Closing this issue then...
