### ISSUE TITLE
Update BYTE conversion behavior

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#7]
@igarashitm commented on [Wed Nov 08 2017](https://github.com/atlasmap/atlasmap-runtime/issues/279)

It looks Byte related converters are all marked as UNSUPPORTED but shouldn't be, easy to implement. Also NUMBER type conversion must be provided OOTB as it often appears in the JSON schema.

BYTE -> Short 
BYTE -> String (string representation of the number)
...

-127 to 127
Int, Short, Long -> BYTE (range concern)
String -> BYTE (range concern and type concern)
Decimal -> BYTE (precision concern.. if 1.2 comes in as a source value throw an exception)

**Comment by rohanmars** [comment]
Fixed by https://github.com/atlasmap/atlasmap/pull/137

**Comment by igarashitm** [comment]
@rohanmars ugh I overlooked the BYTE<>String conversion is not really what we want, BYTE should be considered as a number. reopening.

**Comment by rohanmars** [comment]
@igarashitm the intention is that a byte is converted to the literal numerical number for string conversion, "-128" to "127"?

**Comment by igarashitm** [comment]
String>BYTE could be just `Byte.parseByte()` actually

**Comment by rohanmars** [comment]
I think the approach I took was to treat them all as numerical values, without encoding.  A String>BYTE using parseByte() implies an additional encoding structure. Which is okay, but we should do the same on BYTE>String too. Additionally, it will have a slightly different notion for BYTE to char then also.

**Comment by igarashitm** [comment]
What do you mean by additional encoding structure for the `parseByte()`? are you saying about the `+` and `-`?
https://docs.oracle.com/javase/8/docs/api/java/lang/Byte.html#parseByte-java.lang.String-

This cast implies character code mapping...
https://github.com/atlasmap/atlasmap/pull/137/files#diff-5d8856e41e9f7105c28eafbf94141dbfR64
but I'm now feeling like it's OK for now. this is too trivial, and strictly speaking `char` is also just a 2byte number... plus other number converters are doing same. So let's keep this as is.

But for String>BYTE, I would just take it as a string representation of a number with format and range concern.

For BYTE>String do you mean this doesn't return a string representation of decimal number?
https://github.com/rohanmars/atlasmap/blame/78da1a51a9142d92d3db30ee7108734f2bfc8d79/runtime/core/src/main/java/io/atlasmap/converters/ByteConverter.java#L148

**Comment by rohanmars** [comment]
I took the approach for the String handling to be consistent with BYTE<>char. So a string "c" would be treated as the char ASCII value 99, without any notion of encoding. Obviously parseByte() won't work on "c".  I meant by encoding is that a Byte value to String will go from value 99, to the string "99", where as a Byte to char will go from 99 to 'c', or in Java 99. The former has an encoded structure hence the parse. Similar to if we supported additional hex style encodings for example.  Should we use the decode() method instead to support HEX formats too?

Oh, yes BYTE>String is already doing that. So the change will be consistent with that already.

I'll make the change.

**Comment by igarashitm** [comment]
Yeah I agree BYTE<>char is doing too much around that, maybe better to fix to align with what we decide.

**Comment by igarashitm** [comment]
I don't think HEX is needed here, if you want to handle non-decimal string representation, that would be a field action

**Comment by rohanmars** [comment]
Is this what you were thinking: https://github.com/rohanmars/atlasmap/commit/e1d45ef7dfdc84909beaf2b74706e1d4481218e8

**Comment by igarashitm** [comment]
Yep, I guess this is good enough for the decimal representation
