### ISSUE TITLE
Unit Test fails on master

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap#73]
See build log https://circleci.com/gh/atlasmap/atlasmap/72 , can be reproduced locally, too.

```
LengthValidatorTest
Running io.atlasmap.validators.StringPatternValidatorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.118 sec - in io.atlasmap.validators.StringPatternValidatorTest

Results :

Failed tests:
  AtlasUtilTest.testFindClassesForPackage:116 expected:<4> but was:<0>

Tests run: 426, Failures: 1, Errors: 0, Skipped: 2
```

**Comment by mattrpav** [comment]
1. Updated utility method to include scanning resources from within self classpath
2. Original use case had it for scanning external paths for inspection
    (in order to isolate classloading to outside running classpath and support the ability to reload jars without a JVM restart)

**Comment by mattrpav** [comment]
Builds passing CI
