### ISSUE TITLE
Be compatible with VS Code Webview API

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#740]
VS Code WebView API is not supporting cookie/localstorage (and they don't want to [support it](https://github.com/Microsoft/vscode/issues/66207))

AtlasMap is using cookie/localstorage . Some details of investigation in the conversation of this PR: https://github.com/jboss-fuse/vscode-atlasmap/pull/9

to help setup environment for investigation see https://github.com/jboss-fuse/tooling_material/blob/master/atlasmap.md (ask to @paoloantinori for right access) or this mail https://post-office.corp.redhat.com/mailman/private/atlasmap-dev/2019-January/msg00013.html (a bit less detailed)

**Comment by pleacu** [comment]
![vs1](https://user-images.githubusercontent.com/2981421/52236257-53efb500-2894-11e9-9547-bfdee0887f20.png)

There's another issue - see https://github.com/atlasmap/atlasmap/issues/744
