### ISSUE TITLE
vscode support - errors when writing to runtime service from vscode-view resident DM

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#744]
1. Launch my own private ADM runtime
2. Open w/ VSCode - all if well

![vs1](https://user-images.githubusercontent.com/2981421/52235371-daef5e00-2891-11e9-831f-2ea6ffeb8c0a.png)

3.  Import a JSON file - rt errors

![vs2](https://user-images.githubusercontent.com/2981421/52235296-b3989100-2891-11e9-9c9c-27c33929ed7a.png)

![vs3](https://user-images.githubusercontent.com/2981421/52235274-a4b1de80-2891-11e9-8c79-364ea30095df.png)

Related issue: https://github.com/atlasmap/atlasmap/issues/740

**Comment by pleacu** [comment]
Seems fully functional now - to test - select the tools bar import icon - include this file:
https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/components/mock-documents/mockdoc.adm

![vs1-ok](https://user-images.githubusercontent.com/2981421/52302941-a0062c80-295c-11e9-8cff-3d7a6d31b79d.png)

**Comment by apupier** [comment]
> Seems fully functional now

that's cool!
Is it possible to do a release of the standalone artifact including the modifications then? (I can create a specific issue if needed)

**Comment by igarashitm** [comment]
Released 1.39.2
