### ISSUE TITLE
VSCode - blank column on each side

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#749]
![image](https://user-images.githubusercontent.com/1105127/52400705-28e9a900-2ac0-11e9-8478-8b77be8aa7a6.png)

I check that it is displayed well in Chrome with the same instance:
![image](https://user-images.githubusercontent.com/1105127/52400768-56365700-2ac0-11e9-904a-a73cbefdfc51.png)

**Comment by igarashitm** [comment]
VSCode should fix its HTML rendering

**Comment by apupier** [comment]
Can you help to create a ticket in [VS Code tracker](https://github.com/microsoft/vscode/issues)?
An idea on what would be the minimal html to reproduce the error?

**Comment by apupier** [comment]
I think that it comes from a "padding" inside vscode-light class if I understand well:
![image](https://user-images.githubusercontent.com/1105127/52429244-f366af00-2b03-11e9-8310-20a6eb54a691.png)

When overriding padding to set 0, the navigation bar is correct on the borders:
![image](https://user-images.githubusercontent.com/1105127/52429283-08dbd900-2b04-11e9-96a6-7bf92508212a.png)

**Comment by apupier** [comment]
created https://github.com/Microsoft/vscode/issues/68137

**Comment by apupier** [comment]
the answer from Microsoft team is that the css with padding is done on purpose "so that content without good stylesheets doesn't look terrible."
and that we "can use css in your webview to override these"

Is it something that we can add in CSS of AtlasMap directly? or is it better to find a way to inject the CSS on VS Code side?

**Comment by apupier** [comment]
If we replace _<body>_ by _<body style="padding: 0">_ https://github.com/apupier/vscode-atlasmap/pull/2
is it a good solution? Will it not break something else?

VS Code is providing several defaults css rules:
https://github.com/Microsoft/vscode/blob/35523f6c51bdc1edae1696a586dadd021fe47096/src/vs/workbench/contrib/webview/electron-browser/webview-pre.js#L412-L466

how to know which one will affect AtlasMap UI?

**Comment by igarashitm** [comment]
We won't optimize the look & feel to the VSCode

**Comment by apupier** [comment]
> We won't optimize the look & feel to the VSCode since Syndesis is the primary focus

I proposed a modification in vscode-atlasmap project so that it is not affecting AtlasMap inside Syndesis.
What I don't know is if the proposed modification will impact other parts of AtlasMap inside VS Code or not. And how to check if there are other similar issues that we might encounter.

I need help from AtlasMap developers to answer these [questions](https://github.com/atlasmap/atlasmap/issues/749#issuecomment-461742742)

**Comment by igarashitm** [comment]
@apupier Don't you have vscode-atlasmap repository? It makes us to track AtlasMap issue harder if you mess up with the issues of other projects here.

**Comment by apupier** [comment]
I didn't know if it was a specific AtlasMap issue or not when opening it.
As I'm asking help from AtlasMap dev team, I thought that it would be convenient to have it in your dashboard to monitor time spent/to allocate on it.
i'm fine to duplicate it in vscode-atlasmap.
