### ISSUE TITLE
Some lines are disappearing when moving from one screen to another

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#750]
I don't understand how ti can be possible and how it can be an AtlasMap issue but I'm reporting it to have a confirmation or infirmation:
on first screen
![image](https://user-images.githubusercontent.com/1105127/52400837-93024e00-2ac0-11e9-85d1-7368db6ea777.png)
![image](https://user-images.githubusercontent.com/1105127/52400907-bcbb7500-2ac0-11e9-9693-9ffe66b73c02.png)

on second screen
![image](https://user-images.githubusercontent.com/1105127/52400846-985f9880-2ac0-11e9-87a3-0a3173bb06c7.png)
![image](https://user-images.githubusercontent.com/1105127/52400911-c0e79280-2ac0-11e9-8c8b-27301a076851.png)

the only difference is the "recommended" scale and layout which 125% for first screen and 100% on second

**Comment by igarashitm** [comment]
VSCode should fix its HTML rendering

**Comment by apupier** [comment]
it is working in VS Code. It is in Chrome that it is not working

**Comment by igarashitm** [comment]
Still nothing to do from AtlasMap, HTML never changes in that kind of window system events

**Comment by apupier** [comment]
I'm reproducing by changing the size of the Chrome window
