### ISSUE TITLE
Support specifying ADM file path via Java system property at backend startup

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#755]
Support specifying ADM file path via Java system property like `-Datlasmap.adm.path` or whatever at backend startup so that the client like VSCode can provide a ADM file and have it preloaded in AtlasMap UI.

Only for initial loading purpose. User need to export explicitly to get adm file updated.

**Comment by lhein** [comment]
that sounds like a great idea

**Comment by apupier** [comment]
it will preload all files provided in this folder? And how to open the UI with a specific file? There is a specific uri parameter to provide?

**Comment by lhein** [comment]
"so that the client like VSCode can provide a ADM file and have it preloaded"

**Comment by apupier** [comment]
started some work in this branch: https://github.com/apupier/atlasmap/tree/755-providepropertyToInitAtlasMapWithAdmFile

**Comment by apupier** [comment]
> started some work in this branch: https://github.com/apupier/atlasmap/tree/755-providepropertyToInitAtlasMapWithAdmFile

I started a bit of work with some tests that might be reusable but it is far from working.
I was expecting to have the DefaultAtlasContextFactory.createContext(URI) supporting having an .adm file passed to it. In fact it seems not the case and the upload of .adm file from the UI has some splitted work between UI and server (or I have not found the correct entrypoint)
I'm wondering if I started to look at the right place then.
@igarashitm @pleacu Have i understood well? Do ou think that we (Fuse Tooling dev) can implement the functionality in a reasonable time? Can you provide some guidance please?

**Comment by igarashitm** [comment]
It looks this is not trivial to achieve, need some refactoring around startup/working-directory/adm-file handling. Would be better to leave it to @pleacu

**Comment by pleacu** [comment]
I'm tracking down an odd timing issue - I can look at this after that... :)
         --Paul
