### ISSUE TITLE
Enable CI on PR's 

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#76]
CI doesn't appear to be running on PR's

See: https://github.com/atlasmap/atlasmap/pull/69

**Comment by mattrpav** [comment]
FYI-- It appears that CircleCI runs on PR's created directly off the upstream project, but not from forked repos.

**Comment by rhuss** [comment]
Yes, for PR and merge we have a different mechanism by using our internal Jenkins CI. @iocanel would it be hard to setup this repo for a CI build, too ?

**Comment by rhuss** [comment]
@jimmidyson could we add purebot also for the atlasmap organisation ?

**Comment by jimmidyson** [comment]
@rhuss I don't have karma to do so - could someone make me an org admin/owner perhaps?

**Comment by jimmidyson** [comment]
@mattrpav @rhuss By default, circleci doesn't build forked PRs, go to https://circleci.com/gh/atlasmap/atlasmap/edit#advanced-settings and enable `Build forked pull requests`.

**Comment by rhuss** [comment]
@jimmidyson I made you an owner of the orga.

**Comment by rhuss** [comment]
@mattrpav @jimmidyson I enabled the circle builds on forked pull requests.

**Comment by jimmidyson** [comment]
Pure bot is now enabled on all atlasmap orga repositories.

**Comment by mattrpav** [comment]
Thanks!
