### ISSUE TITLE
Source panel lines don't align correctly w/ multiple ADM import

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#761]
1.  Start with a blank canvas
2.  import mockdoc.adm
3.  import mockdocfhir.adm
4.  import mockdoc.adm again - lines appear but are not sync'd to correct source panel fields

* Note that you can import mockdoc.adm multiple times consecutively without issue

**Comment by igarashitm** [comment]
One question related to this, what happens with this steps - are they going to be merged, or clear previous adm and import new? I expect latter.
e.g. import adm1{source1,target1} and then import adm2{source2,target2}. I expect source1 and target1 disappear and only source2 and target2 are shown.

**Comment by pleacu** [comment]
Correct - the import of a catalog file wipes out whatever was previously there.

**Comment by pleacu** [comment]
After rebasing and rebuilding I'm having trouble getting this to fail again.  Will leave open for now...

**Comment by pleacu** [comment]
Seems to have been a build issue - closing.
