### ISSUE TITLE
Wrong name for the constant to remove - first letter uppercased

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#767]
- add a constant with a name starting with a lowercase letter
- click on "delete"
--> the name in the dialog is wrong, it is using an uppercased first letter

![image](https://user-images.githubusercontent.com/1105127/52966574-ee2d1e00-33a7-11e9-8e89-b44d1e032360.png)

**Comment by apupier** [comment]
there are some strange cases around uppercase/lowercase and first letter:

- create "aValue"
--> cannot create "AValue" but can create "AValuE

**Comment by pleacu** [comment]
@jpav - seems like this is in your ballpark
