### ISSUE TITLE
the p and g of "Mappings" is truncated in mapping table view

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#769]
![image](https://user-images.githubusercontent.com/1105127/52967631-f20e6f80-33aa-11e9-97d8-bd806a255d43.png)

**Comment by igarashitm** [comment]
what do you mean?

**Comment by apupier** [comment]
the bottom of the letters are truncated:

![image](https://user-images.githubusercontent.com/1105127/52968200-c42a2a80-33ac-11e9-8ff5-cd250f83d036.png)
