### ISSUE TITLE
Remove empty structure

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#774]
in some cases, there are structures with a little "arrow down" but when clicking on it there is nothing. As we can't do anything with it maybe we can get rid of them?

(notice the arrows down without any content)
![image](https://user-images.githubusercontent.com/1105127/52970160-2423cf80-33b3-11e9-9e25-142aac198f22.png)

**Comment by igarashitm** [comment]
They are basically "supposed to be expandable", but not ATM due to lack of features. #255 for example. Please open more specific issue if there's no existing.

**Comment by apupier** [comment]
I understand that for now they are empty and it is planned that they will be populated.
I wanted to suggest to hide them until it is supported. What is the timeframe to have them supported? If it is more than a month, my personal point of view is that it is worthy to hide them. They will reappear anyway as soon as the support will be added. In the mean time it will avoid to have users like me wondering what is happening with all these fields and trying to click each of them. it is also wasting a lot of place.
