### ISSUE TITLE
[Feature] Provide an example on how to use AtlasMap in a standalone Camel project

### ISSUE THREAD

**Issue by paoloantinori** [atlasmap/atlasmap#784]
We should consider providing a full working code example on how to use `camel-atlasmap`.

Hisao has put out a step by step description here, but we should consider adding a full Runnable maven project with our codebase.

**Comment by igarashitm** [comment]
FWIW I'm creating a top `examples` directory as a part of #68, https://github.com/igarashitm/atlasmap/commit/18c87ffed132996237f997eb7c4684792457986b#diff-9c09368afd1dedd339f8e2b725b72f6f
