### ISSUE TITLE
Remove old atlasmapping-UI.nnn.xml in the working directory at startup

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#792]
I see sometimes there're two `target/mappings.atlasmapping-UI.nnn.xml` file and seems like one of them is a leftover from previous run. It might be better to remove it at the startup if it's not supposed to be used.

**Comment by pleacu** [comment]
Hey @igarashitm - I believe this PR has fixed this issue:

https://github.com/atlasmap/atlasmap/commit/4e21e37fbf13446a6c2408270f485d34178bccc3#diff-771b607d8264ab9083bc4e9d397ec745

the toolbar.component.ts change clears the existing mappings files before processing an imported catalog.

**Comment by pleacu** [comment]
Closing this - it should not reappear - if it does I'll reopen it.  Ref previous comment.
