### ISSUE TITLE
not possible to define java collection as root document in standalone 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#815]
Currently it's not possible to define java collection as root document from UI or from `DocumentInitializationModel `.

**Comment by igarashitm** [comment]
We need to deliver `collectionType` and `collectionClass` to the inspection service when adding a Java document
https://github.com/atlasmap/atlasmap/blob/master/lib/modules/java/service/src/main/java/io/atlasmap/java/service/JavaService.java#L162-L163
