### ISSUE TITLE
Transformation text input is right-aligned

### ISSUE THREAD

**Issue by mcoker** [atlasmap/atlasmap#831]
From https://github.com/syndesisio/syndesis/issues/4868

Looks like it's because of `text-align: right;` on this line

https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css#L223

Is this on purpose or is the alignment needed in another context? Curious if it would it be safe to remove it so the text is left-aligned?

cc  @dongniwang

**Comment by dongniwang** [comment]
@igarashitm Can you please take a look at this? ^^ thanks!

**Comment by igarashitm** [comment]
Seems it's right-aligned from beginning, and I'm OK with changing to left-aligned. @pleacu could you maybe clean it up as a part of #828 design refactoring?

**Comment by pleacu** [comment]
sure - will keep this open as a reminder.

**Comment by gaughan** [comment]
+1
