### ISSUE TITLE
Transformation is duplicated in Syndesis

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#834]
See https://github.com/atlasmap/atlasmap/issues/827#issuecomment-473990408 - The `Concatenate` transformation is duplicated in the 2nd visit.

It's reproducible only in Syndesis ATM, but I found it's happening within AtlasMap. Need further investigation.

**Comment by igarashitm** [comment]
@heiko-braun I think this is potentially p0, as it could break any transformation user added. I'm investigating if
 1. any workaround?
 1. any condition to cause it which could lower the severity?

**Comment by heiko-braun** [comment]
@igarashitm Can you elaborate on these points:

- An example scenario
- What do you see?
- What did you expect to see?

This might help others (like me) to better understand the issue and assess it's impact.

**Comment by heiko-braun** [comment]
@igarashitm nevermind, I didn't see the issue referenced in the description.

**Comment by heiko-braun** [comment]
Loweing the prio, as there seems to be a workaround:

> A workaround for this is to focus out from input field after enter the delimiter. The onBlur event on the input field triggers save mappings, and the delimiter is reflected to the saved mappings.

**Comment by igarashitm** [comment]
@heiko-braun sorry for the confusion, but that workaround is for "delimiter is not saved (#827) issue, and this one "transformation duplicates" looks separate problem which has no workaround. In @avano's comment here https://github.com/atlasmap/atlasmap/issues/827#issuecomment-473990408 , there's a gif showing transformation is unexpectedly duplicated (two Concatenate transformation).

**Comment by heiko-braun** [comment]
ok, than we should raise it to blocking

**Comment by heiko-braun** [comment]
@igarashitm Please let me know if you can reproduce it in Syndesis

**Comment by gashcrumb** [comment]
I *could* maybe be convinced to add some code into the data mapper host component that would disable the 'Done' button...  Maybe as a last resort kinda thing.

**Comment by igarashitm** [comment]
@heiko-braun it does reproduce, actually only within Syndesis. It's easier if there's a way to reproduce in standalone though - will keep updating here.

**Comment by igarashitm** [comment]
@gashcrumb ah good point, I think that's an option for #827. This one is more deeper in the AtlasMap it seems.

**Comment by gashcrumb** [comment]
@igarashitm yep, lemme know :-)

**Comment by igarashitm** [comment]
This is now race condition suspect. It doesn't happen if I put breakpoints to the all of `actions.push()` and step debugging it.
It seems to be happening exactly when mapping is activated, i.e. when click the mapped field.

**Comment by igarashitm** [comment]
`MappingDefinition.updateMappedFieldsFromDocuments()` is invoked twice when the symptom is seen, and I think it shouldn't...

**Comment by igarashitm** [comment]
So the last resort would be to clear `mappedField.actions` before entering this for loop
https://github.com/atlasmap/atlasmap/blob/c934c06a75b958249fd1da2ddddc540b9cadc28c/ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts#L414

But that's just placing a lid on stinky pan while we have to wash it.

**Comment by igarashitm** [comment]
Got `console.trace()` for that duplicated invocation
[console.trace-1st.txt](https://github.com/atlasmap/atlasmap/files/2992027/console.trace-1st.txt)
[console.trace-2nd.txt](https://github.com/atlasmap/atlasmap/files/2992028/console.trace-2nd.txt)

**Comment by igarashitm** [comment]
After a deeper debugging and discussion with Paul, actually that last resort seems to be an only option at this stage, it now looks more promising than I thought first. Tested on both of standalone and Syndesis and looks working fine. I'll submit a PR in a short.
