### ISSUE TITLE
Mapping validation doesn't work for JSON and XML

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#843]
When we add `STRING` to `INTEGER` mapping then it's possible that string field doesn't have number format and ends up with an error. We used to have a warning for it but it doesn't show up today.

**Comment by pleacu** [comment]
![tomo1](https://user-images.githubusercontent.com/2981421/55166612-d2a2f900-5145-11e9-8ec9-edb29181bc63.png)

**Comment by igarashitm** [comment]
This should hit this one at least, and then UI should show it as a warning in the `Mapping Details` pane.
https://github.com/atlasmap/atlasmap/blob/31926f0a03ada22381991d23aab97fc1c0bfc1a0/lib/core/src/main/java/io/atlasmap/core/BaseModuleValidationService.java#L350

https://github.com/atlasmap/atlasmap/blob/31926f0a03ada22381991d23aab97fc1c0bfc1a0/lib/core/src/main/java/io/atlasmap/core/BaseModuleValidationService.java#L329
