### ISSUE TITLE
Display a validation error when user combine multiple collection fields

### ISSUE THREAD

**Issue by claudio4j** [atlasmap/atlasmap#844]
When user maps a collection to a single element, displays a validation error.

![datamapper](https://user-images.githubusercontent.com/836543/55201259-f47d9980-51a0-11e9-969f-62b2396c5d04.png)

**Comment by christophd** [comment]
Also I noticed that the target document is a collection in that case, too. Although we have a single element specification as target. 

For instance if you have a Json array collection schema as source and want to map to a single element Java type you end up having a singleton list with the Java object in it.

I would expect AtlasMap to map the first element in the source collection to the Java object without any wrapping list type. This seems to be only the case for Java type target documents.

@igarashitm should I open a separate issue for that?

**Comment by igarashitm** [comment]
@christophd Yes please, actual payload example would help - I don't completely understand, if it's `JSON collection field` to `Java non-collection field` mapping, default behavior should be to pick up last element in the collection. `itemAt` transformation could be used to pick up first or something else. There could be a pitfall with separate/conbine case though.

**Comment by igarashitm** [comment]
This one specifically needs to get an validation error that we don't support combining collection fields. It would need to wait for #244 and #843 to be fixed beforehand.
