### ISSUE TITLE
Last added document disappears after refreshing website

### ISSUE THREAD

**Issue by kuhy** [atlasmap/atlasmap#857]
Steps to reproduce:
1.  Import 3 or more files as "source".
2.  Refresh website.

Then the file that was last added disappears. It happens in Chrome and also in Firefox.

Before refreshing:
![Screenshot from 2019-04-04 15-21-46](https://user-images.githubusercontent.com/3624908/55560493-9c8ae980-56f0-11e9-9fee-3fbacf6497c8.png)

After refreshing:
![Screenshot from 2019-04-04 15-21-56](https://user-images.githubusercontent.com/3624908/55560508-a3b1f780-56f0-11e9-87e6-364330bf83f3.png)

**Comment by igarashitm** [comment]
It reproduced for me, and also found that it only matters if there's no mapping. Once any mapping is created this doesn't happen.

**Comment by igarashitm** [comment]
It still reproduces, I got a trace log when it happens.
[localhost-1564696358488.log](https://github.com/atlasmap/atlasmap/files/3458788/localhost-1564696358488.log)

The source document import starts from L67, and target document import starts from L77, `Mapping Service Request`.
L81 stinks... receiving `Set Compressed Mapping Service Response` even before L83, starting to request a JSON inspection for a target document.
