### ISSUE TITLE
Migrate to React from Angular

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#874]
~~It's gonna be a whole rewrite of UI.~~
Syndesis UI has proved it could be achieved incrementally. Learn from them and bake into a plan.

**Comment by igarashitm** [comment]
Hi @riccardo-forina, we created an Epic here for AtlasMap React migration. Could you review those and comment if you see anything? The toolchain concern #1197 is the most unclear thing from my POV.

**Comment by pleacu** [comment]
Substantially complete - UI tests will be handled by separate issues.
