### ISSUE TITLE
`undefined` instead of field name in the alert during enum mapping

### ISSUE THREAD

**Issue by kuhy** [atlasmap/atlasmap#875]
Problem is the wrong alert when I map some field to enum. In the alert message is `undefined` instead of the name of the field.

Steps to reproduce:
1. Click on some field that can't be mapped to enum.
2. Click on some enum. (in my case `SourceEnum`)
3. It shows alert with the text `The field 'undefined' cannot be selected, Enumeration fields are not valid for this mapping.`. The problem here is that it prints `undefined` instead of `SourceEnum`.

It didn't happen on `1.39.0`. So when I do this mapping there, the message is: `The field 'SourceEnum' cannot be selected, Enumeration fields are not valid for this mapping.`. And I think this should be correct behavior.

**Comment by igarashitm** [comment]
Now it doesn't reproduce, perhaps it has been fixed by #1199
