### ISSUE TITLE
Correct AtlasMap lib build to include patternfly-bootstrap-combobox

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#884]
Currently it's possible to call combobox if AtlasMap is built as a standalone app.  It won't compile when built as a lib for inclusion into Syndesis.  To reproduce:

Modify transition-selection.component.ts - uncomment this line:
`   // $('select#separator').combobox({clearIfNoMatch: false});
`
from atlasmap/ui:  ./build.sh -Pitests

**Comment by igarashitm** [comment]
Continue with #895
