### ISSUE TITLE
Transformations actions are broken

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#887]
Create a simple mapping and add an Append transformation.

![bug1](https://user-images.githubusercontent.com/2981421/56811959-ed7d9180-6807-11e9-8b9a-e8ebb29768f2.png)

**Comment by igarashitm** [comment]
This is a backward compatibility issue, seems to be a problem with reading old field action format.

**Comment by pleacu** [comment]
Creating a new field action transformation in a fresh mapping - no old files - still fails.

**Comment by igarashitm** [comment]
Right, once it reload. The mapping file at backend looks OK until reload. Now backend side deserialization is suspected.

**Comment by igarashitm** [comment]
backend side is working fine, but it converts to new `@type: actionName` style of action description when it serializes it into JSON. So UI had to support it.

**Comment by pleacu** [comment]
There's also an issue with volume conversions with numberic actions.

![bug2](https://user-images.githubusercontent.com/2981421/56824699-3263f100-6825-11e9-9d61-7100249fee58.png)
