### ISSUE TITLE
Support invoking arbitrary transformation in expression

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#890]
Add field action function to invoke arbitrary field action in conditional mapping expression.

I would start from `DefaultAtlasFunctionResolver#resolve()`, if no OOTB function is found for given name, then delegate to transformation. Maybe create a `FieldActionFunction` as a wrapper which lookup field action. We also have to investigate if we need any trick for user developped custom transformation that would be uploaded via UI.

**Comment by rkorytkowski** [comment]
PR at https://github.com/atlasmap/atlasmap/pull/1610
