### ISSUE TITLE
[UI] Don't show multiplicity transformations where not eligible

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#905]
many-to-one transformation like `Concatenate` and `Expression`, and one-to-many transformation like `Split` should not show up in the regular transformation pull down. They must be applied in specific order, i.e. many-to-one must come first and one-to-many must come last. We already kinda handle it in UI, just have to hide those transformations in the pull down.

~~We might have to consider transitioning to many-to-one if source field is in a collection and target field is not in a collection.~~ -> filed a separate issue #918

**Comment by jpav** [comment]
Isolated the situation causing this, which is only when source/target is a collection/map/array. Just need to now trigger the code in the UI that marks these as combine/separate as appropriate and ensure many-to-one/one-to-many transformations don't show up in pull-downs.
