### ISSUE TITLE
[UI] - Cond Expr - Don't evaluate expression on blur - wait for them to be done

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#910]
Probably add a done button next to the input text box

**Comment by igarashitm** [comment]
I don't like having only expression as an exception, rather prefer
having a preview execution button if needed. But IMO it's fine having expression evaluated with onblur, as user explicitly enabled preview mode.

**Comment by igarashitm** [comment]
Maybe we want to add an instant expression validation feature including separate REST endpoint. Currently we don't have anything other than executing preview.

**Comment by igarashitm** [comment]
#1139
