### ISSUE TITLE
No CMD or ENTRYPOINT configured for atlasmap docker image

### ISSUE THREAD

**Issue by jamesnetherton** [atlasmap/atlasmap#913]
If you do `docker run -ti atlasmap/atlasmap`, then you end up at a root CLI prompt instead of having the atlasmap JAR being executed.

Shouldn't we set a default command or entrypoint? Or maybe switch to the `fabric8/java-centos-openjdk8-jdk` image which already handles running fat JARs and adds some additional goodies like Jolokia and Prometheus agents.

@igarashitm WDYT?

**Comment by igarashitm** [comment]
Sounds good!
