### ISSUE TITLE
Establish per-mapping validation logs

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#926]
There should exist per-mapping error and warning logs that the user can see in the current active mappings main panel and in the mapping table as a link.

**Comment by igarashitm** [comment]
We can show icons (orange-triangle and/or red-circle) on `Mapping Details` pane and clicking it shows per-mapping validation errors/warns. We're already showing those in table view (mapping-list), just have to make it clickable and show the detailed logs.

**Comment by igarashitm** [comment]
Changing to bug - since this is a regression sacrificed to eliminate the errors/warns to push `Mapping Details` contents down.

**Comment by igarashitm** [comment]
addressed in React UI
