### ISSUE TITLE
Cond expr - labels embedded in cond expr appear at the end on restart

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#942]
Ref:
![bug1](https://user-images.githubusercontent.com/2981421/58186316-a2c62c80-7c82-11e9-904e-5b91e8be29fe.png)

**Comment by igarashitm** [comment]
I guess the root cause is #935

**Comment by pleacu** [comment]
Dupl: https://github.com/atlasmap/atlasmap/issues/990
