### ISSUE TITLE
cond-expr: Selecting a new mapping with cond expr enabled show old

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#961]
Selecting a new mapping when the cond expr is enabled for the old mapping still shows old cexpression.

**Comment by igarashitm** [comment]
I don't see this issue, there might be some condition to reproduce

**Comment by pleacu** [comment]
Procedure:
  1.  Establish 2 different mappings
  2.  Select mapping-A, select the conditional expression icon
  3.  Enter an arbitrary expression
  4.  Select mapping-B, select the conditional expression icon
  5.  Select mapping-A - the conditional expression retains the expression for mapping-B

Workaround:
  Close the expression box and re-open it.
