### ISSUE TITLE
Add an basic conditonal example when fx is displayed

### ISSUE THREAD

**Issue by gaughan** [atlasmap/atlasmap#975]
When the user hits the fx button, no example is available to start using the conditional mapping.
Something similar to conditional flows would be cool:

![image](https://user-images.githubusercontent.com/674767/59207587-4feedf00-8b75-11e9-99b4-fbde0279ae84.png)

**Comment by pleacu** [comment]
@gaughan - Is this ok?

![sc1](https://user-images.githubusercontent.com/2981421/59629256-6d412180-9110-11e9-9ed0-0e0093e7adc3.png)

**Comment by gaughan** [comment]
Awesome, yes!

**Comment by pleacu** [comment]
Moved the tool tip text to the bottom of the widget to keep it in the canvas (don't want to wonder outside ou our footprint in vscode or syndesis).  I also added an 8 second timeout for the text or if you click in the expression input widget.

![sc2](https://user-images.githubusercontent.com/2981421/59712539-69c69c80-91db-11e9-8791-47ff30b2846d.png)
