### ISSUE TITLE
Lines aren't rendered when mapping is specified via add new mapping.

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#978]
When mapping is specified via add new mapping dialog lines aren't rendered. Separate:
![screenshot_20190610_221305](https://user-images.githubusercontent.com/6814482/59224155-fb2b8280-8bcd-11e9-8862-6a3fcf4c543f.png)

**Comment by pleacu** [comment]
@mmelko - does this still fail for you?  I can't get it to fail

**Comment by pleacu** [comment]
@mmelko - plz see if this now works for you.

**Comment by pleacu** [comment]
This now works ok.
![sc1](https://user-images.githubusercontent.com/2981421/60122110-85d5bb00-9752-11e9-98a8-c61f86b2cb4d.png)
