### ISSUE TITLE
wrong displaying of conditional mapping expression

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#979]
As you can see here condition expression don't fit into text input. Maybe increasing size of expression input. It's not serious but doesn't leave good impression though. 
![screenshot_20190611_121940](https://user-images.githubusercontent.com/6814482/59272408-44bfb000-8c56-11e9-885d-40afcd7133f8.png)

**Comment by igarashitm** [comment]
Hi @seanforyou23, is there a PF3 or Angular OOTB widget that expands its row size to show texts fully and shrink back to one line once it focuses out?

**Comment by igarashitm** [comment]
might be possible only with CSS... 
https://stackoverflow.com/questions/5648464/how-to-expand-a-text-area-when-click-on
https://stackoverflow.com/questions/15865982/it-is-possible-to-expand-a-textarea-only-with-css

**Comment by igarashitm** [comment]
Toast Notification for instant one showing latest ones and disappear in 10 secs for example
https://www.patternfly.org/v3/pattern-library/communication/toast-notifications/

Then Notification Drawer to revisit, it would be great if we can show a number of errors/warns on a bell icon at top right (#924)
https://www.patternfly.org/v3/pattern-library/communication/notification-drawer/

**Comment by igarashitm** [comment]
#1155 only makes overflowed text hidden and scroll as cursor goes. We'll continue to provide more expression workspace with #1154
