### ISSUE TITLE
[Conditional mapping] Unable to specify one field twice

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#988]
I find it limiting that I can't specify one field twice. i.e:
```if(ISEMPTY(a), b, a}``` or ```if(a < 20, b, a * 2 )```

If you think it's not a bug but rather enhancement feel free to change the label, but from my POV it's a bug.

**Comment by igarashitm** [comment]
It's a bug for sure, what happen when you try to add it 2nd time?

**Comment by mmelko** [comment]
nothing... it will leave there empty space. So IFEMPTY will throw an exception that it needs 3 arguments.
